"""Masar COURSE-013 lesson seed.

This file is intentionally plain-Python and framework-neutral so it can be
adapted to the application seeding layer without assuming unprovided DB fields.
"""

LESSON_META = {'lesson_id': 'L013-009', 'module_id': 'M013-02', 'title': 'NumPy Indexing, Slicing & Filtering', 'slug': 'numpy-indexing-slicing-filtering', 'learning_objective': 'Apply numpy indexing, slicing & filtering correctly in a reproducible data-analysis workflow and explain the analytical tradeoffs.', 'concepts': ['indexing', 'slicing', 'boolean masks', 'fancy indexing'], 'source_references': [{'source_id': 'BOOK-013', 'chapter': 2}], 'difficulty': 'Beginner', 'estimated_minutes': 45, 'prerequisites': ['L013-008'], 'practice': {'type': 'guided_lab', 'description': 'Use a realistic analyst dataset to practice numpy indexing, slicing & filtering, document assumptions, and validate the result.', 'deliverable': 'A reproducible notebook or script plus a short analytical interpretation.'}, 'assessment': {'type': 'applied_check', 'description': 'Complete a scenario-based task demonstrating correct use of numpy indexing, slicing & filtering and explain the decision or result.'}, 'status': 'curriculum_finalized_content_seed', 'modernization_notes': ['Use current NumPy ndarray indexing APIs; source figures 2.8 required, 2.7 optional.']}

TOPIC = {'lesson_id': 'L013-009', 'module_id': 'M013-02', 'slug': 'numpy-indexing-slicing-filtering', 'title': 'NumPy Indexing, Slicing & Filtering', 'content_markdown': ('# L013-009 — NumPy Indexing, Slicing & Filtering\n'
                                                                                                                                                                           '\n'
                                                                                                                                                                           '## Learning objective\n'
                                                                                                                                                                           'Apply numpy indexing, slicing & filtering correctly in a reproducible data-analysis workflow and explain the analytical tradeoffs.\n'
                                                                                                                                                                           '\n'
                                                                                                                                                                           '## Why this matters\n'
                                                                                                                                                                           'This lesson develops a practical Data Analyst capability inside **NumPy & pandas for Analytical Data Work**. The focus is correct method selection, reproducible implementation, validation, and clear interpretation rather than memorizing APIs.\n'
                                                                                                                                                                           '\n'
                                                                                                                                                                           '## Core concepts\n'
                                                                                                                                                                           '- indexing\n'
                                                                                                                                                                           '- slicing\n'
                                                                                                                                                                           '- boolean masks\n'
                                                                                                                                                                           '- fancy indexing\n'
                                                                                                                                                                           '\n'
                                                                                                                                                                           '{{figure:fancy-indexing}}\n'
                                                                                                                                                                           '\n'
                                                                                                                                                                           '## Source mapping\n'
                                                                                                                                                                           '- BOOK-013 — Chapter 2\n'
                                                                                                                                                                           '\n'
                                                                                                                                                                           '## Learn\n'
                                                                                                                                                                           'Work through the concepts using a realistic business dataset. Explain what the method does, what assumptions or data conditions matter, and what can go wrong if it is applied mechanically.\n'
                                                                                                                                                                           '\n'
                                                                                                                                                                           '{{figure:fancy-index-pairs}}\n'
                                                                                                                                                                           '\n'
                                                                                                                                                                           '## Practice\n'
                                                                                                                                                                           'Use a realistic analyst dataset to practice numpy indexing, slicing & filtering, document assumptions, and validate the result.\n'
                                                                                                                                                                           '\n'
                                                                                                                                                                           '**Deliverable:** A reproducible notebook or script plus a short analytical interpretation.\n'
                                                                                                                                                                           '\n'
                                                                                                                                                                           '## Analyst checks\n'
                                                                                                                                                                           '- State the business/analytical objective before applying the technique.\n'
                                                                                                                                                                           '- Inspect and validate inputs before trusting outputs.\n'
                                                                                                                                                                           '- Keep transformations reproducible.\n'
                                                                                                                                                                           '- Protect raw data and final evaluation data when relevant.\n'
                                                                                                                                                                           '- Separate observed evidence from causal or business conclusions.\n'
                                                                                                                                                                           '\n'
                                                                                                                                                                           '## Assessment\n'
                                                                                                                                                                           'Complete a scenario-based task demonstrating correct use of numpy indexing, slicing & filtering and explain the decision or result.\n'
                                                                                                                                                                           '\n'
                                                                                                                                                                           '## Modernization / correctness notes\n'
                                                                                                                                                                           '- Use current NumPy ndarray indexing APIs.\n'), 'exercises': [{'title': 'Guided practice — NumPy Indexing, Slicing & Filtering', 'instructions': 'Apply indexing, slicing, boolean masks to a small realistic dataset. Record assumptions and validate the output.', 'expected_output': 'Working code/notebook with a concise interpretation.'}, {'title': 'Analyst decision challenge', 'instructions': 'Given a changed business scenario, choose the appropriate method, justify it, and identify one failure mode or limitation.', 'expected_output': 'A short written decision plus any supporting code or calculation.'}], 'quiz': [{'question': 'What is the primary purpose of indexing in this lesson?', 'options': ['Support the analytical objective', 'Replace validation', 'Guarantee causality', 'Remove the need for data quality checks'], 'answer': 'Support the analytical objective', 'explanation': 'indexing is useful only when it supports the analytical objective and is validated in context.'}, {'question': 'Which statement best reflects good practice when using slicing?', 'options': ['Apply it deliberately and validate assumptions', 'Always use the default without checking', 'Use it only after the test set is inspected', 'Treat it as proof of causality'], 'answer': 'Apply it deliberately and validate assumptions', 'explanation': 'Masar emphasizes explicit assumptions, validation, and business context rather than mechanical defaults.'}, {'question': 'Which workflow principle applies throughout COURSE-013?', 'options': ['Keep the work reproducible and document decisions', 'Overwrite raw data to save space', 'Evaluate on the training set only', 'Hide assumptions from stakeholders'], 'answer': 'Keep the work reproducible and document decisions', 'explanation': 'Reproducibility, transparent assumptions, and protected raw data are recurring course standards.'}], 'project_contribution': 'Multi-Source Retail Data Preparation & Analysis'}
