"""Masar curriculum seed — L011-003."""

LESSON_META = {'lesson_id': 'L011-003', 'course_id': 'COURSE-011', 'module_id': 'M011-01', 'title': 'AWS Security Groups & Controlled Network Exposure', 'slug': 'aws-security-groups-and-controlled-network-exposure', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply aws security groups & controlled network exposure concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['security groups', 'inbound and outbound rules', 'CIDR and /32 access', 'trusted IP/VPN access', 'minimizing exposed ports']

SOURCE_REFERENCES = ['BOOK-011 Chapters 1, 4, 5, 6, 7, 8']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-003 — AWS Security Groups & Controlled Network Exposure\n\n## Learning objective\n\nApply aws security groups & controlled network exposure concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- security groups\n- inbound and outbound rules\n- CIDR and /32 access\n- trusted IP/VPN access\n- minimizing exposed ports\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-003-EX1', 'title': 'Apply AWS Security Groups & Controlled Network Exposure', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: security groups, inbound and outbound rules, CIDR and /32 access. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-003-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to aws security groups & controlled network exposure. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-003-Q1', 'type': 'short_answer', 'question': 'What production problem is aws security groups & controlled network exposure intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: security groups, inbound and outbound rules, CIDR and /32 access.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-003-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-003-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by AWS Security Groups & Controlled Network Exposure.', 'answer': 'security groups, inbound and outbound rules', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
