"""Masar curriculum seed — L011-007."""

LESSON_META = {'lesson_id': 'L011-007', 'course_id': 'COURSE-011', 'module_id': 'M011-01', 'title': 'Deployment Security Assets & Sensitive Configuration', 'slug': 'deployment-security-assets-and-sensitive-configuration', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply deployment security assets & sensitive configuration concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['SSH and TLS private keys', 'certificate assets', 'runtime credentials', 'file permissions', 'separating sensitive configuration from application source']

SOURCE_REFERENCES = ['BOOK-011 Chapters 1, 4, 5, 6, 7, 8']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-007 — Deployment Security Assets & Sensitive Configuration\n\n## Learning objective\n\nApply deployment security assets & sensitive configuration concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- SSH and TLS private keys\n- certificate assets\n- runtime credentials\n- file permissions\n- separating sensitive configuration from application source\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-007-EX1', 'title': 'Apply Deployment Security Assets & Sensitive Configuration', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: SSH and TLS private keys, certificate assets, runtime credentials. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-007-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to deployment security assets & sensitive configuration. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-007-Q1', 'type': 'short_answer', 'question': 'What production problem is deployment security assets & sensitive configuration intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: SSH and TLS private keys, certificate assets, runtime credentials.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-007-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-007-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Deployment Security Assets & Sensitive Configuration.', 'answer': 'SSH and TLS private keys, certificate assets', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
