"""Masar curriculum seed — L011-008."""

LESSON_META = {'lesson_id': 'L011-008', 'course_id': 'COURSE-011', 'module_id': 'M011-01', 'title': 'Cross-Cloud Deployment Patterns: AWS vs GCP', 'slug': 'cross-cloud-deployment-patterns-aws-vs-gcp', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply cross-cloud deployment patterns: aws vs gcp concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['AWS/GCP service mapping', 'EC2 vs Compute Engine', 'security groups vs firewall rules', 'static addressing', 'repeatable VM bootstrap with startup scripts']

SOURCE_REFERENCES = ['BOOK-011 Chapters 1, 4, 5, 6, 7, 8']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-008 — Cross-Cloud Deployment Patterns: AWS vs GCP\n\n## Learning objective\n\nApply cross-cloud deployment patterns: aws vs gcp concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- AWS/GCP service mapping\n- EC2 vs Compute Engine\n- security groups vs firewall rules\n- static addressing\n- repeatable VM bootstrap with startup scripts\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-008-EX1', 'title': 'Apply Cross-Cloud Deployment Patterns: AWS vs GCP', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: AWS/GCP service mapping, EC2 vs Compute Engine, security groups vs firewall rules. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-008-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to cross-cloud deployment patterns: aws vs gcp. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-008-Q1', 'type': 'short_answer', 'question': 'What production problem is cross-cloud deployment patterns: aws vs gcp intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: AWS/GCP service mapping, EC2 vs Compute Engine, security groups vs firewall rules.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-008-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-008-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Cross-Cloud Deployment Patterns: AWS vs GCP.', 'answer': 'AWS/GCP service mapping, EC2 vs Compute Engine', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
