"""Masar curriculum seed — L011-004."""

LESSON_META = {'lesson_id': 'L011-004', 'course_id': 'COURSE-011', 'module_id': 'M011-01', 'title': 'Static Public Networking with Elastic IP', 'slug': 'static-public-networking-with-elastic-ip', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply static public networking with elastic ip concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['dynamic vs static public addresses', 'Elastic IP allocation and association', 'public vs private IPv4', 'stable deployment endpoints', 'preparing for DNS']

SOURCE_REFERENCES = ['BOOK-011 Chapters 1, 4, 5, 6, 7, 8']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-004 — Static Public Networking with Elastic IP\n\n## Learning objective\n\nApply static public networking with elastic ip concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- dynamic vs static public addresses\n- Elastic IP allocation and association\n- public vs private IPv4\n- stable deployment endpoints\n- preparing for DNS\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-004-EX1', 'title': 'Apply Static Public Networking with Elastic IP', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: dynamic vs static public addresses, Elastic IP allocation and association, public vs private IPv4. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-004-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to static public networking with elastic ip. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-004-Q1', 'type': 'short_answer', 'question': 'What production problem is static public networking with elastic ip intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: dynamic vs static public addresses, Elastic IP allocation and association, public vs private IPv4.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-004-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-004-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Static Public Networking with Elastic IP.', 'answer': 'dynamic vs static public addresses, Elastic IP allocation and association', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
