"""Masar curriculum seed — L011-021."""

LESSON_META = {'lesson_id': 'L011-021', 'course_id': 'COURSE-011', 'module_id': 'M011-02', 'title': 'Amazon ECR & Container Release Workflow', 'slug': 'amazon-ecr-and-container-release-workflow', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply amazon ecr & container release workflow concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['private ECR repositories', 'registry authentication', 'Docker build/tag/push', 'image URI', 'container image as release artifact']

SOURCE_REFERENCES = ['BOOK-011 Chapters 9 and 10']

FIGURE_REFERENCES = [{'source_figure': 'Figure 10-3', 'title': 'ECR repositories', 'priority': 'optional', 'suggested_path': 'assets/m011-02/fig-10-3-ecr-repositories.png'}]

LESSON_MARKDOWN = '# L011-021 — Amazon ECR & Container Release Workflow\n\n## Learning objective\n\nApply amazon ecr & container release workflow concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- private ECR repositories\n- registry authentication\n- Docker build/tag/push\n- image URI\n- container image as release artifact\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n\n## Manual visual references\n- `Figure 10-3` — ECR repositories (optional); add manually at `assets/m011-02/fig-10-3-ecr-repositories.png`.\n'

EXERCISES = [{'id': 'L011-021-EX1', 'title': 'Apply Amazon ECR & Container Release Workflow', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: private ECR repositories, registry authentication, Docker build/tag/push. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-021-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to amazon ecr & container release workflow. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-021-Q1', 'type': 'short_answer', 'question': 'What production problem is amazon ecr & container release workflow intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: private ECR repositories, registry authentication, Docker build/tag/push.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-021-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-021-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Amazon ECR & Container Release Workflow.', 'answer': 'private ECR repositories, registry authentication', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
