"""Masar curriculum seed — L011-023."""

LESSON_META = {'lesson_id': 'L011-023', 'course_id': 'COURSE-011', 'module_id': 'M011-02', 'title': 'Target Groups & Application Load Balancer Routing', 'slug': 'target-groups-and-application-load-balancer-routing', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply target groups & application load balancer routing concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['IP target groups', 'dynamic Fargate registration', 'listeners', 'host-based routing', 'subdomain-to-target-group mapping']

SOURCE_REFERENCES = ['BOOK-011 Chapters 9 and 10']

FIGURE_REFERENCES = [{'source_figure': 'Figure 10-15', 'title': 'ALB listener rules final result', 'priority': 'required', 'suggested_path': 'assets/m011-02/fig-10-15-alb-listener-rules.png'}, {'source_figure': 'Figure 10-7', 'title': 'Target-group configuration', 'priority': 'optional', 'suggested_path': 'assets/m011-02/fig-10-7-target-group.png'}]

LESSON_MARKDOWN = '# L011-023 — Target Groups & Application Load Balancer Routing\n\n## Learning objective\n\nApply target groups & application load balancer routing concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- IP target groups\n- dynamic Fargate registration\n- listeners\n- host-based routing\n- subdomain-to-target-group mapping\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n\n## Manual visual references\n- `Figure 10-15` — ALB listener rules final result (required); add manually at `assets/m011-02/fig-10-15-alb-listener-rules.png`.\n- `Figure 10-7` — Target-group configuration (optional); add manually at `assets/m011-02/fig-10-7-target-group.png`.\n'

EXERCISES = [{'id': 'L011-023-EX1', 'title': 'Apply Target Groups & Application Load Balancer Routing', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: IP target groups, dynamic Fargate registration, listeners. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-023-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to target groups & application load balancer routing. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-023-Q1', 'type': 'short_answer', 'question': 'What production problem is target groups & application load balancer routing intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: IP target groups, dynamic Fargate registration, listeners.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-023-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-023-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Target Groups & Application Load Balancer Routing.', 'answer': 'IP target groups, dynamic Fargate registration', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
