"""Masar curriculum seed — L011-025."""

LESSON_META = {'lesson_id': 'L011-025', 'course_id': 'COURSE-011', 'module_id': 'M011-02', 'title': 'ECS Task Definitions for AI Services', 'slug': 'ecs-task-definitions-for-ai-services', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply ecs task definitions for ai services concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['task definitions', 'Fargate launch type', 'container image URI', 'CPU and memory settings', 'container ports and execution roles']

SOURCE_REFERENCES = ['BOOK-011 Chapters 9 and 10']

FIGURE_REFERENCES = [{'source_figure': 'Figure 10-16', 'title': 'ECS/Fargate cluster', 'priority': 'required', 'suggested_path': 'assets/m011-02/fig-10-16-ecs-cluster.png'}]

LESSON_MARKDOWN = '# L011-025 — ECS Task Definitions for AI Services\n\n## Learning objective\n\nApply ecs task definitions for ai services concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- task definitions\n- Fargate launch type\n- container image URI\n- CPU and memory settings\n- container ports and execution roles\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n\n## Manual visual references\n- `Figure 10-16` — ECS/Fargate cluster (required); add manually at `assets/m011-02/fig-10-16-ecs-cluster.png`.\n'

EXERCISES = [{'id': 'L011-025-EX1', 'title': 'Apply ECS Task Definitions for AI Services', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: task definitions, Fargate launch type, container image URI. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-025-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to ecs task definitions for ai services. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-025-Q1', 'type': 'short_answer', 'question': 'What production problem is ecs task definitions for ai services intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: task definitions, Fargate launch type, container image URI.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-025-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-025-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by ECS Task Definitions for AI Services.', 'answer': 'task definitions, Fargate launch type', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
