"""Masar curriculum seed — L011-016."""

LESSON_META = {'lesson_id': 'L011-016', 'course_id': 'COURSE-011', 'module_id': 'M011-02', 'title': 'Host-Based Routing, DNS & HTTPS on Cloud Run', 'slug': 'host-based-routing-dns-and-https-on-cloud-run', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply host-based routing, dns & https on cloud run concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['HTTPS frontend', 'TLS certificate attachment', 'host and path rules', 'subdomains', 'DNS to load-balancer IP']

SOURCE_REFERENCES = ['BOOK-011 Chapters 9 and 10']

FIGURE_REFERENCES = [{'source_figure': 'Figure 9-6', 'title': 'Adjusting load-balancer routing rules', 'priority': 'required', 'suggested_path': 'assets/m011-02/fig-9-6-routing-rules.png'}]

LESSON_MARKDOWN = '# L011-016 — Host-Based Routing, DNS & HTTPS on Cloud Run\n\n## Learning objective\n\nApply host-based routing, dns & https on cloud run concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- HTTPS frontend\n- TLS certificate attachment\n- host and path rules\n- subdomains\n- DNS to load-balancer IP\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n\n## Manual visual references\n- `Figure 9-6` — Adjusting load-balancer routing rules (required); add manually at `assets/m011-02/fig-9-6-routing-rules.png`.\n'

EXERCISES = [{'id': 'L011-016-EX1', 'title': 'Apply Host-Based Routing, DNS & HTTPS on Cloud Run', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: HTTPS frontend, TLS certificate attachment, host and path rules. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-016-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to host-based routing, dns & https on cloud run. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-016-Q1', 'type': 'short_answer', 'question': 'What production problem is host-based routing, dns & https on cloud run intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: HTTPS frontend, TLS certificate attachment, host and path rules.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-016-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-016-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Host-Based Routing, DNS & HTTPS on Cloud Run.', 'answer': 'HTTPS frontend, TLS certificate attachment', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
