"""Masar curriculum seed — L011-017."""

LESSON_META = {'lesson_id': 'L011-017', 'course_id': 'COURSE-011', 'module_id': 'M011-02', 'title': 'Securing Cloud Run Ingress', 'slug': 'securing-cloud-run-ingress', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply securing cloud run ingress concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['direct service URLs', 'internal-and-cloud-load-balancing ingress', 'load-balancer-only access', 'reducing alternate public paths', 'edge security']

SOURCE_REFERENCES = ['BOOK-011 Chapters 9 and 10']

FIGURE_REFERENCES = [{'source_figure': 'Figure 9-9', 'title': 'Restricted direct Cloud Run URL', 'priority': 'optional', 'suggested_path': 'assets/m011-02/fig-9-9-cloud-run-restricted-url.png'}]

LESSON_MARKDOWN = '# L011-017 — Securing Cloud Run Ingress\n\n## Learning objective\n\nApply securing cloud run ingress concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- direct service URLs\n- internal-and-cloud-load-balancing ingress\n- load-balancer-only access\n- reducing alternate public paths\n- edge security\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n\n## Manual visual references\n- `Figure 9-9` — Restricted direct Cloud Run URL (optional); add manually at `assets/m011-02/fig-9-9-cloud-run-restricted-url.png`.\n'

EXERCISES = [{'id': 'L011-017-EX1', 'title': 'Apply Securing Cloud Run Ingress', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: direct service URLs, internal-and-cloud-load-balancing ingress, load-balancer-only access. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-017-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to securing cloud run ingress. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-017-Q1', 'type': 'short_answer', 'question': 'What production problem is securing cloud run ingress intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: direct service URLs, internal-and-cloud-load-balancing ingress, load-balancer-only access.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-017-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-017-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Securing Cloud Run Ingress.', 'answer': 'direct service URLs, internal-and-cloud-load-balancing ingress', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
