"""Masar curriculum seed — L011-015."""

LESSON_META = {'lesson_id': 'L011-015', 'course_id': 'COURSE-011', 'module_id': 'M011-02', 'title': 'Serverless Network Endpoint Groups & Load Balancing', 'slug': 'serverless-network-endpoint-groups-and-load-balancing', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply serverless network endpoint groups & load balancing concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['serverless NEGs', 'backend services', 'Cloud Run to load-balancer integration', 'multiple serverless services', 'managed ingress']

SOURCE_REFERENCES = ['BOOK-011 Chapters 9 and 10']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-015 — Serverless Network Endpoint Groups & Load Balancing\n\n## Learning objective\n\nApply serverless network endpoint groups & load balancing concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- serverless NEGs\n- backend services\n- Cloud Run to load-balancer integration\n- multiple serverless services\n- managed ingress\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-015-EX1', 'title': 'Apply Serverless Network Endpoint Groups & Load Balancing', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: serverless NEGs, backend services, Cloud Run to load-balancer integration. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-015-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to serverless network endpoint groups & load balancing. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-015-Q1', 'type': 'short_answer', 'question': 'What production problem is serverless network endpoint groups & load balancing intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: serverless NEGs, backend services, Cloud Run to load-balancer integration.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-015-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-015-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Serverless Network Endpoint Groups & Load Balancing.', 'answer': 'serverless NEGs, backend services', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
