"""Masar curriculum seed — L011-010."""

LESSON_META = {'lesson_id': 'L011-010', 'course_id': 'COURSE-011', 'module_id': 'M011-02', 'title': 'Serverless Computing & Workload Suitability', 'slug': 'serverless-computing-and-workload-suitability', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply serverless computing & workload suitability concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['serverless computing', 'VM vs managed runtime', 'stateful vs stateless vs ephemeral workloads', 'automatic scaling', 'workload suitability']

SOURCE_REFERENCES = ['BOOK-011 Chapters 9 and 10']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-010 — Serverless Computing & Workload Suitability\n\n## Learning objective\n\nApply serverless computing & workload suitability concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- serverless computing\n- VM vs managed runtime\n- stateful vs stateless vs ephemeral workloads\n- automatic scaling\n- workload suitability\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-010-EX1', 'title': 'Apply Serverless Computing & Workload Suitability', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: serverless computing, VM vs managed runtime, stateful vs stateless vs ephemeral workloads. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-010-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to serverless computing & workload suitability. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-010-Q1', 'type': 'short_answer', 'question': 'What production problem is serverless computing & workload suitability intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: serverless computing, VM vs managed runtime, stateful vs stateless vs ephemeral workloads.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-010-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-010-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Serverless Computing & Workload Suitability.', 'answer': 'serverless computing, VM vs managed runtime', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
