"""Masar curriculum seed — L011-022."""

LESSON_META = {'lesson_id': 'L011-022', 'course_id': 'COURSE-011', 'module_id': 'M011-02', 'title': 'AWS Serverless Networking & Security Boundaries', 'slug': 'aws-serverless-networking-and-security-boundaries', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply aws serverless networking & security boundaries concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['ALB security group', 'ECS task security group', 'frontend vs backend exposure', 'security-group references', 'restricting task ingress to ALB']

SOURCE_REFERENCES = ['BOOK-011 Chapters 9 and 10']

FIGURE_REFERENCES = [{'source_figure': 'Figure 10-6', 'title': 'ECS security group', 'priority': 'required', 'suggested_path': 'assets/m011-02/fig-10-6-ecs-security-group.png'}]

LESSON_MARKDOWN = '# L011-022 — AWS Serverless Networking & Security Boundaries\n\n## Learning objective\n\nApply aws serverless networking & security boundaries concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- ALB security group\n- ECS task security group\n- frontend vs backend exposure\n- security-group references\n- restricting task ingress to ALB\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n\n## Manual visual references\n- `Figure 10-6` — ECS security group (required); add manually at `assets/m011-02/fig-10-6-ecs-security-group.png`.\n'

EXERCISES = [{'id': 'L011-022-EX1', 'title': 'Apply AWS Serverless Networking & Security Boundaries', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: ALB security group, ECS task security group, frontend vs backend exposure. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-022-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to aws serverless networking & security boundaries. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-022-Q1', 'type': 'short_answer', 'question': 'What production problem is aws serverless networking & security boundaries intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: ALB security group, ECS task security group, frontend vs backend exposure.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-022-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-022-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by AWS Serverless Networking & Security Boundaries.', 'answer': 'ALB security group, ECS task security group', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
