"""Masar curriculum seed — L011-024."""

LESSON_META = {'lesson_id': 'L011-024', 'course_id': 'COURSE-011', 'module_id': 'M011-02', 'title': 'Restricting Alternate Access Paths on AWS', 'slug': 'restricting-alternate-access-paths-on-aws', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply restricting alternate access paths on aws concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['ALB generated DNS name', 'custom production domain', 'default fixed responses', 'HTTP 403', 'approved hostnames']

SOURCE_REFERENCES = ['BOOK-011 Chapters 9 and 10']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-024 — Restricting Alternate Access Paths on AWS\n\n## Learning objective\n\nApply restricting alternate access paths on aws concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- ALB generated DNS name\n- custom production domain\n- default fixed responses\n- HTTP 403\n- approved hostnames\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-024-EX1', 'title': 'Apply Restricting Alternate Access Paths on AWS', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: ALB generated DNS name, custom production domain, default fixed responses. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-024-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to restricting alternate access paths on aws. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-024-Q1', 'type': 'short_answer', 'question': 'What production problem is restricting alternate access paths on aws intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: ALB generated DNS name, custom production domain, default fixed responses.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-024-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-024-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Restricting Alternate Access Paths on AWS.', 'answer': 'ALB generated DNS name, custom production domain', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
