"""Masar curriculum seed — L011-011."""

LESSON_META = {'lesson_id': 'L011-011', 'course_id': 'COURSE-011', 'module_id': 'M011-02', 'title': 'Designing Stateless AI Services for Serverless Deployment', 'slug': 'designing-stateless-ai-services-for-serverless-deployment', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply designing stateless ai services for serverless deployment concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['externalizing persistent state', 'ephemeral filesystems', 'external databases/vector stores/object storage', 'session-state considerations', 'serverless-friendly AI service design']

SOURCE_REFERENCES = ['BOOK-011 Chapters 9 and 10']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-011 — Designing Stateless AI Services for Serverless Deployment\n\n## Learning objective\n\nApply designing stateless ai services for serverless deployment concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- externalizing persistent state\n- ephemeral filesystems\n- external databases/vector stores/object storage\n- session-state considerations\n- serverless-friendly AI service design\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-011-EX1', 'title': 'Apply Designing Stateless AI Services for Serverless Deployment', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: externalizing persistent state, ephemeral filesystems, external databases/vector stores/object storage. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-011-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to designing stateless ai services for serverless deployment. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-011-Q1', 'type': 'short_answer', 'question': 'What production problem is designing stateless ai services for serverless deployment intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: externalizing persistent state, ephemeral filesystems, external databases/vector stores/object storage.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-011-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-011-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Designing Stateless AI Services for Serverless Deployment.', 'answer': 'externalizing persistent state, ephemeral filesystems', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
