"""Masar curriculum seed — L011-014."""

LESSON_META = {'lesson_id': 'L011-014', 'course_id': 'COURSE-011', 'module_id': 'M011-02', 'title': 'Cloud Run Autoscaling, Cold Starts & Monitoring', 'slug': 'cloud-run-autoscaling-cold-starts-and-monitoring', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply cloud run autoscaling, cold starts & monitoring concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['minimum instances', 'cold-start trade-offs', 'request latency', 'container instance count', 'Cloud Run metrics and logs']

SOURCE_REFERENCES = ['BOOK-011 Chapters 9 and 10']

FIGURE_REFERENCES = [{'source_figure': 'Figure 9-2', 'title': 'Cloud Run service metrics dashboard', 'priority': 'required', 'suggested_path': 'assets/m011-02/fig-9-2-cloud-run-metrics.png'}, {'source_figure': 'Figure 9-3', 'title': 'Cloud Run minimum autoscaling instances', 'priority': 'optional', 'suggested_path': 'assets/m011-02/fig-9-3-cloud-run-min-instances.png'}]

LESSON_MARKDOWN = '# L011-014 — Cloud Run Autoscaling, Cold Starts & Monitoring\n\n## Learning objective\n\nApply cloud run autoscaling, cold starts & monitoring concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- minimum instances\n- cold-start trade-offs\n- request latency\n- container instance count\n- Cloud Run metrics and logs\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n\n## Manual visual references\n- `Figure 9-2` — Cloud Run service metrics dashboard (required); add manually at `assets/m011-02/fig-9-2-cloud-run-metrics.png`.\n- `Figure 9-3` — Cloud Run minimum autoscaling instances (optional); add manually at `assets/m011-02/fig-9-3-cloud-run-min-instances.png`.\n'

EXERCISES = [{'id': 'L011-014-EX1', 'title': 'Apply Cloud Run Autoscaling, Cold Starts & Monitoring', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: minimum instances, cold-start trade-offs, request latency. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-014-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to cloud run autoscaling, cold starts & monitoring. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-014-Q1', 'type': 'short_answer', 'question': 'What production problem is cloud run autoscaling, cold starts & monitoring intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: minimum instances, cold-start trade-offs, request latency.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-014-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-014-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Cloud Run Autoscaling, Cold Starts & Monitoring.', 'answer': 'minimum instances, cold-start trade-offs', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
