"""M08.L01 — Image Classification and Modern ConvNet Architecture.

One Topic -> one complete learner-facing Lesson + inline Exercises + lesson Quiz.
BOOK-002, Chapters 8–9, page ranges not provided in supplied sources.
Instructor-authored curriculum adaptation.
"""

from app.models.learning import DifficultyLevel


# ---------------------------------------------------------------------------
# Lesson metadata
# ---------------------------------------------------------------------------

LESSON_CODE = "M08.L01"

MODULE_ORDER = 8

MODULE_TITLE = "Image Classification and Modern ConvNet Architecture"

MODULE_DESCRIPTION = (
    "Learn how convolutional neural networks represent images, how to train "
    "image classifiers on small datasets, how to reuse pretrained visual "
    "features through feature extraction and fine-tuning, and how modern "
    "ConvNet architecture patterns such as residual connections, batch "
    "normalization, and depthwise separable convolutions improve image models."
)

SOURCE_CHAPTER = "8–9"

SOURCE_PAGES = "Chapters 8–9 — page ranges not provided"


# ---------------------------------------------------------------------------
# Topic
# ---------------------------------------------------------------------------

TOPIC = {
    "title": "Image Classification with ConvNets: From Foundations to Modern Architectures",

    "slug": "deep-learning-foundations-m08-l01",

    "description": (
        "Build an intuitive and practical understanding of convolutional "
        "neural networks, small-data image classification, data augmentation, "
        "transfer learning, fine-tuning, residual connections, batch "
        "normalization, and efficient convolutional architectures."
    ),

    "order": 1,

    "difficulty": DifficultyLevel.beginner,

    "estimated_hours": 3.0,

    "skill_tags": [
        "deep-learning",
        "computer-vision",
        "image-classification",
        "convnets",
        "convolution",
        "max-pooling",
        "data-augmentation",
        "transfer-learning",
        "feature-extraction",
        "fine-tuning",
        "residual-connections",
        "batch-normalization",
        "separable-convolution",
        "module-08",
    ],

    "prerequisite_ids": [],


    # =======================================================================
    # LESSON
    # =======================================================================

    "lesson": {
        "title": "Image Classification with ConvNets: From Foundations to Modern Architectures",

        "content": (
            "# Image Classification with ConvNets: From Foundations to Modern Architectures\n"
            "\n"
            "> **Course:** Deep Learning Foundations  \n"
            "> **Lesson:** M08.L01  \n"
            "> **Module:** Image Classification and Modern ConvNet Architecture  \n"
            "> **Source alignment:** BOOK-002, Chapters 8–9. "
            "The supplied sources did not specify page ranges. "
            "This lesson is an instructor-authored curriculum adaptation "
            "rather than a reproduction of the source text.\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Learning outcomes
            # ----------------------------------------------------------------

            "## Learning outcomes\n"
            "\n"
            "By the end of this lesson, you should be able to:\n"
            "\n"
            "- Explain why ConvNets are well suited to image data.\n"
            "- Distinguish local visual patterns from the global patterns "
            "learned by ordinary Dense layers.\n"
            "- Explain feature maps, filters, convolution kernels, padding, "
            "strides, and max pooling.\n"
            "- Trace how image tensor shapes change through a ConvNet.\n"
            "- Explain why spatial feature-map size usually decreases while "
            "channel depth increases.\n"
            "- Build the mental model for a basic image-classification ConvNet.\n"
            "- Explain why small image datasets are especially vulnerable to "
            "overfitting.\n"
            "- Use data augmentation conceptually to improve generalization.\n"
            "- Explain feature extraction using a pretrained backbone.\n"
            "- Explain why pretrained layers are frozen before training a new "
            "classifier head.\n"
            "- Describe the correct fine-tuning sequence.\n"
            "- Explain why fine-tuning uses a small learning rate.\n"
            "- Explain the modularity-hierarchy-reuse principle.\n"
            "- Explain how residual connections help train deep networks.\n"
            "- Explain the purpose and behavior of batch normalization.\n"
            "- Explain depthwise separable convolution and why it can be more "
            "parameter efficient than ordinary convolution.\n"
            "- Recognize the design pattern used by modern ConvNets.\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Section 1
            # ----------------------------------------------------------------

            "## 1. How Convolutional Neural Networks Understand Images\n"
            "\n"
            "Images have an important structure that ordinary tabular data "
            "does not have: nearby pixels are related to one another.\n"
            "\n"
            "A convolutional neural network, or **ConvNet**, takes advantage "
            "of this spatial structure.\n"
            "\n"
            "A basic image-classification pipeline looks like:\n"
            "\n"
            "```text\n"
            "Image\n"
            "  ↓\n"
            "Convolution\n"
            "  ↓\n"
            "Feature maps\n"
            "  ↓\n"
            "Pooling\n"
            "  ↓\n"
            "More convolution\n"
            "  ↓\n"
            "Higher-level features\n"
            "  ↓\n"
            "Global pooling\n"
            "  ↓\n"
            "Classifier\n"
            "  ↓\n"
            "Class probabilities\n"
            "```\n"
            "\n"
            "### A first ConvNet\n"
            "\n"
            "For MNIST digit classification, a simple network can look like:\n"
            "\n"
            "```python\n"
            "inputs = keras.Input(shape=(28, 28, 1))\n"
            "\n"
            "x = layers.Conv2D(64, 3, activation=\"relu\")(inputs)\n"
            "x = layers.MaxPooling2D(2)(x)\n"
            "\n"
            "x = layers.Conv2D(128, 3, activation=\"relu\")(x)\n"
            "x = layers.MaxPooling2D(2)(x)\n"
            "\n"
            "x = layers.Conv2D(256, 3, activation=\"relu\")(x)\n"
            "x = layers.GlobalAveragePooling2D()(x)\n"
            "\n"
            "outputs = layers.Dense(10, activation=\"softmax\")(x)\n"
            "\n"
            "model = keras.Model(inputs, outputs)\n"
            "```\n"
            "\n"
            "The input shape is:\n"
            "\n"
            "```text\n"
            "(height, width, channels)\n"
            "\n"
            "(28, 28, 1)\n"
            "```\n"
            "\n"
            "The final dimension is 1 because MNIST images are grayscale.\n"
            "\n"
            "For an RGB image, the channel dimension would normally be 3:\n"
            "\n"
            "```text\n"
            "(height, width, 3)\n"
            "```\n"
            "\n"
            "### Why convolution instead of only Dense layers?\n"
            "\n"
            "A Dense layer learns relationships across its entire input "
            "representation at once.\n"
            "\n"
            "A convolutional layer instead looks at small local regions.\n"
            "\n"
            "For example, a 3 × 3 convolution examines small image patches:\n"
            "\n"
            "```text\n"
            "Image\n"
            "\n"
            "┌─────────────────┐\n"
            "│                 │\n"
            "│    ┌─────┐      │\n"
            "│    │3 × 3│      │\n"
            "│    └─────┘      │\n"
            "│                 │\n"
            "└─────────────────┘\n"
            "```\n"
            "\n"
            "The same learned detector is reused at many locations throughout "
            "the image.\n"
            "\n"
            "This gives ConvNets two extremely useful properties.\n"
            "\n"
            "### Property 1: translation invariance\n"
            "\n"
            "Suppose the network learns a detector for a certain edge.\n"
            "\n"
            "That detector can recognize the edge whether it appears near the "
            "top-left, center, or bottom-right of the image.\n"
            "\n"
            "Conceptually:\n"
            "\n"
            "```text\n"
            "learn pattern once\n"
            "      ↓\n"
            "reuse detector across image locations\n"
            "```\n"
            "\n"
            "This is much more data efficient than relearning the same visual "
            "pattern independently for every possible image position.\n"
            "\n"
            "### Property 2: spatial feature hierarchies\n"
            "\n"
            "Visual concepts naturally form hierarchies.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "pixels\n"
            "  ↓\n"
            "edges and textures\n"
            "  ↓\n"
            "simple shapes\n"
            "  ↓\n"
            "eyes / ears / wheels\n"
            "  ↓\n"
            "faces / animals / objects\n"
            "```\n"
            "\n"
            "Earlier convolutional layers tend to represent simple local "
            "patterns.\n"
            "\n"
            "Deeper layers combine them into more abstract concepts.\n"
            "\n"
            "### Feature maps\n"
            "\n"
            "The output of a convolutional layer is called a **feature map**.\n"
            "\n"
            "A feature map normally has shape:\n"
            "\n"
            "```text\n"
            "(height, width, channels)\n"
            "```\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "(26, 26, 64)\n"
            "```\n"
            "\n"
            "means:\n"
            "\n"
            "```text\n"
            "26 positions vertically\n"
            "26 positions horizontally\n"
            "64 learned feature channels\n"
            "```\n"
            "\n"
            "The channels no longer mean RGB colors.\n"
            "\n"
            "Instead, each channel represents the response of a learned "
            "feature detector.\n"
            "\n"
            "One channel may respond strongly to one kind of texture, another "
            "to a particular edge orientation, and deeper channels may respond "
            "to more complicated structures.\n"
            "\n"
            "### What is a filter?\n"
            "\n"
            "A convolutional layer contains multiple learned filters.\n"
            "\n"
            "Each filter scans local patches and produces one output feature "
            "channel.\n"
            "\n"
            "So if a layer has:\n"
            "\n"
            "```python\n"
            "layers.Conv2D(filters=64, kernel_size=3)\n"
            "```\n"
            "\n"
            "then:\n"
            "\n"
            "```text\n"
            "kernel size = 3 × 3\n"
            "number of output feature channels = 64\n"
            "```\n"
            "\n"
            "### The convolution kernel is reused\n"
            "\n"
            "The same learned kernel is applied to every valid spatial patch.\n"
            "\n"
            "This parameter sharing is a major reason ConvNets can represent "
            "visual patterns efficiently.\n"
            "\n"
            "### Padding\n"
            "\n"
            "A convolution can shrink spatial dimensions because the kernel "
            "cannot be centered at every border pixel without going beyond "
            "the image.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "5 × 5 input\n"
            "+ 3 × 3 convolution\n"
            "+ no padding\n"
            "→ 3 × 3 output\n"
            "```\n"
            "\n"
            "Two common padding modes are:\n"
            "\n"
            "```text\n"
            "padding=\"valid\"\n"
            "→ no padding\n"
            "→ spatial dimensions may shrink\n"
            "\n"
            "padding=\"same\"\n"
            "→ add border values\n"
            "→ preserve width and height when stride = 1\n"
            "```\n"
            "\n"
            "### Strides\n"
            "\n"
            "The **stride** controls how far the convolution window moves each "
            "time.\n"
            "\n"
            "With:\n"
            "\n"
            "```text\n"
            "stride = 1\n"
            "```\n"
            "\n"
            "the window moves one position at a time.\n"
            "\n"
            "With:\n"
            "\n"
            "```text\n"
            "stride = 2\n"
            "```\n"
            "\n"
            "it skips positions and therefore reduces the spatial size more "
            "aggressively.\n"
            "\n"
            "### Max pooling\n"
            "\n"
            "Image classifiers often downsample feature maps with max pooling.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "26 × 26 feature map\n"
            "       ↓ 2 × 2 max pooling\n"
            "13 × 13 feature map\n"
            "```\n"
            "\n"
            "For every small region, max pooling keeps the largest activation.\n"
            "\n"
            "If a local patch contains:\n"
            "\n"
            "```text\n"
            "[1, 7]\n"
            "[2, 4]\n"
            "```\n"
            "\n"
            "max pooling outputs:\n"
            "\n"
            "```text\n"
            "7\n"
            "```\n"
            "\n"
            "The intuition is that a feature map often represents the presence "
            "of some pattern. Keeping the strongest local activation preserves "
            "evidence that the pattern was present while reducing spatial size.\n"
            "\n"
            "### Why reduce spatial dimensions?\n"
            "\n"
            "As the network gets deeper, we want higher-level feature detectors "
            "to see increasingly larger regions of the original image.\n"
            "\n"
            "A common ConvNet progression is therefore:\n"
            "\n"
            "```text\n"
            "spatial dimensions ↓\n"
            "channel depth      ↑\n"
            "```\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "180 × 180 × 3\n"
            "       ↓\n"
            "178 × 178 × 32\n"
            "       ↓\n"
            "89 × 89 × 32\n"
            "       ↓\n"
            "87 × 87 × 64\n"
            "       ↓\n"
            "...\n"
            "       ↓\n"
            "7 × 7 × 512\n"
            "```\n"
            "\n"
            "The model gradually converts detailed spatial information into "
            "richer semantic feature channels.\n"
            "\n"
            "### Global average pooling\n"
            "\n"
            "A Dense classifier expects a vector rather than a 3D feature map.\n"
            "\n"
            "`GlobalAveragePooling2D` averages each feature channel across "
            "its spatial positions.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "(3, 3, 256)\n"
            "      ↓ GlobalAveragePooling2D\n"
            "(256,)\n"
            "```\n"
            "\n"
            "Each output value summarizes how strongly one learned feature "
            "was present across the image.\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Section 2
            # ----------------------------------------------------------------

            "## 2. Training an Image Classifier with a Small Dataset\n"
            "\n"
            "A common real-world problem is having only a few thousand labeled "
            "images rather than millions.\n"
            "\n"
            "The chapter uses dogs-versus-cats classification to demonstrate "
            "the problem.\n"
            "\n"
            "The smaller working dataset contains:\n"
            "\n"
            "```text\n"
            "Training   → 2,000 images\n"
            "Validation → 1,000 images\n"
            "Test       → 2,000 images\n"
            "```\n"
            "\n"
            "Both classes are evenly represented.\n"
            "\n"
            "### Building a ConvNet from scratch\n"
            "\n"
            "A basic model uses alternating convolution and pooling stages:\n"
            "\n"
            "```python\n"
            "inputs = keras.Input(shape=(180, 180, 3))\n"
            "\n"
            "x = layers.Rescaling(1.0 / 255)(inputs)\n"
            "\n"
            "x = layers.Conv2D(32, 3, activation=\"relu\")(x)\n"
            "x = layers.MaxPooling2D(2)(x)\n"
            "\n"
            "x = layers.Conv2D(64, 3, activation=\"relu\")(x)\n"
            "x = layers.MaxPooling2D(2)(x)\n"
            "\n"
            "x = layers.Conv2D(128, 3, activation=\"relu\")(x)\n"
            "x = layers.MaxPooling2D(2)(x)\n"
            "\n"
            "x = layers.Conv2D(256, 3, activation=\"relu\")(x)\n"
            "x = layers.MaxPooling2D(2)(x)\n"
            "\n"
            "x = layers.Conv2D(512, 3, activation=\"relu\")(x)\n"
            "x = layers.GlobalAveragePooling2D()(x)\n"
            "\n"
            "outputs = layers.Dense(1, activation=\"sigmoid\")(x)\n"
            "\n"
            "model = keras.Model(inputs, outputs)\n"
            "```\n"
            "\n"
            "Notice the architecture pattern:\n"
            "\n"
            "```text\n"
            "feature-map width / height ↓\n"
            "number of channels         ↑\n"
            "```\n"
            "\n"
            "Because this is binary classification, the final layer is:\n"
            "\n"
            "```python\n"
            "Dense(1, activation=\"sigmoid\")\n"
            "```\n"
            "\n"
            "and the loss is:\n"
            "\n"
            "```text\n"
            "binary_crossentropy\n"
            "```\n"
            "\n"
            "### Image preprocessing pipeline\n"
            "\n"
            "Images on disk begin as files such as JPEGs.\n"
            "\n"
            "Before a neural network can train on them, the pipeline needs to:\n"
            "\n"
            "```text\n"
            "read image file\n"
            "    ↓\n"
            "decode JPEG\n"
            "    ↓\n"
            "convert to pixel tensor\n"
            "    ↓\n"
            "resize to shared dimensions\n"
            "    ↓\n"
            "group into batches\n"
            "    ↓\n"
            "feed model\n"
            "```\n"
            "\n"
            "Keras can create this pipeline directly from class directories:\n"
            "\n"
            "```python\n"
            "from keras.utils import image_dataset_from_directory\n"
            "\n"
            "train_dataset = image_dataset_from_directory(\n"
            "    train_dir,\n"
            "    image_size=(180, 180),\n"
            "    batch_size=64,\n"
            ")\n"
            "```\n"
            "\n"
            "A batch might therefore have shape:\n"
            "\n"
            "```text\n"
            "images → (64, 180, 180, 3)\n"
            "labels → (64,)\n"
            "```\n"
            "\n"
            "### Saving the best model\n"
            "\n"
            "When training for many epochs, the best model is not always the "
            "model from the final epoch.\n"
            "\n"
            "A checkpoint can save the model whenever validation loss improves:\n"
            "\n"
            "```python\n"
            "keras.callbacks.ModelCheckpoint(\n"
            "    filepath=\"best_model.keras\",\n"
            "    save_best_only=True,\n"
            "    monitor=\"val_loss\",\n"
            ")\n"
            "```\n"
            "\n"
            "This becomes especially important when overfitting begins.\n"
            "\n"
            "### Small datasets and overfitting\n"
            "\n"
            "Training a large neural network on only a few thousand images "
            "creates a major risk:\n"
            "\n"
            "```text\n"
            "training accuracy → keeps increasing\n"
            "validation accuracy → stops improving\n"
            "training loss → keeps decreasing\n"
            "validation loss → begins increasing\n"
            "```\n"
            "\n"
            "The model is learning details specific to the training images "
            "instead of learning patterns that generalize.\n"
            "\n"
            "In the chapter's initial dogs-versus-cats experiment, the "
            "training accuracy approaches 100%, while validation performance "
            "levels off much earlier.\n"
            "\n"
            "This is classic overfitting.\n"
            "\n"
            "### Data augmentation\n"
            "\n"
            "One of the most important regularization techniques for image "
            "models is **data augmentation**.\n"
            "\n"
            "Instead of showing the exact same image every epoch, randomly "
            "transform it in believable ways.\n"
            "\n"
            "Examples include:\n"
            "\n"
            "```text\n"
            "horizontal flipping\n"
            "small rotations\n"
            "small zoom changes\n"
            "```\n"
            "\n"
            "For example:\n"
            "\n"
            "```python\n"
            "data_augmentation_layers = [\n"
            "    layers.RandomFlip(\"horizontal\"),\n"
            "    layers.RandomRotation(0.1),\n"
            "    layers.RandomZoom(0.2),\n"
            "]\n"
            "```\n"
            "\n"
            "The model may see different variations of the same original image:\n"
            "\n"
            "```text\n"
            "original dog\n"
            "   ↓\n"
            "slightly rotated dog\n"
            "flipped dog\n"
            "zoomed dog\n"
            "```\n"
            "\n"
            "The class does not change, but the visual presentation does.\n"
            "\n"
            "This encourages the model to focus on robust patterns rather "
            "than memorizing exact pixel arrangements.\n"
            "\n"
            "### Augmentation does not create truly new information\n"
            "\n"
            "This distinction is important.\n"
            "\n"
            "Data augmentation creates new **variations**, but all variations "
            "still come from the same limited set of original images.\n"
            "\n"
            "So augmentation reduces overfitting, but it cannot fully replace "
            "collecting genuinely new training examples.\n"
            "\n"
            "### Combining augmentation and dropout\n"
            "\n"
            "The chapter also adds dropout before the classifier:\n"
            "\n"
            "```python\n"
            "x = layers.GlobalAveragePooling2D()(x)\n"
            "x = layers.Dropout(0.25)(x)\n"
            "outputs = layers.Dense(1, activation=\"sigmoid\")(x)\n"
            "```\n"
            "\n"
            "Together:\n"
            "\n"
            "```text\n"
            "data augmentation\n"
            "+\n"
            "dropout\n"
            "      ↓\n"
            "slower overfitting\n"
            "      ↓\n"
            "better validation performance\n"
            "```\n"
            "\n"
            "Data augmentation is used during training, not when evaluating "
            "the unchanged validation or test images.\n"
            "\n"

            # Exercise EX01 is rendered here by the frontend.
            "{{exercise:M08.L01.EX01}}\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Section 3
            # ----------------------------------------------------------------

            "## 3. Reusing a Pretrained ConvNet\n"
            "\n"
            "When you only have a small dataset, training every visual feature "
            "detector from random initialization can be inefficient.\n"
            "\n"
            "A powerful alternative is **transfer learning**.\n"
            "\n"
            "The central idea is:\n"
            "\n"
            "> A network trained on a large image dataset may already have "
            "learned useful visual features that can be reused for your new task.\n"
            "\n"
            "### Why visual features can be reused\n"
            "\n"
            "Early convolutional layers often learn generic patterns such as:\n"
            "\n"
            "```text\n"
            "edges\n"
            "colors\n"
            "textures\n"
            "simple shapes\n"
            "```\n"
            "\n"
            "Higher layers learn more task-specific concepts such as:\n"
            "\n"
            "```text\n"
            "eyes\n"
            "ears\n"
            "fur patterns\n"
            "object parts\n"
            "```\n"
            "\n"
            "This means a network trained on one large image dataset can often "
            "provide useful features for another image task.\n"
            "\n"
            "### Backbone and classifier head\n"
            "\n"
            "An image classifier can be thought of as two parts:\n"
            "\n"
            "```text\n"
            "Image\n"
            "  ↓\n"
            "Pretrained backbone\n"
            "  ↓\n"
            "Feature representation\n"
            "  ↓\n"
            "Task-specific classifier\n"
            "```\n"
            "\n"
            "The **backbone** is the feature extractor.\n"
            "\n"
            "The classifier head converts those features into predictions for "
            "your specific classes.\n"
            "\n"
            "### Feature extraction\n"
            "\n"
            "Feature extraction means:\n"
            "\n"
            "1. Use the pretrained backbone to compute features.\n"
            "2. Keep the pretrained representation fixed.\n"
            "3. Train a new classifier using those features.\n"
            "\n"
            "Conceptually:\n"
            "\n"
            "```text\n"
            "Pretrained network\n"
            "\n"
            "[generic visual feature extractor]\n"
            "              ↓\n"
            "         keep this\n"
            "\n"
            "[old classifier]\n"
            "              ↓\n"
            "         remove this\n"
            "\n"
            "add new task-specific classifier\n"
            "```\n"
            "\n"
            "### Why not normally reuse the old classifier?\n"
            "\n"
            "The old classifier is specialized for the classes of the original "
            "training task.\n"
            "\n"
            "The backbone is more reusable because it contains spatial visual "
            "representations rather than only final class decisions.\n"
            "\n"
            "### Fast feature extraction\n"
            "\n"
            "One approach is to run every image through the pretrained backbone "
            "once and save the resulting features.\n"
            "\n"
            "For example, your images may become feature tensors with shape:\n"
            "\n"
            "```text\n"
            "(samples, 6, 6, 2048)\n"
            "```\n"
            "\n"
            "Then train a small classifier:\n"
            "\n"
            "```python\n"
            "inputs = keras.Input(shape=(6, 6, 2048))\n"
            "x = layers.GlobalAveragePooling2D()(inputs)\n"
            "x = layers.Dense(256, activation=\"relu\")(x)\n"
            "x = layers.Dropout(0.25)(x)\n"
            "outputs = layers.Dense(1, activation=\"sigmoid\")(x)\n"
            "```\n"
            "\n"
            "This is computationally cheap because the expensive pretrained "
            "backbone is only executed once per image.\n"
            "\n"
            "The limitation is important:\n"
            "\n"
            "> You cannot naturally apply new random augmentation every epoch "
            "after the features have already been saved.\n"
            "\n"
            "### Feature extraction with augmentation\n"
            "\n"
            "The alternative is to keep the backbone inside the training model.\n"
            "\n"
            "Now each randomly augmented image passes through the backbone "
            "during training.\n"
            "\n"
            "This costs more computation, but allows augmentation.\n"
            "\n"
            "### Freezing the pretrained backbone\n"
            "\n"
            "Before training the newly added classifier, freeze the pretrained "
            "base:\n"
            "\n"
            "```python\n"
            "conv_base.trainable = False\n"
            "```\n"
            "\n"
            "Why?\n"
            "\n"
            "The new classifier begins with random parameters.\n"
            "\n"
            "Early training therefore produces large, noisy errors.\n"
            "\n"
            "If those updates immediately flow through the pretrained backbone, "
            "they can destroy useful visual representations that took large-scale "
            "training to learn.\n"
            "\n"
            "So initially:\n"
            "\n"
            "```text\n"
            "pretrained backbone\n"
            "→ FROZEN\n"
            "\n"
            "new classifier\n"
            "→ TRAINABLE\n"
            "```\n"
            "\n"
            "### Fine-tuning\n"
            "\n"
            "Once the new classifier has learned to use the pretrained "
            "features, you can carefully adapt the pretrained representation "
            "to the new problem.\n"
            "\n"
            "This is called **fine-tuning**.\n"
            "\n"
            "The correct sequence is important:\n"
            "\n"
            "```text\n"
            "1. Load pretrained backbone\n"
            "2. Add new classifier\n"
            "3. Freeze backbone\n"
            "4. Train new classifier\n"
            "5. Unfreeze some or all appropriate backbone layers\n"
            "6. Recompile the model\n"
            "7. Continue training with a very small learning rate\n"
            "```\n"
            "\n"
            "### Why use a small learning rate?\n"
            "\n"
            "Fine-tuning should **adjust** good pretrained features, not replace "
            "them with large random changes.\n"
            "\n"
            "For example:\n"
            "\n"
            "```python\n"
            "optimizer = keras.optimizers.Adam(learning_rate=1e-5)\n"
            "```\n"
            "\n"
            "A small learning rate makes changes to pretrained representations "
            "more gradual.\n"
            "\n"
            "### Partial fine-tuning\n"
            "\n"
            "You do not always need to unfreeze the entire backbone.\n"
            "\n"
            "A useful strategy is:\n"
            "\n"
            "```text\n"
            "early layers\n"
            "→ keep frozen\n"
            "→ generic edges / textures\n"
            "\n"
            "later layers\n"
            "→ fine-tune\n"
            "→ more task-specific visual concepts\n"
            "```\n"
            "\n"
            "For example:\n"
            "\n"
            "```python\n"
            "conv_base.trainable = True\n"
            "\n"
            "for layer in conv_base.layers[:-4]:\n"
            "    layer.trainable = False\n"
            "```\n"
            "\n"
            "This reduces the number of parameters being adjusted and can lower "
            "the risk of overfitting on a small dataset.\n"
            "\n"
            "### Batch normalization during fine-tuning\n"
            "\n"
            "A special caution applies to pretrained "
            "`BatchNormalization` layers.\n"
            "\n"
            "The source recommends leaving these layers frozen during "
            "fine-tuning so that their internal statistics are not destabilized "
            "by the small fine-tuning updates.\n"
            "\n"
            "### The practical small-data toolbox\n"
            "\n"
            "For a small image dataset, you now have three progressively more "
            "powerful strategies:\n"
            "\n"
            "```text\n"
            "1. Train a small ConvNet from scratch\n"
            "        ↓\n"
            "2. Use a pretrained backbone for feature extraction\n"
            "        ↓\n"
            "3. Fine-tune pretrained representations\n"
            "```\n"
            "\n"
            "The chapter's dogs-versus-cats experiments illustrate why "
            "pretrained visual features can dramatically outperform training "
            "from scratch when only a small amount of data is available.\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Section 4
            # ----------------------------------------------------------------

            "## 4. Modern ConvNet Architecture Patterns\n"
            "\n"
            "Understanding convolution is only the beginning.\n"
            "\n"
            "The way layers are arranged has a major effect on whether a "
            "network trains efficiently and generalizes well.\n"
            "\n"
            "This is **model architecture**.\n"
            "\n"
            "Architecture defines the search space within which gradient "
            "descent tries to find a useful solution.\n"
            "\n"
            "A good architecture makes that search easier.\n"
            "\n"
            "### Modularity, hierarchy, and reuse\n"
            "\n"
            "The chapter introduces a useful general design principle:\n"
            "\n"
            "```text\n"
            "Modularity\n"
            "+\n"
            "Hierarchy\n"
            "+\n"
            "Reuse\n"
            "```\n"
            "\n"
            "or **MHR**.\n"
            "\n"
            "#### Modularity\n"
            "\n"
            "Organize the model into reusable blocks rather than treating it "
            "as one long unstructured list of layers.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "Block 1\n"
            "  Conv\n"
            "  Conv\n"
            "  Pool\n"
            "\n"
            "Block 2\n"
            "  Conv\n"
            "  Conv\n"
            "  Pool\n"
            "```\n"
            "\n"
            "#### Hierarchy\n"
            "\n"
            "Stack blocks so representations become progressively more abstract.\n"
            "\n"
            "```text\n"
            "local edges\n"
            "   ↓\n"
            "textures\n"
            "   ↓\n"
            "object parts\n"
            "   ↓\n"
            "high-level concepts\n"
            "```\n"
            "\n"
            "#### Reuse\n"
            "\n"
            "Use the same useful design pattern repeatedly.\n"
            "\n"
            "Convolution itself is an example of reuse because the same filter "
            "is applied across different spatial positions.\n"
            "\n"
            "### Feature pyramids\n"
            "\n"
            "A common modern ConvNet pattern is:\n"
            "\n"
            "```text\n"
            "early network\n"
            "large spatial maps\n"
            "few channels\n"
            "\n"
            "       ↓\n"
            "\n"
            "deep network\n"
            "small spatial maps\n"
            "many channels\n"
            "```\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "32 filters\n"
            "  ↓\n"
            "64 filters\n"
            "  ↓\n"
            "128 filters\n"
            "  ↓\n"
            "256 filters\n"
            "  ↓\n"
            "512 filters\n"
            "```\n"
            "\n"
            "while width and height decrease.\n"
            "\n"
            "### Deep and narrow versus shallow and broad\n"
            "\n"
            "Deep networks can build abstraction progressively and reuse "
            "features across many levels.\n"
            "\n"
            "The source therefore presents the general design preference:\n"
            "\n"
            "```text\n"
            "deeper hierarchy of narrower layers\n"
            "rather than\n"
            "a very shallow network with extremely broad layers\n"
            "```\n"
            "\n"
            "But increasing depth creates a new problem.\n"
            "\n"
            "### Vanishing gradients\n"
            "\n"
            "Training a deep network requires gradient information to travel "
            "backward through many transformations.\n"
            "\n"
            "Conceptually:\n"
            "\n"
            "```text\n"
            "forward:\n"
            "x → f1 → f2 → f3 → f4 → prediction\n"
            "\n"
            "backward:\n"
            "loss → f4 → f3 → f2 → f1\n"
            "```\n"
            "\n"
            "When the chain becomes very deep, useful gradient information may "
            "become progressively weaker or noisier.\n"
            "\n"
            "This is the **vanishing-gradient problem**.\n"
            "\n"
            "### Residual connections\n"
            "\n"
            "A residual connection creates an information shortcut around a "
            "block.\n"
            "\n"
            "Instead of only computing:\n"
            "\n"
            "```text\n"
            "x → block → output\n"
            "```\n"
            "\n"
            "we also preserve the original input:\n"
            "\n"
            "```text\n"
            "       ┌───────────────┐\n"
            "       │               ↓\n"
            "x → processing block → + → output\n"
            "       │               ↑\n"
            "       └── shortcut ───┘\n"
            "```\n"
            "\n"
            "In pseudocode:\n"
            "\n"
            "```python\n"
            "residual = x\n"
            "x = block(x)\n"
            "x = layers.add([x, residual])\n"
            "```\n"
            "\n"
            "The shortcut preserves a clean path for information and gradient "
            "flow through deep networks.\n"
            "\n"
            "### Shape matching in residual connections\n"
            "\n"
            "The tensors being added must have compatible shapes.\n"
            "\n"
            "Suppose the processing block changes:\n"
            "\n"
            "```text\n"
            "32 channels\n"
            "→ 64 channels\n"
            "```\n"
            "\n"
            "The residual path must also be transformed.\n"
            "\n"
            "A 1 × 1 convolution can project it to the required channel count:\n"
            "\n"
            "```python\n"
            "residual = layers.Conv2D(64, 1)(residual)\n"
            "```\n"
            "\n"
            "If the main path also downsamples spatially, a stride can be used "
            "on the residual projection to match the new dimensions.\n"
            "\n"
            "### Batch normalization\n"
            "\n"
            "You already know about normalizing raw input data.\n"
            "\n"
            "But activations inside a neural network also change as data moves "
            "through layers.\n"
            "\n"
            "`BatchNormalization` normalizes intermediate activations "
            "adaptively during training.\n"
            "\n"
            "A common pattern is:\n"
            "\n"
            "```python\n"
            "x = layers.Conv2D(\n"
            "    32,\n"
            "    3,\n"
            "    use_bias=False,\n"
            ")(x)\n"
            "\n"
            "x = layers.BatchNormalization()(x)\n"
            "x = layers.Activation(\"relu\")(x)\n"
            "```\n"
            "\n"
            "The source recommends the ordering:\n"
            "\n"
            "```text\n"
            "convolution\n"
            "    ↓\n"
            "batch normalization\n"
            "    ↓\n"
            "activation\n"
            "```\n"
            "\n"
            "Batch normalization commonly helps gradient propagation and makes "
            "deep networks easier to train.\n"
            "\n"
            "During training, batch statistics are used.\n"
            "\n"
            "During inference, stored moving statistics collected during "
            "training are used instead.\n"
            "\n"
            "### Why remove the convolution bias before BatchNorm?\n"
            "\n"
            "A convolution normally computes something conceptually like:\n"
            "\n"
            "```text\n"
            "conv(x, kernel) + bias\n"
            "```\n"
            "\n"
            "But BatchNormalization performs a centering operation afterward.\n"
            "\n"
            "So when BatchNorm immediately follows a convolution, the "
            "convolution's bias is usually unnecessary:\n"
            "\n"
            "```python\n"
            "Conv2D(..., use_bias=False)\n"
            "```\n"
            "\n"
            "### Depthwise separable convolution\n"
            "\n"
            "A normal convolution learns spatial patterns and channel mixing "
            "together.\n"
            "\n"
            "A depthwise separable convolution separates these two jobs.\n"
            "\n"
            "```text\n"
            "Input feature map\n"
            "      ↓\n"
            "Depthwise convolution\n"
            "process spatial patterns within each channel\n"
            "      ↓\n"
            "1 × 1 pointwise convolution\n"
            "mix information across channels\n"
            "      ↓\n"
            "Output feature map\n"
            "```\n"
            "\n"
            "In Keras:\n"
            "\n"
            "```python\n"
            "layers.SeparableConv2D(...)\n"
            "```\n"
            "\n"
            "### Why separable convolution can be efficient\n"
            "\n"
            "Consider a regular 3 × 3 convolution with:\n"
            "\n"
            "```text\n"
            "64 input channels\n"
            "64 output channels\n"
            "```\n"
            "\n"
            "Its parameter count is proportional to:\n"
            "\n"
            "```text\n"
            "3 × 3 × 64 × 64\n"
            "= 36,864\n"
            "```\n"
            "\n"
            "A depthwise separable version uses approximately:\n"
            "\n"
            "```text\n"
            "(3 × 3 × 64)\n"
            "+\n"
            "(64 × 64)\n"
            "= 4,672\n"
            "```\n"
            "\n"
            "That is a large reduction in trainable parameters.\n"
            "\n"
            "Fewer parameters can mean:\n"
            "\n"
            "- a smaller model,\n"
            "- less computation in principle,\n"
            "- lower overfitting risk,\n"
            "- and efficient use of limited training data.\n"
            "\n"
            "The source also notes an important engineering reality: fewer "
            "theoretical operations do not automatically guarantee a matching "
            "GPU speedup because actual performance depends heavily on hardware "
            "and software kernel optimization.\n"
            "\n"
            "### Putting the architecture patterns together\n"
            "\n"
            "A modern block can combine:\n"
            "\n"
            "```text\n"
            "BatchNorm\n"
            "   ↓\n"
            "ReLU\n"
            "   ↓\n"
            "SeparableConv2D\n"
            "   ↓\n"
            "BatchNorm\n"
            "   ↓\n"
            "ReLU\n"
            "   ↓\n"
            "SeparableConv2D\n"
            "   ↓\n"
            "MaxPooling\n"
            "   ↓\n"
            "+ residual shortcut\n"
            "```\n"
            "\n"
            "Then repeat this block with increasing filter counts.\n"
            "\n"
            "A simplified Xception-like architecture looks like:\n"
            "\n"
            "```python\n"
            "inputs = keras.Input(shape=(180, 180, 3))\n"
            "x = layers.Rescaling(1.0 / 255)(inputs)\n"
            "\n"
            "# Regular convolution first because RGB channels are strongly related.\n"
            "x = layers.Conv2D(32, 5, use_bias=False)(x)\n"
            "\n"
            "for filters in [32, 64, 128, 256, 512]:\n"
            "    residual = x\n"
            "\n"
            "    x = layers.BatchNormalization()(x)\n"
            "    x = layers.Activation(\"relu\")(x)\n"
            "    x = layers.SeparableConv2D(\n"
            "        filters,\n"
            "        3,\n"
            "        padding=\"same\",\n"
            "        use_bias=False,\n"
            "    )(x)\n"
            "\n"
            "    x = layers.BatchNormalization()(x)\n"
            "    x = layers.Activation(\"relu\")(x)\n"
            "    x = layers.SeparableConv2D(\n"
            "        filters,\n"
            "        3,\n"
            "        padding=\"same\",\n"
            "        use_bias=False,\n"
            "    )(x)\n"
            "\n"
            "    x = layers.MaxPooling2D(\n"
            "        3,\n"
            "        strides=2,\n"
            "        padding=\"same\",\n"
            "    )(x)\n"
            "\n"
            "    residual = layers.Conv2D(\n"
            "        filters,\n"
            "        1,\n"
            "        strides=2,\n"
            "        padding=\"same\",\n"
            "        use_bias=False,\n"
            "    )(residual)\n"
            "\n"
            "    x = layers.add([x, residual])\n"
            "\n"
            "x = layers.GlobalAveragePooling2D()(x)\n"
            "x = layers.Dropout(0.5)(x)\n"
            "outputs = layers.Dense(1, activation=\"sigmoid\")(x)\n"
            "\n"
            "model = keras.Model(inputs, outputs)\n"
            "```\n"
            "\n"
            "The important lesson is not to memorize this code line by line.\n"
            "\n"
            "Instead, notice the design pattern:\n"
            "\n"
            "```text\n"
            "repeated blocks\n"
            "+\n"
            "increasing channel depth\n"
            "+\n"
            "decreasing spatial dimensions\n"
            "+\n"
            "residual connections\n"
            "+\n"
            "batch normalization\n"
            "+\n"
            "efficient convolution\n"
            "+\n"
            "global pooling\n"
            "+\n"
            "regularized classifier\n"
            "```\n"
            "\n"
            "### ConvNets and Vision Transformers\n"
            "\n"
            "ConvNets are not the only architecture used for computer vision.\n"
            "\n"
            "Vision Transformers, or ViTs, represent an image as a sequence of "
            "patches and use Transformer-style processing to model "
            "relationships between them.\n"
            "\n"
            "A simplified picture is:\n"
            "\n"
            "```text\n"
            "image\n"
            "  ↓\n"
            "split into patches\n"
            "  ↓\n"
            "convert patches to vectors\n"
            "  ↓\n"
            "process as a sequence\n"
            "```\n"
            "\n"
            "The chapter emphasizes that Vision Transformers can be especially "
            "effective at very large scale, while ConvNets retain strong "
            "spatial assumptions that make them highly data efficient, "
            "especially for smaller image-classification datasets.\n"
            "\n"

            # Exercise EX02 is rendered here by the frontend.
            "{{exercise:M08.L01.EX02}}\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Misconceptions
            # ----------------------------------------------------------------

            "## Important misconceptions\n"
            "\n"
            "### Misconception 1\n"
            "\n"
            "> A convolutional layer learns a completely different detector "
            "for every image position.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "The same convolution kernel is reused across spatial positions. "
            "This parameter sharing is one reason ConvNets can recognize a "
            "learned pattern in different parts of an image.\n"
            "\n"
            "### Misconception 2\n"
            "\n"
            "> Max pooling learns its own weight parameters.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Max pooling applies a fixed maximum operation to local regions. "
            "Unlike convolution, it does not learn a convolution kernel.\n"
            "\n"
            "### Misconception 3\n"
            "\n"
            "> Data augmentation creates entirely new independent information.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Augmentation generates useful variations of existing examples, "
            "but those examples remain correlated with the original data. "
            "It cannot fully replace collecting genuinely new images.\n"
            "\n"
            "### Misconception 4\n"
            "\n"
            "> When using a pretrained model, all layers should immediately be "
            "trained together with the new classifier.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "The new classifier begins randomly initialized. Large early "
            "updates can damage pretrained representations. The usual sequence "
            "is to freeze the backbone, train the new classifier, and only "
            "then fine-tune appropriate pretrained layers.\n"
            "\n"
            "### Misconception 5\n"
            "\n"
            "> Fine-tuning should use a large learning rate so the pretrained "
            "model can quickly learn the new task.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Fine-tuning is meant to make small adjustments to already useful "
            "representations. Large parameter updates can destroy those "
            "representations.\n"
            "\n"
            "### Misconception 6\n"
            "\n"
            "> Residual connections are only useful because they add more "
            "parameters.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "The core purpose of residual connections is to provide an "
            "information and gradient shortcut around processing blocks, "
            "making deeper networks easier to optimize.\n"
            "\n"
            "### Misconception 7\n"
            "\n"
            "> A lower theoretical FLOP count always guarantees proportionally "
            "faster execution on a GPU.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Actual runtime also depends on implementation quality, memory "
            "behavior, hardware, and how well specific operations have been "
            "optimized by the underlying software stack.\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Key terminology
            # ----------------------------------------------------------------

            "## Key terminology\n"
            "\n"
            "| Term | Meaning |\n"
            "|---|---|\n"
            "| ConvNet / CNN | Neural network designed to exploit local spatial structure in image-like data |\n"
            "| Convolution | Applying a learned local transformation repeatedly across spatial positions |\n"
            "| Kernel | Learned weights used by a convolution to transform local patches |\n"
            "| Filter | Learned feature detector that produces an output feature channel |\n"
            "| Feature map | Spatial map containing activations of learned visual features |\n"
            "| Channel | Depth dimension of an image or intermediate feature map |\n"
            "| Translation invariance | Ability to recognize a learned pattern across different spatial locations |\n"
            "| Spatial hierarchy | Progression from simple local patterns to increasingly abstract visual concepts |\n"
            "| Padding | Adding border values so convolution can control output spatial size |\n"
            "| Stride | Number of positions a convolution window moves at each step |\n"
            "| Max pooling | Downsampling operation that keeps the strongest local activation |\n"
            "| Global average pooling | Averaging each feature map into one value |\n"
            "| Data augmentation | Random realistic transformations used to create training variations |\n"
            "| Backbone | Pretrained or trainable feature-extraction portion of a model |\n"
            "| Feature extraction | Reusing fixed pretrained representations with a new classifier |\n"
            "| Freezing | Preventing selected model parameters from being updated |\n"
            "| Fine-tuning | Carefully updating pretrained parameters for a new task |\n"
            "| Transfer learning | Reusing knowledge learned on one task to help another task |\n"
            "| Residual connection | Shortcut that adds an earlier representation back to a block output |\n"
            "| Vanishing gradient | Loss of useful gradient signal as it passes through a deep chain of operations |\n"
            "| Batch normalization | Layer that adaptively normalizes intermediate activations |\n"
            "| Depthwise convolution | Spatial convolution performed independently for each channel |\n"
            "| Pointwise convolution | 1 × 1 convolution commonly used to mix channels |\n"
            "| SeparableConv2D | Depthwise convolution followed by pointwise channel mixing |\n"
            "| MHR | Modularity, hierarchy, and reuse architecture principle |\n"
            "| Vision Transformer | Vision architecture that processes an image as a sequence of patches |\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Self-check
            # ----------------------------------------------------------------

            "## Self-check\n"
            "\n"
            "Before continuing, make sure you can answer:\n"
            "\n"
            "1. Why do convolutional layers learn local rather than purely global patterns?\n"
            "2. What makes convolutional feature detectors reusable across image positions?\n"
            "3. What does a feature-map shape such as `(26, 26, 64)` mean?\n"
            "4. What is the difference between padding and stride?\n"
            "5. Why does max pooling reduce spatial dimensions?\n"
            "6. Why do ConvNets often increase channel count while reducing feature-map width and height?\n"
            "7. Why is overfitting especially important when training on a few thousand images?\n"
            "8. How does data augmentation help?\n"
            "9. Why does augmentation not truly replace collecting additional data?\n"
            "10. What is the difference between a pretrained backbone and a classifier head?\n"
            "11. Why should a pretrained backbone usually be frozen before training a new classifier?\n"
            "12. What is the correct order of steps for fine-tuning?\n"
            "13. Why should fine-tuning use a small learning rate?\n"
            "14. Why might you fine-tune only the upper layers of a backbone?\n"
            "15. What problem do residual connections help address?\n"
            "16. Why must residual and block-output shapes match before addition?\n"
            "17. Where does BatchNormalization commonly appear relative to convolution and activation?\n"
            "18. How does depthwise separable convolution differ from ordinary convolution?\n"
            "19. What does the modularity-hierarchy-reuse principle mean for ConvNet design?\n"
            "20. Why can ConvNets remain attractive when the available image dataset is relatively small?\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Retention statement
            # ----------------------------------------------------------------

            "## Retain this idea\n"
            "\n"
            "**A ConvNet learns reusable local visual patterns and combines "
            "them into increasingly abstract feature hierarchies. On small "
            "datasets, control overfitting with techniques such as augmentation "
            "and reuse visual knowledge through pretrained backbones and "
            "fine-tuning. As networks become deeper, architecture matters: "
            "repeated blocks, residual shortcuts, batch normalization, and "
            "parameter-efficient convolutions make modern image models easier "
            "to train and more effective.**\n"
            "\n"
            "Keep this progression in mind:\n"
            "\n"
            "```text\n"
            "IMAGE\n"
            "  ↓\n"
            "local convolutional features\n"
            "  ↓\n"
            "feature hierarchy\n"
            "  ↓\n"
            "downsampling + deeper channels\n"
            "  ↓\n"
            "image representation\n"
            "  ↓\n"
            "classifier\n"
            "\n"
            "SMALL DATA\n"
            "  ↓\n"
            "augmentation\n"
            "  ↓\n"
            "pretrained backbone\n"
            "  ↓\n"
            "feature extraction\n"
            "  ↓\n"
            "fine-tuning\n"
            "\n"
            "MODERN ARCHITECTURE\n"
            "  ↓\n"
            "repeated blocks\n"
            "  +\n"
            "residual connections\n"
            "  +\n"
            "batch normalization\n"
            "  +\n"
            "separable convolutions\n"
            "```\n"
        ),

        "estimated_minutes": 180,

        "has_code_examples": True,

        "sections": [
            {
                "id": "convnet-foundations",
                "title": "How Convolutional Neural Networks Understand Images",
                "order": 1,
            },
            {
                "id": "small-data-training",
                "title": "Training an Image Classifier with a Small Dataset",
                "order": 2,
            },
            {
                "id": "transfer-learning",
                "title": "Reusing a Pretrained ConvNet",
                "order": 3,
            },
            {
                "id": "modern-convnet-architecture",
                "title": "Modern ConvNet Architecture Patterns",
                "order": 4,
            },
        ],
    },


    # =======================================================================
    # INLINE EXERCISES
    # =======================================================================

    "exercises": [
        {
            "id": "M08.L01.EX01",

            "title": "Design a Small Image Classifier",

            "lesson_code": "M08.L01",

            "section_id": "small-data-training",

            "placement": "after_section",

            "description": (
                "Practice connecting image tensor shapes, convolution, pooling, "
                "binary classification, augmentation, and overfitting."
            ),

            "instructions": (
                "Imagine you have 3,000 RGB images of healthy and diseased "
                "plant leaves. All images will be resized to 180 × 180.\n\n"
                "1. State the input tensor shape for one image.\n"
                "2. State the problem type.\n"
                "3. Choose a suitable final Dense layer and activation.\n"
                "4. Choose a suitable loss function.\n"
                "5. Sketch a ConvNet containing at least three Conv2D stages "
                "and two MaxPooling2D layers.\n"
                "6. Explain why the number of channels may increase while the "
                "spatial dimensions decrease.\n"
                "7. Propose three realistic augmentation operations.\n"
                "8. Explain why augmentation should be applied to training "
                "images but not randomly applied when evaluating the test set.\n"
                "9. Describe the training/validation pattern that would indicate "
                "overfitting.\n"
                "10. Explain how a best-model checkpoint can help."
            ),

            "expected_output": (
                "A short architecture plan plus explanations of input shape, "
                "binary output configuration, convolution/pooling behavior, "
                "augmentation, and overfitting detection."
            ),

            "difficulty": DifficultyLevel.beginner,

            "skill_tested": [
                "image-tensors",
                "convnet-design",
                "max-pooling",
                "binary-classification",
                "data-augmentation",
                "overfitting",
            ],
        },

        {
            "id": "M08.L01.EX02",

            "title": "Upgrade a ConvNet with Transfer Learning and Modern Blocks",

            "lesson_code": "M08.L01",

            "section_id": "modern-convnet-architecture",

            "placement": "after_section",

            "description": (
                "Practice reasoning about pretrained backbones, fine-tuning, "
                "residual connections, batch normalization, and separable "
                "convolution."
            ),

            "instructions": (
                "You have a small image dataset and an existing ConvNet that "
                "overfits quickly.\n\n"
                "1. Explain how you would replace training from scratch with a "
                "pretrained backbone.\n"
                "2. Explain which part of the pretrained model you would remove "
                "or replace.\n"
                "3. State what should initially be frozen.\n"
                "4. Describe the correct sequence for later fine-tuning.\n"
                "5. Explain why fine-tuning should use a low learning rate.\n"
                "6. Draw a residual block conceptually as a main path plus "
                "shortcut path.\n"
                "7. Explain what must happen if the main path changes from "
                "32 channels to 64 channels before residual addition.\n"
                "8. Write the preferred conceptual ordering of Conv2D, "
                "BatchNormalization, and ReLU described in the lesson.\n"
                "9. Explain the two stages of a depthwise separable convolution.\n"
                "10. Explain why a separable convolution may reduce overfitting "
                "risk on limited data.\n"
                "11. Summarize the MHR principle in your own words."
            ),

            "expected_output": (
                "A structured design explanation showing the transfer-learning "
                "workflow and a modern residual ConvNet block with appropriate "
                "normalization and efficient convolution."
            ),

            "difficulty": DifficultyLevel.beginner,

            "skill_tested": [
                "transfer-learning",
                "feature-extraction",
                "fine-tuning",
                "residual-connections",
                "batch-normalization",
                "separable-convolution",
                "architecture-design",
            ],
        },
    ],


    # =======================================================================
    # LESSON QUIZ
    # =======================================================================

    "quiz": {
        "id": "M08.L01.QZ01",

        "title": "Image Classification and Modern ConvNet Architecture — Knowledge Check",

        "lesson_code": "M08.L01",

        "placement": "lesson_end",

        "questions": [
            {
                "id": "M08.L01.Q01",

                "section_id": "convnet-foundations",

                "question": (
                    "What is one major reason convolutional layers are "
                    "well suited to images?"
                ),

                "options": [
                    "They learn a completely independent set of weights for every pixel location",
                    "They reuse learned local feature detectors across spatial locations",
                    "They require images to contain only one color channel",
                    "They eliminate the need for nonlinear activation functions",
                ],

                "correct": 1,

                "explanation": (
                    "Convolution applies the same learned kernel across many "
                    "spatial locations. This allows a feature learned in one "
                    "part of an image to be detected elsewhere and makes "
                    "ConvNets efficient at learning visual patterns."
                ),
            },

            {
                "id": "M08.L01.Q02",

                "section_id": "small-data-training",

                "question": (
                    "What is the primary purpose of realistic random data "
                    "augmentation when training on a small image dataset?"
                ),

                "options": [
                    "To change the class labels",
                    "To increase the number of parameters in the network",
                    "To expose the model to varied versions of training examples and reduce overfitting",
                    "To replace the validation and test sets",
                ],

                "correct": 2,

                "explanation": (
                    "Augmentation produces believable variations of existing "
                    "training images. This makes exact memorization more "
                    "difficult and encourages the model to learn features that "
                    "remain useful under reasonable image transformations."
                ),
            },

            {
                "id": "M08.L01.Q03",

                "section_id": "transfer-learning",

                "question": (
                    "What is the safest initial strategy when attaching a "
                    "randomly initialized classifier to a pretrained backbone?"
                ),

                "options": [
                    "Train the entire network immediately using a very large learning rate",
                    "Freeze the pretrained backbone and first train the new classifier",
                    "Delete the pretrained weights before training",
                    "Only train the earliest convolution layer",
                ],

                "correct": 1,

                "explanation": (
                    "The classifier begins with random weights. Freezing the "
                    "pretrained backbone protects useful representations while "
                    "the new classifier learns how to use them. Fine-tuning can "
                    "happen afterward."
                ),
            },

            {
                "id": "M08.L01.Q04",

                "section_id": "modern-convnet-architecture",

                "question": (
                    "What is the main purpose of a residual connection?"
                ),

                "options": [
                    "To convert every image into grayscale",
                    "To remove all convolutional filters from a network",
                    "To provide a shortcut that preserves information and helps gradients propagate through deep networks",
                    "To ensure every feature map has only one channel",
                ],

                "correct": 2,

                "explanation": (
                    "A residual shortcut adds an earlier representation to a "
                    "later block output. This provides a less destructive path "
                    "for information and gradients through deep architectures."
                ),
            },

            {
                "id": "M08.L01.Q05",

                "section_id": "modern-convnet-architecture",

                "type": "open",

                "question": (
                    "You have only 2,000 labeled images for a new binary "
                    "classification problem. Design a practical training "
                    "strategy that combines ideas from the entire lesson. "
                    "Explain how you would preprocess the images, control "
                    "overfitting, use a pretrained model, train the classifier, "
                    "fine-tune selected layers, and decide whether residual "
                    "connections, batch normalization, or separable "
                    "convolutions would be useful in a custom architecture."
                ),
            },
        ],

        "passing_score": 70,
    },
}