"""M11.L01 — Image Segmentation and Object Detection.

One Topic -> one complete learner-facing Lesson + inline Exercises + lesson Quiz.
BOOK-002, Chapters 11–12, pages not provided in the supplied extracts.
Instructor-authored curriculum adaptation.
"""

from app.models.learning import DifficultyLevel


# ---------------------------------------------------------------------------
# Lesson metadata
# ---------------------------------------------------------------------------

LESSON_CODE = "M11.L01"

MODULE_ORDER = 11

MODULE_TITLE = "Pixel-Level and Object-Level Computer Vision"

MODULE_DESCRIPTION = (
    "Learn the two major spatial computer-vision tasks beyond classification: "
    "image segmentation and object detection, from encoder-decoder segmentation "
    "and Segment Anything to YOLO-style detection and RetinaNet feature pyramids."
)

SOURCE_CHAPTER = "11–12"

SOURCE_PAGES = "Not provided in supplied chapter extracts"


# ---------------------------------------------------------------------------
# Topic
# ---------------------------------------------------------------------------

TOPIC = {
    "title": "Image Segmentation and Object Detection",

    "slug": "deep-learning-foundations-m11-l01",

    "description": (
        "Understand pixel-level segmentation and bounding-box object detection, "
        "train simplified models from scratch, use IoU to measure spatial quality, "
        "and apply pretrained SAM and RetinaNet models."
    ),

    "order": 1,

    "difficulty": DifficultyLevel.beginner,

    "estimated_hours": 3.25,

    "skill_tags": [
        "computer-vision",
        "image-segmentation",
        "object-detection",
        "semantic-segmentation",
        "sam",
        "yolo",
        "retinanet",
        "iou",
        "module-11",
    ],

    "prerequisite_ids": [],


    # =======================================================================
    # LESSON
    # =======================================================================

    "lesson": {
        "title": "Image Segmentation and Object Detection",

        "content": (
            '# Image Segmentation and Object Detection\n'
            '\n'
            '> **Course:** Deep Learning Foundations  \n'
            '> **Lesson:** M11.L01  \n'
            '> **Module:** Pixel-Level and Object-Level Computer Vision  \n'
            '> **Source alignment:** BOOK-002, Chapters 11–12. The supplied extracts do not include page numbers. This lesson is an instructor-authored curriculum adaptation rather than a reproduction of the source text.\n'
            '\n'
            '---\n'
            '\n'
            '## Learning outcomes\n'
            '\n'
            'By the end of this lesson, you should be able to:\n'
            '\n'
            '- Distinguish image classification, image segmentation, and object detection.\n'
            '- Explain semantic, instance, and panoptic segmentation.\n'
            '- Describe how segmentation masks differ from ordinary image-level labels.\n'
            '- Build the mental model behind an encoder-decoder segmentation network using strided convolutions and transposed convolutions.\n'
            '- Explain Intersection over Union (IoU) and why it is useful for segmentation and detection.\n'
            '- Describe how the Segment Anything Model (SAM) uses image prompts, point prompts, and box prompts.\n'
            '- Compare two-stage R-CNN-style detectors with single-stage detectors such as YOLO and RetinaNet.\n'
            '- Explain how a YOLO-style detector divides an image into a grid and jointly predicts boxes, confidence, and classes.\n'
            '- Explain how IoU is used inside object-detection training.\n'
            '- Describe why feature pyramid networks help RetinaNet detect objects at multiple scales.\n'
            '- Choose between classification, segmentation, and detection based on the information your application actually needs.\n'
            '\n'
            '---\n'
            '\n'
            '## 1. The three core computer-vision tasks\n'
            '\n'
            'Computer vision is not one task.\n'
            '\n'
            'Three fundamental problem types appear again and again:\n'
            '\n'
            '```text\n'
            'Classification\n'
            'Segmentation\n'
            'Detection\n'
            '```\n'
            '\n'
            'They answer different questions.\n'
            '\n'
            '### Image classification\n'
            '\n'
            'Classification asks:\n'
            '\n'
            '> What is in this image?\n'
            '\n'
            'Example:\n'
            '\n'
            '```text\n'
            'input: photo\n'
            'output: "cat"\n'
            '```\n'
            '\n'
            'A multilabel classifier may return several labels:\n'
            '\n'
            '```text\n'
            '["person", "bicycle", "tree"]\n'
            '```\n'
            '\n'
            'But classification normally does not tell you exactly where those things are.\n'
            '\n'
            '### Image segmentation\n'
            '\n'
            'Segmentation asks:\n'
            '\n'
            '> Which class does each pixel belong to?\n'
            '\n'
            'The output has spatial structure.\n'
            '\n'
            'For example:\n'
            '\n'
            '```text\n'
            'pixel (20, 10) -> background\n'
            'pixel (20, 11) -> background\n'
            'pixel (20, 12) -> cat\n'
            'pixel (20, 13) -> cat\n'
            '...\n'
            '```\n'
            '\n'
            'So the output is a **mask** aligned with the input image.\n'
            '\n'
            'This makes segmentation useful when precise boundaries matter.\n'
            '\n'
            'Examples:\n'
            '\n'
            '- separating a person from a video-call background,\n'
            '- finding a tumor region in a medical image,\n'
            '- identifying road, sidewalk, vehicle, and pedestrian pixels,\n'
            '- selecting an object for image editing.\n'
            '\n'
            '### Object detection\n'
            '\n'
            'Detection asks:\n'
            '\n'
            '> Which objects are present, and where are they approximately located?\n'
            '\n'
            'The output consists of:\n'
            '\n'
            '```text\n'
            'class label + bounding box\n'
            '```\n'
            '\n'
            'For example:\n'
            '\n'
            '```text\n'
            'dog -> [x, y, width, height]\n'
            'person -> [x, y, width, height]\n'
            '```\n'
            '\n'
            'Bounding boxes are less precise than segmentation masks, but they are usually cheaper to label and cheaper to predict.\n'
            '\n'
            '### One picture, three possible outputs\n'
            '\n'
            'Imagine one image containing a dog beside a bicycle.\n'
            '\n'
            'A classifier might return:\n'
            '\n'
            '```text\n'
            'dog\n'
            'bicycle\n'
            '```\n'
            '\n'
            'A detector might return:\n'
            '\n'
            '```text\n'
            'dog     -> bounding box A\n'
            'bicycle -> bounding box B\n'
            '```\n'
            '\n'
            'A segmentation model might return:\n'
            '\n'
            '```text\n'
            'every dog pixel     -> dog class\n'
            'every bicycle pixel -> bicycle class\n'
            'all other pixels    -> background\n'
            '```\n'
            '\n'
            '### Segmentation versus detection\n'
            '\n'
            'Segmentation contains more spatial information than detection.\n'
            '\n'
            'If you already have an accurate instance mask, you can compute a bounding box around that mask.\n'
            '\n'
            'So in an information sense:\n'
            '\n'
            '```text\n'
            'segmentation > detection\n'
            '```\n'
            '\n'
            'But the additional detail has a cost.\n'
            '\n'
            'Pixel-accurate segmentation often requires:\n'
            '\n'
            '- more computation,\n'
            '- more memory,\n'
            '- more expensive labels,\n'
            '- more detailed ground-truth annotations.\n'
            '\n'
            'If your application only needs:\n'
            '\n'
            '```text\n'
            '"How many cars are visible?"\n'
            '```\n'
            '\n'
            'bounding boxes may be enough.\n'
            '\n'
            'If your application needs:\n'
            '\n'
            '```text\n'
            '"Which exact pixels belong to the car?"\n'
            '```\n'
            '\n'
            'segmentation is more appropriate.\n'
            '\n'
            '### A practical selection rule\n'
            '\n'
            'Use the simplest output that contains the information you actually need.\n'
            '\n'
            '```text\n'
            'Need only image-level identity?\n'
            '-> classification\n'
            '\n'
            'Need object location but not exact boundaries?\n'
            '-> detection\n'
            '\n'
            'Need pixel-level boundaries?\n'
            '-> segmentation\n'
            '```\n'
            '\n'
            '---\n'
            '\n'
            '## 2. Understanding image segmentation\n'
            '\n'
            'Deep-learning segmentation assigns a category to pixels.\n'
            '\n'
            'There are three major forms.\n'
            '\n'
            '### Semantic segmentation\n'
            '\n'
            'Semantic segmentation assigns each pixel a semantic class.\n'
            '\n'
            'Example:\n'
            '\n'
            '```text\n'
            'cat pixels        -> cat\n'
            'dog pixels        -> dog\n'
            'background pixels -> background\n'
            '```\n'
            '\n'
            'If two cats appear in the image, both belong to the same class:\n'
            '\n'
            '```text\n'
            'cat\n'
            '```\n'
            '\n'
            'The model does not distinguish one cat from the other.\n'
            '\n'
            '### Instance segmentation\n'
            '\n'
            'Instance segmentation distinguishes individual objects.\n'
            '\n'
            'Two cats become:\n'
            '\n'
            '```text\n'
            'cat instance 1\n'
            'cat instance 2\n'
            '```\n'
            '\n'
            'This is important when you need to count or manipulate objects independently.\n'
            '\n'
            '### Panoptic segmentation\n'
            '\n'
            'Panoptic segmentation combines the two ideas.\n'
            '\n'
            'Each pixel receives:\n'
            '\n'
            '```text\n'
            'semantic category\n'
            '+\n'
            'instance identity\n'
            '```\n'
            '\n'
            'Conceptually:\n'
            '\n'
            '```text\n'
            'pixel -> ("cat", instance 2)\n'
            '```\n'
            '\n'
            'This gives both category and individual-object information.\n'
            '\n'
            '### Segmentation masks\n'
            '\n'
            'A segmentation dataset pairs:\n'
            '\n'
            '```text\n'
            'input image\n'
            '+\n'
            'target mask\n'
            '```\n'
            '\n'
            'The mask is usually the same height and width as the image.\n'
            '\n'
            'Instead of RGB color values, each pixel stores a class ID.\n'
            '\n'
            'A simple pet dataset may use something like:\n'
            '\n'
            '```text\n'
            '0 -> foreground\n'
            '1 -> background\n'
            '2 -> contour\n'
            '```\n'
            '\n'
            'The important concept is:\n'
            '\n'
            '> The mask is the target label, but the label exists at every pixel position.\n'
            '\n'
            '### Input and target shapes\n'
            '\n'
            'Suppose images are resized to:\n'
            '\n'
            '```text\n'
            '200 × 200\n'
            '```\n'
            '\n'
            'Then an RGB input batch may have shape:\n'
            '\n'
            '```text\n'
            '(batch, 200, 200, 3)\n'
            '```\n'
            '\n'
            'while sparse target masks may have shape:\n'
            '\n'
            '```text\n'
            '(batch, 200, 200, 1)\n'
            '```\n'
            '\n'
            'The model should eventually return a class distribution for every pixel:\n'
            '\n'
            '```text\n'
            '(batch, 200, 200, num_classes)\n'
            '```\n'
            '\n'
            '---\n'
            '\n'
            '## 3. Building a segmentation model from scratch\n'
            '\n'
            'A segmentation network has a different job from a classifier.\n'
            '\n'
            'A classifier can progressively destroy spatial detail and end with one global vector.\n'
            '\n'
            'A segmentation model must eventually return to the original image resolution.\n'
            '\n'
            'This naturally leads to an **encoder-decoder** structure.\n'
            '\n'
            '```text\n'
            'input image\n'
            '    ↓\n'
            'encoder\n'
            '    ↓\n'
            'compressed spatial representation\n'
            '    ↓\n'
            'decoder\n'
            '    ↓\n'
            'pixel-level mask\n'
            '```\n'
            '\n'
            '### Encoder: compress while learning useful features\n'
            '\n'
            'The first half looks similar to an ordinary ConvNet.\n'
            '\n'
            'Example idea:\n'
            '\n'
            '```python\n'
            'inputs = keras.Input(shape=(200, 200, 3))\n'
            'x = layers.Rescaling(1 / 255.0)(inputs)\n'
            '\n'
            'x = layers.Conv2D(64, 3, strides=2, padding="same",\n'
            '                  activation="relu")(x)\n'
            'x = layers.Conv2D(64, 3, padding="same",\n'
            '                  activation="relu")(x)\n'
            '\n'
            'x = layers.Conv2D(128, 3, strides=2, padding="same",\n'
            '                  activation="relu")(x)\n'
            'x = layers.Conv2D(128, 3, padding="same",\n'
            '                  activation="relu")(x)\n'
            '```\n'
            '\n'
            'The spatial resolution becomes smaller while the number of learned channels grows.\n'
            '\n'
            'You can think of this as:\n'
            '\n'
            '```text\n'
            'large image\n'
            '   ↓\n'
            'smaller but richer feature maps\n'
            '```\n'
            '\n'
            '### Why strided convolution instead of max pooling?\n'
            '\n'
            'For classification, losing exact position information is often acceptable.\n'
            '\n'
            'For segmentation, position is essential because the model must reconstruct a pixel-level output.\n'
            '\n'
            'A `2 × 2` max-pooling operation says:\n'
            '\n'
            '> Keep the strongest value in this local region.\n'
            '\n'
            'But it discards which location inside that window produced the value.\n'
            '\n'
            'Strided convolutions can downsample while learning a spatial transformation.\n'
            '\n'
            'So for tasks where location matters, a useful principle is:\n'
            '\n'
            '```text\n'
            'prefer spatially aware downsampling\n'
            '```\n'
            '\n'
            'rather than aggressively throwing position information away.\n'
            '\n'
            '### Decoder: reconstruct spatial resolution\n'
            '\n'
            'After encoding, you may have something like:\n'
            '\n'
            '```text\n'
            '25 × 25 × 256\n'
            '```\n'
            '\n'
            'but the desired output is:\n'
            '\n'
            '```text\n'
            '200 × 200 × num_classes\n'
            '```\n'
            '\n'
            'The decoder must therefore upsample.\n'
            '\n'
            'One useful layer is:\n'
            '\n'
            '```text\n'
            'Conv2DTranspose\n'
            '```\n'
            '\n'
            'A transposed convolution learns how to increase spatial resolution.\n'
            '\n'
            'Conceptually:\n'
            '\n'
            '```text\n'
            '25 × 25\n'
            '   ↓\n'
            '50 × 50\n'
            '   ↓\n'
            '100 × 100\n'
            '   ↓\n'
            '200 × 200\n'
            '```\n'
            '\n'
            'A simplified decoder might look like:\n'
            '\n'
            '```python\n'
            'x = layers.Conv2DTranspose(\n'
            '    256, 3, padding="same", activation="relu"\n'
            ')(x)\n'
            '\n'
            'x = layers.Conv2DTranspose(\n'
            '    128, 3, strides=2, padding="same", activation="relu"\n'
            ')(x)\n'
            '\n'
            'x = layers.Conv2DTranspose(\n'
            '    64, 3, strides=2, padding="same", activation="relu"\n'
            ')(x)\n'
            '\n'
            'outputs = layers.Conv2D(\n'
            '    num_classes,\n'
            '    3,\n'
            '    padding="same",\n'
            '    activation="softmax",\n'
            ')(x)\n'
            '```\n'
            '\n'
            'The final softmax returns a class probability distribution for each pixel.\n'
            '\n'
            '### Per-pixel classification\n'
            '\n'
            'This is the key idea:\n'
            '\n'
            '> Semantic segmentation is classification performed at every pixel location.\n'
            '\n'
            'If there are three classes, then every output pixel contains three scores.\n'
            '\n'
            'For one location:\n'
            '\n'
            '```text\n'
            'foreground = 0.91\n'
            'background = 0.06\n'
            'contour    = 0.03\n'
            '```\n'
            '\n'
            'The predicted class is the highest-scoring class.\n'
            '\n'
            '---\n'
            '\n'
            '## 4. Intersection over Union: a shared metric for segmentation and detection\n'
            '\n'
            'Both chapters rely on **Intersection over Union**, usually abbreviated **IoU**.\n'
            '\n'
            'IoU measures how well a predicted spatial region matches the ground truth.\n'
            '\n'
            '### Step 1 — Find the intersection\n'
            '\n'
            'The intersection is the region covered by both:\n'
            '\n'
            '```text\n'
            'predicted region\n'
            'AND\n'
            'ground-truth region\n'
            '```\n'
            '\n'
            '### Step 2 — Find the union\n'
            '\n'
            'The union is the total area covered by either region:\n'
            '\n'
            '```text\n'
            'predicted region\n'
            'OR\n'
            'ground-truth region\n'
            '```\n'
            '\n'
            '### Step 3 — Divide\n'
            '\n'
            '```text\n'
            'IoU =\n'
            'intersection area\n'
            '─────────────────\n'
            'union area\n'
            '```\n'
            '\n'
            'The result lies between:\n'
            '\n'
            '```text\n'
            '0 and 1\n'
            '```\n'
            '\n'
            'Interpretation:\n'
            '\n'
            '```text\n'
            'IoU = 1.0 -> perfect overlap\n'
            'IoU ≈ 0.5 -> partial overlap\n'
            'IoU = 0.0 -> no overlap\n'
            '```\n'
            '\n'
            '### Why accuracy alone is not enough\n'
            '\n'
            'Suppose the foreground object covers only 10% of the image.\n'
            '\n'
            'A model that predicts every pixel as background could still obtain high raw pixel accuracy.\n'
            '\n'
            'IoU focuses directly on spatial overlap and is therefore often more informative for masks and boxes.\n'
            '\n'
            '### IoU in segmentation\n'
            '\n'
            'For semantic segmentation, IoU can be computed separately per class.\n'
            '\n'
            'For example:\n'
            '\n'
            '```text\n'
            'foreground IoU\n'
            'background IoU\n'
            'contour IoU\n'
            '```\n'
            '\n'
            'or averaged across classes.\n'
            '\n'
            '### IoU in object detection\n'
            '\n'
            'For bounding boxes, IoU measures:\n'
            '\n'
            '```text\n'
            'how well the predicted box overlaps the ground-truth box\n'
            '```\n'
            '\n'
            'This becomes important later when YOLO learns confidence scores.\n'
            '\n'
            '---\n'
            '\n'
            '## 5. Training and validating the segmentation model\n'
            '\n'
            'With sparse integer masks, a natural loss is:\n'
            '\n'
            '```text\n'
            'sparse categorical cross-entropy\n'
            '```\n'
            '\n'
            'because each pixel contains one integer class ID.\n'
            '\n'
            'A high-level compile step might look like:\n'
            '\n'
            '```python\n'
            'model.compile(\n'
            '    optimizer="adam",\n'
            '    loss="sparse_categorical_crossentropy",\n'
            '    metrics=[foreground_iou],\n'
            ')\n'
            '```\n'
            '\n'
            '### Why validation still matters\n'
            '\n'
            'A segmentation network can overfit just like any other neural network.\n'
            '\n'
            'Typical pattern:\n'
            '\n'
            '```text\n'
            'training loss   -> keeps falling\n'
            'validation loss -> falls, reaches a minimum, then rises\n'
            '```\n'
            '\n'
            'The correct response is not to use the final epoch automatically.\n'
            '\n'
            'Instead, save the best model according to validation performance.\n'
            '\n'
            'For example:\n'
            '\n'
            '```python\n'
            'checkpoint = keras.callbacks.ModelCheckpoint(\n'
            '    "best_segmentation.keras",\n'
            '    save_best_only=True,\n'
            ')\n'
            '```\n'
            '\n'
            'Then train with:\n'
            '\n'
            '```python\n'
            'model.fit(\n'
            '    train_images,\n'
            '    train_masks,\n'
            '    validation_data=(val_images, val_masks),\n'
            '    callbacks=[checkpoint],\n'
            ')\n'
            '```\n'
            '\n'
            '### Turning predictions into masks\n'
            '\n'
            'The model outputs class probabilities:\n'
            '\n'
            '```text\n'
            'height × width × num_classes\n'
            '```\n'
            '\n'
            'To get the final predicted class ID for each pixel:\n'
            '\n'
            '```python\n'
            'mask = np.argmax(prediction, axis=-1)\n'
            '```\n'
            '\n'
            'The resulting 2D array can then be displayed as a segmentation mask.\n'
            '\n'
            '---\n'
            '\n'
            '## 6. Using a pretrained segmentation model: Segment Anything\n'
            '\n'
            'Training a segmentation model from scratch is useful for learning the mechanics.\n'
            '\n'
            'In real applications, a large pretrained segmentation model can provide much stronger behavior.\n'
            '\n'
            'The chapter introduces the **Segment Anything Model (SAM)**.\n'
            '\n'
            'Its key idea is unusual and powerful:\n'
            '\n'
            '> The model is prompted with an image plus a hint about which object you want segmented.\n'
            '\n'
            'The prompt can be:\n'
            '\n'
            '```text\n'
            'a foreground point\n'
            'a background point\n'
            'multiple points\n'
            'a bounding box\n'
            '```\n'
            '\n'
            '### High-level architecture\n'
            '\n'
            'SAM can be understood as three parts:\n'
            '\n'
            '```text\n'
            'image\n'
            '  ↓\n'
            'image encoder\n'
            '  ↓\n'
            'image embedding\n'
            '                \\\n'
            '                 -> mask decoder -> candidate masks\n'
            '                /\n'
            'prompt\n'
            '  ↓\n'
            'prompt encoder\n'
            '  ↓\n'
            'prompt embedding\n'
            '```\n'
            '\n'
            'The image encoder represents the visual content.\n'
            '\n'
            "The prompt encoder represents the user's hint.\n"
            '\n'
            "The mask decoder combines both to predict the requested object's mask.\n"
            '\n'
            '### Training data structure\n'
            '\n'
            'Conceptually, SAM learns from triples:\n'
            '\n'
            '```text\n'
            '(image, prompt, target mask)\n'
            '```\n'
            '\n'
            'For an object mask, a prompt can be generated automatically.\n'
            '\n'
            'For example:\n'
            '\n'
            '```text\n'
            'choose one object mask\n'
            '       ↓\n'
            'sample a point inside it\n'
            '       ↓\n'
            'use that point as the prompt\n'
            '```\n'
            '\n'
            'or:\n'
            '\n'
            '```text\n'
            'choose one object mask\n'
            '       ↓\n'
            'compute a box around it\n'
            '       ↓\n'
            'use the box as the prompt\n'
            '```\n'
            '\n'
            'This allows many training examples to be generated from richly annotated images.\n'
            '\n'
            '### Point prompting\n'
            '\n'
            'Suppose you click on a peach.\n'
            '\n'
            'The input to the model includes:\n'
            '\n'
            '```text\n'
            'image\n'
            'point coordinates\n'
            'point label = foreground\n'
            '```\n'
            '\n'
            'The model returns candidate masks for the object that contains that point.\n'
            '\n'
            'If the request is ambiguous, multiple points can help.\n'
            '\n'
            'You can also mark background points to say:\n'
            '\n'
            '```text\n'
            'do not include this area\n'
            '```\n'
            '\n'
            '### Multiple candidate masks\n'
            '\n'
            'An ambiguous prompt may correspond to more than one sensible object region.\n'
            '\n'
            'For example, clicking one banana in a pair may lead to candidates such as:\n'
            '\n'
            '```text\n'
            'only one banana\n'
            'both bananas\n'
            'a larger grouped region\n'
            '```\n'
            '\n'
            'Returning alternative masks makes the system more useful when object boundaries are ambiguous.\n'
            '\n'
            '### Box prompting\n'
            '\n'
            'A box prompt says roughly:\n'
            '\n'
            '> Segment the object inside this region.\n'
            '\n'
            "The box does not need to trace the object's exact boundary.\n"
            '\n'
            'That is the point of the segmentation model.\n'
            '\n'
            'The box provides a coarse spatial hint, and the model generates a precise mask.\n'
            '\n'
            '### Why pretrained segmentation is valuable\n'
            '\n'
            'A large pretrained segmentation model is especially useful when:\n'
            '\n'
            '- you have little labeled data,\n'
            '- you need rapid annotation,\n'
            '- you need interactive object selection,\n'
            '- you want to bootstrap a custom segmentation dataset.\n'
            '\n'
            'One particularly useful workflow is:\n'
            '\n'
            '```text\n'
            'raw images\n'
            '   ↓\n'
            'human gives point/box prompts\n'
            '   ↓\n'
            'SAM proposes masks\n'
            '   ↓\n'
            'human corrects masks\n'
            '   ↓\n'
            'new labeled segmentation dataset\n'
            '```\n'
            '\n'
            '### Manual figures to add for the segmentation half\n'
            '\n'
            'You do **not** need every figure from the source. The most educational ones are:\n'
            '\n'
            '1. **Figure 11.1** — Classification vs. segmentation vs. detection.\n'
            '2. **Figure 11.2** — Semantic vs. instance segmentation.\n'
            '3. **Figure 11.4** — Example segmentation mask.\n'
            '4. **Figure 11.8** — High-level SAM architecture.\n'
            '5. **One prompt example:** either Figure 11.11 (point prompt result) or Figure 11.15 (box prompt result).\n'
            '\n'
            'Place each figure immediately after the section that explains it.\n'
            '\n'
            '{{exercise:M11.L01.EX01}}\n'
            '\n'
            '---\n'
            '\n'
            '## 7. Object detection: labels plus bounding boxes\n'
            '\n'
            'Object detection identifies objects and estimates where they are.\n'
            '\n'
            'A detector typically returns several predictions:\n'
            '\n'
            '```text\n'
            'class\n'
            'bounding box\n'
            'confidence\n'
            '```\n'
            '\n'
            'Example:\n'
            '\n'
            '```text\n'
            'person\n'
            'box = [x, y, width, height]\n'
            'confidence = 0.93\n'
            '```\n'
            '\n'
            '### Why use detection when segmentation is richer?\n'
            '\n'
            'Because detection is often:\n'
            '\n'
            '- faster,\n'
            '- cheaper to annotate,\n'
            '- simpler to deploy,\n'
            '- sufficient for counting and tracking.\n'
            '\n'
            'Common uses include:\n'
            '\n'
            '#### Counting\n'
            '\n'
            '```text\n'
            'How many cars are in this frame?\n'
            '```\n'
            '\n'
            '#### Tracking\n'
            '\n'
            'Detect objects in each video frame, then associate detections over time.\n'
            '\n'
            '#### Cropping\n'
            '\n'
            'Find a region and send that crop to:\n'
            '\n'
            '- a high-resolution classifier,\n'
            '- OCR,\n'
            '- another specialized model.\n'
            '\n'
            '### Bounding-box labels are cheaper\n'
            '\n'
            'For detection, a human annotator draws:\n'
            '\n'
            '```text\n'
            'rectangle around object\n'
            '```\n'
            '\n'
            'For segmentation, the annotator must trace:\n'
            '\n'
            '```text\n'
            'pixel-accurate object boundary\n'
            '```\n'
            '\n'
            'This difference becomes enormous when datasets contain thousands or millions of objects.\n'
            '\n'
            '---\n'
            '\n'
            '## 8. Two-stage versus single-stage detectors\n'
            '\n'
            'Object detectors can be organized into two broad families.\n'
            '\n'
            '### Two-stage detectors\n'
            '\n'
            'R-CNN-style methods separate detection into two steps.\n'
            '\n'
            '#### Stage 1 — Region proposals\n'
            '\n'
            'The model proposes many areas that may contain objects.\n'
            '\n'
            '```text\n'
            'image\n'
            '  ↓\n'
            'candidate region A\n'
            'candidate region B\n'
            'candidate region C\n'
            '...\n'
            '```\n'
            '\n'
            '#### Stage 2 — Classification and refinement\n'
            '\n'
            'Each candidate is then:\n'
            '\n'
            '- classified,\n'
            '- scored,\n'
            '- refined,\n'
            '- filtered.\n'
            '\n'
            'Conceptually:\n'
            '\n'
            '```text\n'
            'image\n'
            '   ↓\n'
            'region proposals\n'
            '   ↓\n'
            'classify each region\n'
            '   ↓\n'
            'refine boxes\n'
            '   ↓\n'
            'final detections\n'
            '```\n'
            '\n'
            'Later R-CNN versions replaced hand-designed region proposal systems with learned proposal networks.\n'
            '\n'
            '### Strength of two-stage detection\n'
            '\n'
            'The approach can be accurate because it spends substantial computation examining candidate regions.\n'
            '\n'
            '### Cost of two-stage detection\n'
            '\n'
            'The same design can be expensive because many regions must be processed.\n'
            '\n'
            'This can be undesirable for:\n'
            '\n'
            '- real-time inference,\n'
            '- embedded systems,\n'
            '- latency-sensitive applications.\n'
            '\n'
            '### Single-stage detectors\n'
            '\n'
            'Single-stage detectors predict object information directly in one network pass.\n'
            '\n'
            'Examples include:\n'
            '\n'
            '```text\n'
            'YOLO\n'
            'RetinaNet\n'
            'SSD\n'
            '```\n'
            '\n'
            'The network jointly predicts:\n'
            '\n'
            '```text\n'
            'where the object is\n'
            '+\n'
            'what the object is\n'
            '```\n'
            '\n'
            'This is generally faster and more suitable for real-time use.\n'
            '\n'
            '### Main tradeoff\n'
            '\n'
            'A useful simplified comparison is:\n'
            '\n'
            '| Two-stage | Single-stage |\n'
            '|---|---|\n'
            '| Region proposals first | Direct prediction |\n'
            '| More processing steps | One main prediction pipeline |\n'
            '| Often computationally heavier | Usually faster |\n'
            '| Historically strong accuracy | Strong speed/accuracy balance |\n'
            '| R-CNN family | YOLO, RetinaNet, SSD |\n'
            '\n'
            '---\n'
            '\n'
            '## 9. Understanding a YOLO-style single-stage detector\n'
            '\n'
            'YOLO stands for:\n'
            '\n'
            '```text\n'
            'You Only Look Once\n'
            '```\n'
            '\n'
            'The core idea is to divide an image into a grid and make predictions at grid locations.\n'
            '\n'
            'Imagine a:\n'
            '\n'
            '```text\n'
            '6 × 6 grid\n'
            '```\n'
            '\n'
            'Each cell predicts information such as:\n'
            '\n'
            '```text\n'
            'box coordinates\n'
            'object confidence\n'
            'class probabilities\n'
            '```\n'
            '\n'
            '### One possible output per cell\n'
            '\n'
            'A simplified box prediction contains:\n'
            '\n'
            '```text\n'
            'x\n'
            'y\n'
            'width\n'
            'height\n'
            'confidence\n'
            '```\n'
            '\n'
            'The class head contains probabilities over all supported object categories.\n'
            '\n'
            'So a grid location produces:\n'
            '\n'
            '```text\n'
            'box output\n'
            '+\n'
            'class output\n'
            '```\n'
            '\n'
            '### Which grid cell owns an object?\n'
            '\n'
            'A common rule is:\n'
            '\n'
            '> The grid cell containing the center of the object becomes responsible for that object.\n'
            '\n'
            'Suppose a car spans several cells.\n'
            '\n'
            'The model does not need every covered cell to predict the box.\n'
            '\n'
            "The box can be assigned to the cell containing the object's center.\n"
            '\n'
            '### Relative coordinates\n'
            '\n'
            'Instead of storing all coordinates in raw pixels, it is convenient to normalize them.\n'
            '\n'
            'For example:\n'
            '\n'
            '```text\n'
            'x in [0, 1]\n'
            'y in [0, 1]\n'
            'width in [0, 1]\n'
            'height in [0, 1]\n'
            '```\n'
            '\n'
            'This makes box representation independent of the original image size.\n'
            '\n'
            'Within the YOLO grid, center coordinates can also be represented relative to the responsible cell.\n'
            '\n'
            '### ConvNet backbone\n'
            '\n'
            'A detector still needs visual features.\n'
            '\n'
            'A pretrained ConvNet can act as a **backbone**:\n'
            '\n'
            '```text\n'
            'image\n'
            '  ↓\n'
            'ResNet or another ConvNet\n'
            '  ↓\n'
            'high-level feature map\n'
            '  ↓\n'
            'detection head\n'
            '```\n'
            '\n'
            'The detection head converts learned visual features into:\n'
            '\n'
            '```text\n'
            'grid predictions\n'
            '```\n'
            '\n'
            '### Why spatial structure matters\n'
            '\n'
            'Object detection needs location.\n'
            '\n'
            'So, just like segmentation, the model should not carelessly destroy spatial information.\n'
            '\n'
            'This is one reason strided convolutions are useful in detection backbones.\n'
            '\n'
            '---\n'
            '\n'
            '## 10. Training a YOLO-style detector\n'
            '\n'
            'Detection training is more complicated than ordinary classification because several outputs must be learned together.\n'
            '\n'
            'The model needs to learn:\n'
            '\n'
            '```text\n'
            '1. object class\n'
            '2. box location\n'
            '3. box size\n'
            '4. object confidence\n'
            '```\n'
            '\n'
            '### Classification loss\n'
            '\n'
            'Class prediction can use a familiar classification loss such as:\n'
            '\n'
            '```text\n'
            'sparse categorical cross-entropy\n'
            '```\n'
            '\n'
            '### Bounding-box regression\n'
            '\n'
            'For grid cells containing objects, the model also needs to minimize errors in:\n'
            '\n'
            '```text\n'
            'x\n'
            'y\n'
            'width\n'
            'height\n'
            '```\n'
            '\n'
            'A simple approach uses squared error.\n'
            '\n'
            '### Confidence is not only "object exists"\n'
            '\n'
            "The chapter's simplified YOLO training gives confidence a richer target.\n"
            '\n'
            'If the grid cell is empty:\n'
            '\n'
            '```text\n'
            'confidence target = 0\n'
            '```\n'
            '\n'
            'If the grid cell contains an object:\n'
            '\n'
            '```text\n'
            'confidence target = IoU(predicted box, true box)\n'
            '```\n'
            '\n'
            'This means confidence reflects both:\n'
            '\n'
            '```text\n'
            'object presence\n'
            '+\n'
            'box quality\n'
            '```\n'
            '\n'
            'A model with a poorly placed box should not be highly confident.\n'
            '\n'
            '### Why IoU is such a useful bridge\n'
            '\n'
            'IoU appears in both chapters because it captures spatial quality.\n'
            '\n'
            'For segmentation:\n'
            '\n'
            '```text\n'
            'predicted mask vs. true mask\n'
            '```\n'
            '\n'
            'For detection:\n'
            '\n'
            '```text\n'
            'predicted box vs. true box\n'
            '```\n'
            '\n'
            'So IoU is a general tool for measuring overlap.\n'
            '\n'
            '### Balancing parts of the box loss\n'
            '\n'
            'Detection data is highly imbalanced.\n'
            '\n'
            'Most grid cells contain no object.\n'
            '\n'
            'If all cells contribute equally, empty locations can dominate training.\n'
            '\n'
            'A practical detector may therefore:\n'
            '\n'
            '- increase the weight of localization errors,\n'
            '- reduce the weight of confidence errors from empty cells,\n'
            '- transform width and height errors so large boxes do not dominate.\n'
            '\n'
            'The general engineering lesson is:\n'
            '\n'
            '> Multi-part losses often need careful balancing because not all prediction errors have equal importance or frequency.\n'
            '\n'
            '### Streaming large datasets\n'
            '\n'
            'Large detection datasets can be too big to load into memory as decoded image tensors.\n'
            '\n'
            'A streaming pipeline such as:\n'
            '\n'
            '```text\n'
            'tf.data\n'
            '```\n'
            '\n'
            'can:\n'
            '\n'
            '- load images batch by batch,\n'
            '- preprocess only what is needed,\n'
            '- release memory after use,\n'
            '- prefetch future batches.\n'
            '\n'
            'This is much more realistic for large image datasets than loading all image tensors at once.\n'
            '\n'
            '### Why training from scratch is difficult\n'
            '\n'
            'An accurate general-purpose detector requires:\n'
            '\n'
            '- a large dataset,\n'
            '- many training epochs,\n'
            '- careful augmentation,\n'
            '- tuned losses,\n'
            '- multiple boxes per location in modern systems,\n'
            '- substantial compute.\n'
            '\n'
            'A small from-scratch YOLO exercise is best viewed as a way to understand the mechanics.\n'
            '\n'
            'For real applications, pretrained detectors are often the better starting point.\n'
            '\n'
            '{{exercise:M11.L01.EX02}}\n'
            '\n'
            '---\n'
            '\n'
            '## 11. Pretrained detection with RetinaNet\n'
            '\n'
            'RetinaNet is also a single-stage detector.\n'
            '\n'
            'The chapter uses it to show how a stronger pretrained detector handles objects of different sizes.\n'
            '\n'
            '### The scale problem\n'
            '\n'
            'A deep ConvNet produces features at multiple resolutions.\n'
            '\n'
            'Early features:\n'
            '\n'
            '```text\n'
            'high spatial resolution\n'
            'low semantic abstraction\n'
            '```\n'
            '\n'
            'Late features:\n'
            '\n'
            '```text\n'
            'low spatial resolution\n'
            'high semantic abstraction\n'
            '```\n'
            '\n'
            'This creates a problem.\n'
            '\n'
            'Small objects need high-resolution features.\n'
            '\n'
            'But good object recognition needs high-level semantic features.\n'
            '\n'
            '### Feature Pyramid Network\n'
            '\n'
            'RetinaNet addresses this with a **Feature Pyramid Network (FPN)**.\n'
            '\n'
            'The idea is to combine:\n'
            '\n'
            '```text\n'
            'high-level semantics\n'
            '+\n'
            'high spatial resolution\n'
            '```\n'
            '\n'
            'A simplified flow:\n'
            '\n'
            '```text\n'
            'deep low-resolution features\n'
            '          ↓ upsample\n'
            '          +\n'
            'earlier high-resolution features\n'
            '          ↓\n'
            'multi-scale semantic feature maps\n'
            '```\n'
            '\n'
            'These lateral connections produce strong representations at several spatial scales.\n'
            '\n'
            'The detector can then handle:\n'
            '\n'
            '```text\n'
            'small objects\n'
            'medium objects\n'
            'large objects\n'
            '```\n'
            '\n'
            'more effectively.\n'
            '\n'
            '### Why feature pyramids matter beyond RetinaNet\n'
            '\n'
            'Modern object-detection systems frequently use multi-scale representations.\n'
            '\n'
            'The general principle is:\n'
            '\n'
            '> Do not force every object size to be detected from only one feature-map resolution.\n'
            '\n'
            '### Pretrained detector workflow\n'
            '\n'
            'A high-level pretrained detector typically looks like:\n'
            '\n'
            '```python\n'
            'detector = keras_hub.models.ObjectDetector.from_preset(\n'
            '    "retinanet_resnet50_fpn_v2_coco",\n'
            '    bounding_box_format="rel_xywh",\n'
            ')\n'
            '\n'
            'predictions = detector.predict(images)\n'
            '```\n'
            '\n'
            'The returned structure may contain:\n'
            '\n'
            '```text\n'
            'boxes\n'
            'confidence scores\n'
            'labels\n'
            'number of detections\n'
            '```\n'
            '\n'
            'The model therefore packages much of the complex training and decoding logic behind one inference API.\n'
            '\n'
            '### Out-of-distribution robustness\n'
            '\n'
            'The source demonstrates a pretrained detector on an artistic painting rather than a normal photograph.\n'
            '\n'
            'This illustrates an important advantage of learned high-level visual structure:\n'
            '\n'
            '```text\n'
            'pixels can change dramatically\n'
            'while object-level organization remains recognizable\n'
            '```\n'
            '\n'
            'It does not mean detectors are universally robust, but it shows why semantic feature learning can transfer beyond the exact visual style seen during training.\n'
            '\n'
            '### Manual figures to add for the detection half\n'
            '\n'
            'The most educational figures are:\n'
            '\n'
            '1. **Figure 12.1** — Detection as labeled bounding boxes.\n'
            '2. **Figure 12.2** — Two-stage R-CNN pipeline.\n'
            '3. **Figure 12.4** — YOLO grid output concept.\n'
            '4. **Figure 12.8** — Feature Pyramid Network.\n'
            '5. **Figure 12.9** — Example pretrained RetinaNet detections.\n'
            '\n'
            'You can skip other screenshots unless you specifically want a more code-heavy lesson.\n'
            '\n'
            '---\n'
            '\n'
            '## 12. Choosing classification, segmentation, or detection\n'
            '\n'
            'The most important practical lesson from these two chapters is not how to memorize individual architectures.\n'
            '\n'
            'It is how to define the computer-vision problem correctly.\n'
            '\n'
            '### Scenario 1 — Product recognition\n'
            '\n'
            'Requirement:\n'
            '\n'
            '```text\n'
            '"Tell me what product appears in this image."\n'
            '```\n'
            '\n'
            'Use:\n'
            '\n'
            '```text\n'
            'classification\n'
            '```\n'
            '\n'
            '### Scenario 2 — Count cars in traffic\n'
            '\n'
            'Requirement:\n'
            '\n'
            '```text\n'
            '"How many cars are visible, and where are they?"\n'
            '```\n'
            '\n'
            'Use:\n'
            '\n'
            '```text\n'
            'object detection\n'
            '```\n'
            '\n'
            'There is no need to pay the cost of pixel-perfect masks.\n'
            '\n'
            "### Scenario 3 — Replace a person's video-call background\n"
            '\n'
            'Requirement:\n'
            '\n'
            '```text\n'
            '"Separate the person from every background pixel."\n'
            '```\n'
            '\n'
            'Use:\n'
            '\n'
            '```text\n'
            'segmentation\n'
            '```\n'
            '\n'
            '### Scenario 4 — Identify and separately edit every fruit\n'
            '\n'
            'Requirement:\n'
            '\n'
            '```text\n'
            '"Give me the exact pixels for each individual fruit."\n'
            '```\n'
            '\n'
            'Use:\n'
            '\n'
            '```text\n'
            'instance segmentation\n'
            '```\n'
            '\n'
            '### Scenario 5 — Real-time embedded perception\n'
            '\n'
            'If latency and compute are highly constrained, detection may be more practical than segmentation when boxes are sufficient.\n'
            '\n'
            'Single-stage detectors are especially attractive for real-time systems.\n'
            '\n'
            '### Scenario 6 — Rapidly create a segmentation dataset\n'
            '\n'
            'Use a pretrained promptable segmentation model.\n'
            '\n'
            'Workflow:\n'
            '\n'
            '```text\n'
            'point/box prompt\n'
            '    ↓\n'
            'predicted mask\n'
            '    ↓\n'
            'human review\n'
            '    ↓\n'
            'saved label\n'
            '```\n'
            '\n'
            '### One decision tree to remember\n'
            '\n'
            '```text\n'
            'Do I need spatial location?\n'
            '        |\n'
            '        +-- No --> Classification\n'
            '        |\n'
            '        +-- Yes\n'
            '             |\n'
            '             +-- Is a bounding box enough?\n'
            '             |       |\n'
            '             |       +-- Yes --> Object Detection\n'
            '             |\n'
            '             +-- No --> Segmentation\n'
            '                      |\n'
            '                      +-- Need separate object identities?\n'
            '                              |\n'
            '                              +-- No --> Semantic Segmentation\n'
            '                              |\n'
            '                              +-- Yes --> Instance / Panoptic Segmentation\n'
            '```\n'
            '\n'
            '---\n'
            '\n'
            '## Important misconceptions\n'
            '\n'
            '### Misconception 1\n'
            '\n'
            '> "Segmentation and detection are just two names for the same problem."\n'
            '\n'
            'They both locate objects, but the output resolution is different.\n'
            '\n'
            '```text\n'
            'detection   -> boxes\n'
            'segmentation -> pixel masks\n'
            '```\n'
            '\n'
            '### Misconception 2\n'
            '\n'
            '> "If segmentation gives more information, it is always the better choice."\n'
            '\n'
            'More information can mean more:\n'
            '\n'
            '- compute,\n'
            '- labeling cost,\n'
            '- memory,\n'
            '- system complexity.\n'
            '\n'
            'If boxes are enough, detection may be the better engineering choice.\n'
            '\n'
            '### Misconception 3\n'
            '\n'
            '> "YOLO only predicts classes."\n'
            '\n'
            'A detector must learn spatial outputs as well.\n'
            '\n'
            'A YOLO-style model jointly predicts:\n'
            '\n'
            '```text\n'
            'class information\n'
            'box geometry\n'
            'object confidence\n'
            '```\n'
            '\n'
            '### Misconception 4\n'
            '\n'
            '> "IoU is only a segmentation metric."\n'
            '\n'
            'IoU is useful for any spatial-overlap problem.\n'
            '\n'
            'It works for:\n'
            '\n'
            '```text\n'
            'mask overlap\n'
            'bounding-box overlap\n'
            '```\n'
            '\n'
            '---\n'
            '\n'
            '## Key terminology\n'
            '\n'
            '| Term | Meaning |\n'
            '|---|---|\n'
            '| Image classification | Assigning one or more labels to an entire image |\n'
            '| Image segmentation | Assigning labels at pixel level |\n'
            '| Object detection | Predicting object classes and bounding boxes |\n'
            '| Semantic segmentation | Pixel classification without separating instances of the same class |\n'
            '| Instance segmentation | Pixel-level segmentation that separates individual object instances |\n'
            '| Panoptic segmentation | Semantic class plus instance identity for pixels |\n'
            '| Segmentation mask | Pixel-level target or prediction aligned with an image |\n'
            '| Encoder | Network stage that compresses an image into learned features |\n'
            '| Decoder | Network stage that reconstructs spatial output from learned features |\n'
            '| Strided convolution | Convolution that also reduces spatial resolution |\n'
            '| Transposed convolution | Learnable operation commonly used to increase spatial resolution |\n'
            '| IoU | Intersection area divided by union area |\n'
            '| SAM | Promptable pretrained segmentation model |\n'
            '| Point prompt | A point indicating foreground or background for segmentation |\n'
            '| Box prompt | A rough box indicating the object to segment |\n'
            '| Bounding box | Rectangle describing approximate object location |\n'
            '| R-CNN | Two-stage detection family based on region proposals followed by classification |\n'
            '| Single-stage detector | Detector that predicts box and class information directly |\n'
            '| YOLO | Popular single-stage detection family |\n'
            '| Confidence score | Estimate of whether a prediction represents a valid object and/or how reliable the box is |\n'
            '| Backbone | Feature-extraction network used inside a larger vision system |\n'
            '| RetinaNet | Single-stage object detector |\n'
            '| Feature Pyramid Network | Multi-scale feature architecture combining semantic and spatial information |\n'
            '| COCO | Large annotated computer-vision dataset used for detection and segmentation research |\n'
            '\n'
            '---\n'
            '\n'
            '## Self-check\n'
            '\n'
            'Before continuing, make sure you can answer:\n'
            '\n'
            '1. What is the output difference between classification, detection, and segmentation?\n'
            '2. What is the difference between semantic and instance segmentation?\n'
            '3. Why must a segmentation model preserve spatial information?\n'
            '4. What is the purpose of `Conv2DTranspose` in a simple segmentation decoder?\n'
            '5. How is IoU calculated?\n'
            '6. Why can IoU be more informative than raw pixel accuracy?\n'
            '7. How do point prompts and box prompts differ in SAM?\n'
            '8. Why can a pretrained model like SAM help with dataset creation?\n'
            '9. Why is object detection often cheaper than segmentation?\n'
            '10. What is the difference between two-stage and single-stage detection?\n'
            '11. What does a YOLO grid cell predict?\n'
            '12. Why can the center of an object determine which grid cell owns it?\n'
            '13. Why can empty grid cells dominate a detection loss?\n'
            '14. Why is IoU useful as a confidence target for a predicted box?\n'
            '15. What problem does a Feature Pyramid Network solve?\n'
            '16. When would you choose detection instead of segmentation?\n'
            '\n'
            '---\n'
            '\n'
            '## Retain this idea\n'
            '\n'
            '**Classification tells you what is present, detection tells you what is present and approximately where, and segmentation tells you exactly which pixels belong to what. Segmentation provides richer spatial information, while detection is often more efficient. Modern systems build on shared ConvNet features, overlap metrics such as IoU, and pretrained representations to solve both tasks effectively.**\n'
        ),

        "estimated_minutes": 195,

        "has_code_examples": True,

        "sections": [
            {
                "id": 'cv-task-map',
                "title": 'The three core computer-vision tasks',
                "order": 1,
            },
            {
                "id": 'segmentation-types',
                "title": 'Understanding image segmentation',
                "order": 2,
            },
            {
                "id": 'segmentation-from-scratch',
                "title": 'Building a segmentation model from scratch',
                "order": 3,
            },
            {
                "id": 'iou',
                "title": 'Intersection over Union: a shared metric for segmentation and detection',
                "order": 4,
            },
            {
                "id": 'segmentation-training',
                "title": 'Training and validating the segmentation model',
                "order": 5,
            },
            {
                "id": 'sam',
                "title": 'Using a pretrained segmentation model: Segment Anything',
                "order": 6,
            },
            {
                "id": 'object-detection',
                "title": 'Object detection: labels plus bounding boxes',
                "order": 7,
            },
            {
                "id": 'two-stage-vs-single-stage',
                "title": 'Two-stage versus single-stage detectors',
                "order": 8,
            },
            {
                "id": 'yolo',
                "title": 'Understanding a YOLO-style single-stage detector',
                "order": 9,
            },
            {
                "id": 'yolo-training',
                "title": 'Training a YOLO-style detector',
                "order": 10,
            },
            {
                "id": 'retinanet',
                "title": 'Pretrained detection with RetinaNet',
                "order": 11,
            },
            {
                "id": 'choosing-task',
                "title": 'Choosing classification, segmentation, or detection',
                "order": 12,
            }
        ],
    },


    # =======================================================================
    # INLINE EXERCISES
    # =======================================================================

    "exercises": [
        {
            "id": 'M11.L01.EX01',
            "title": 'Design a Segmentation Pipeline',
            "lesson_code": "M11.L01",
            "section_id": 'sam',
            "placement": "after_section",
            "description": 'Connect segmentation targets, encoder-decoder architecture, IoU evaluation, and pretrained prompting into one coherent workflow.',
            "instructions": '1. Assume you need to separate products from the background in catalog images.\n2. Define what the target segmentation mask should contain.\n3. Sketch an encoder-decoder architecture using strided Conv2D layers and Conv2DTranspose layers.\n4. Explain why spatial information matters more here than in image classification.\n5. State how IoU would be used to evaluate the masks.\n6. Explain one way a promptable pretrained model such as SAM could reduce manual labeling work.',
            "expected_output": 'A concise segmentation-system design covering target-mask format, encoder-decoder flow, spatial reasoning, IoU evaluation, and one SAM-assisted labeling workflow.',
            "difficulty": DifficultyLevel.beginner,
            "skill_tested": [
                'semantic-segmentation',
                'encoder-decoder',
                'iou',
                'sam',
            ],
        },

        {
            "id": 'M11.L01.EX02',
            "title": 'Choose and Design a Detector',
            "lesson_code": "M11.L01",
            "section_id": 'yolo-training',
            "placement": "after_section",
            "description": 'Apply the detection concepts to a real-time object-localization problem and reason about YOLO-style outputs.',
            "instructions": '1. Imagine a warehouse camera must count boxes moving on a conveyor belt in real time.\n2. Decide whether classification, detection, or segmentation is the most appropriate task and justify your choice.\n3. Describe the outputs a YOLO-style grid cell would predict.\n4. Explain how the responsible grid cell could be selected for one object.\n5. Explain how IoU can influence the confidence target during training.\n6. State why a pretrained single-stage detector may be preferable to training a detector from scratch.',
            "expected_output": 'A short system-design answer selecting the task, explaining YOLO box/class/confidence predictions, linking IoU to confidence, and justifying pretrained single-stage detection.',
            "difficulty": DifficultyLevel.beginner,
            "skill_tested": [
                'object-detection',
                'yolo',
                'bounding-boxes',
                'iou',
                'model-selection',
            ],
        }
    ],


    # =======================================================================
    # LESSON QUIZ
    # =======================================================================

    "quiz": {
        "id": "M11.L01.QZ01",

        "title": "Image Segmentation and Object Detection — Knowledge Check",

        "lesson_code": "M11.L01",

        "placement": "lesson_end",

        "questions": [
            {
                "id": 'M11.L01.Q01',
                "section_id": 'cv-task-map',
                "question": 'Which task gives the most precise spatial output?',
                "options": [
                    'Image classification',
                    'Image segmentation',
                    'Ordinary image tagging',
                    'Dataset shuffling',
                ],
                "correct": 1,
                "explanation": 'Segmentation produces pixel-level spatial predictions, which are more precise than image labels or bounding boxes.',
            },

            {
                "id": 'M11.L01.Q02',
                "section_id": 'segmentation-types',
                "question": 'What distinguishes instance segmentation from semantic segmentation?',
                "options": [
                    'Instance segmentation separates different objects belonging to the same semantic class',
                    'Instance segmentation has no pixel-level output',
                    'Semantic segmentation always produces bounding boxes',
                    'There is no difference',
                ],
                "correct": 0,
                "explanation": 'Semantic segmentation assigns class labels to pixels, while instance segmentation also separates individual object instances of the same class.',
            },

            {
                "id": 'M11.L01.Q03',
                "section_id": 'segmentation-from-scratch',
                "question": 'Why are transposed convolutions useful in a simple segmentation network?',
                "options": [
                    'They remove labels from the dataset',
                    'They help increase spatial resolution in the decoder',
                    'They convert masks into bounding boxes',
                    'They prevent all overfitting',
                ],
                "correct": 1,
                "explanation": 'After the encoder compresses the spatial representation, transposed convolutions can learn to upsample features toward the original image resolution.',
            },

            {
                "id": 'M11.L01.Q04',
                "section_id": 'iou',
                "question": 'What does an IoU value of 1 mean?',
                "options": [
                    'The prediction and target do not overlap',
                    'The prediction and target overlap perfectly',
                    'The image has one class',
                    'The model has one layer',
                ],
                "correct": 1,
                "explanation": 'IoU equals intersection divided by union; a value of 1 means the two regions match perfectly.',
            },

            {
                "id": 'M11.L01.Q05',
                "section_id": 'sam',
                "question": 'What is the role of a prompt in a promptable segmentation model such as SAM?',
                "options": [
                    'It identifies which object or region the user wants segmented',
                    'It changes the image file format',
                    'It replaces the image encoder',
                    'It permanently modifies the model weights during every prediction',
                ],
                "correct": 0,
                "explanation": 'Point or box prompts specify the target object or region while the pretrained model produces a corresponding mask.',
            },

            {
                "id": 'M11.L01.Q06',
                "section_id": 'object-detection',
                "question": 'Why might an engineer prefer object detection over segmentation?',
                "options": [
                    'Detection always produces more spatial information',
                    'Bounding boxes can be sufficient while being cheaper to label and faster to predict',
                    'Detection never needs labels',
                    'Segmentation cannot locate objects',
                ],
                "correct": 1,
                "explanation": 'If exact object boundaries are unnecessary, detection can provide enough information at lower annotation and computational cost.',
            },

            {
                "id": 'M11.L01.Q07',
                "section_id": 'two-stage-vs-single-stage',
                "question": 'What is the basic difference between a two-stage detector and a single-stage detector?',
                "options": [
                    'Two-stage systems first generate candidate regions and then classify/refine them; single-stage systems predict detections more directly',
                    'Single-stage systems cannot predict classes',
                    'Two-stage systems only work on video',
                    'Single-stage systems are segmentation networks',
                ],
                "correct": 0,
                "explanation": 'R-CNN-style methods separate region proposal from later classification/refinement, while YOLO/RetinaNet-style systems make detection predictions in a single overall stage.',
            },

            {
                "id": 'M11.L01.Q08',
                "section_id": 'yolo',
                "question": 'What does a simplified YOLO-style grid location predict?',
                "options": [
                    'Only a class name',
                    'Bounding-box information, confidence, and class probabilities',
                    'Only a segmentation mask',
                    'Only the learning rate',
                ],
                "correct": 1,
                "explanation": 'YOLO jointly predicts object geometry, object confidence, and class information at grid locations.',
            },

            {
                "id": 'M11.L01.Q09',
                "section_id": 'yolo-training',
                "question": 'Why can IoU be used as a target for object confidence?',
                "options": [
                    'It measures how well the predicted box overlaps the true box',
                    'It counts the model parameters',
                    'It measures only class imbalance',
                    'It determines the image file size',
                ],
                "correct": 0,
                "explanation": 'A high-IoU prediction is better localized, so IoU provides a smooth spatial-quality signal for confidence.',
            },

            {
                "id": 'M11.L01.Q10',
                "section_id": 'yolo-training',
                "question": 'Why must object-detection losses handle empty grid cells carefully?',
                "options": [
                    'Most grid cells may contain no object and could dominate the loss if weighted equally',
                    'Empty cells always contain hidden labels',
                    'Empty cells cannot be represented numerically',
                    'The detector is unable to predict confidence values',
                ],
                "correct": 0,
                "explanation": 'Object detection has many negative locations, so careless weighting can make background confidence errors overwhelm useful localization learning.',
            },

            {
                "id": 'M11.L01.Q11',
                "section_id": 'retinanet',
                "question": 'What problem does a Feature Pyramid Network primarily address?',
                "options": [
                    'Detecting objects at different spatial scales using semantically strong multi-resolution features',
                    'Removing all object classes',
                    'Converting detection into language modeling',
                    'Avoiding convolution entirely',
                ],
                "correct": 0,
                "explanation": 'FPNs combine deep semantic features with higher-resolution features so detectors can better handle both small and large objects.',
            },

            {
                "id": 'M11.L01.Q12',
                "section_id": 'choosing-task',
                "type": "open",
                "question": 'For each of these applications, choose classification, object detection, or segmentation and justify the choice: (1) identify whether a photo contains a damaged package, (2) count every package on a conveyor belt, (3) remove the exact background around each package for image editing.',
            }
        ],

        "passing_score": 70,
    },
}
