"""M18.L01 — Real-World Deep Learning: Tuning, Scaling, and Efficient Inference.

One Topic -> one complete learner-facing Lesson + inline Exercises + lesson Quiz.
BOOK-002, Chapter 18, page range not provided in supplied source.
Instructor-authored curriculum adaptation.
"""

from app.models.learning import DifficultyLevel


# ---------------------------------------------------------------------------
# Lesson metadata
# ---------------------------------------------------------------------------

LESSON_CODE = "M18.L01"

MODULE_ORDER = 18

MODULE_TITLE = "Best Practices for Real-World Deep Learning"

MODULE_DESCRIPTION = (
    "Move from small experimental models toward real-world machine learning "
    "engineering by systematically tuning hyperparameters, combining diverse "
    "models with ensembles, scaling training across GPUs and TPUs, and using "
    "lower-precision computation and quantization to improve performance."
)

SOURCE_CHAPTER = 18

SOURCE_PAGES = "Chapter 18 — page range not provided"


# ---------------------------------------------------------------------------
# Topic
# ---------------------------------------------------------------------------

TOPIC = {
    "title": "Real-World Deep Learning: Tuning, Scaling, and Efficient Inference",

    "slug": "deep-learning-foundations-m18-l01",

    "description": (
        "Learn the practical techniques used to improve and scale deep learning "
        "systems: hyperparameter optimization, diverse model ensembles, "
        "data and model parallelism, TPU training, mixed precision, loss "
        "scaling, and int8 quantization."
    ),

    "order": 1,

    "difficulty": DifficultyLevel.intermediate,

    "estimated_hours": 3.0,

    "skill_tags": [
        "deep-learning",
        "machine-learning-engineering",
        "hyperparameter-tuning",
        "keras-tuner",
        "ensembling",
        "distributed-training",
        "data-parallelism",
        "model-parallelism",
        "gpu",
        "tpu",
        "mixed-precision",
        "float16",
        "bfloat16",
        "loss-scaling",
        "quantization",
        "int8",
    ],

    "prerequisite_ids": [],


    # =======================================================================
    # LESSON
    # =======================================================================

    "lesson": {
        "title": "Real-World Deep Learning: Tuning, Scaling, and Efficient Inference",

        "content": (
            "# Real-World Deep Learning: Tuning, Scaling, and Efficient Inference\n"
            "\n"
            "> **Course:** Deep Learning Foundations  \n"
            "> **Lesson:** M18.L01  \n"
            "> **Module:** Best Practices for Real-World Deep Learning  \n"
            "> **Source alignment:** BOOK-002, Chapter 18. "
            "The supplied source did not specify a page range. "
            "This lesson is an instructor-authored curriculum adaptation "
            "rather than a reproduction of the source text.\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Learning outcomes
            # ----------------------------------------------------------------

            "## Learning outcomes\n"
            "\n"
            "By the end of this lesson, you should be able to:\n"
            "\n"
            "- Distinguish model parameters from hyperparameters.\n"
            "- Explain why systematic hyperparameter search can outperform "
            "manual trial and error.\n"
            "- Define a useful hyperparameter search space.\n"
            "- Explain how KerasTuner evaluates model configurations.\n"
            "- Explain why validation data—not test data—should guide tuning.\n"
            "- Recognize validation-set overfitting during extensive tuning.\n"
            "- Explain model ensembling and why diversity matters.\n"
            "- Distinguish equal averaging from weighted ensembling.\n"
            "- Distinguish data parallelism from model parallelism.\n"
            "- Explain synchronous multi-GPU training.\n"
            "- Explain why large models may require parameter sharding.\n"
            "- Explain the roles of device meshes and layout maps.\n"
            "- Explain when TPU training can improve throughput.\n"
            "- Explain why large batches may require learning-rate changes.\n"
            "- Explain the purpose of `steps_per_execution`.\n"
            "- Compare float16, float32, float64, and bfloat16 conceptually.\n"
            "- Explain mixed-precision training.\n"
            "- Explain why small gradients can underflow in low precision.\n"
            "- Explain loss scaling.\n"
            "- Explain how int8 quantization accelerates inference.\n"
            "- Distinguish training-time mixed precision from post-training "
            "quantization.\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Section 1
            # ----------------------------------------------------------------

            "## 1. Getting More Performance from Your Models\n"
            "\n"
            "Once you know how to train a model that works, the next question is:\n"
            "\n"
            "> How do you systematically make it better?\n"
            "\n"
            "Real machine learning engineering involves much more than writing "
            "one architecture and training it once.\n"
            "\n"
            "You repeatedly make choices such as:\n"
            "\n"
            "```text\n"
            "How many layers?\n"
            "How many units?\n"
            "Which optimizer?\n"
            "What learning rate?\n"
            "How much dropout?\n"
            "Should BatchNormalization be used?\n"
            "Which architecture family?\n"
            "```\n"
            "\n"
            "These choices are **hyperparameters**.\n"
            "\n"
            "### Parameters versus hyperparameters\n"
            "\n"
            "A **parameter** is learned by gradient descent.\n"
            "\n"
            "Examples:\n"
            "\n"
            "```text\n"
            "Dense layer weights\n"
            "convolution kernels\n"
            "bias vectors\n"
            "embedding vectors\n"
            "```\n"
            "\n"
            "A **hyperparameter** is chosen outside the normal backpropagation "
            "process.\n"
            "\n"
            "Examples:\n"
            "\n"
            "```text\n"
            "number of units\n"
            "number of layers\n"
            "optimizer choice\n"
            "dropout rate\n"
            "learning rate\n"
            "```\n"
            "\n"
            "Think of it this way:\n"
            "\n"
            "```text\n"
            "BACKPROPAGATION\n"
            "→ learns weights\n"
            "\n"
            "HYPERPARAMETER SEARCH\n"
            "→ chooses how the model itself should be configured\n"
            "```\n"
            "\n"
            "### Why can't gradient descent optimize everything?\n"
            "\n"
            "Many hyperparameter choices are discrete.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "optimizer = Adam OR RMSprop\n"
            "\n"
            "units = 32 OR 64 OR 128\n"
            "\n"
            "use BatchNorm = True OR False\n"
            "```\n"
            "\n"
            "These choices do not form a smooth differentiable space in the "
            "same way neural-network weights do.\n"
            "\n"
            "Therefore hyperparameter optimization usually relies on "
            "gradient-free search strategies such as:\n"
            "\n"
            "```text\n"
            "random search\n"
            "Bayesian optimization\n"
            "genetic algorithms\n"
            "```\n"
            "\n"
            "### The hyperparameter tuning loop\n"
            "\n"
            "The process is:\n"
            "\n"
            "```text\n"
            "Choose configuration\n"
            "       ↓\n"
            "Build model\n"
            "       ↓\n"
            "Train model\n"
            "       ↓\n"
            "Evaluate on validation data\n"
            "       ↓\n"
            "Use result to choose next configuration\n"
            "       ↓\n"
            "Repeat\n"
            "```\n"
            "\n"
            "Only after the search and final model selection should the "
            "untouched test set be used for final evaluation.\n"
            "\n"
            "### Why tuning is expensive\n"
            "\n"
            "When ordinary training updates model weights, each update only "
            "needs a mini-batch forward and backward pass.\n"
            "\n"
            "Hyperparameter optimization is much more expensive because one "
            "evaluation may require training an entirely new model.\n"
            "\n"
            "```text\n"
            "one hyperparameter trial\n"
            "=\n"
            "build model\n"
            "+\n"
            "train from scratch\n"
            "+\n"
            "evaluate\n"
            "```\n"
            "\n"
            "If you test 100 configurations, that could mean 100 substantial "
            "training runs.\n"
            "\n"
            "### Training noise\n"
            "\n"
            "Two identical architectures can produce slightly different results "
            "because of:\n"
            "\n"
            "- random initialization,\n"
            "- mini-batch ordering,\n"
            "- stochastic regularization,\n"
            "- and other randomness.\n"
            "\n"
            "So a configuration that scores 0.2% better once may not actually "
            "be better.\n"
            "\n"
            "Repeating a trial multiple times and averaging performance can "
            "reduce this uncertainty.\n"
            "\n"
            "### KerasTuner\n"
            "\n"
            "KerasTuner allows hardcoded choices to become searchable ranges.\n"
            "\n"
            "Instead of:\n"
            "\n"
            "```python\n"
            "layers.Dense(32, activation=\"relu\")\n"
            "```\n"
            "\n"
            "we can define:\n"
            "\n"
            "```python\n"
            "units = hp.Int(\n"
            "    name=\"units\",\n"
            "    min_value=16,\n"
            "    max_value=64,\n"
            "    step=16,\n"
            ")\n"
            "```\n"
            "\n"
            "Now possible values are:\n"
            "\n"
            "```text\n"
            "16\n"
            "32\n"
            "48\n"
            "64\n"
            "```\n"
            "\n"
            "Optimizer choice can also be searched:\n"
            "\n"
            "```python\n"
            "optimizer = hp.Choice(\n"
            "    name=\"optimizer\",\n"
            "    values=[\"rmsprop\", \"adam\"],\n"
            ")\n"
            "```\n"
            "\n"
            "### Search space\n"
            "\n"
            "The complete collection of possibilities is the **search space**.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "units:\n"
            "16, 32, 48, 64\n"
            "\n"
            "optimizer:\n"
            "RMSprop, Adam\n"
            "```\n"
            "\n"
            "Even this tiny search space already contains:\n"
            "\n"
            "```text\n"
            "4 × 2 = 8 configurations\n"
            "```\n"
            "\n"
            "Search spaces can grow combinatorially, so they must be designed "
            "carefully.\n"
            "\n"
            "### Defining the model-building function\n"
            "\n"
            "A tuner needs a function that accepts hyperparameters and returns "
            "a compiled model.\n"
            "\n"
            "```python\n"
            "def build_model(hp):\n"
            "    units = hp.Int(\n"
            "        \"units\",\n"
            "        min_value=16,\n"
            "        max_value=64,\n"
            "        step=16,\n"
            "    )\n"
            "\n"
            "    model = keras.Sequential([\n"
            "        layers.Dense(units, activation=\"relu\"),\n"
            "        layers.Dense(10, activation=\"softmax\"),\n"
            "    ])\n"
            "\n"
            "    optimizer = hp.Choice(\n"
            "        \"optimizer\",\n"
            "        [\"rmsprop\", \"adam\"],\n"
            "    )\n"
            "\n"
            "    model.compile(\n"
            "        optimizer=optimizer,\n"
            "        loss=\"sparse_categorical_crossentropy\",\n"
            "        metrics=[\"accuracy\"],\n"
            "    )\n"
            "\n"
            "    return model\n"
            "```\n"
            "\n"
            "### Choosing a tuner\n"
            "\n"
            "The source mentions several KerasTuner strategies:\n"
            "\n"
            "```text\n"
            "RandomSearch\n"
            "BayesianOptimization\n"
            "Hyperband\n"
            "```\n"
            "\n"
            "Bayesian optimization attempts to use results from previous trials "
            "to choose promising future configurations.\n"
            "\n"
            "For example:\n"
            "\n"
            "```python\n"
            "tuner = kt.BayesianOptimization(\n"
            "    build_model,\n"
            "    objective=\"val_accuracy\",\n"
            "    max_trials=20,\n"
            "    executions_per_trial=2,\n"
            ")\n"
            "```\n"
            "\n"
            "`max_trials=20` means at most 20 different configurations are tested.\n"
            "\n"
            "`executions_per_trial=2` means each configuration is trained twice, "
            "helping reduce the effect of random training variation.\n"
            "\n"
            "### Optimize validation metrics\n"
            "\n"
            "The tuner should optimize a validation metric:\n"
            "\n"
            "```text\n"
            "val_accuracy\n"
            "val_loss\n"
            "```\n"
            "\n"
            "not test performance.\n"
            "\n"
            "Why?\n"
            "\n"
            "Because tuning itself is a learning process.\n"
            "\n"
            "If you repeatedly choose hyperparameters based on test results, "
            "the test set becomes part of your optimization process.\n"
            "\n"
            "Its final score would no longer be trustworthy.\n"
            "\n"
            "### Early stopping during tuning\n"
            "\n"
            "Different model configurations may require different numbers of "
            "epochs.\n"
            "\n"
            "Instead of guessing one fixed epoch count, you can train for a "
            "large maximum and stop when validation performance stops improving.\n"
            "\n"
            "```python\n"
            "keras.callbacks.EarlyStopping(\n"
            "    monitor=\"val_loss\",\n"
            "    patience=5,\n"
            ")\n"
            "```\n"
            "\n"
            "This saves significant search time.\n"
            "\n"
            "### Validation-set overfitting\n"
            "\n"
            "There is a subtle danger.\n"
            "\n"
            "Suppose you run:\n"
            "\n"
            "```text\n"
            "10 trials\n"
            "100 trials\n"
            "1,000 trials\n"
            "10,000 trials\n"
            "```\n"
            "\n"
            "and every decision is based on the same validation set.\n"
            "\n"
            "Eventually, your hyperparameter search begins adapting to random "
            "quirks of that validation set.\n"
            "\n"
            "This is **validation-set overfitting**.\n"
            "\n"
            "Therefore:\n"
            "\n"
            "```text\n"
            "training set\n"
            "→ learn weights\n"
            "\n"
            "validation set\n"
            "→ choose architecture + hyperparameters\n"
            "\n"
            "test set\n"
            "→ final independent evaluation\n"
            "```\n"
            "\n"
            "### Search-space design still requires expertise\n"
            "\n"
            "Hyperparameter optimization is automation, not magic.\n"
            "\n"
            "Searching everything would be too expensive.\n"
            "\n"
            "You still need architectural knowledge to choose promising ranges.\n"
            "\n"
            "A good engineer moves from questions such as:\n"
            "\n"
            "```text\n"
            "\"Should this layer have 128 or 192 units?\"\n"
            "```\n"
            "\n"
            "toward higher-level decisions such as:\n"
            "\n"
            "```text\n"
            "\"Should this architecture use residual blocks?\"\n"
            "\"Should normalization be included?\"\n"
            "```\n"
            "\n"
            "### Model ensembling\n"
            "\n"
            "Hyperparameter tuning tries to find one strong model.\n"
            "\n"
            "Ensembling asks another question:\n"
            "\n"
            "> What if several strong models are combined?\n"
            "\n"
            "Suppose four classifiers produce probabilities:\n"
            "\n"
            "```python\n"
            "pred_a = model_a.predict(x)\n"
            "pred_b = model_b.predict(x)\n"
            "pred_c = model_c.predict(x)\n"
            "pred_d = model_d.predict(x)\n"
            "```\n"
            "\n"
            "A simple ensemble averages them:\n"
            "\n"
            "```python\n"
            "final_pred = 0.25 * (\n"
            "    pred_a + pred_b + pred_c + pred_d\n"
            ")\n"
            "```\n"
            "\n"
            "### Why ensembling works\n"
            "\n"
            "Different models can make different errors.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "Model A\n"
            "→ excellent at pattern type 1\n"
            "→ weaker at pattern type 2\n"
            "\n"
            "Model B\n"
            "→ weaker at pattern type 1\n"
            "→ excellent at pattern type 2\n"
            "```\n"
            "\n"
            "Combining them can produce a better overall system.\n"
            "\n"
            "### Weighted averaging\n"
            "\n"
            "If models have different quality, equal averaging may not be best.\n"
            "\n"
            "For example:\n"
            "\n"
            "```python\n"
            "final_pred = (\n"
            "    0.50 * pred_a\n"
            "    + 0.25 * pred_b\n"
            "    + 0.10 * pred_c\n"
            "    + 0.15 * pred_d\n"
            ")\n"
            "```\n"
            "\n"
            "The weights can be tuned using validation data.\n"
            "\n"
            "### Diversity matters more than repetition\n"
            "\n"
            "The main principle of ensembling is:\n"
            "\n"
            "> Strong models should ideally make different kinds of mistakes.\n"
            "\n"
            "Ensembling several nearly identical models trained from different "
            "random initializations may produce only a small improvement.\n"
            "\n"
            "Greater diversity may come from combining:\n"
            "\n"
            "```text\n"
            "different architectures\n"
            "different feature representations\n"
            "different model families\n"
            "```\n"
            "\n"
            "The source even discusses combining tree-based methods and neural "
            "networks because their different biases can make the ensemble stronger.\n"
            "\n"
            "> **Recommended manual figure:** Add a diagram here showing "
            "`Model A + Model B + Model C → weighted averaging → final prediction`.\n"
            "\n"

            # Exercise EX01 is rendered here by the frontend.
            "{{exercise:M18.L01.EX01}}\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Section 2
            # ----------------------------------------------------------------

            "## 2. Scaling Training Across Multiple Devices\n"
            "\n"
            "Model quality depends heavily on experimentation.\n"
            "\n"
            "A useful engineering loop is:\n"
            "\n"
            "```text\n"
            "idea\n"
            " ↓\n"
            "experiment\n"
            " ↓\n"
            "results\n"
            " ↓\n"
            "analysis\n"
            " ↓\n"
            "better idea\n"
            " ↓\n"
            "repeat\n"
            "```\n"
            "\n"
            "If training one experiment takes two days, iteration is slow.\n"
            "\n"
            "If it takes fifteen minutes, many more ideas can be tested.\n"
            "\n"
            "Faster training therefore contributes indirectly to better models.\n"
            "\n"
            "### Two forms of parallelism\n"
            "\n"
            "There are two main ways to distribute deep-learning computation:\n"
            "\n"
            "```text\n"
            "DATA PARALLELISM\n"
            "→ split the data\n"
            "\n"
            "MODEL PARALLELISM\n"
            "→ split the model\n"
            "```\n"
            "\n"
            "### Data parallelism\n"
            "\n"
            "With data parallelism, every device stores a full copy of the model.\n"
            "\n"
            "The batch is divided among devices.\n"
            "\n"
            "Suppose:\n"
            "\n"
            "```text\n"
            "global batch size = 128\n"
            "GPUs              = 2\n"
            "```\n"
            "\n"
            "Then:\n"
            "\n"
            "```text\n"
            "GPU 0\n"
            "→ model replica\n"
            "→ 64 samples\n"
            "\n"
            "GPU 1\n"
            "→ model replica\n"
            "→ 64 samples\n"
            "```\n"
            "\n"
            "Each replica computes gradients from its local sub-batch.\n"
            "\n"
            "The gradients are then combined—typically averaged—and all model "
            "replicas receive the same update.\n"
            "\n"
            "Conceptually:\n"
            "\n"
            "```text\n"
            "batch\n"
            " ├── GPU 0 → gradients ──┐\n"
            " └── GPU 1 → gradients ──┤\n"
            "                          ↓\n"
            "                    average gradients\n"
            "                          ↓\n"
            "                    update all replicas\n"
            "```\n"
            "\n"
            "This keeps model weights synchronized.\n"
            "\n"
            "### Limitation of data parallelism\n"
            "\n"
            "Every device must contain a full copy of the model.\n"
            "\n"
            "Therefore:\n"
            "\n"
            "```text\n"
            "model must fit on one GPU\n"
            "```\n"
            "\n"
            "If the model itself is larger than one device's memory, data "
            "parallelism alone is not enough.\n"
            "\n"
            "### Model parallelism\n"
            "\n"
            "With model parallelism, one model is divided across several devices.\n"
            "\n"
            "```text\n"
            "GPU 0 → part of model\n"
            "GPU 1 → part of model\n"
            "GPU 2 → part of model\n"
            "GPU 3 → part of model\n"
            "```\n"
            "\n"
            "This enables training models that cannot fit on one accelerator.\n"
            "\n"
            "### Horizontal model partitioning\n"
            "\n"
            "One approach puts different layers on different devices.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "GPU 0\n"
            "→ Layer 1\n"
            "\n"
            "GPU 1\n"
            "→ Layer 2\n"
            "```\n"
            "\n"
            "The disadvantage is communication overhead.\n"
            "\n"
            "The output from GPU 0 must travel to GPU 1 before computation can continue.\n"
            "\n"
            "If intermediate tensors are large, device communication may become "
            "a bottleneck.\n"
            "\n"
            "### Vertical partitioning\n"
            "\n"
            "Another approach divides individual layer parameters across devices.\n"
            "\n"
            "Suppose a Dense kernel has shape:\n"
            "\n"
            "```text\n"
            "(16000, 64000)\n"
            "```\n"
            "\n"
            "With two GPUs, it could be divided into:\n"
            "\n"
            "```text\n"
            "GPU 0 → (16000, 32000)\n"
            "GPU 1 → (16000, 32000)\n"
            "```\n"
            "\n"
            "Each GPU computes part of the output, then the pieces are combined.\n"
            "\n"
            "This is often called **sharding** or **partitioning**.\n"
            "\n"
            "### Combining data and model parallelism\n"
            "\n"
            "Large training systems may use both.\n"
            "\n"
            "For example, with eight GPUs:\n"
            "\n"
            "```text\n"
            "4 GPUs\n"
            "→ one sharded model replica\n"
            "\n"
            "another 4 GPUs\n"
            "→ second sharded model replica\n"
            "```\n"
            "\n"
            "Now you have:\n"
            "\n"
            "```text\n"
            "model parallelism within each group\n"
            "+\n"
            "data parallelism between groups\n"
            "```\n"
            "\n"
            "### Keras data parallelism\n"
            "\n"
            "The chapter demonstrates Keras distribution with the JAX backend.\n"
            "\n"
            "Data parallelism can be enabled before model construction:\n"
            "\n"
            "```python\n"
            "keras.distribution.set_distribution(\n"
            "    keras.distribution.DataParallel()\n"
            ")\n"
            "```\n"
            "\n"
            "Specific devices can also be supplied:\n"
            "\n"
            "```python\n"
            "keras.distribution.set_distribution(\n"
            "    keras.distribution.DataParallel([\n"
            "        \"gpu:0\",\n"
            "        \"gpu:1\",\n"
            "    ])\n"
            ")\n"
            "```\n"
            "\n"
            "### Scaling is not perfectly linear\n"
            "\n"
            "Two GPUs do not always make training exactly twice as fast.\n"
            "\n"
            "Additional overhead comes from:\n"
            "\n"
            "```text\n"
            "gradient synchronization\n"
            "communication\n"
            "device coordination\n"
            "data loading\n"
            "```\n"
            "\n"
            "The source reports example scaling close to:\n"
            "\n"
            "```text\n"
            "2 GPUs → about 2×\n"
            "4 GPUs → about 3.8×\n"
            "8 GPUs → about 7.3×\n"
            "```\n"
            "\n"
            "provided the global batch is large enough to keep all devices busy.\n"
            "\n"
            "### Device meshes\n"
            "\n"
            "For more complex distributed setups, Keras uses a **device mesh**.\n"
            "\n"
            "Imagine eight GPUs arranged logically as:\n"
            "\n"
            "```text\n"
            "        model axis\n"
            "        → → → →\n"
            "\n"
            "data ↓  GPU GPU GPU GPU\n"
            "axis ↓  GPU GPU GPU GPU\n"
            "```\n"
            "\n"
            "For example:\n"
            "\n"
            "```python\n"
            "device_mesh = keras.distribution.DeviceMesh(\n"
            "    shape=(2, 4),\n"
            "    axis_names=[\"data\", \"model\"],\n"
            ")\n"
            "```\n"
            "\n"
            "This means:\n"
            "\n"
            "```text\n"
            "2-way data parallelism\n"
            "4-way model parallelism\n"
            "```\n"
            "\n"
            "### Layout maps\n"
            "\n"
            "A `LayoutMap` tells Keras how variables should be distributed over "
            "the mesh.\n"
            "\n"
            "For each variable dimension, it can choose to:\n"
            "\n"
            "```text\n"
            "replicate it\n"
            "or\n"
            "shard it\n"
            "```\n"
            "\n"
            "A simple rule presented in the source is:\n"
            "\n"
            "```text\n"
            "shard the last variable dimension along the model axis\n"
            "replicate the remaining dimensions\n"
            "```\n"
            "\n"
            "For example:\n"
            "\n"
            "```python\n"
            "layout_map[\n"
            "    \"sequential/dense/kernel\"\n"
            "] = (None, \"model\")\n"
            "```\n"
            "\n"
            "`None` means that dimension is replicated.\n"
            "\n"
            "`\"model\"` means that dimension is sharded across the model axis.\n"
            "\n"
            "### Data pipelines matter\n"
            "\n"
            "A fast GPU cluster is useless if it spends most of its time waiting "
            "for data.\n"
            "\n"
            "The source recommends efficient `tf.data` pipelines and prefetching:\n"
            "\n"
            "```python\n"
            "dataset = dataset.prefetch(tf.data.AUTOTUNE)\n"
            "```\n"
            "\n"
            "This allows data preparation to overlap with model computation.\n"
            "\n"
            "> **Recommended manual figure:** Add a diagram here comparing "
            "`data parallelism` and `model parallelism`, then show a combined "
            "2 × 4 device mesh underneath.\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Section 3
            # ----------------------------------------------------------------

            "## 3. TPU Training and Keeping Accelerators Busy\n"
            "\n"
            "GPUs are not the only hardware used for deep learning.\n"
            "\n"
            "A **Tensor Processing Unit**, or TPU, is specialized hardware "
            "designed for machine-learning tensor computation.\n"
            "\n"
            "The general principle is the same:\n"
            "\n"
            "> Specialized hardware is useful only when you feed it enough work.\n"
            "\n"
            "### TPU distribution\n"
            "\n"
            "The chapter explains that Keras distribution APIs can also be used "
            "with TPU devices.\n"
            "\n"
            "As with GPU distribution, the distribution configuration should be "
            "set before creating the model.\n"
            "\n"
            "### Data loading can become the bottleneck\n"
            "\n"
            "Suppose a TPU can consume batches extremely quickly.\n"
            "\n"
            "If your storage delivers data slowly, the TPU may sit idle.\n"
            "\n"
            "```text\n"
            "slow storage\n"
            "      ↓\n"
            "waiting\n"
            "      ↓\n"
            "underutilized accelerator\n"
            "```\n"
            "\n"
            "For small enough datasets, caching can help:\n"
            "\n"
            "```python\n"
            "dataset = dataset.cache()\n"
            "```\n"
            "\n"
            "### Batch size and accelerator utilization\n"
            "\n"
            "Large accelerators generally need sufficient batch sizes to reach "
            "high utilization.\n"
            "\n"
            "A tiny batch might not provide enough matrix operations to occupy "
            "all available compute units.\n"
            "\n"
            "### Large batches and learning rate\n"
            "\n"
            "If the batch size grows substantially, the model performs fewer "
            "parameter updates per epoch.\n"
            "\n"
            "But each update is based on more examples and may therefore provide "
            "a more stable gradient estimate.\n"
            "\n"
            "The source notes that larger batches often call for a larger "
            "learning rate.\n"
            "\n"
            "Conceptually:\n"
            "\n"
            "```text\n"
            "larger batch\n"
            "→ fewer updates\n"
            "→ each gradient uses more samples\n"
            "→ potentially larger useful update step\n"
            "```\n"
            "\n"
            "This is a tuning decision rather than a universal fixed formula.\n"
            "\n"
            "### Step fusing\n"
            "\n"
            "Another approach is to perform several training steps within one "
            "accelerator execution cycle.\n"
            "\n"
            "In Keras:\n"
            "\n"
            "```python\n"
            "model.compile(\n"
            "    ...,\n"
            "    steps_per_execution=8,\n"
            ")\n"
            "```\n"
            "\n"
            "Instead of:\n"
            "\n"
            "```text\n"
            "host ↔ accelerator\n"
            "for every single step\n"
            "```\n"
            "\n"
            "you perform:\n"
            "\n"
            "```text\n"
            "host\n"
            " ↓\n"
            "accelerator runs several steps\n"
            " ↓\n"
            "host\n"
            "```\n"
            "\n"
            "This reduces communication overhead and can improve accelerator "
            "utilization, especially for relatively small models.\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Section 4
            # ----------------------------------------------------------------

            "## 4. Mixed Precision and Quantization\n"
            "\n"
            "Another major way to speed up deep learning is to make individual "
            "numerical operations cheaper.\n"
            "\n"
            "This leads us to numerical precision.\n"
            "\n"
            "### What is numerical precision?\n"
            "\n"
            "Computers represent numbers with a finite number of bits.\n"
            "\n"
            "Common floating-point types include:\n"
            "\n"
            "```text\n"
            "float16 → 16 bits\n"
            "float32 → 32 bits\n"
            "float64 → 64 bits\n"
            "```\n"
            "\n"
            "More bits provide finer numerical resolution but require more "
            "memory and computation.\n"
            "\n"
            "Think of numerical precision like image resolution:\n"
            "\n"
            "```text\n"
            "more bits\n"
            "→ finer detail\n"
            "→ greater cost\n"
            "\n"
            "fewer bits\n"
            "→ less detail\n"
            "→ lower cost\n"
            "```\n"
            "\n"
            "### Why low precision can be faster\n"
            "\n"
            "Modern GPUs and TPUs contain hardware optimized for lower-precision "
            "matrix operations.\n"
            "\n"
            "Benefits can include:\n"
            "\n"
            "```text\n"
            "less memory use\n"
            "higher throughput\n"
            "faster matrix multiplication\n"
            "larger possible batch sizes\n"
            "```\n"
            "\n"
            "### Float16 inference\n"
            "\n"
            "For inference, lower precision is often straightforward.\n"
            "\n"
            "The source demonstrates:\n"
            "\n"
            "```python\n"
            "keras.config.set_dtype_policy(\"float16\")\n"
            "```\n"
            "\n"
            "This should be configured before creating the model.\n"
            "\n"
            "The chapter notes that suitable GPU or TPU hardware may approach "
            "roughly a 2× inference speedup.\n"
            "\n"
            "### bfloat16\n"
            "\n"
            "`bfloat16` also uses 16 bits but distributes those bits differently.\n"
            "\n"
            "Compared with float16:\n"
            "\n"
            "```text\n"
            "float16\n"
            "→ more mantissa precision\n"
            "→ smaller exponent range\n"
            "\n"
            "bfloat16\n"
            "→ less mantissa precision\n"
            "→ larger exponent range\n"
            "```\n"
            "\n"
            "Some hardware is better optimized for bfloat16.\n"
            "\n"
            "### Why not train everything directly in float16?\n"
            "\n"
            "Training introduces a problem that inference does not have:\n"
            "\n"
            "```text\n"
            "gradients can become extremely small\n"
            "```\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "1e-5\n"
            "1e-6\n"
            "```\n"
            "\n"
            "Low precision may not represent these updates accurately enough.\n"
            "\n"
            "A tiny gradient may even round to zero.\n"
            "\n"
            "Then learning stops for that parameter.\n"
            "\n"
            "### Mixed-precision training\n"
            "\n"
            "The solution is to use different precisions for different parts "
            "of training.\n"
            "\n"
            "The basic idea is:\n"
            "\n"
            "```text\n"
            "forward computation\n"
            "→ mostly float16\n"
            "\n"
            "model variables\n"
            "→ float32\n"
            "\n"
            "sensitive updates\n"
            "→ float32\n"
            "```\n"
            "\n"
            "In Keras:\n"
            "\n"
            "```python\n"
            "keras.config.set_dtype_policy(\"mixed_float16\")\n"
            "```\n"
            "\n"
            "This aims to keep much of the speed advantage of half-precision "
            "computation while preserving stable optimization.\n"
            "\n"
            "### Compute dtype versus variable dtype\n"
            "\n"
            "A Keras layer can conceptually have:\n"
            "\n"
            "```text\n"
            "compute_dtype\n"
            "→ precision used for operations\n"
            "\n"
            "variable_dtype\n"
            "→ precision used to store weights\n"
            "```\n"
            "\n"
            "Under mixed precision:\n"
            "\n"
            "```text\n"
            "compute_dtype  ≈ float16\n"
            "variable_dtype = float32\n"
            "```\n"
            "\n"
            "This lets the model use fast low-precision matrix operations while "
            "keeping parameter updates accurate.\n"
            "\n"
            "### Some operations need float32\n"
            "\n"
            "Certain operations can be numerically unstable in float16.\n"
            "\n"
            "The source specifically mentions operations such as:\n"
            "\n"
            "```text\n"
            "softmax\n"
            "crossentropy\n"
            "```\n"
            "\n"
            "A layer can opt out of mixed precision:\n"
            "\n"
            "```python\n"
            "layers.Dense(..., dtype=\"float32\")\n"
            "```\n"
            "\n"
            "### Gradient underflow\n"
            "\n"
            "Imagine a gradient:\n"
            "\n"
            "```text\n"
            "0.000001\n"
            "```\n"
            "\n"
            "If float16 cannot represent it accurately, it could effectively "
            "become:\n"
            "\n"
            "```text\n"
            "0\n"
            "```\n"
            "\n"
            "This is called **underflow**.\n"
            "\n"
            "### Loss scaling\n"
            "\n"
            "Gradients are proportional to the loss.\n"
            "\n"
            "If we temporarily make the loss larger, gradients become larger too.\n"
            "\n"
            "Suppose:\n"
            "\n"
            "```text\n"
            "original gradient = 0.000001\n"
            "```\n"
            "\n"
            "If loss is scaled by 1,000:\n"
            "\n"
            "```text\n"
            "scaled gradient ≈ 0.001\n"
            "```\n"
            "\n"
            "This larger number is easier to represent in float16.\n"
            "\n"
            "Afterward the scaling can be accounted for correctly during the "
            "optimizer update.\n"
            "\n"
            "The source demonstrates automatic loss scaling:\n"
            "\n"
            "```python\n"
            "optimizer = keras.optimizers.LossScaleOptimizer(\n"
            "    keras.optimizers.Adam(learning_rate=1e-3)\n"
            ")\n"
            "```\n"
            "\n"
            "Automatic scaling is useful because an appropriate scale can change "
            "during training.\n"
            "\n"
            "### What about float8?\n"
            "\n"
            "Going from float32 to float16 often works with relatively little "
            "special handling.\n"
            "\n"
            "Going to float8 is much harder because considerably more numerical "
            "information is lost.\n"
            "\n"
            "The source explains that special rescaling logic is required and "
            "that the overhead is generally worthwhile only for very large models "
            "and suitable modern hardware.\n"
            "\n"
            "So:\n"
            "\n"
            "```text\n"
            "float16 mixed precision\n"
            "→ broadly practical\n"
            "\n"
            "float8 training\n"
            "→ specialized large-scale optimization\n"
            "```\n"
            "\n"
            "### Quantization\n"
            "\n"
            "Mixed precision focuses mainly on computation during training and "
            "inference.\n"
            "\n"
            "**Quantization** takes an already trained model and represents "
            "certain values using a smaller numerical format.\n"
            "\n"
            "A common example is:\n"
            "\n"
            "```text\n"
            "float32 weights\n"
            "→ int8 weights\n"
            "```\n"
            "\n"
            "### Why int8?\n"
            "\n"
            "`int8` uses only eight bits.\n"
            "\n"
            "Its signed range is approximately:\n"
            "\n"
            "```text\n"
            "-127 to 127\n"
            "```\n"
            "\n"
            "Using int8 can provide:\n"
            "\n"
            "```text\n"
            "smaller model size\n"
            "less memory bandwidth\n"
            "faster supported matrix operations\n"
            "faster inference\n"
            "```\n"
            "\n"
            "### Why not simply cast floats to integers?\n"
            "\n"
            "Suppose:\n"
            "\n"
            "```text\n"
            "0.1\n"
            "0.9\n"
            "-0.8\n"
            "```\n"
            "\n"
            "A naive integer conversion could destroy most information:\n"
            "\n"
            "```text\n"
            "0.1 → 0\n"
            "0.9 → 0\n"
            "-0.8 → 0\n"
            "```\n"
            "\n"
            "Instead, values are **scaled** to use the available int8 range.\n"
            "\n"
            "### Abs-max scaling intuition\n"
            "\n"
            "Suppose the largest absolute value in a tensor is:\n"
            "\n"
            "```text\n"
            "1.2\n"
            "```\n"
            "\n"
            "We want that value to map near:\n"
            "\n"
            "```text\n"
            "127\n"
            "```\n"
            "\n"
            "So:\n"
            "\n"
            "```text\n"
            "scale ≈ 127 / 1.2\n"
            "```\n"
            "\n"
            "Then:\n"
            "\n"
            "```text\n"
            "floating values\n"
            "   ↓ scale\n"
            "larger numerical values\n"
            "   ↓ round\n"
            "integers\n"
            "   ↓ cast\n"
            "int8\n"
            "```\n"
            "\n"
            "After int8 matrix multiplication, the result is converted back and "
            "unscaled.\n"
            "\n"
            "The result is not perfectly identical to float32 because rounding "
            "loses some information, but it can remain very close.\n"
            "\n"
            "### Keras quantization\n"
            "\n"
            "The source demonstrates the high-level workflow:\n"
            "\n"
            "```python\n"
            "model = ...\n"
            "model.quantize(\"int8\")\n"
            "predictions = model.predict(...)\n"
            "```\n"
            "\n"
            "Supported layers can then use int8 computation during inference.\n"
            "\n"
            "### Mixed precision versus quantization\n"
            "\n"
            "Keep these concepts separate:\n"
            "\n"
            "| Technique | Main goal | Typical use |\n"
            "|---|---|---|\n"
            "| float16 inference | Faster forward pass | Inference |\n"
            "| mixed precision | Fast compute + stable weight updates | Training |\n"
            "| loss scaling | Prevent tiny low-precision gradients from disappearing | Mixed-precision training |\n"
            "| int8 quantization | Smaller/faster numerical representation | Inference |\n"
            "\n"
            "### The real-world optimization stack\n"
            "\n"
            "You can now see several independent ways to improve a system:\n"
            "\n"
            "```text\n"
            "BETTER MODEL QUALITY\n"
            "→ hyperparameter tuning\n"
            "→ model ensembling\n"
            "\n"
            "FASTER TRAINING\n"
            "→ multi-GPU\n"
            "→ TPU\n"
            "→ data parallelism\n"
            "→ model parallelism\n"
            "→ mixed precision\n"
            "\n"
            "FASTER / SMALLER INFERENCE\n"
            "→ float16\n"
            "→ int8 quantization\n"
            "```\n"
            "\n"
            "> **Recommended manual figure:** Add one comparison figure here "
            "showing `float32 → mixed float16 → int8`, with the tradeoff between "
            "precision, memory usage, and computational cost.\n"
            "\n"

            # Exercise EX02 is rendered here by the frontend.
            "{{exercise:M18.L01.EX02}}\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Misconceptions
            # ----------------------------------------------------------------

            "## Important misconceptions\n"
            "\n"
            "### Misconception 1\n"
            "\n"
            "> Hyperparameters and model weights are learned in the same way.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Model weights are optimized with gradient descent. Hyperparameters "
            "such as model depth or optimizer choice are usually selected using "
            "a separate search procedure.\n"
            "\n"
            "### Misconception 2\n"
            "\n"
            "> The test set should be used as the objective during hyperparameter tuning.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Repeatedly choosing models based on test results effectively trains "
            "the development process on the test set. Validation data should "
            "guide tuning, while the test set remains reserved for final evaluation.\n"
            "\n"
            "### Misconception 3\n"
            "\n"
            "> An ensemble improves simply because it contains many models.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Diversity is critical. Many nearly identical models tend to make "
            "similar errors and provide less ensemble benefit.\n"
            "\n"
            "### Misconception 4\n"
            "\n"
            "> Data parallelism allows a model larger than one GPU's memory.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Every data-parallel worker stores a complete model replica. If the "
            "model cannot fit on one device, model parallelism or sharding is needed.\n"
            "\n"
            "### Misconception 5\n"
            "\n"
            "> Eight GPUs guarantee exactly eight times faster training.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Communication, synchronization, data loading, and insufficient "
            "device utilization introduce scaling overhead.\n"
            "\n"
            "### Misconception 6\n"
            "\n"
            "> Running every part of training in float16 is always safe.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Small gradients and some numerically sensitive operations require "
            "greater precision. Mixed precision keeps sensitive state and updates "
            "in float32.\n"
            "\n"
            "### Misconception 7\n"
            "\n"
            "> Quantization means simply casting float values directly to int8.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Values must first be scaled into the representable integer range. "
            "Naively casting small floating-point values would destroy information.\n"
            "\n"
            "### Misconception 8\n"
            "\n"
            "> Lower numerical precision always makes a model faster.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Actual speed depends on hardware support, model size, implementation "
            "overhead, and whether the workload is large enough to benefit from "
            "specialized low-precision computation.\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Key terminology
            # ----------------------------------------------------------------

            "## Key terminology\n"
            "\n"
            "| Term | Meaning |\n"
            "|---|---|\n"
            "| Parameter | Value learned during model training, such as a weight |\n"
            "| Hyperparameter | Model or training configuration selected outside ordinary backpropagation |\n"
            "| Search space | Set of hyperparameter configurations available to an optimizer |\n"
            "| Trial | Training and evaluation of one hyperparameter configuration |\n"
            "| Bayesian optimization | Search strategy using previous trial results to select promising future trials |\n"
            "| Validation-set overfitting | Adapting hyperparameters too strongly to one validation set |\n"
            "| Ensemble | Combination of predictions from multiple models |\n"
            "| Weighted ensemble | Ensemble where different models contribute with different weights |\n"
            "| Model diversity | Degree to which ensemble members use different representations or make different errors |\n"
            "| Data parallelism | Replicating a model and splitting batches across devices |\n"
            "| Model parallelism | Splitting one model's computation or parameters across devices |\n"
            "| Replica | Full model copy used in data-parallel training |\n"
            "| Sharding | Splitting a tensor or model variable across devices |\n"
            "| Device mesh | Logical multidimensional arrangement of accelerator devices |\n"
            "| Layout map | Specification of how model variables are replicated or sharded across a device mesh |\n"
            "| TPU | Tensor Processing Unit; accelerator specialized for machine-learning computation |\n"
            "| Step fusing | Executing several training steps per accelerator execution cycle |\n"
            "| float16 | 16-bit floating-point numerical format |\n"
            "| float32 | 32-bit floating-point numerical format |\n"
            "| bfloat16 | 16-bit format with greater exponent range than standard float16 |\n"
            "| Mixed precision | Combining low-precision computation with higher-precision model state and updates |\n"
            "| Underflow | Very small numerical value becoming unrepresentable and effectively rounding toward zero |\n"
            "| Loss scaling | Multiplying loss to make low-precision gradients numerically larger during training |\n"
            "| Quantization | Representing trained model values using lower-precision numerical formats |\n"
            "| int8 | Signed 8-bit integer representation commonly used for efficient inference |\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Self-check
            # ----------------------------------------------------------------

            "## Self-check\n"
            "\n"
            "Before continuing, make sure you can answer:\n"
            "\n"
            "1. What is the difference between a model parameter and a hyperparameter?\n"
            "2. Why can't ordinary gradient descent optimize most hyperparameter choices?\n"
            "3. What is a hyperparameter search space?\n"
            "4. Why should KerasTuner optimize a validation metric rather than a test metric?\n"
            "5. What is validation-set overfitting?\n"
            "6. Why can repeating a trial several times improve tuning reliability?\n"
            "7. What is model ensembling?\n"
            "8. Why can a diverse ensemble outperform several nearly identical models?\n"
            "9. What is the difference between equal and weighted averaging?\n"
            "10. How does data parallelism split a training workload?\n"
            "11. Why must a data-parallel model fit on one device?\n"
            "12. How does model parallelism differ from data parallelism?\n"
            "13. What does sharding mean?\n"
            "14. What is the purpose of a device mesh?\n"
            "15. Why can distributed training fail to achieve perfect linear scaling?\n"
            "16. Why is prefetching important for accelerator utilization?\n"
            "17. Why can large batches require learning-rate adjustment?\n"
            "18. What problem does `steps_per_execution` attempt to reduce?\n"
            "19. Why is float16 attractive for inference?\n"
            "20. Why is pure float16 training potentially unstable?\n"
            "21. How does mixed precision solve this problem?\n"
            "22. What is gradient underflow?\n"
            "23. How does loss scaling help?\n"
            "24. Why must values be scaled before int8 conversion?\n"
            "25. What is the main difference between mixed precision and quantization?\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Retention statement
            # ----------------------------------------------------------------

            "## Retain this idea\n"
            "\n"
            "**Real-world deep learning engineering is not only about building "
            "a correct neural network. Strong systems come from systematically "
            "searching model configurations, combining diverse models when "
            "useful, scaling computation across hardware, and choosing numerical "
            "representations that balance precision with speed and memory.**\n"
            "\n"
            "Keep this progression in mind:\n"
            "\n"
            "```text\n"
            "IMPROVE QUALITY\n"
            "\n"
            "good baseline\n"
            "   ↓\n"
            "hyperparameter search\n"
            "   ↓\n"
            "best configurations\n"
            "   ↓\n"
            "diverse ensembles\n"
            "\n"
            "\n"
            "SCALE TRAINING\n"
            "\n"
            "1 device\n"
            "   ↓\n"
            "data parallelism\n"
            "   ↓\n"
            "model parallelism / sharding\n"
            "   ↓\n"
            "GPU / TPU clusters\n"
            "\n"
            "\n"
            "REDUCE COMPUTE COST\n"
            "\n"
            "float32\n"
            "   ↓\n"
            "mixed float16 training\n"
            "   ↓\n"
            "float16 inference\n"
            "   ↓\n"
            "int8 quantized inference\n"
            "```\n"
        ),

        "estimated_minutes": 180,

        "has_code_examples": True,

        "sections": [
            {
                "id": "model-optimization",
                "title": "Getting More Performance from Your Models",
                "order": 1,
            },
            {
                "id": "distributed-training",
                "title": "Scaling Training Across Multiple Devices",
                "order": 2,
            },
            {
                "id": "tpu-scaling",
                "title": "TPU Training and Keeping Accelerators Busy",
                "order": 3,
            },
            {
                "id": "precision-quantization",
                "title": "Mixed Precision and Quantization",
                "order": 4,
            },
        ],
    },


    # =======================================================================
    # INLINE EXERCISES
    # =======================================================================

    "exercises": [
        {
            "id": "M18.L01.EX01",

            "title": "Design a Tuning and Ensembling Strategy",

            "lesson_code": "M18.L01",

            "section_id": "model-optimization",

            "placement": "after_section",

            "description": (
                "Practice turning manual modeling decisions into a principled "
                "hyperparameter search and combining diverse candidate models."
            ),

            "instructions": (
                "Suppose you have an image-classification model and want to "
                "improve validation performance.\n\n"
                "You are considering:\n"
                "- hidden widths: 128, 256, 512\n"
                "- dropout: 0.2, 0.4\n"
                "- optimizer: Adam, RMSprop\n\n"
                "1. Calculate the number of possible configurations if every "
                "combination is allowed.\n"
                "2. Explain why validation accuracy should be the tuning "
                "objective rather than test accuracy.\n"
                "3. Explain how EarlyStopping can reduce tuning cost.\n"
                "4. Explain why `executions_per_trial=2` may produce more "
                "reliable results than one execution.\n"
                "5. Explain how an extremely large search can overfit the "
                "validation set.\n"
                "6. Suppose the best three configurations produce different "
                "architectures. Describe how you could create an ensemble.\n"
                "7. Explain when weighted averaging would be preferable to "
                "simple averaging.\n"
                "8. Explain why three highly diverse strong models can be more "
                "valuable than three copies of the same architecture trained "
                "from different random seeds."
            ),

            "expected_output": (
                "A structured tuning and ensembling plan. The hyperparameter "
                "space contains 3 × 2 × 2 = 12 configurations."
            ),

            "difficulty": DifficultyLevel.intermediate,

            "skill_tested": [
                "hyperparameter-search",
                "validation",
                "keras-tuner",
                "early-stopping",
                "ensembling",
                "model-diversity",
            ],
        },

        {
            "id": "M18.L01.EX02",

            "title": "Scale and Optimize a Large Training Workload",

            "lesson_code": "M18.L01",

            "section_id": "precision-quantization",

            "placement": "after_section",

            "description": (
                "Practice selecting distributed-training and numerical-precision "
                "strategies for realistic engineering constraints."
            ),

            "instructions": (
                "Consider the following scenarios.\n\n"
                "A. Your model fits comfortably on one GPU, but training is too slow. "
                "You have four GPUs available.\n\n"
                "B. Your model is too large to fit in the memory of one GPU. "
                "You have eight GPUs available.\n\n"
                "C. Training is complete, but deployment requires faster "
                "inference and lower memory usage.\n\n"
                "Answer:\n"
                "1. For scenario A, choose between data parallelism and model "
                "parallelism and explain why.\n"
                "2. If the global batch is 512 across four GPUs using data "
                "parallelism, what is the local batch per GPU?\n"
                "3. For scenario B, explain why data parallelism alone is not enough.\n"
                "4. Explain how model sharding could solve scenario B.\n"
                "5. Explain how data and model parallelism could be combined "
                "across eight GPUs.\n"
                "6. Explain one reason distributed speedup will be less than "
                "the theoretical device count.\n"
                "7. Explain how dataset prefetching helps.\n"
                "8. Explain how mixed precision could speed training.\n"
                "9. Explain why model weights may remain float32 even while "
                "many computations use float16.\n"
                "10. Explain why loss scaling may be required.\n"
                "11. For scenario C, explain how int8 quantization can help.\n"
                "12. Explain why directly casting every float value to int8 "
                "without scaling would be incorrect."
            ),

            "expected_output": (
                "A deployment and training plan covering data parallelism, "
                "model sharding, combined parallelism, input pipelines, mixed "
                "precision, loss scaling, and int8 quantization. For scenario "
                "A, each GPU receives a local batch of 128."
            ),

            "difficulty": DifficultyLevel.intermediate,

            "skill_tested": [
                "data-parallelism",
                "model-parallelism",
                "distributed-training",
                "mixed-precision",
                "loss-scaling",
                "quantization",
            ],
        },
    ],


    # =======================================================================
    # LESSON QUIZ
    # =======================================================================

    "quiz": {
        "id": "M18.L01.QZ01",

        "title": "Real-World Deep Learning Best Practices — Knowledge Check",

        "lesson_code": "M18.L01",

        "placement": "lesson_end",

        "questions": [
            {
                "id": "M18.L01.Q01",

                "section_id": "model-optimization",

                "question": (
                    "Which value is a hyperparameter rather than a model "
                    "parameter learned through backpropagation?"
                ),

                "options": [
                    "A Dense layer kernel value",
                    "A learned embedding coordinate",
                    "The number of units in a hidden layer",
                    "A learned bias coefficient",
                ],

                "correct": 2,

                "explanation": (
                    "The number of units is chosen as part of the model "
                    "configuration. Individual kernel, embedding, and bias "
                    "values are learned during training."
                ),
            },

            {
                "id": "M18.L01.Q02",

                "section_id": "model-optimization",

                "question": (
                    "Why is diversity important in a model ensemble?"
                ),

                "options": [
                    "Because all models should make exactly the same errors",
                    "Because differently biased models may contribute complementary information",
                    "Because ensemble models cannot use neural networks",
                    "Because diversity eliminates the need for validation data",
                ],

                "correct": 1,

                "explanation": (
                    "An ensemble is most useful when its members make different "
                    "errors or capture different aspects of the data. Their "
                    "strengths can then complement one another."
                ),
            },

            {
                "id": "M18.L01.Q03",

                "section_id": "distributed-training",

                "question": (
                    "What is the key requirement for ordinary data-parallel "
                    "training?"
                ),

                "options": [
                    "The model must fit completely on one device",
                    "Every device must contain different model layers",
                    "The test set must be duplicated across devices",
                    "Each GPU must use a different optimizer",
                ],

                "correct": 0,

                "explanation": (
                    "Data parallelism replicates the entire model on every "
                    "worker. Therefore one complete model must fit in the memory "
                    "of each participating device."
                ),
            },

            {
                "id": "M18.L01.Q04",

                "section_id": "precision-quantization",

                "question": (
                    "What is the main idea of mixed-precision training?"
                ),

                "options": [
                    "Store and compute everything using int8",
                    "Use lower precision for suitable computations while retaining higher precision where numerical stability matters",
                    "Train different layers on unrelated datasets",
                    "Remove small gradient values completely",
                ],

                "correct": 1,

                "explanation": (
                    "Mixed precision performs many operations in float16 for "
                    "speed while keeping model state and sensitive updates in "
                    "float32 where greater precision is needed."
                ),
            },

            {
                "id": "M18.L01.Q05",

                "section_id": "precision-quantization",

                "type": "open",

                "question": (
                    "You have trained a large model and now want to improve both "
                    "model quality and engineering efficiency. Describe an "
                    "end-to-end strategy using ideas from this lesson: "
                    "hyperparameter tuning, validation discipline, ensembling, "
                    "distributed training, efficient input pipelines, mixed "
                    "precision, and quantized inference. Explain what problem "
                    "each technique solves and where in the development "
                    "lifecycle you would apply it."
                ),
            },
        ],

        "passing_score": 70,
    },
}
