"""M15.L01 — Language Models and the Transformer.

One Topic -> one complete learner-facing Lesson + inline Exercises + lesson Quiz.
BOOK-002, Chapter 15, pages not provided in the supplied extract.
Instructor-authored curriculum adaptation.
"""

from app.models.learning import DifficultyLevel


# ---------------------------------------------------------------------------
# Lesson metadata
# ---------------------------------------------------------------------------

LESSON_CODE = "M15.L01"

MODULE_ORDER = 15

MODULE_TITLE = "Language Models and the Transformer"

MODULE_DESCRIPTION = (
    "Learn how next-token language models generate text, how encoder-decoder "
    "sequence-to-sequence systems perform translation, and how attention leads "
    "to Transformer architectures, large-scale pretraining, and fine-tuning."
)

SOURCE_CHAPTER = 15

SOURCE_PAGES = "Not provided in supplied chapter extract"


# ---------------------------------------------------------------------------
# Topic
# ---------------------------------------------------------------------------

TOPIC = {
    "title": "Language Models and the Transformer",

    "slug": "deep-learning-foundations-m15-l01",

    "description": (
        "Build a complete mental model of autoregressive language modeling, "
        "sequence-to-sequence learning, attention, Transformer encoders and "
        "decoders, positional embeddings, masked-language-model pretraining, "
        "and downstream fine-tuning."
    ),

    "order": 1,

    "difficulty": DifficultyLevel.beginner,

    "estimated_hours": 3.5,

    "skill_tags": [
        "nlp",
        "language-modeling",
        "autoregressive-generation",
        "sequence-to-sequence",
        "attention",
        "transformer",
        "positional-embeddings",
        "pretraining",
        "fine-tuning",
        "module-15",
    ],

    "prerequisite_ids": [],


    # =======================================================================
    # LESSON
    # =======================================================================

    "lesson": {
        "title": "Language Models and the Transformer",

        "content": (
            '# Language Models and the Transformer\n'
            '\n'
            '> **Course:** Deep Learning Foundations  \n'
            '> **Lesson:** M15.L01  \n'
            '> **Module:** Language Models and the Transformer  \n'
            '> **Source alignment:** BOOK-002, Chapter 15. The supplied chapter extract does not include page numbers. This lesson is an instructor-authored curriculum adaptation rather than a reproduction of the source text.\n'
            '\n'
            '---\n'
            '\n'
            '## Learning outcomes\n'
            '\n'
            'By the end of this lesson, you should be able to:\n'
            '\n'
            '- Explain language modeling as predicting a probability distribution over the next token.\n'
            '- Describe how autoregressive text generation feeds previously generated tokens back into a model.\n'
            '- Explain sequence-to-sequence learning using an encoder and decoder.\n'
            '- Describe why recurrent encoder-decoder models struggle with long sequences.\n'
            '- Explain dot-product attention using queries, keys, values, softmax weighting, and weighted sums.\n'
            '- Explain why scaled multi-head attention is more expressive than a single attention operation.\n'
            '- Describe the structure of Transformer encoder and decoder blocks.\n'
            '- Explain padding masks, causal masks, residual connections, and layer normalization.\n'
            '- Explain why Transformers need positional information.\n'
            '- Distinguish causal language modeling from masked language modeling.\n'
            '- Explain pretraining and fine-tuning using a pretrained Transformer encoder.\n'
            '- Build a practical mental model for why attention-based Transformer representations are effective.\n'
            '\n'
            '---\n'
            '\n'
            '## 1. Language modeling: predicting one token at a time\n'
            '\n'
            'Text generation looks impossible if we imagine predicting an entire sentence as one gigantic classification problem.\n'
            '\n'
            'Suppose the vocabulary contains:\n'
            '\n'
            '```text\n'
            '20,000 tokens\n'
            '```\n'
            '\n'
            'Even a four-token output would have:\n'
            '\n'
            '```text\n'
            '20,000⁴\n'
            '```\n'
            '\n'
            'possible combinations.\n'
            '\n'
            'The output space grows too quickly.\n'
            '\n'
            'The key simplification is:\n'
            '\n'
            '> Predict only the **next token**, then repeat.\n'
            '\n'
            'A language model learns a distribution of the form:\n'
            '\n'
            '```text\n'
            'p(next token | previous tokens)\n'
            '```\n'
            '\n'
            'For example:\n'
            '\n'
            '```text\n'
            'Input:\n'
            '"The cat sat on the"\n'
            '\n'
            'Model output:\n'
            'mat    -> 0.48\n'
            'floor  -> 0.19\n'
            'chair  -> 0.08\n'
            'roof   -> 0.01\n'
            '...\n'
            '```\n'
            '\n'
            'The model does not directly generate a complete paragraph.\n'
            '\n'
            'It predicts one probability distribution over the vocabulary.\n'
            '\n'
            'Then generation repeatedly turns those one-token predictions into a sequence.\n'
            '\n'
            '### Tokenization turns text into a numerical sequence\n'
            '\n'
            'A tokenizer maps text to integer IDs.\n'
            '\n'
            'Conceptually:\n'
            '\n'
            '```text\n'
            '"hello world"\n'
            '      ↓\n'
            '["hello", "world"]\n'
            '      ↓\n'
            '[142, 587]\n'
            '```\n'
            '\n'
            'A character-level tokenizer does the same at character granularity:\n'
            '\n'
            '```text\n'
            '"cat"\n'
            ' ↓\n'
            '["c", "a", "t"]\n'
            ' ↓\n'
            '[12, 4, 31]\n'
            '```\n'
            '\n'
            'The chapter begins with a small character-level language model trained on Shakespeare-like text because character tokenization keeps the vocabulary tiny and makes the mechanics easy to see.\n'
            '\n'
            '### Creating next-token training pairs\n'
            '\n'
            'Suppose the original sequence is:\n'
            '\n'
            '```text\n'
            'FIRST\n'
            '```\n'
            '\n'
            'The training input and target can be offset by one token:\n'
            '\n'
            '```text\n'
            'input:  F I R S\n'
            'target: I R S T\n'
            '```\n'
            '\n'
            'At each position, the target is simply:\n'
            '\n'
            '```text\n'
            'the next token\n'
            '```\n'
            '\n'
            'For a longer text chunk:\n'
            '\n'
            '```text\n'
            'input:\n'
            '"Before we proceed"\n'
            '\n'
            'target:\n'
            '"efore we proceed "\n'
            '```\n'
            '\n'
            'This creates many next-token classification examples from ordinary unlabeled text.\n'
            '\n'
            '### A small recurrent language model\n'
            '\n'
            'A simple character language model can be built from:\n'
            '\n'
            '```text\n'
            'Embedding\n'
            '   ↓\n'
            'GRU\n'
            '   ↓\n'
            'Dropout\n'
            '   ↓\n'
            'Dense softmax over vocabulary\n'
            '```\n'
            '\n'
            'Example:\n'
            '\n'
            '```python\n'
            'inputs = keras.Input(shape=(sequence_length,), dtype="int")\n'
            '\n'
            'x = layers.Embedding(\n'
            '    vocabulary_size,\n'
            '    embedding_dim,\n'
            ')(inputs)\n'
            '\n'
            'x = layers.GRU(\n'
            '    hidden_dim,\n'
            '    return_sequences=True,\n'
            ')(x)\n'
            '\n'
            'x = layers.Dropout(0.1)(x)\n'
            '\n'
            'outputs = layers.Dense(\n'
            '    vocabulary_size,\n'
            '    activation="softmax",\n'
            ')(x)\n'
            '\n'
            'model = keras.Model(inputs, outputs)\n'
            '```\n'
            '\n'
            'The output shape is conceptually:\n'
            '\n'
            '```text\n'
            'batch × sequence_length × vocabulary_size\n'
            '```\n'
            '\n'
            'So the model performs a vocabulary classification at every position.\n'
            '\n'
            '### Language modeling is still classification\n'
            '\n'
            'This is an important connection.\n'
            '\n'
            'At one token position:\n'
            '\n'
            '```text\n'
            'model input:\n'
            'previous context\n'
            '\n'
            'model output:\n'
            'probability over all vocabulary tokens\n'
            '```\n'
            '\n'
            'So the loss can still be:\n'
            '\n'
            '```text\n'
            'sparse categorical cross-entropy\n'
            '```\n'
            '\n'
            'The novelty comes from applying classification across a sequence and using it autoregressively during inference.\n'
            '\n'
            '---\n'
            '\n'
            '## 2. Autoregressive text generation\n'
            '\n'
            'After training a next-token model, we want to generate a sequence.\n'
            '\n'
            'The basic loop is:\n'
            '\n'
            '```text\n'
            'prompt\n'
            '  ↓\n'
            'predict next token\n'
            '  ↓\n'
            'append predicted token\n'
            '  ↓\n'
            'feed it back into model\n'
            '  ↓\n'
            'predict next token\n'
            '  ↓\n'
            'repeat\n'
            '```\n'
            '\n'
            'This is called **autoregressive generation**.\n'
            '\n'
            '### Why recurrent state matters\n'
            '\n'
            'An RNN contains a hidden state that summarizes earlier tokens.\n'
            '\n'
            'During generation:\n'
            '\n'
            '```text\n'
            'current token + previous hidden state\n'
            '                ↓\n'
            '             RNN\n'
            '                ↓\n'
            'next-token distribution + new hidden state\n'
            '```\n'
            '\n'
            'The state must persist from one generated token to the next.\n'
            '\n'
            'A model used for training may process entire fixed-length sequences.\n'
            '\n'
            'A generation model can instead accept:\n'
            '\n'
            '```text\n'
            'one token\n'
            '+\n'
            'previous state\n'
            '```\n'
            '\n'
            'and return:\n'
            '\n'
            '```text\n'
            'next-token probabilities\n'
            '+\n'
            'updated state\n'
            '```\n'
            '\n'
            '### Priming the model with a prompt\n'
            '\n'
            'Suppose the prompt is:\n'
            '\n'
            '```text\n'
            'KING RICHARD III:\n'
            '```\n'
            '\n'
            'Before generating anything new, feed the prompt through the recurrent model one token at a time.\n'
            '\n'
            'This updates the hidden state until it represents the prompt context.\n'
            '\n'
            'Then generation begins.\n'
            '\n'
            '### Greedy token selection\n'
            '\n'
            'The simplest decoding strategy selects the token with highest probability:\n'
            '\n'
            '```python\n'
            'next_token = np.argmax(predictions, axis=-1)\n'
            '```\n'
            '\n'
            'Then:\n'
            '\n'
            '```text\n'
            'predicted token\n'
            '     ↓\n'
            'becomes next input\n'
            '```\n'
            '\n'
            'This process can continue until:\n'
            '\n'
            '- a chosen maximum length,\n'
            '- an end token,\n'
            '- another stopping condition.\n'
            '\n'
            '### Training and inference are not identical\n'
            '\n'
            'During training, the model sees correct previous tokens from the dataset.\n'
            '\n'
            'During generation, it sees:\n'
            '\n'
            '```text\n'
            'its own previous predictions\n'
            '```\n'
            '\n'
            'This creates a practical difference:\n'
            '\n'
            '```text\n'
            'training:\n'
            'true context -> predict next token\n'
            '\n'
            'generation:\n'
            'generated context -> predict next token\n'
            '```\n'
            '\n'
            'Errors can therefore accumulate during generation.\n'
            '\n'
            '### Why bidirectionality breaks autoregressive training\n'
            '\n'
            'A next-token language model must not look into the future.\n'
            '\n'
            'If the representation of position `t` contains information from position:\n'
            '\n'
            '```text\n'
            't + 1\n'
            '```\n'
            '\n'
            'then the model can directly see the answer it is supposed to predict.\n'
            '\n'
            'That creates **information leakage**.\n'
            '\n'
            'So a generative next-token model requires one-directional information flow.\n'
            '\n'
            'This principle becomes extremely important again when we build a Transformer decoder.\n'
            '\n'
            '{{exercise:M15.L01.EX01}}\n'
            '\n'
            '---\n'
            '\n'
            '## 3. Sequence-to-sequence learning\n'
            '\n'
            'Some tasks map one sequence to another.\n'
            '\n'
            'Examples:\n'
            '\n'
            '```text\n'
            'English sentence -> Spanish sentence\n'
            'question         -> answer\n'
            'document         -> summary\n'
            '```\n'
            '\n'
            'These are **sequence-to-sequence**, or **seq2seq**, problems.\n'
            '\n'
            '### Encoder-decoder idea\n'
            '\n'
            'A traditional seq2seq model contains:\n'
            '\n'
            '```text\n'
            'source sequence\n'
            '      ↓\n'
            '    encoder\n'
            '      ↓\n'
            'source representation\n'
            '      ↓\n'
            '    decoder\n'
            '      ↓\n'
            'target sequence\n'
            '```\n'
            '\n'
            'The encoder reads the source.\n'
            '\n'
            'The decoder generates the target.\n'
            '\n'
            '### Training the decoder\n'
            '\n'
            'During training, the decoder receives the target sentence shifted by one step.\n'
            '\n'
            'Example:\n'
            '\n'
            '```text\n'
            'decoder input:\n'
            '[start] yo estoy aquí\n'
            '\n'
            'decoder target:\n'
            'yo estoy aquí [end]\n'
            '```\n'
            '\n'
            'The decoder learns:\n'
            '\n'
            '```text\n'
            'p(next target token |\n'
            '  previous target tokens,\n'
            '  encoded source)\n'
            '```\n'
            '\n'
            '### Inference\n'
            '\n'
            'During inference, the true target sentence is unavailable.\n'
            '\n'
            'So we generate:\n'
            '\n'
            '```text\n'
            '[start]\n'
            '   ↓\n'
            'predict token 1\n'
            '   ↓\n'
            '[start] token1\n'
            '   ↓\n'
            'predict token 2\n'
            '   ↓\n'
            '...\n'
            '   ↓\n'
            '[end]\n'
            '```\n'
            '\n'
            'The decoder repeatedly consumes what has already been generated.\n'
            '\n'
            '### Why an encoder is necessary\n'
            '\n'
            'A naive recurrent translation model might try to produce target token `N` from source tokens `0...N`.\n'
            '\n'
            'This fails when word order differs between languages.\n'
            '\n'
            'For example, information needed for the first translated token may appear near the end of the source sentence.\n'
            '\n'
            'A proper encoder reads the **entire source sequence first**.\n'
            '\n'
            'Then the decoder begins generation.\n'
            '\n'
            '### RNN encoder-decoder\n'
            '\n'
            'A recurrent encoder can transform the source sequence into a final state.\n'
            '\n'
            'Conceptually:\n'
            '\n'
            '```text\n'
            'English tokens\n'
            '     ↓\n'
            'Bidirectional GRU\n'
            '     ↓\n'
            'source state\n'
            '```\n'
            '\n'
            'Then:\n'
            '\n'
            '```text\n'
            'Spanish previous tokens\n'
            '        +\n'
            'source state\n'
            '        ↓\n'
            '      GRU\n'
            '        ↓\n'
            'next Spanish token\n'
            '```\n'
            '\n'
            'Using a bidirectional RNN is acceptable in the **encoder** because the full source sentence is already available.\n'
            '\n'
            'But using bidirectionality in the autoregressive decoder would leak future target tokens.\n'
            '\n'
            '### Main weakness of the RNN encoder-decoder\n'
            '\n'
            'The entire source sentence must eventually be compressed into a limited state representation.\n'
            '\n'
            'For short sequences this may work.\n'
            '\n'
            'For long sequences:\n'
            '\n'
            '```text\n'
            'early information\n'
            '      ↓\n'
            'must survive many recurrent steps\n'
            '      ↓\n'
            'progressively harder to retain\n'
            '```\n'
            '\n'
            'RNNs also process sequence positions sequentially.\n'
            '\n'
            'That makes training difficult to parallelize across the time dimension.\n'
            '\n'
            'These limitations motivated attention.\n'
            '\n'
            '---\n'
            '\n'
            '## 4. Attention: retrieving relevant information directly\n'
            '\n'
            'The core problem attention solves is:\n'
            '\n'
            '> How can the model retrieve information from anywhere in a sequence without forcing that information through a long recurrent chain?\n'
            '\n'
            'Imagine translating one target token.\n'
            '\n'
            'Instead of relying only on a single compressed source state, allow the decoder to examine every source-token representation.\n'
            '\n'
            'For each source token, compute:\n'
            '\n'
            '```text\n'
            'How relevant is this source token\n'
            'to the target token being processed?\n'
            '```\n'
            '\n'
            'This produces **attention scores**.\n'
            '\n'
            '### Basic attention idea\n'
            '\n'
            'Suppose:\n'
            '\n'
            '```text\n'
            'target representation = q\n'
            '\n'
            'source representations =\n'
            's1, s2, s3, ..., sn\n'
            '```\n'
            '\n'
            'Compute a score:\n'
            '\n'
            '```text\n'
            'score(q, s1)\n'
            'score(q, s2)\n'
            '...\n'
            'score(q, sn)\n'
            '```\n'
            '\n'
            'Then normalize the scores using softmax:\n'
            '\n'
            '```text\n'
            'weights = softmax(scores)\n'
            '```\n'
            '\n'
            'Finally compute a weighted sum:\n'
            '\n'
            '```text\n'
            'context =\n'
            'w1*s1 + w2*s2 + ... + wn*sn\n'
            '```\n'
            '\n'
            'Important source tokens receive larger weights.\n'
            '\n'
            '### Dot-product attention\n'
            '\n'
            'A very effective relevance measure is the dot product.\n'
            '\n'
            '```text\n'
            'score(query, key)\n'
            '=\n'
            'query · key\n'
            '```\n'
            '\n'
            'If two vectors are well aligned in the learned representation space, their dot product is larger.\n'
            '\n'
            'For whole sequences, the operation produces an attention matrix:\n'
            '\n'
            '```text\n'
            'target positions × source positions\n'
            '```\n'
            '\n'
            'Each row answers:\n'
            '\n'
            '> For this target position, how much attention should be assigned to every source position?\n'
            '\n'
            '### Query, key, and value\n'
            '\n'
            'Modern attention uses three roles.\n'
            '\n'
            '#### Query\n'
            '\n'
            'What information am I currently looking for?\n'
            '\n'
            '#### Key\n'
            '\n'
            'What information does each source position advertise for matching?\n'
            '\n'
            '#### Value\n'
            '\n'
            'What information should actually be retrieved if that source position is relevant?\n'
            '\n'
            'The computation is conceptually:\n'
            '\n'
            '```text\n'
            'scores = query × keys\n'
            'weights = softmax(scores)\n'
            'output = weighted sum(values)\n'
            '```\n'
            '\n'
            'Or more compactly:\n'
            '\n'
            '```text\n'
            'Attention(Q, K, V)\n'
            '=\n'
            'softmax(QKᵀ) V\n'
            '```\n'
            '\n'
            '### Why project Q, K, and V?\n'
            '\n'
            'Instead of comparing raw token vectors directly, the model learns linear projections:\n'
            '\n'
            '```text\n'
            'Q = input × Wq\n'
            'K = input × Wk\n'
            'V = input × Wv\n'
            '```\n'
            '\n'
            'This gives the model freedom to learn:\n'
            '\n'
            '- what should be compared,\n'
            '- what similarity means,\n'
            '- what information should be retrieved.\n'
            '\n'
            '### Scaled dot-product attention\n'
            '\n'
            'As vector dimensionality grows, raw dot products can become large.\n'
            '\n'
            'Large softmax inputs may produce unstable or overly sharp gradients.\n'
            '\n'
            'So the scores are scaled:\n'
            '\n'
            '```text\n'
            'QKᵀ\n'
            '────\n'
            '√d\n'
            '```\n'
            '\n'
            'where `d` is the key/query dimension.\n'
            '\n'
            'The usual formula becomes:\n'
            '\n'
            '```text\n'
            'Attention(Q,K,V)\n'
            '=\n'
            'softmax(QKᵀ / √d) V\n'
            '```\n'
            '\n'
            '### Multi-head attention\n'
            '\n'
            'A single attention operation produces one weighted mixture.\n'
            '\n'
            'But a sequence may contain several useful relationships at once.\n'
            '\n'
            'One head may learn to focus on:\n'
            '\n'
            '```text\n'
            'subject relationships\n'
            '```\n'
            '\n'
            'another on:\n'
            '\n'
            '```text\n'
            'verb relationships\n'
            '```\n'
            '\n'
            'another on:\n'
            '\n'
            '```text\n'
            'punctuation or syntax\n'
            '```\n'
            '\n'
            'So we perform attention multiple times with separate learned projections.\n'
            '\n'
            '```text\n'
            'input\n'
            ' ├─> head 1\n'
            ' ├─> head 2\n'
            ' ├─> head 3\n'
            ' └─> head 4\n'
            '       ↓\n'
            ' concatenate\n'
            '       ↓\n'
            ' output projection\n'
            '```\n'
            '\n'
            'This is **multi-head attention**.\n'
            '\n'
            'It allows several different relationship spaces to be learned simultaneously.\n'
            '\n'
            '### Why attention improves long-range information flow\n'
            '\n'
            'With an RNN, information may travel through:\n'
            '\n'
            '```text\n'
            'token 1 -> token 2 -> token 3 -> ... -> token 100\n'
            '```\n'
            '\n'
            'With attention:\n'
            '\n'
            '```text\n'
            'token 100\n'
            '   ↓ directly attends to\n'
            'token 1\n'
            '```\n'
            '\n'
            'The information path becomes much shorter.\n'
            '\n'
            'This is one of the Transformer’s central advantages.\n'
            '\n'
            '---\n'
            '\n'
            '## 5. Transformer encoder block\n'
            '\n'
            'The Transformer removes recurrence and uses attention as the main mechanism for exchanging information across sequence positions.\n'
            '\n'
            'A Transformer encoder block contains two major sublayers:\n'
            '\n'
            '```text\n'
            '1. Self-attention\n'
            '2. Feedforward network\n'
            '```\n'
            '\n'
            'plus:\n'
            '\n'
            '```text\n'
            'residual connections\n'
            'layer normalization\n'
            '```\n'
            '\n'
            '### Self-attention\n'
            '\n'
            'In self-attention:\n'
            '\n'
            '```text\n'
            'query = source\n'
            'key   = source\n'
            'value = source\n'
            '```\n'
            '\n'
            'Every source token can inspect every other source token.\n'
            '\n'
            'Example:\n'
            '\n'
            '```text\n'
            '"The train left the station."\n'
            '```\n'
            '\n'
            'The word:\n'
            '\n'
            '```text\n'
            'station\n'
            '```\n'
            '\n'
            'can attend strongly to:\n'
            '\n'
            '```text\n'
            'train\n'
            '```\n'
            '\n'
            'This helps the representation encode that the sentence is probably discussing a train station rather than a radio station.\n'
            '\n'
            '### Self-attention creates contextual representations\n'
            '\n'
            'An ordinary token embedding represents a word largely independently of context.\n'
            '\n'
            'Self-attention transforms it into:\n'
            '\n'
            '```text\n'
            'word representation\n'
            'conditioned on surrounding tokens\n'
            '```\n'
            '\n'
            'So the representation of:\n'
            '\n'
            '```text\n'
            'bank\n'
            '```\n'
            '\n'
            'can differ between:\n'
            '\n'
            '```text\n'
            'river bank\n'
            '```\n'
            '\n'
            'and:\n'
            '\n'
            '```text\n'
            'financial bank\n'
            '```\n'
            '\n'
            '### Why attention alone is not enough\n'
            '\n'
            'Attention is built from linear projections and weighted sums.\n'
            '\n'
            'Without nonlinear transformations, stacking attention repeatedly would have limited expressive power.\n'
            '\n'
            'So each encoder block includes a feedforward network:\n'
            '\n'
            '```text\n'
            'Dense\n'
            '  ↓\n'
            'nonlinear activation\n'
            '  ↓\n'
            'Dense\n'
            '```\n'
            '\n'
            'Attention handles:\n'
            '\n'
            '```text\n'
            'communication between tokens\n'
            '```\n'
            '\n'
            'The feedforward network handles:\n'
            '\n'
            '```text\n'
            'nonlinear transformation of each token representation\n'
            '```\n'
            '\n'
            '### Residual connections\n'
            '\n'
            'Instead of replacing a representation entirely, the block adds the sublayer output back to the original input:\n'
            '\n'
            '```text\n'
            'x = sublayer(x) + x\n'
            '```\n'
            '\n'
            'Residual connections help deep networks optimize more reliably.\n'
            '\n'
            '### Layer normalization\n'
            '\n'
            'Transformers commonly use `LayerNormalization`.\n'
            '\n'
            'Unlike batch normalization, layer normalization does not require statistics aggregated across different examples in the batch.\n'
            '\n'
            'It normalizes features within each sequence representation.\n'
            '\n'
            'This is well suited to variable text batches and sequence modeling.\n'
            '\n'
            '### Padding masks\n'
            '\n'
            'Batches often contain padded sequences:\n'
            '\n'
            '```text\n'
            '[token, token, token, PAD, PAD]\n'
            '```\n'
            '\n'
            'Padding carries no semantic information.\n'
            '\n'
            'An attention mask tells the model:\n'
            '\n'
            '```text\n'
            'do not attend to padding positions\n'
            '```\n'
            '\n'
            'This prevents meaningless padding tokens from affecting contextual representations.\n'
            '\n'
            '### Stackability\n'
            '\n'
            'An encoder block keeps the same overall sequence shape:\n'
            '\n'
            '```text\n'
            'batch × sequence_length × hidden_dim\n'
            '```\n'
            '\n'
            'Therefore many encoder blocks can be stacked:\n'
            '\n'
            '```text\n'
            'embeddings\n'
            '    ↓\n'
            'encoder block 1\n'
            '    ↓\n'
            'encoder block 2\n'
            '    ↓\n'
            'encoder block 3\n'
            '    ↓\n'
            '...\n'
            '```\n'
            '\n'
            'Each block refines the contextual embedding space.\n'
            '\n'
            '---\n'
            '\n'
            '## 6. Transformer decoder block\n'
            '\n'
            'A seq2seq Transformer decoder must handle two different information sources:\n'
            '\n'
            '```text\n'
            'previous target tokens\n'
            '+\n'
            'encoded source sequence\n'
            '```\n'
            '\n'
            'So it uses two attention operations.\n'
            '\n'
            '### 1. Masked self-attention\n'
            '\n'
            'The decoder first attends to the target sequence itself.\n'
            '\n'
            'But the model must not see future tokens.\n'
            '\n'
            'Therefore it uses a **causal mask**.\n'
            '\n'
            'For five target positions:\n'
            '\n'
            '```text\n'
            '1 0 0 0 0\n'
            '1 1 0 0 0\n'
            '1 1 1 0 0\n'
            '1 1 1 1 0\n'
            '1 1 1 1 1\n'
            '```\n'
            '\n'
            'Position 0 can see only itself.\n'
            '\n'
            'Position 1 can see positions 0 and 1.\n'
            '\n'
            'Position 4 can see positions 0 through 4.\n'
            '\n'
            'This recreates the one-directional constraint needed for autoregressive generation.\n'
            '\n'
            '### 2. Cross-attention\n'
            '\n'
            'The decoder must also inspect the encoded source sentence.\n'
            '\n'
            'For cross-attention:\n'
            '\n'
            '```text\n'
            'query = decoder representation\n'
            'key   = encoder output\n'
            'value = encoder output\n'
            '```\n'
            '\n'
            'This lets each target position retrieve whichever source information is useful for predicting the next token.\n'
            '\n'
            '### Full decoder block\n'
            '\n'
            'A conceptual decoder block is:\n'
            '\n'
            '```text\n'
            'target representations\n'
            '        ↓\n'
            'causal self-attention\n'
            '        ↓\n'
            'residual + normalization\n'
            '        ↓\n'
            'cross-attention to encoder\n'
            '        ↓\n'
            'residual + normalization\n'
            '        ↓\n'
            'feedforward network\n'
            '        ↓\n'
            'residual + normalization\n'
            '```\n'
            '\n'
            '### Self-attention versus cross-attention\n'
            '\n'
            'Keep this distinction clear:\n'
            '\n'
            '```text\n'
            'self-attention:\n'
            'sequence attends to itself\n'
            '\n'
            'cross-attention:\n'
            'one sequence attends to another sequence\n'
            '```\n'
            '\n'
            'The encoder uses self-attention.\n'
            '\n'
            'The decoder uses both.\n'
            '\n'
            '---\n'
            '\n'
            '## 7. Transformers need positional information\n'
            '\n'
            'There is a subtle problem.\n'
            '\n'
            'Attention compares token representations based on content.\n'
            '\n'
            'By itself, it does not inherently know:\n'
            '\n'
            '```text\n'
            'which token came first\n'
            'which token came second\n'
            'which token came last\n'
            '```\n'
            '\n'
            'If we rearrange tokens but keep the same token vectors, pure attention treats them like a set rather than an ordered sequence.\n'
            '\n'
            'But word order matters.\n'
            '\n'
            'Compare:\n'
            '\n'
            '```text\n'
            'dog bites man\n'
            '```\n'
            '\n'
            'with:\n'
            '\n'
            '```text\n'
            'man bites dog\n'
            '```\n'
            '\n'
            'The same words appear, but the meaning changes.\n'
            '\n'
            '### Positional embeddings\n'
            '\n'
            'To make the Transformer order-aware, add a position representation to each token embedding.\n'
            '\n'
            'Conceptually:\n'
            '\n'
            '```text\n'
            'token embedding\n'
            '+\n'
            'position embedding\n'
            '=\n'
            'position-aware token representation\n'
            '```\n'
            '\n'
            'For the third token:\n'
            '\n'
            '```text\n'
            'embedding(token)\n'
            '+\n'
            'embedding(position=2)\n'
            '```\n'
            '\n'
            '### Learned positional embeddings\n'
            '\n'
            'A simple implementation uses two embedding tables:\n'
            '\n'
            '```text\n'
            'token embedding table\n'
            'position embedding table\n'
            '```\n'
            '\n'
            'Example:\n'
            '\n'
            '```python\n'
            'class PositionalEmbedding(keras.Layer):\n'
            '    def __init__(self, sequence_length, input_dim, output_dim):\n'
            '        super().__init__()\n'
            '\n'
            '        self.token_embeddings = layers.Embedding(\n'
            '            input_dim,\n'
            '            output_dim,\n'
            '        )\n'
            '\n'
            '        self.position_embeddings = layers.Embedding(\n'
            '            sequence_length,\n'
            '            output_dim,\n'
            '        )\n'
            '\n'
            '    def call(self, inputs):\n'
            '        positions = (\n'
            '            keras.ops.cumsum(\n'
            '                keras.ops.ones_like(inputs),\n'
            '                axis=-1,\n'
            '            )\n'
            '            - 1\n'
            '        )\n'
            '\n'
            '        token_vectors = self.token_embeddings(inputs)\n'
            '        position_vectors = self.position_embeddings(positions)\n'
            '\n'
            '        return token_vectors + position_vectors\n'
            '```\n'
            '\n'
            'The resulting vector contains both:\n'
            '\n'
            '```text\n'
            'what token is this?\n'
            '+\n'
            'where is it?\n'
            '```\n'
            '\n'
            '### Why this improves translation\n'
            '\n'
            'Without position information, attention understands relationships but not sequence order.\n'
            '\n'
            'Adding positional embeddings converts attention into a true sequence-modeling system.\n'
            '\n'
            '### Training efficiency\n'
            '\n'
            'Unlike an RNN, Transformer attention does not require a recurrent loop across all token positions during training.\n'
            '\n'
            'This allows many sequence operations to run in parallel on GPUs and TPUs.\n'
            '\n'
            'This parallelism is a major reason Transformers scale well to large datasets and large models.\n'
            '\n'
            '---\n'
            '\n'
            '## 8. Building a Transformer sequence-to-sequence model\n'
            '\n'
            'Now combine the pieces.\n'
            '\n'
            '### Source side\n'
            '\n'
            '```text\n'
            'English token IDs\n'
            '      ↓\n'
            'token + position embeddings\n'
            '      ↓\n'
            'Transformer encoder\n'
            '      ↓\n'
            'contextual source sequence\n'
            '```\n'
            '\n'
            '### Target side\n'
            '\n'
            '```text\n'
            'previous Spanish token IDs\n'
            '      ↓\n'
            'token + position embeddings\n'
            '      ↓\n'
            'Transformer decoder\n'
            '      ↓\n'
            'Dense softmax\n'
            '      ↓\n'
            'next-token probabilities\n'
            '```\n'
            '\n'
            'A simplified model looks like:\n'
            '\n'
            '```python\n'
            'source = keras.Input(\n'
            '    shape=(None,),\n'
            '    dtype="int32",\n'
            '    name="english",\n'
            ')\n'
            '\n'
            'source_x = PositionalEmbedding(\n'
            '    sequence_length,\n'
            '    vocab_size,\n'
            '    hidden_dim,\n'
            ')(source)\n'
            '\n'
            'encoder_output = TransformerEncoder(\n'
            '    hidden_dim,\n'
            '    intermediate_dim,\n'
            '    num_heads,\n'
            ')(\n'
            '    source=source_x,\n'
            '    source_mask=source != 0,\n'
            ')\n'
            '\n'
            'target = keras.Input(\n'
            '    shape=(None,),\n'
            '    dtype="int32",\n'
            '    name="spanish",\n'
            ')\n'
            '\n'
            'target_x = PositionalEmbedding(\n'
            '    sequence_length,\n'
            '    vocab_size,\n'
            '    hidden_dim,\n'
            ')(target)\n'
            '\n'
            'target_x = TransformerDecoder(\n'
            '    hidden_dim,\n'
            '    intermediate_dim,\n'
            '    num_heads,\n'
            ')(\n'
            '    target=target_x,\n'
            '    source=encoder_output,\n'
            '    source_mask=source != 0,\n'
            ')\n'
            '\n'
            'target_x = layers.Dropout(0.5)(target_x)\n'
            '\n'
            'outputs = layers.Dense(\n'
            '    vocab_size,\n'
            '    activation="softmax",\n'
            ')(target_x)\n'
            '\n'
            'transformer = keras.Model(\n'
            '    [source, target],\n'
            '    outputs,\n'
            ')\n'
            '```\n'
            '\n'
            '### Translation inference\n'
            '\n'
            'Generation still remains autoregressive.\n'
            '\n'
            'Start with:\n'
            '\n'
            '```text\n'
            '[start]\n'
            '```\n'
            '\n'
            'Then repeatedly:\n'
            '\n'
            '```text\n'
            'source sentence\n'
            '+\n'
            'generated target so far\n'
            '      ↓\n'
            'Transformer\n'
            '      ↓\n'
            'next-token distribution\n'
            '      ↓\n'
            'choose token\n'
            '      ↓\n'
            'append token\n'
            '```\n'
            '\n'
            'until:\n'
            '\n'
            '```text\n'
            '[end]\n'
            '```\n'
            '\n'
            '### Why training and inference still differ\n'
            '\n'
            'During training, all correct previous target tokens are available.\n'
            '\n'
            "During generation, previous target tokens come from the model's own outputs.\n"
            '\n'
            'The Transformer eliminates recurrent computation during **training**, but target generation itself remains autoregressive when using a decoder in this way.\n'
            '\n'
            '---\n'
            '\n'
            '## 9. Pretrained Transformer encoders\n'
            '\n'
            'Transformers benefit greatly from scale.\n'
            '\n'
            'Instead of training a large model from scratch for every task, a common workflow is:\n'
            '\n'
            '```text\n'
            'large-scale pretraining\n'
            '        ↓\n'
            'general language representation\n'
            '        ↓\n'
            'small task-specific head\n'
            '        ↓\n'
            'fine-tuning\n'
            '```\n'
            '\n'
            'One influential example is BERT and related encoder models such as RoBERTa.\n'
            '\n'
            '### Bidirectional Transformer encoder\n'
            '\n'
            'A Transformer encoder can allow every token to attend to tokens on both sides.\n'
            '\n'
            'That makes it useful for understanding input text.\n'
            '\n'
            'It is not naturally a left-to-right generator because a token can use information from future positions.\n'
            '\n'
            '### Masked language modeling\n'
            '\n'
            'A masked-language-model objective looks like:\n'
            '\n'
            '```text\n'
            '"The cat sat on the [MASK]."\n'
            '```\n'
            '\n'
            'The model predicts:\n'
            '\n'
            '```text\n'
            'mat\n'
            '```\n'
            '\n'
            'The probability is conceptually:\n'
            '\n'
            '```text\n'
            'p(masked token | surrounding tokens)\n'
            '```\n'
            '\n'
            'This differs from causal language modeling:\n'
            '\n'
            '```text\n'
            'p(next token | past tokens)\n'
            '```\n'
            '\n'
            '### Why masked language modeling is self-supervised\n'
            '\n'
            'No human needs to write labels.\n'
            '\n'
            'Given raw text:\n'
            '\n'
            '1. choose some tokens,\n'
            '2. replace them with `[MASK]`,\n'
            '3. use the original tokens as targets.\n'
            '\n'
            'The text creates its own training labels.\n'
            '\n'
            'This makes very large pretraining datasets possible.\n'
            '\n'
            '### Contextual embeddings\n'
            '\n'
            'A pretrained Transformer encoder does more than learn one fixed vector for each word.\n'
            '\n'
            'It produces a context-dependent representation.\n'
            '\n'
            'So:\n'
            '\n'
            '```text\n'
            'bank\n'
            '```\n'
            '\n'
            'in:\n'
            '\n'
            '```text\n'
            'river bank\n'
            '```\n'
            '\n'
            'can have a different final representation from:\n'
            '\n'
            '```text\n'
            'bank account\n'
            '```\n'
            '\n'
            'This is one of the major advantages of pretrained Transformer encoders.\n'
            '\n'
            '---\n'
            '\n'
            '## 10. Fine-tuning a pretrained Transformer\n'
            '\n'
            'Using a pretrained Transformer correctly requires matching its original preprocessing.\n'
            '\n'
            'Three pieces belong together:\n'
            '\n'
            '```text\n'
            'tokenizer\n'
            'model architecture\n'
            'pretrained weights\n'
            '```\n'
            '\n'
            'If token IDs differ from what the model saw during pretraining, the learned embedding table no longer has the intended meaning.\n'
            '\n'
            '### Subword tokenization\n'
            '\n'
            'Large pretrained models commonly use subword tokenization.\n'
            '\n'
            'This provides a useful compromise.\n'
            '\n'
            'Character tokenization:\n'
            '\n'
            '```text\n'
            'small vocabulary\n'
            'very long sequences\n'
            '```\n'
            '\n'
            'Word tokenization:\n'
            '\n'
            '```text\n'
            'shorter sequences\n'
            'huge vocabulary\n'
            'many unknown words\n'
            '```\n'
            '\n'
            'Subword tokenization:\n'
            '\n'
            '```text\n'
            'moderate vocabulary\n'
            'reasonable sequence length\n'
            'can represent rare/new words\n'
            '```\n'
            '\n'
            '### Pretrained backbone\n'
            '\n'
            'A pretrained model without a task-specific output head is often called a **backbone**.\n'
            '\n'
            'Conceptually:\n'
            '\n'
            '```text\n'
            'token IDs\n'
            '   ↓\n'
            'pretrained Transformer encoder\n'
            '   ↓\n'
            'contextual sequence representations\n'
            '```\n'
            '\n'
            'Then attach a task-specific head.\n'
            '\n'
            '### Text classification head\n'
            '\n'
            'For sentiment classification, the backbone returns:\n'
            '\n'
            '```text\n'
            'batch × sequence_length × hidden_dim\n'
            '```\n'
            '\n'
            'We need one prediction per review.\n'
            '\n'
            'One strategy is to use the representation of the first special token as a pooled sequence representation.\n'
            '\n'
            'Because that token can attend to the rest of the sequence, it can gather context from across the input.\n'
            '\n'
            'Then:\n'
            '\n'
            '```text\n'
            'first-token representation\n'
            '       ↓\n'
            'Dense / Dropout\n'
            '       ↓\n'
            'sigmoid\n'
            '       ↓\n'
            'positive or negative\n'
            '```\n'
            '\n'
            'Example:\n'
            '\n'
            '```python\n'
            'inputs = backbone.input\n'
            '\n'
            'x = backbone(inputs)\n'
            'x = x[:, 0, :]\n'
            '\n'
            'x = layers.Dropout(0.1)(x)\n'
            'x = layers.Dense(768, activation="relu")(x)\n'
            'x = layers.Dropout(0.1)(x)\n'
            '\n'
            'outputs = layers.Dense(\n'
            '    1,\n'
            '    activation="sigmoid",\n'
            ')(x)\n'
            '\n'
            'classifier = keras.Model(inputs, outputs)\n'
            '```\n'
            '\n'
            '### Fine-tuning\n'
            '\n'
            'Fine-tuning means continuing training on the downstream labeled task.\n'
            '\n'
            'Usually the learning rate is kept small because the pretrained model already contains useful representations.\n'
            '\n'
            'Conceptually:\n'
            '\n'
            '```text\n'
            'general pretrained language knowledge\n'
            '             +\n'
            'small labeled task dataset\n'
            '             ↓\n'
            'task-specialized model\n'
            '```\n'
            '\n'
            '### Why this matters\n'
            '\n'
            'Pretraining moves expensive representation learning into one reusable model.\n'
            '\n'
            'Instead of learning language structure from a small sentiment dataset, the classifier begins with representations learned from much larger text corpora.\n'
            '\n'
            'This is the foundation of the modern pretrained-model workflow.\n'
            '\n'
            '{{exercise:M15.L01.EX02}}\n'
            '\n'
            '---\n'
            '\n'
            '## 11. A mental model for why Transformers are effective\n'
            '\n'
            'The chapter connects Transformers to earlier embedding methods such as Word2Vec.\n'
            '\n'
            'The shared idea is that language can be represented geometrically.\n'
            '\n'
            'Words or tokens that behave similarly in context become related in a learned vector space.\n'
            '\n'
            '### From static to contextual embeddings\n'
            '\n'
            'A simple embedding gives:\n'
            '\n'
            '```text\n'
            'token -> vector\n'
            '```\n'
            '\n'
            'A Transformer repeatedly refines token representations:\n'
            '\n'
            '```text\n'
            'initial token embeddings\n'
            '       ↓\n'
            'attention\n'
            '       ↓\n'
            'contextual embedding space 1\n'
            '       ↓\n'
            'attention\n'
            '       ↓\n'
            'contextual embedding space 2\n'
            '       ↓\n'
            '...\n'
            '```\n'
            '\n'
            'Each layer recombines information from the previous layer.\n'
            '\n'
            '### Attention as learned information retrieval\n'
            '\n'
            'One useful mental model is:\n'
            '\n'
            '```text\n'
            'query -> what am I looking for?\n'
            'keys  -> what does each token offer?\n'
            'values -> what information should be retrieved?\n'
            '```\n'
            '\n'
            'Then:\n'
            '\n'
            '```text\n'
            'similar query/key\n'
            '     ↓\n'
            'large attention weight\n'
            '     ↓\n'
            'more of that value enters the new representation\n'
            '```\n'
            '\n'
            '### Semantic continuity\n'
            '\n'
            'The chapter frames learned embedding spaces as semantically continuous:\n'
            '\n'
            '```text\n'
            'small movement in representation space\n'
            '≈\n'
            'small change in represented meaning\n'
            '```\n'
            '\n'
            'This is one reason interpolation in learned representations can produce useful generalization.\n'
            '\n'
            '### Representation power\n'
            '\n'
            'A shallow embedding such as Word2Vec can capture relatively simple geometric relationships.\n'
            '\n'
            'A deep Transformer stacks many:\n'
            '\n'
            '```text\n'
            'attention transformations\n'
            '+\n'
            'nonlinear feedforward transformations\n'
            '```\n'
            '\n'
            'so it can represent much more complicated relationships.\n'
            '\n'
            'The chapter describes these complex learned transformations as something closer to **vector programs** than simple static relationships.\n'
            '\n'
            'That phrase is best understood as an intuition:\n'
            '\n'
            '> The model can learn complex functions over a continuous representation space rather than storing only a table of isolated symbolic rules.\n'
            '\n'
            '### Interpolation and limitations\n'
            '\n'
            'The chapter also emphasizes an important caution.\n'
            '\n'
            'A model can generate outputs by navigating and recombining patterns in a learned representation space.\n'
            '\n'
            'That can produce:\n'
            '\n'
            '```text\n'
            'useful generalization\n'
            '```\n'
            '\n'
            'but it can also produce:\n'
            '\n'
            '```text\n'
            'plausible but inaccurate outputs\n'
            '```\n'
            '\n'
            'The latter is one way to think about hallucination in generative language models.\n'
            '\n'
            'So fluent generation should not automatically be treated as verified factual retrieval or symbolic reasoning.\n'
            '\n'
            '---\n'
            '\n'
            '## 12. The complete progression from RNN language models to Transformers\n'
            '\n'
            'The chapter can be remembered as one progression.\n'
            '\n'
            '### Stage 1 — Next-token prediction\n'
            '\n'
            '```text\n'
            'past tokens\n'
            '   ↓\n'
            'language model\n'
            '   ↓\n'
            'next-token probabilities\n'
            '```\n'
            '\n'
            '### Stage 2 — Autoregressive generation\n'
            '\n'
            '```text\n'
            'predict token\n'
            '   ↓\n'
            'append token\n'
            '   ↓\n'
            'predict again\n'
            '```\n'
            '\n'
            '### Stage 3 — Sequence-to-sequence modeling\n'
            '\n'
            '```text\n'
            'source\n'
            '  ↓\n'
            'encoder\n'
            '  ↓\n'
            'decoder + previous target tokens\n'
            '  ↓\n'
            'next target token\n'
            '```\n'
            '\n'
            '### Stage 4 — RNN limitation\n'
            '\n'
            '```text\n'
            'long source\n'
            '  ↓\n'
            'compressed recurrent state\n'
            '  ↓\n'
            'information bottleneck\n'
            '```\n'
            '\n'
            'plus:\n'
            '\n'
            '```text\n'
            'sequential computation\n'
            '  ↓\n'
            'limited training parallelism\n'
            '```\n'
            '\n'
            '### Stage 5 — Attention\n'
            '\n'
            '```text\n'
            'current query\n'
            '  ↓\n'
            'compare directly with all keys\n'
            '  ↓\n'
            'weighted sum of values\n'
            '```\n'
            '\n'
            '### Stage 6 — Transformer\n'
            '\n'
            '```text\n'
            'self-attention\n'
            '+\n'
            'feedforward network\n'
            '+\n'
            'residual connections\n'
            '+\n'
            'layer normalization\n'
            '+\n'
            'position information\n'
            '```\n'
            '\n'
            '### Stage 7 — Pretraining\n'
            '\n'
            '```text\n'
            'very large raw text corpus\n'
            '      ↓\n'
            'self-supervised objective\n'
            '      ↓\n'
            'general language representation\n'
            '```\n'
            '\n'
            '### Stage 8 — Fine-tuning\n'
            '\n'
            '```text\n'
            'pretrained backbone\n'
            '      +\n'
            'task-specific labeled data\n'
            '      ↓\n'
            'specialized model\n'
            '```\n'
            '\n'
            'This progression explains why Transformers became such a powerful foundation for modern NLP.\n'
            '\n'
            '---\n'
            '\n'
            '## Important misconceptions\n'
            '\n'
            '### Misconception 1\n'
            '\n'
            '> "A language model predicts an entire sentence at once."\n'
            '\n'
            'A standard autoregressive language model predicts one next-token distribution at a time.\n'
            '\n'
            'Long text is generated by repeating this operation.\n'
            '\n'
            '### Misconception 2\n'
            '\n'
            '> "Attention automatically understands token order."\n'
            '\n'
            'Pure attention compares relationships among token representations but is not inherently aware of sequence position.\n'
            '\n'
            'Transformers therefore inject positional information.\n'
            '\n'
            '### Misconception 3\n'
            '\n'
            '> "A Transformer decoder can attend to future target tokens during training."\n'
            '\n'
            'Not in an autoregressive setup.\n'
            '\n'
            'Causal masking prevents target positions from seeing future tokens.\n'
            '\n'
            '### Misconception 4\n'
            '\n'
            '> "Self-attention and cross-attention are the same operation with identical inputs."\n'
            '\n'
            'The mathematical mechanism is similar, but their inputs differ.\n'
            '\n'
            '```text\n'
            'self-attention:\n'
            'Q, K, V from the same sequence\n'
            '\n'
            'cross-attention:\n'
            'Q from decoder\n'
            'K, V from encoder\n'
            '```\n'
            '\n'
            '### Misconception 5\n'
            '\n'
            '> "Masked language models and causal language models optimize the same conditional probability."\n'
            '\n'
            'They use related but different objectives.\n'
            '\n'
            '```text\n'
            'causal LM:\n'
            'p(token | past tokens)\n'
            '\n'
            'masked LM:\n'
            'p(masked token | surrounding tokens)\n'
            '```\n'
            '\n'
            '### Misconception 6\n'
            '\n'
            '> "Fine-tuning means throwing away pretrained weights and training a new model."\n'
            '\n'
            'Fine-tuning begins from pretrained weights and adjusts them, usually with a comparatively small task-specific dataset and a task-specific head.\n'
            '\n'
            '---\n'
            '\n'
            '## Key terminology\n'
            '\n'
            '| Term | Meaning |\n'
            '|---|---|\n'
            '| Language model | Model that learns a probability distribution over tokens conditioned on context |\n'
            '| Autoregressive generation | Generating one token at a time and feeding generated tokens back into the model |\n'
            '| Token | Basic text unit represented by an integer ID |\n'
            '| Vocabulary | Set of tokens the model can directly represent |\n'
            '| Sequence-to-sequence model | Model mapping one input sequence to another output sequence |\n'
            '| Encoder | Component that builds a representation of the source sequence |\n'
            '| Decoder | Component that generates the target sequence |\n'
            '| Attention | Mechanism for selectively combining information from sequence positions |\n'
            '| Query | Representation describing what information is being requested |\n'
            '| Key | Representation used for relevance matching |\n'
            '| Value | Representation actually combined into the attention output |\n'
            '| Dot-product attention | Attention that scores query-key relevance with dot products |\n'
            '| Scaled attention | Dot-product attention whose scores are divided by a dimension-dependent scale |\n'
            '| Multi-head attention | Multiple parallel attention operations with separate learned projections |\n'
            '| Self-attention | A sequence attending to itself |\n'
            '| Cross-attention | One sequence attending to another |\n'
            '| Transformer encoder | Stack using self-attention and feedforward blocks for contextual representation |\n'
            '| Transformer decoder | Stack using causal self-attention, cross-attention, and feedforward blocks |\n'
            '| Causal mask | Mask preventing a position from attending to future target positions |\n'
            '| Padding mask | Mask preventing attention to padding tokens |\n'
            '| Positional embedding | Representation added to token embeddings to encode token order |\n'
            '| Residual connection | Shortcut adding a sublayer input to its output |\n'
            '| Layer normalization | Feature normalization performed within sequence representations |\n'
            '| Masked language model | Model trained to reconstruct hidden tokens from surrounding context |\n'
            '| Causal language model | Model trained to predict tokens from preceding tokens |\n'
            '| Pretraining | Large-scale initial training on a broad objective and dataset |\n'
            '| Fine-tuning | Adapting a pretrained model to a downstream task |\n'
            '| Backbone | Pretrained representation model without a task-specific prediction head |\n'
            '| Contextual embedding | Token representation that depends on surrounding tokens |\n'
            '| Subword tokenization | Tokenization using units smaller than many words but larger than individual characters |\n'
            '\n'
            '---\n'
            '\n'
            '## Manual figures to add\n'
            '\n'
            'You said you will add figures manually, so these are the most useful figures from this chapter rather than every source image.\n'
            '\n'
            '1. **Figure 15.1 — Sequence-to-sequence learning**  \n'
            '   Place after **Section 3: Sequence-to-sequence learning**. It visually explains the encoder-decoder training and inference flow.\n'
            '\n'
            '2. **Figure 15.3 — General concept of attention**  \n'
            '   Place near the start of **Section 4: Attention**. It makes selective weighting easier to understand.\n'
            '\n'
            '3. **Figure 15.5 — Attention score matrix**  \n'
            '   Place after the explanation of dot-product attention. It shows target-to-source relevance scores.\n'
            '\n'
            '4. **Figure 15.7 — Multi-head attention**  \n'
            '   Place after the multi-head explanation. It helps show why several attention heads can capture different relationships.\n'
            '\n'
            '5. **Figure 15.8 — Transformer encoder and decoder blocks**  \n'
            '   Place after **Section 6: Transformer decoder block**. This is the most important architecture diagram in the chapter.\n'
            '\n'
            'You do not need every code-output screenshot. These five figures add the most conceptual value.\n'
            '\n'
            '---\n'
            '\n'
            '## Self-check\n'
            '\n'
            'Before continuing, make sure you can answer:\n'
            '\n'
            '1. What probability distribution does a causal language model learn?\n'
            '2. Why is predicting a complete output sequence as one class impractical?\n'
            '3. How does autoregressive generation turn next-token prediction into long-form text?\n'
            '4. Why must next-token models avoid future-token leakage?\n'
            '5. What is the difference between an encoder and a decoder in seq2seq learning?\n'
            '6. Why do RNN encoder-decoder models struggle with long sequences?\n'
            '7. What are queries, keys, and values in attention?\n'
            '8. Why is softmax applied to attention scores?\n'
            '9. Why are dot-product scores scaled?\n'
            '10. Why use multiple attention heads?\n'
            '11. What is self-attention?\n'
            '12. What is cross-attention?\n'
            '13. Why does a Transformer encoder still need a feedforward network?\n'
            '14. Why are residual connections useful?\n'
            '15. What is the difference between a padding mask and a causal mask?\n'
            '16. Why does a Transformer require positional information?\n'
            '17. Why can Transformer training be more parallel than RNN training?\n'
            '18. What is masked language modeling?\n'
            '19. Why must a pretrained model use its matching tokenizer?\n'
            '20. What does fine-tuning change compared with pretraining?\n'
            '21. Why can the first-token representation be useful for classification?\n'
            '22. How can interpolation in learned representation spaces support both generalization and occasional hallucination?\n'
            '\n'
            '---\n'
            '\n'
            '## Retain this idea\n'
            '\n'
            '**A language model reduces text generation to repeated next-token prediction. Attention then removes the need to pass all context through a recurrent chain by letting each token retrieve relevant information directly. The Transformer turns this idea into a scalable architecture using self-attention, cross-attention, feedforward layers, residual connections, normalization, masking, and positional information. Large-scale pretraining turns Transformer representations into reusable language backbones that can be adapted to many downstream tasks.**\n'
        ),

        "estimated_minutes": 210,

        "has_code_examples": True,

        "sections": [
            {
                "id": 'language-model',
                "title": 'Language modeling: predicting one token at a time',
                "order": 1,
            },
            {
                "id": 'autoregressive-generation',
                "title": 'Autoregressive text generation',
                "order": 2,
            },
            {
                "id": 'seq2seq',
                "title": 'Sequence-to-sequence learning',
                "order": 3,
            },
            {
                "id": 'attention',
                "title": 'Attention: retrieving relevant information directly',
                "order": 4,
            },
            {
                "id": 'transformer-encoder',
                "title": 'Transformer encoder block',
                "order": 5,
            },
            {
                "id": 'transformer-decoder',
                "title": 'Transformer decoder block',
                "order": 6,
            },
            {
                "id": 'positional-embeddings',
                "title": 'Transformers need positional information',
                "order": 7,
            },
            {
                "id": 'transformer-seq2seq',
                "title": 'Building a Transformer sequence-to-sequence model',
                "order": 8,
            },
            {
                "id": 'pretrained-transformers',
                "title": 'Pretrained Transformer encoders',
                "order": 9,
            },
            {
                "id": 'fine-tuning',
                "title": 'Fine-tuning a pretrained Transformer',
                "order": 10,
            },
            {
                "id": 'why-transformers-work',
                "title": 'A mental model for why Transformers are effective',
                "order": 11,
            },
            {
                "id": 'complete-workflow',
                "title": 'The complete progression from RNN language models to Transformers',
                "order": 12,
            }
        ],
    },


    # =======================================================================
    # INLINE EXERCISES
    # =======================================================================

    "exercises": [
        {
            "id": 'M15.L01.EX01',
            "title": 'Trace an Autoregressive Language Model',
            "lesson_code": "M15.L01",
            "section_id": 'autoregressive-generation',
            "placement": "after_section",
            "description": 'Practice the difference between next-token training and token-by-token generation.',
            "instructions": "1. Start with the prompt 'machine learning is'.\n2. Invent a four-token vocabulary and a probability distribution for the next token.\n3. Select the highest-probability token and append it to the prompt.\n4. Repeat the process for two more generated tokens.\n5. Explain why the model must not use future tokens while predicting the current token.\n6. Explain one way an error in an early generated token can affect later tokens.",
            "expected_output": 'A three-step token-generation trace with probability distributions, selected tokens, and a short explanation of causal information flow and error accumulation.',
            "difficulty": DifficultyLevel.beginner,
            "skill_tested": [
                'language-modeling',
                'autoregressive-generation',
                'causal-modeling',
            ],
        },

        {
            "id": 'M15.L01.EX02',
            "title": 'Design the Information Flow of a Transformer Translator',
            "lesson_code": "M15.L01",
            "section_id": 'fine-tuning',
            "placement": "after_section",
            "description": 'Connect positional embeddings, encoder self-attention, decoder causal attention, cross-attention, and output prediction.',
            "instructions": "1. Assume the source sentence is 'I will see you tomorrow' and the target language is Spanish.\n2. Describe what happens to source token IDs before the encoder receives them.\n3. Explain what encoder self-attention allows each source token to do.\n4. Explain why decoder self-attention must use a causal mask.\n5. Explain how cross-attention connects the decoder to the source sentence.\n6. State what the final Dense-softmax layer predicts.\n7. Finally, contrast this seq2seq decoder with a bidirectional pretrained encoder used for text classification.",
            "expected_output": 'A step-by-step Transformer information-flow explanation from token IDs through positional embeddings, encoder and decoder attention, and next-token prediction, followed by a comparison with encoder-only classification.',
            "difficulty": DifficultyLevel.beginner,
            "skill_tested": [
                'transformer',
                'self-attention',
                'cross-attention',
                'causal-mask',
                'positional-embedding',
                'pretrained-encoders',
            ],
        }
    ],


    # =======================================================================
    # LESSON QUIZ
    # =======================================================================

    "quiz": {
        "id": "M15.L01.QZ01",

        "title": "Language Models and the Transformer — Knowledge Check",

        "lesson_code": "M15.L01",

        "placement": "lesson_end",

        "questions": [
            {
                "id": 'M15.L01.Q01',
                "section_id": 'language-model',
                "question": 'What does a basic causal language model attempt to predict?',
                "options": [
                    'A probability distribution over the next token given previous tokens',
                    'The entire possible sentence space as one class',
                    'Only the number of tokens in a document',
                    'A segmentation mask for text',
                ],
                "correct": 0,
                "explanation": 'The language-model formulation makes generation tractable by predicting one next-token distribution at a time.',
            },

            {
                "id": 'M15.L01.Q02',
                "section_id": 'autoregressive-generation',
                "question": 'What makes text generation autoregressive?',
                "options": [
                    'Previously generated tokens are fed back as context for later predictions',
                    'All future tokens are visible during prediction',
                    'The model predicts only one fixed label for a document',
                    'The vocabulary changes after every token',
                ],
                "correct": 0,
                "explanation": 'Autoregressive generation repeatedly conditions future predictions on tokens generated earlier in the same output.',
            },

            {
                "id": 'M15.L01.Q03',
                "section_id": 'seq2seq',
                "question": 'What is the role of an encoder in sequence-to-sequence learning?',
                "options": [
                    'Build a representation of the source sequence',
                    'Delete the target vocabulary',
                    'Predict only padding positions',
                    'Replace the tokenizer',
                ],
                "correct": 0,
                "explanation": 'The encoder represents the source sequence so the decoder can condition target generation on the complete input.',
            },

            {
                "id": 'M15.L01.Q04',
                "section_id": 'attention',
                "question": 'In attention terminology, what do queries and keys primarily determine?',
                "options": [
                    'Relevance scores used to decide which values should contribute strongly',
                    'The number of epochs',
                    'The tokenizer vocabulary',
                    'The final test split',
                ],
                "correct": 0,
                "explanation": 'Queries are compared with keys, usually through dot products, and the resulting scores determine the weighting of values.',
            },

            {
                "id": 'M15.L01.Q05',
                "section_id": 'attention',
                "question": 'Why is multi-head attention useful?',
                "options": [
                    'Different heads can learn different relevance relationships in parallel',
                    'It removes the need for token embeddings',
                    'It makes every attention score identical',
                    'It prevents all overfitting automatically',
                ],
                "correct": 0,
                "explanation": 'Separate heads have separate learned projections, allowing the model to represent different relationships simultaneously.',
            },

            {
                "id": 'M15.L01.Q06',
                "section_id": 'transformer-encoder',
                "question": 'Why does a Transformer encoder contain a feedforward network in addition to attention?',
                "options": [
                    'It adds nonlinear transformation capacity to each token representation',
                    'Attention cannot operate on tensors',
                    'It provides the tokenizer vocabulary',
                    'It creates test labels',
                ],
                "correct": 0,
                "explanation": 'Attention primarily mixes information across sequence positions; the feedforward sublayer adds nonlinear representational power.',
            },

            {
                "id": 'M15.L01.Q07',
                "section_id": 'transformer-decoder',
                "question": 'What is the purpose of a causal attention mask?',
                "options": [
                    'Prevent a target position from attending to future target tokens',
                    'Prevent the encoder from seeing the source sentence',
                    'Delete all padding from the dataset permanently',
                    'Force every attention weight to be equal',
                ],
                "correct": 0,
                "explanation": 'Causal masking preserves the next-token prediction constraint by blocking information from positions that occur later in the target sequence.',
            },

            {
                "id": 'M15.L01.Q08',
                "section_id": 'positional-embeddings',
                "question": 'Why are positional embeddings needed in a Transformer?',
                "options": [
                    'Attention alone does not inherently encode token order',
                    'They reduce the vocabulary to one token',
                    'They replace the feedforward network',
                    'They are used only for image models',
                ],
                "correct": 0,
                "explanation": 'Pure attention focuses on relationships among token representations and must be given explicit position information to model order.',
            },

            {
                "id": 'M15.L01.Q09',
                "section_id": 'pretrained-transformers',
                "question": 'How does masked language modeling differ from causal language modeling?',
                "options": [
                    'Masked language modeling predicts hidden tokens using surrounding context, while causal modeling predicts from past context',
                    'Masked language modeling uses no tokens',
                    'Causal language modeling is bidirectional',
                    'They are exactly the same training objective',
                ],
                "correct": 0,
                "explanation": 'Masked models can use context on both sides of a hidden token, while causal models preserve left-to-right next-token prediction.',
            },

            {
                "id": 'M15.L01.Q10',
                "section_id": 'fine-tuning',
                "question": 'Why must a pretrained Transformer use a tokenizer compatible with its pretraining?',
                "options": [
                    'Token IDs must correspond to the representations the pretrained model learned',
                    'The tokenizer controls GPU temperature',
                    'Any integer sequence has the same meaning to the model',
                    'It is required only for image classification',
                ],
                "correct": 0,
                "explanation": 'Pretrained token embeddings are tied to specific token IDs, so incompatible tokenization would misalign text with learned representations.',
            },

            {
                "id": 'M15.L01.Q11',
                "section_id": 'why-transformers-work',
                "question": "Which statement best captures the chapter's intuition about deep Transformer representations?",
                "options": [
                    'Successive attention and feedforward layers repeatedly refine token representations in learned embedding spaces',
                    'Transformers store only a table of exact sentences',
                    'Attention removes the need for learned vectors',
                    'All Transformer layers use fixed symbolic rules written by a programmer',
                ],
                "correct": 0,
                "explanation": 'The chapter frames Transformer computation as repeated refinement and recombination of learned vector representations.',
            },

            {
                "id": 'M15.L01.Q12',
                "section_id": 'complete-workflow',
                "type": "open",
                "question": 'Explain the progression from an RNN next-token language model to a Transformer-based pretrained NLP system. Your answer should include autoregressive generation, encoder-decoder sequence-to-sequence learning, attention, positional information, causal masking, pretraining, and fine-tuning.',
            }
        ],

        "passing_score": 70,
    },
}
