"""M14.L01 — Text Classification: From Tokenization to Pretrained Embeddings.

One Topic -> one complete learner-facing Lesson + inline Exercises + lesson Quiz.
BOOK-002, Chapter 14, page range not provided in supplied source.
Instructor-authored curriculum adaptation.
"""

from app.models.learning import DifficultyLevel


# ---------------------------------------------------------------------------
# Lesson metadata
# ---------------------------------------------------------------------------

LESSON_CODE = "M14.L01"

MODULE_ORDER = 14

MODULE_TITLE = "Text Classification"

MODULE_DESCRIPTION = (
    "Learn how raw language becomes numerical input for machine learning, "
    "compare character, word, and subword tokenization, build bag-of-words "
    "and n-gram classifiers, preserve word order with sequence models, "
    "represent tokens with learned embeddings, and use unsupervised "
    "pretraining to improve downstream text classification."
)

SOURCE_CHAPTER = 14

SOURCE_PAGES = "Chapter 14 — page range not provided"


# ---------------------------------------------------------------------------
# Topic
# ---------------------------------------------------------------------------

TOPIC = {
    "title": "Text Classification: From Tokenization to Pretrained Embeddings",

    "slug": "deep-learning-foundations-m14-l01",

    "description": (
        "Understand the complete text-classification pipeline from raw text "
        "through tokenization and numerical encoding to bag-of-words models, "
        "sequence models, learned embeddings, and pretrained representations."
    ),

    "order": 1,

    "difficulty": DifficultyLevel.beginner,

    "estimated_hours": 3.0,

    "skill_tags": [
        "deep-learning",
        "nlp",
        "text-classification",
        "tokenization",
        "subword-tokenization",
        "byte-pair-encoding",
        "bag-of-words",
        "ngrams",
        "sequence-models",
        "lstm",
        "word-embeddings",
        "pretraining",
        "cbow",
        "module-14",
    ],

    "prerequisite_ids": [],


    # =======================================================================
    # LESSON
    # =======================================================================

    "lesson": {
        "title": "Text Classification: From Tokenization to Pretrained Embeddings",

        "content": (
            "# Text Classification: From Tokenization to Pretrained Embeddings\n"
            "\n"
            "> **Course:** Deep Learning Foundations  \n"
            "> **Lesson:** M14.L01  \n"
            "> **Module:** Text Classification  \n"
            "> **Source alignment:** BOOK-002, Chapter 14. "
            "The supplied source did not specify a page range. "
            "This lesson is an instructor-authored curriculum adaptation "
            "rather than a reproduction of the source text.\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Learning outcomes
            # ----------------------------------------------------------------

            "## Learning outcomes\n"
            "\n"
            "By the end of this lesson, you should be able to:\n"
            "\n"
            "- Explain what natural language processing is and why raw text "
            "cannot be passed directly to a neural network.\n"
            "- Describe the three stages of text preprocessing: "
            "standardization, splitting, and indexing.\n"
            "- Explain the role of a vocabulary and the `[UNK]` token.\n"
            "- Compare character-, word-, and subword-level tokenization.\n"
            "- Explain the basic intuition behind byte-pair encoding.\n"
            "- Distinguish set-based text models from sequence models.\n"
            "- Build the mental model of a bag-of-words classifier.\n"
            "- Explain how bigrams and other n-grams preserve limited local "
            "word-order information.\n"
            "- Explain why variable-length text needs padding or truncation "
            "when batching sequences.\n"
            "- Explain why one-hot token representations are inefficient.\n"
            "- Explain what an embedding layer learns.\n"
            "- Explain why padding tokens should be masked.\n"
            "- Describe how a bidirectional LSTM can be used for text classification.\n"
            "- Explain why simple bag-of-words models can outperform larger "
            "sequence models when labeled data is limited.\n"
            "- Explain the purpose of unsupervised pretraining.\n"
            "- Explain the intuition behind Continuous Bag of Words pretraining.\n"
            "- Transfer a pretrained embedding conceptually into a downstream classifier.\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Section 1
            # ----------------------------------------------------------------

            "## 1. Turning Human Language into Numbers\n"
            "\n"
            "Neural networks operate on numerical tensors.\n"
            "\n"
            "But text begins as strings:\n"
            "\n"
            "```text\n"
            "The quick brown fox jumped over the lazy dog.\n"
            "```\n"
            "\n"
            "A neural network cannot directly multiply this sentence by a "
            "weight matrix.\n"
            "\n"
            "Before modeling text, we therefore need a transformation:\n"
            "\n"
            "```text\n"
            "Raw text\n"
            "   ↓\n"
            "tokens\n"
            "   ↓\n"
            "token IDs\n"
            "   ↓\n"
            "numeric representation\n"
            "   ↓\n"
            "machine learning model\n"
            "```\n"
            "\n"
            "This numerical preprocessing is fundamental to natural language "
            "processing, or **NLP**.\n"
            "\n"
            "### What is NLP?\n"
            "\n"
            "Natural language processing applies computational techniques to "
            "human language.\n"
            "\n"
            "Examples include:\n"
            "\n"
            "```text\n"
            "Email → spam probability\n"
            "\n"
            "English sentence → translated sentence\n"
            "\n"
            "Incomplete sentence → likely next word\n"
            "\n"
            "Movie review → positive / negative sentiment\n"
            "```\n"
            "\n"
            "Modern NLP models generally learn statistical regularities from "
            "large amounts of text instead of depending entirely on manually "
            "written grammar rules.\n"
            "\n"
            "### The three stages of tokenization\n"
            "\n"
            "The preprocessing pipeline in this chapter can be understood as:\n"
            "\n"
            "```text\n"
            "1. STANDARDIZATION\n"
            "       ↓\n"
            "2. SPLITTING\n"
            "       ↓\n"
            "3. INDEXING\n"
            "```\n"
            "\n"
            "People often use the word **tokenization** for this overall process.\n"
            "\n"
            "### Stage 1: Standardization\n"
            "\n"
            "Text can contain many superficial differences.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "Movie\n"
            "movie\n"
            "MOVIE\n"
            "```\n"
            "\n"
            "A simple tokenizer might initially treat these as three distinct "
            "tokens.\n"
            "\n"
            "Standardization attempts to remove differences that we do not want "
            "the model to learn independently.\n"
            "\n"
            "A simple standardization strategy could include:\n"
            "\n"
            "```text\n"
            "convert to lowercase\n"
            "remove selected punctuation\n"
            "normalize character encoding\n"
            "```\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "\"This Movie Is GREAT!\"\n"
            "          ↓\n"
            "\"this movie is great\"\n"
            "```\n"
            "\n"
            "However, aggressive normalization can remove useful information.\n"
            "\n"
            "Word tense, punctuation, capitalization, and morphology can carry "
            "meaning, so larger modern models often use relatively light "
            "standardization.\n"
            "\n"
            "### Stage 2: Splitting\n"
            "\n"
            "Splitting converts a string into smaller units called **tokens**.\n"
            "\n"
            "There are several possible token units.\n"
            "\n"
            "#### Character tokens\n"
            "\n"
            "```text\n"
            "\"cat\"\n"
            " ↓\n"
            "[\"c\", \"a\", \"t\"]\n"
            "```\n"
            "\n"
            "#### Word tokens\n"
            "\n"
            "```text\n"
            "\"the quick fox\"\n"
            " ↓\n"
            "[\"the\", \"quick\", \"fox\"]\n"
            "```\n"
            "\n"
            "#### Subword tokens\n"
            "\n"
            "A word may be divided into reusable pieces:\n"
            "\n"
            "```text\n"
            "\"unbelievable\"\n"
            " ↓\n"
            "[\"un\", \"believ\", \"able\"]\n"
            "```\n"
            "\n"
            "The exact pieces depend on the tokenizer vocabulary and algorithm.\n"
            "\n"
            "### Stage 3: Indexing\n"
            "\n"
            "After splitting, the tokens are still strings.\n"
            "\n"
            "We need to map each token to an integer.\n"
            "\n"
            "Suppose our vocabulary is:\n"
            "\n"
            "```python\n"
            "vocabulary = {\n"
            "    \"[UNK]\": 0,\n"
            "    \"the\": 1,\n"
            "    \"quick\": 2,\n"
            "    \"brown\": 3,\n"
            "    \"fox\": 4,\n"
            "}\n"
            "```\n"
            "\n"
            "Then:\n"
            "\n"
            "```text\n"
            "\"the quick fox\"\n"
            "      ↓\n"
            "[1, 2, 4]\n"
            "```\n"
            "\n"
            "These integer IDs can then be used by machine-learning layers.\n"
            "\n"
            "### Vocabulary\n"
            "\n"
            "A **vocabulary** is the collection of known tokens that the "
            "tokenizer can map to IDs.\n"
            "\n"
            "For word tokenization, a vocabulary might contain:\n"
            "\n"
            "```text\n"
            "[UNK]\n"
            "the\n"
            "movie\n"
            "great\n"
            "terrible\n"
            "actor\n"
            "...\n"
            "```\n"
            "\n"
            "Large vocabularies allow more tokens to be represented directly, "
            "but they also increase memory requirements and model size.\n"
            "\n"
            "### The `[UNK]` token\n"
            "\n"
            "What happens when the tokenizer sees a token that is not in its "
            "vocabulary?\n"
            "\n"
            "A special token is used:\n"
            "\n"
            "```text\n"
            "[UNK] = unknown token\n"
            "```\n"
            "\n"
            "Suppose `lazy` is missing from the vocabulary:\n"
            "\n"
            "```text\n"
            "\"the lazy dog\"\n"
            "      ↓\n"
            "[1, 0, 7]\n"
            "```\n"
            "\n"
            "The unknown word is mapped to ID 0 in this example.\n"
            "\n"
            "### Character tokenization\n"
            "\n"
            "Character tokenizers have a small vocabulary.\n"
            "\n"
            "For example, an entire English book may be representable using "
            "only dozens of frequent characters.\n"
            "\n"
            "Advantage:\n"
            "\n"
            "```text\n"
            "small vocabulary\n"
            "few unknown symbols\n"
            "```\n"
            "\n"
            "Disadvantage:\n"
            "\n"
            "```text\n"
            "very long sequences\n"
            "```\n"
            "\n"
            "The sentence:\n"
            "\n"
            "```text\n"
            "\"machine learning\"\n"
            "```\n"
            "\n"
            "requires many character tokens but only two word tokens.\n"
            "\n"
            "### Word tokenization\n"
            "\n"
            "Word-level tokenization greatly shortens sequences.\n"
            "\n"
            "```text\n"
            "\"machine learning is useful\"\n"
            " ↓\n"
            "[machine, learning, is, useful]\n"
            "```\n"
            "\n"
            "However, natural language contains huge numbers of possible words, "
            "including names, spelling variants, rare terms, and new words.\n"
            "\n"
            "A fixed word vocabulary therefore creates a tradeoff:\n"
            "\n"
            "```text\n"
            "small vocabulary\n"
            "→ many unknown words\n"
            "\n"
            "huge vocabulary\n"
            "→ expensive model\n"
            "```\n"
            "\n"
            "### Subword tokenization\n"
            "\n"
            "Subword tokenization aims to combine the strengths of character "
            "and word approaches.\n"
            "\n"
            "The goal is:\n"
            "\n"
            "```text\n"
            "reasonably short sequences\n"
            "+\n"
            "manageable vocabulary\n"
            "+\n"
            "ability to represent rare words\n"
            "```\n"
            "\n"
            "A common word may become one token while an unusual word is split "
            "into several smaller units.\n"
            "\n"
            "For example, conceptually:\n"
            "\n"
            "```text\n"
            "common word:\n"
            "\"movie\"\n"
            "→ [movie]\n"
            "\n"
            "rare word:\n"
            "\"movielike\"\n"
            "→ [movie, like]\n"
            "```\n"
            "\n"
            "### Byte-pair encoding intuition\n"
            "\n"
            "One popular way to learn subword units is **byte-pair encoding**, "
            "or BPE.\n"
            "\n"
            "The basic idea is surprisingly simple.\n"
            "\n"
            "Start from small symbols such as characters:\n"
            "\n"
            "```text\n"
            "t h e\n"
            "b r o w n\n"
            "f o x\n"
            "```\n"
            "\n"
            "Then repeatedly find frequently neighboring symbol pairs and "
            "merge them.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "t h\n"
            "→ th\n"
            "\n"
            "th e\n"
            "→ the\n"
            "```\n"
            "\n"
            "Common sequences eventually become whole tokens, while uncommon "
            "words may remain divided into smaller pieces.\n"
            "\n"
            "This gives the tokenizer a useful compromise between character "
            "and word tokenization.\n"
            "\n"
            "### Which tokenization should you choose?\n"
            "\n"
            "There is no universal answer.\n"
            "\n"
            "```text\n"
            "Character-level\n"
            "→ useful when individual characters matter\n"
            "→ long sequences\n"
            "\n"
            "Word-level\n"
            "→ simple and interpretable\n"
            "→ vocabulary can become huge\n"
            "\n"
            "Subword-level\n"
            "→ good balance of vocabulary size and sequence length\n"
            "→ widely used by modern language models\n"
            "```\n"
            "\n"
            "When using a pretrained language model, however, you generally "
            "must use the same tokenization scheme that was used during "
            "pretraining.\n"
            "\n"
            "> **Recommended manual figure:** Add a diagram showing "
            "`raw text → standardization → splitting → indexing → token IDs` "
            "immediately here.\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Section 2
            # ----------------------------------------------------------------

            "## 2. Set-Based Text Classification: Bag of Words and N-Grams\n"
            "\n"
            "Once text has been tokenized, a major design question remains:\n"
            "\n"
            "> How much should the model care about token order?\n"
            "\n"
            "The simplest answer is:\n"
            "\n"
            "> Ignore order completely.\n"
            "\n"
            "This produces a **bag-of-words** model.\n"
            "\n"
            "### Bag of words\n"
            "\n"
            "Suppose we have:\n"
            "\n"
            "```text\n"
            "\"this movie made me cry\"\n"
            "```\n"
            "\n"
            "After tokenization:\n"
            "\n"
            "```text\n"
            "[this, movie, made, me, cry]\n"
            "```\n"
            "\n"
            "A bag-of-words representation does not care which word came first.\n"
            "\n"
            "It only cares which vocabulary terms are present.\n"
            "\n"
            "Suppose the vocabulary is:\n"
            "\n"
            "```text\n"
            "0 → [UNK]\n"
            "1 → movie\n"
            "2 → film\n"
            "3 → made\n"
            "4 → laugh\n"
            "5 → cry\n"
            "```\n"
            "\n"
            "The review might become:\n"
            "\n"
            "```text\n"
            "[1, 1, 0, 1, 0, 1]\n"
            "```\n"
            "\n"
            "This is a **multi-hot vector**.\n"
            "\n"
            "Each position means:\n"
            "\n"
            "```text\n"
            "1 → token appears\n"
            "0 → token absent\n"
            "```\n"
            "\n"
            "### A very small sentiment classifier\n"
            "\n"
            "Using a 20,000-token vocabulary, an IMDb review becomes:\n"
            "\n"
            "```text\n"
            "(20000,)\n"
            "```\n"
            "\n"
            "One simple classifier is:\n"
            "\n"
            "```python\n"
            "inputs = keras.Input(shape=(20000,))\n"
            "outputs = layers.Dense(1, activation=\"sigmoid\")(inputs)\n"
            "\n"
            "model = keras.Model(inputs, outputs)\n"
            "```\n"
            "\n"
            "For binary sentiment classification:\n"
            "\n"
            "```text\n"
            "output      → one sigmoid unit\n"
            "loss        → binary crossentropy\n"
            "metric      → accuracy\n"
            "```\n"
            "\n"
            "Despite being extremely small, this model can perform surprisingly "
            "well because sentiment is often strongly associated with the "
            "presence of particular words.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "\"terrible\"\n"
            "→ evidence for negative sentiment\n"
            "\n"
            "\"excellent\"\n"
            "→ evidence for positive sentiment\n"
            "```\n"
            "\n"
            "The source's unigram model reaches about 88% test accuracy while "
            "using only about twenty thousand trainable parameters.\n"
            "\n"
            "### Why bag of words is limited\n"
            "\n"
            "Consider:\n"
            "\n"
            "```text\n"
            "\"not bad\"\n"
            "```\n"
            "\n"
            "and:\n"
            "\n"
            "```text\n"
            "\"bad\"\n"
            "```\n"
            "\n"
            "A simple bag-of-words representation sees the word `bad` in both.\n"
            "\n"
            "But the phrase `not bad` can have very different sentiment.\n"
            "\n"
            "Word order contains information.\n"
            "\n"
            "### N-grams\n"
            "\n"
            "An **n-gram** is an ordered sequence of `n` consecutive tokens.\n"
            "\n"
            "For:\n"
            "\n"
            "```text\n"
            "\"this movie made me cry\"\n"
            "```\n"
            "\n"
            "the unigrams are:\n"
            "\n"
            "```text\n"
            "this\n"
            "movie\n"
            "made\n"
            "me\n"
            "cry\n"
            "```\n"
            "\n"
            "The bigrams are:\n"
            "\n"
            "```text\n"
            "this movie\n"
            "movie made\n"
            "made me\n"
            "me cry\n"
            "```\n"
            "\n"
            "Trigrams would contain three consecutive tokens.\n"
            "\n"
            "### Why bigrams help\n"
            "\n"
            "A unigram model treats:\n"
            "\n"
            "```text\n"
            "not\n"
            "bad\n"
            "```\n"
            "\n"
            "as separate clues.\n"
            "\n"
            "A bigram vocabulary can contain:\n"
            "\n"
            "```text\n"
            "\"not bad\"\n"
            "```\n"
            "\n"
            "as its own feature.\n"
            "\n"
            "This preserves some local word order without requiring a full "
            "sequence model.\n"
            "\n"
            "In the chapter, adding unigram and bigram features increases test "
            "accuracy from roughly 88% to roughly 90%.\n"
            "\n"
            "### Why not use arbitrarily large n-grams?\n"
            "\n"
            "The number of possible combinations grows extremely quickly.\n"
            "\n"
            "For a vocabulary of `V` words:\n"
            "\n"
            "```text\n"
            "possible unigrams  ~ V\n"
            "possible bigrams   ~ V²\n"
            "possible trigrams  ~ V³\n"
            "```\n"
            "\n"
            "In practice, not all combinations occur, but the explosion is "
            "still severe.\n"
            "\n"
            "Large n-grams can also cause the model to memorize exact phrases "
            "rather than generalize.\n"
            "\n"
            "This motivates models that consume the original ordered sequence "
            "instead of manually creating every possible phrase feature.\n"
            "\n"
            "### Set models versus sequence models\n"
            "\n"
            "The distinction is:\n"
            "\n"
            "```text\n"
            "SET MODEL\n"
            "text → which tokens / n-grams are present?\n"
            "\n"
            "SEQUENCE MODEL\n"
            "text → which tokens occur, and in what order?\n"
            "```\n"
            "\n"
            "Bag-of-words models are computationally cheap and often excellent "
            "baselines for text classification.\n"
            "\n"

            # Exercise EX01 is rendered here by the frontend.
            "{{exercise:M14.L01.EX01}}\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Section 3
            # ----------------------------------------------------------------

            "## 3. Sequence Models and Learned Word Embeddings\n"
            "\n"
            "N-grams preserve only limited local ordering.\n"
            "\n"
            "To model longer relationships, we can provide the complete ordered "
            "token sequence to the neural network.\n"
            "\n"
            "These are **sequence models**.\n"
            "\n"
            "Possible sequence architectures include:\n"
            "\n"
            "```text\n"
            "RNN / LSTM / GRU\n"
            "1D ConvNet\n"
            "Transformer\n"
            "```\n"
            "\n"
            "This chapter focuses on an LSTM-based classifier, while the next "
            "chapter builds toward Transformers.\n"
            "\n"
            "### Variable-length text creates a batching problem\n"
            "\n"
            "Movie reviews have different lengths.\n"
            "\n"
            "```text\n"
            "Review A → 80 tokens\n"
            "Review B → 240 tokens\n"
            "Review C → 510 tokens\n"
            "```\n"
            "\n"
            "GPU batch computations work most conveniently with rectangular "
            "tensors.\n"
            "\n"
            "We therefore use **padding** and **truncation**.\n"
            "\n"
            "### Truncation\n"
            "\n"
            "Suppose we choose:\n"
            "\n"
            "```text\n"
            "maximum sequence length = 600\n"
            "```\n"
            "\n"
            "Reviews longer than 600 tokens are shortened.\n"
            "\n"
            "### Padding\n"
            "\n"
            "Shorter reviews receive a special `[PAD]` token.\n"
            "\n"
            "Suppose the desired length is 8:\n"
            "\n"
            "```text\n"
            "\"the slow brown badger\"\n"
            "```\n"
            "\n"
            "becomes:\n"
            "\n"
            "```text\n"
            "[the, slow, brown, badger, PAD, PAD, PAD, PAD]\n"
            "```\n"
            "\n"
            "Now every sample in the batch has the same length.\n"
            "\n"
            "With batch size 32 and maximum length 600:\n"
            "\n"
            "```text\n"
            "batch shape = (32, 600)\n"
            "```\n"
            "\n"
            "Each value is a token ID.\n"
            "\n"
            "### First attempt: one-hot encoding each token\n"
            "\n"
            "One way to convert a token ID into a vector is one-hot encoding.\n"
            "\n"
            "Suppose the vocabulary has 30,000 terms.\n"
            "\n"
            "Token ID 4 becomes something like:\n"
            "\n"
            "```text\n"
            "[0, 0, 0, 0, 1, 0, 0, ..., 0]\n"
            "```\n"
            "\n"
            "This vector contains 30,000 dimensions.\n"
            "\n"
            "A 600-token review therefore becomes conceptually:\n"
            "\n"
            "```text\n"
            "(600, 30000)\n"
            "```\n"
            "\n"
            "That is:\n"
            "\n"
            "```text\n"
            "18,000,000 values\n"
            "```\n"
            "\n"
            "for one review.\n"
            "\n"
            "This is extremely inefficient.\n"
            "\n"
            "### Bidirectional LSTM classifier\n"
            "\n"
            "The chapter first uses one-hot token vectors with a bidirectional "
            "LSTM:\n"
            "\n"
            "```python\n"
            "inputs = keras.Input(shape=(600,), dtype=\"int32\")\n"
            "x = one_hot_encoding(inputs)\n"
            "x = layers.Bidirectional(layers.LSTM(64))(x)\n"
            "x = layers.Dropout(0.5)(x)\n"
            "outputs = layers.Dense(1, activation=\"sigmoid\")(x)\n"
            "```\n"
            "\n"
            "Why bidirectional?\n"
            "\n"
            "For sentiment classification, the entire review is already "
            "available before prediction.\n"
            "\n"
            "So the representation can benefit from processing relationships "
            "in both directions:\n"
            "\n"
            "```text\n"
            "left → right\n"
            "+\n"
            "right → left\n"
            "```\n"
            "\n"
            "This differs from causal forecasting, where future information "
            "must not be available when predicting the future.\n"
            "\n"
            "### Bigger does not automatically mean better\n"
            "\n"
            "The one-hot LSTM has around 15 million trainable parameters in the "
            "chapter experiment and is much slower than the linear bag-of-words "
            "classifier.\n"
            "\n"
            "Yet its test accuracy is only around 84%.\n"
            "\n"
            "The much smaller bigram model reaches about 90%.\n"
            "\n"
            "This demonstrates an important engineering lesson:\n"
            "\n"
            "> Architectural complexity is only useful when the data and "
            "training setup allow the model to exploit it.\n"
            "\n"
            "### Why one-hot word vectors are conceptually weak\n"
            "\n"
            "One-hot encoding treats all vocabulary terms as unrelated.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "movie\n"
            "film\n"
            "```\n"
            "\n"
            "are semantically similar.\n"
            "\n"
            "But their one-hot vectors are completely separate and equally "
            "distant from one another as any unrelated words.\n"
            "\n"
            "This is not a natural representation of language.\n"
            "\n"
            "### Word embeddings\n"
            "\n"
            "A **word embedding** represents each token with a relatively small "
            "dense floating-point vector.\n"
            "\n"
            "Instead of:\n"
            "\n"
            "```text\n"
            "one-hot vector\n"
            "30,000 dimensions\n"
            "mostly zeros\n"
            "```\n"
            "\n"
            "we might use:\n"
            "\n"
            "```text\n"
            "embedding vector\n"
            "64 dimensions\n"
            "dense floating-point values\n"
            "```\n"
            "\n"
            "Conceptually:\n"
            "\n"
            "```text\n"
            "movie → [ 0.18, -0.42, 0.73, ... ]\n"
            "film  → [ 0.21, -0.39, 0.70, ... ]\n"
            "```\n"
            "\n"
            "During learning, related words can develop related geometric "
            "representations.\n"
            "\n"
            "### Embedding as a learned lookup table\n"
            "\n"
            "An Embedding layer can be thought of as a table:\n"
            "\n"
            "```text\n"
            "token ID\n"
            "   ↓\n"
            "look up row\n"
            "   ↓\n"
            "dense vector\n"
            "```\n"
            "\n"
            "For example:\n"
            "\n"
            "```python\n"
            "layers.Embedding(\n"
            "    input_dim=30000,\n"
            "    output_dim=64,\n"
            ")\n"
            "```\n"
            "\n"
            "means:\n"
            "\n"
            "```text\n"
            "30,000 possible token IDs\n"
            "64 learned values per token\n"
            "```\n"
            "\n"
            "The embedding therefore contains:\n"
            "\n"
            "```text\n"
            "30000 × 64\n"
            "= 1,920,000 parameters\n"
            "```\n"
            "\n"
            "This is far smaller than the parameter cost induced by feeding "
            "30,000-dimensional one-hot tokens into the LSTM.\n"
            "\n"
            "### Embedding-based sequence classifier\n"
            "\n"
            "The model becomes:\n"
            "\n"
            "```python\n"
            "inputs = keras.Input(shape=(600,), dtype=\"int32\")\n"
            "\n"
            "x = layers.Embedding(\n"
            "    input_dim=30000,\n"
            "    output_dim=64,\n"
            "    mask_zero=True,\n"
            ")(inputs)\n"
            "\n"
            "x = layers.Bidirectional(layers.LSTM(64))(x)\n"
            "x = layers.Dropout(0.5)(x)\n"
            "outputs = layers.Dense(1, activation=\"sigmoid\")(x)\n"
            "```\n"
            "\n"
            "The model size drops dramatically compared with one-hot input.\n"
            "\n"
            "### Masking padding tokens\n"
            "\n"
            "Remember that many reviews end with padding:\n"
            "\n"
            "```text\n"
            "the movie was awful PAD PAD PAD PAD\n"
            "```\n"
            "\n"
            "We do not want the LSTM's final representation to reflect repeated "
            "processing of meaningless padding tokens.\n"
            "\n"
            "Using:\n"
            "\n"
            "```python\n"
            "mask_zero=True\n"
            "```\n"
            "\n"
            "tells Keras that token ID 0 represents padding.\n"
            "\n"
            "The mask is propagated to compatible layers such as the LSTM, "
            "allowing padded timesteps to be ignored.\n"
            "\n"
            "The useful final state then corresponds to real sequence content "
            "rather than repeated padding.\n"
            "\n"
            "### Why learned embeddings still do not solve everything\n"
            "\n"
            "The embedding-based LSTM is much more efficient than the one-hot "
            "version.\n"
            "\n"
            "But in the chapter experiment, its accuracy remains around 84%.\n"
            "\n"
            "The problem is not that embeddings are useless.\n"
            "\n"
            "The issue is that the labeled IMDb training set is relatively "
            "small for jointly learning:\n"
            "\n"
            "```text\n"
            "good language representations\n"
            "+\n"
            "good sentiment classifier\n"
            "```\n"
            "\n"
            "The model can overfit the labeled training examples before it "
            "learns the best general-purpose word representation.\n"
            "\n"
            "This motivates **pretraining**.\n"
            "\n"
            "> **Recommended manual figure:** Add a side-by-side comparison of "
            "a sparse 30,000-dimensional one-hot word vector and a dense "
            "64-dimensional learned embedding immediately here.\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Section 4
            # ----------------------------------------------------------------

            "## 4. Pretraining Embeddings Before Classification\n"
            "\n"
            "Labeled examples are expensive.\n"
            "\n"
            "Raw text is much easier to collect.\n"
            "\n"
            "This creates a powerful idea:\n"
            "\n"
            "> Learn useful language representations from unlabeled text first, "
            "then reuse those representations for the supervised task.\n"
            "\n"
            "This is **pretraining**.\n"
            "\n"
            "### Pretraining versus downstream training\n"
            "\n"
            "Think of the process as two stages.\n"
            "\n"
            "```text\n"
            "STAGE 1 — PRETRAINING\n"
            "\n"
            "large amount of unlabeled text\n"
            "        ↓\n"
            "learn general language representations\n"
            "\n"
            "STAGE 2 — DOWNSTREAM TRAINING\n"
            "\n"
            "smaller labeled dataset\n"
            "        ↓\n"
            "specialize representations for the target task\n"
            "```\n"
            "\n"
            "This general principle eventually became central to modern NLP.\n"
            "\n"
            "### Continuous Bag of Words\n"
            "\n"
            "The chapter demonstrates embedding pretraining with **Continuous "
            "Bag of Words**, or CBOW.\n"
            "\n"
            "The pretraining task is:\n"
            "\n"
            "> Given nearby context words, predict a missing middle word.\n"
            "\n"
            "Suppose we have:\n"
            "\n"
            "```text\n"
            "the movie was surprisingly good and enjoyable\n"
            "```\n"
            "\n"
            "If `good` is hidden, context words around it might help predict it.\n"
            "\n"
            "Conceptually:\n"
            "\n"
            "```text\n"
            "context:\n"
            "movie, was, surprisingly, and, enjoyable, ...\n"
            "\n"
            "        ↓\n"
            "embedding representations\n"
            "        ↓\n"
            "predict missing token\n"
            "        ↓\n"
            "good\n"
            "```\n"
            "\n"
            "### Why predicting nearby words teaches embeddings\n"
            "\n"
            "Words used in similar contexts tend to have related meanings.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "\"excellent movie\"\n"
            "\"great movie\"\n"
            "\"wonderful movie\"\n"
            "```\n"
            "\n"
            "The words `excellent`, `great`, and `wonderful` occur in similar "
            "contexts.\n"
            "\n"
            "A model that repeatedly predicts words from their contexts can "
            "learn useful geometry in the embedding space.\n"
            "\n"
            "### Creating context windows\n"
            "\n"
            "The chapter uses windows of nine tokens.\n"
            "\n"
            "The middle token becomes the target.\n"
            "\n"
            "The four tokens to the left and four tokens to the right become "
            "the context.\n"
            "\n"
            "```text\n"
            "w1 w2 w3 w4 TARGET w6 w7 w8 w9\n"
            "\n"
            "context =\n"
            "[w1, w2, w3, w4, w6, w7, w8, w9]\n"
            "```\n"
            "\n"
            "### CBOW model\n"
            "\n"
            "The architecture is simple:\n"
            "\n"
            "```python\n"
            "inputs = keras.Input(shape=(8,))\n"
            "\n"
            "embedding = layers.Embedding(\n"
            "    30000,\n"
            "    64,\n"
            ")\n"
            "\n"
            "x = embedding(inputs)\n"
            "x = layers.GlobalAveragePooling1D()(x)\n"
            "outputs = layers.Dense(30000, activation=\"sigmoid\")(x)\n"
            "```\n"
            "\n"
            "The important component is the embedding matrix.\n"
            "\n"
            "The missing-word prediction task exists primarily to force those "
            "embedding vectors to become useful representations of language.\n"
            "\n"
            "### Unsupervised text is valuable\n"
            "\n"
            "The IMDb dataset contains additional unlabeled reviews.\n"
            "\n"
            "They cannot directly train a positive-versus-negative sentiment "
            "classifier because they have no sentiment labels.\n"
            "\n"
            "But they can still train the embedding because CBOW creates its "
            "own learning targets from the text itself.\n"
            "\n"
            "That is a central advantage of self-supervised or unsupervised "
            "pretraining-style tasks:\n"
            "\n"
            "```text\n"
            "raw text itself\n"
            "→ creates training signal\n"
            "```\n"
            "\n"
            "### Transfer the embedding\n"
            "\n"
            "After pretraining, create the sentiment classifier again:\n"
            "\n"
            "```python\n"
            "inputs = keras.Input(shape=(600,))\n"
            "\n"
            "lstm_embedding = layers.Embedding(\n"
            "    input_dim=30000,\n"
            "    output_dim=64,\n"
            "    mask_zero=True,\n"
            ")\n"
            "\n"
            "x = lstm_embedding(inputs)\n"
            "x = layers.Bidirectional(layers.LSTM(64))(x)\n"
            "x = layers.Dropout(0.5)(x)\n"
            "outputs = layers.Dense(1, activation=\"sigmoid\")(x)\n"
            "```\n"
            "\n"
            "Then initialize the new embedding using the pretrained weights:\n"
            "\n"
            "```python\n"
            "lstm_embedding.embeddings.assign(\n"
            "    cbow_embedding.embeddings\n"
            ")\n"
            "```\n"
            "\n"
            "Now the classifier does not begin with random token representations.\n"
            "\n"
            "It begins with embeddings already trained to capture contextual "
            "regularities from additional text.\n"
            "\n"
            "### Effect of embedding pretraining\n"
            "\n"
            "The source reports approximately:\n"
            "\n"
            "```text\n"
            "LSTM + randomly learned embedding\n"
            "≈ 84% test accuracy\n"
            "\n"
            "LSTM + pretrained CBOW embedding\n"
            "≈ 89% test accuracy\n"
            "```\n"
            "\n"
            "This is a substantial improvement.\n"
            "\n"
            "It brings the sequence model close to the strong bigram baseline.\n"
            "\n"
            "### Why doesn't the sequence model clearly dominate yet?\n"
            "\n"
            "Sequence models are more expressive, but they are also more "
            "data-hungry.\n"
            "\n"
            "The model must learn relationships across ordered text, which is "
            "more complicated than learning individual unigram or bigram weights.\n"
            "\n"
            "With only a limited amount of labeled ordered text, the simple "
            "model can still be highly competitive.\n"
            "\n"
            "This leads to a valuable engineering principle:\n"
            "\n"
            "> Always compare sophisticated models with strong simple baselines.\n"
            "\n"
            "### Text augmentation is difficult\n"
            "\n"
            "In computer vision, an image can often be flipped, cropped, or "
            "slightly rotated without changing its class.\n"
            "\n"
            "Language is much more fragile.\n"
            "\n"
            "Changing one word or changing word order can change the sentence's "
            "meaning.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "\"The movie was good.\"\n"
            "```\n"
            "\n"
            "and:\n"
            "\n"
            "```text\n"
            "\"The movie was not good.\"\n"
            "```\n"
            "\n"
            "differ by only one token but have nearly opposite sentiment.\n"
            "\n"
            "Random deletion or word swapping can therefore corrupt labels.\n"
            "\n"
            "This is one reason text augmentation has historically been less "
            "straightforward than image augmentation.\n"
            "\n"
            "### The broader NLP progression\n"
            "\n"
            "This chapter reveals an important progression in NLP modeling:\n"
            "\n"
            "```text\n"
            "RAW TEXT\n"
            "   ↓\n"
            "tokenization\n"
            "   ↓\n"
            "simple set representation\n"
            "   ↓\n"
            "bag of words\n"
            "   ↓\n"
            "n-grams\n"
            "   ↓\n"
            "ordered token sequences\n"
            "   ↓\n"
            "embeddings\n"
            "   ↓\n"
            "sequence model\n"
            "   ↓\n"
            "pretraining\n"
            "```\n"
            "\n"
            "The next major step is the Transformer, which addresses ordered "
            "relationships differently and scales much more effectively to "
            "large amounts of text and compute.\n"
            "\n"

            # Exercise EX02 is rendered here by the frontend.
            "{{exercise:M14.L01.EX02}}\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Misconceptions
            # ----------------------------------------------------------------

            "## Important misconceptions\n"
            "\n"
            "### Misconception 1\n"
            "\n"
            "> Tokenization simply means splitting text on spaces.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "The chapter treats text preprocessing as a larger process "
            "including standardization, splitting, and indexing. Modern "
            "tokenizers may also operate on subword units rather than words.\n"
            "\n"
            "### Misconception 2\n"
            "\n"
            "> A larger vocabulary is always better.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Larger vocabularies increase representation and model costs. "
            "Subword tokenization provides a compromise by representing rare "
            "words with smaller reusable pieces.\n"
            "\n"
            "### Misconception 3\n"
            "\n"
            "> Bag-of-words models understand sentence order.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "A basic bag-of-words representation records token presence while "
            "discarding sequence order. N-grams restore only limited local order.\n"
            "\n"
            "### Misconception 4\n"
            "\n"
            "> A more sophisticated LSTM must outperform a simple linear model.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Model usefulness depends on data, representation, optimization, "
            "and task structure. In the source experiment, a small bigram "
            "classifier outperforms the much larger initial LSTM model.\n"
            "\n"
            "### Misconception 5\n"
            "\n"
            "> One-hot token vectors encode semantic similarity between words.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "One-hot vectors treat token categories independently. Learned "
            "embeddings can instead place related words in related regions of "
            "a dense representation space.\n"
            "\n"
            "### Misconception 6\n"
            "\n"
            "> Padding tokens should be processed like ordinary words.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Padding exists only to make batch tensors rectangular. Masking "
            "prevents padded positions from contaminating the sequence representation.\n"
            "\n"
            "### Misconception 7\n"
            "\n"
            "> Pretraining requires labels for the final task.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "The CBOW example learns from raw text by creating its own "
            "context-prediction objective. The learned embedding parameters "
            "can later be transferred to a labeled downstream task.\n"
            "\n"
            "### Misconception 8\n"
            "\n"
            "> Text augmentation is as safe as rotating an image.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Small textual edits can change meaning or sentiment. Text "
            "augmentation therefore requires much more care.\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Key terminology
            # ----------------------------------------------------------------

            "## Key terminology\n"
            "\n"
            "| Term | Meaning |\n"
            "|---|---|\n"
            "| NLP | Computational processing of human language |\n"
            "| Token | Basic text unit used by a model |\n"
            "| Tokenization | Converting raw text into token representations |\n"
            "| Standardization | Normalizing text before token splitting |\n"
            "| Splitting | Dividing text into characters, words, or subwords |\n"
            "| Indexing | Mapping tokens to integer IDs |\n"
            "| Vocabulary | Collection of tokens known to a tokenizer |\n"
            "| `[UNK]` | Special representation for an unknown token |\n"
            "| `[PAD]` | Special token used to make sequence lengths equal within batches |\n"
            "| Character tokenization | Representing text using individual characters |\n"
            "| Word tokenization | Representing text using complete words |\n"
            "| Subword tokenization | Representing text using reusable pieces smaller than or equal to words |\n"
            "| BPE | Byte-pair encoding; iteratively merges frequent neighboring symbols |\n"
            "| Bag of words | Representation based on token presence without full sequence order |\n"
            "| Multi-hot encoding | Vector indicating which vocabulary features are present |\n"
            "| Unigram | One-token feature |\n"
            "| Bigram | Two consecutive token feature |\n"
            "| N-gram | Ordered sequence of N adjacent tokens |\n"
            "| Sequence model | Model that processes ordered token sequences |\n"
            "| Truncation | Cutting sequences that exceed a chosen maximum length |\n"
            "| Padding | Adding special tokens to shorter sequences |\n"
            "| One-hot encoding | Sparse categorical representation with one active dimension |\n"
            "| Embedding | Learned dense vector representation of a token |\n"
            "| Embedding space | Geometric latent space containing learned token representations |\n"
            "| Masking | Preventing selected sequence positions such as padding from affecting later computation |\n"
            "| Bidirectional LSTM | LSTM processing a sequence in both forward and reverse directions |\n"
            "| Pretraining | Learning transferable parameters before training on the final task |\n"
            "| CBOW | Continuous Bag of Words; predicts a token from surrounding context |\n"
            "| Downstream task | Final supervised problem that reuses pretrained representations |\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Self-check
            # ----------------------------------------------------------------

            "## Self-check\n"
            "\n"
            "Before continuing, make sure you can answer:\n"
            "\n"
            "1. Why must raw text be transformed before entering a neural network?\n"
            "2. What are the three stages of tokenization described in this lesson?\n"
            "3. What is the purpose of `[UNK]`?\n"
            "4. What is the main tradeoff between character and word tokenization?\n"
            "5. Why is subword tokenization useful?\n"
            "6. What basic idea does byte-pair encoding use to construct subwords?\n"
            "7. What information does a bag-of-words representation discard?\n"
            "8. Why can bigrams outperform unigrams?\n"
            "9. Why don't we simply use very large n-grams?\n"
            "10. Why do sequence batches require padding or truncation?\n"
            "11. Why is one-hot encoding individual words inefficient?\n"
            "12. What does an Embedding layer learn?\n"
            "13. Why should padding positions be masked?\n"
            "14. Why can a bidirectional LSTM be appropriate for sentiment classification?\n"
            "15. Why did the simple bigram model outperform the initial LSTM experiment?\n"
            "16. What problem does pretraining attempt to solve?\n"
            "17. How does CBOW create a training target without sentiment labels?\n"
            "18. What parameters are transferred from the CBOW model into the classifier?\n"
            "19. Why can pretrained embeddings improve downstream classification?\n"
            "20. Why should simple set-based text models still be considered even when sophisticated models are available?\n"
            "\n"
            "---\n"
            "\n"

            # ----------------------------------------------------------------
            # Retention statement
            # ----------------------------------------------------------------

            "## Retain this idea\n"
            "\n"
            "**Text classification begins by converting raw language into "
            "tokens and numerical representations. Simple set-based models can "
            "be extremely strong and efficient, while sequence models preserve "
            "word order but require more data and compute. Learned embeddings "
            "replace sparse one-hot token representations with compact semantic "
            "vectors, and pretraining lets those representations learn from "
            "large amounts of unlabeled text before being transferred to the "
            "final supervised task.**\n"
            "\n"
            "Keep this progression in mind:\n"
            "\n"
            "```text\n"
            "RAW TEXT\n"
            "   ↓\n"
            "standardize\n"
            "   ↓\n"
            "split into tokens\n"
            "   ↓\n"
            "index with vocabulary\n"
            "   ↓\n"
            "token IDs\n"
            "\n"
            "SIMPLE CLASSIFICATION\n"
            "   ↓\n"
            "bag of words\n"
            "   ↓\n"
            "bigrams / n-grams\n"
            "\n"
            "SEQUENCE MODELING\n"
            "   ↓\n"
            "padding + truncation\n"
            "   ↓\n"
            "embedding\n"
            "   ↓\n"
            "LSTM / sequence model\n"
            "\n"
            "PRETRAINING\n"
            "   ↓\n"
            "unlabeled text\n"
            "   ↓\n"
            "context prediction\n"
            "   ↓\n"
            "pretrained embedding\n"
            "   ↓\n"
            "downstream classifier\n"
            "```\n"
        ),

        "estimated_minutes": 180,

        "has_code_examples": True,

        "sections": [
            {
                "id": "text-preprocessing",
                "title": "Turning Human Language into Numbers",
                "order": 1,
            },
            {
                "id": "set-models",
                "title": "Set-Based Text Classification: Bag of Words and N-Grams",
                "order": 2,
            },
            {
                "id": "sequence-models",
                "title": "Sequence Models and Learned Word Embeddings",
                "order": 3,
            },
            {
                "id": "pretraining",
                "title": "Pretraining Embeddings Before Classification",
                "order": 4,
            },
        ],
    },


    # =======================================================================
    # INLINE EXERCISES
    # =======================================================================

    "exercises": [
        {
            "id": "M14.L01.EX01",

            "title": "Build a Text-Classification Preprocessing Pipeline",

            "lesson_code": "M14.L01",

            "section_id": "set-models",

            "placement": "after_section",

            "description": (
                "Practice moving from raw text through tokenization into "
                "bag-of-words and bigram features."
            ),

            "instructions": (
                "Suppose you are building a binary classifier for customer "
                "reviews.\n\n"
                "Use the example review:\n\n"
                "`The product is not bad, but delivery was slow.`\n\n"
                "1. Show one reasonable standardized version of the text.\n"
                "2. Split it into word-level tokens.\n"
                "3. Explain what should happen if the vocabulary does not "
                "contain the word `delivery`.\n"
                "4. Explain how the review would be represented by a "
                "bag-of-words model.\n"
                "5. List at least four bigrams that could be extracted.\n"
                "6. Explain why the bigram `not bad` can contain information "
                "that the individual words `not` and `bad` do not capture as well.\n"
                "7. Choose an appropriate final output layer for the sentiment "
                "classifier.\n"
                "8. Choose an appropriate loss function.\n"
                "9. Explain one reason a simple bigram classifier might be a "
                "better starting baseline than a large LSTM."
            ),

            "expected_output": (
                "A complete preprocessing example showing standardization, "
                "tokenization, unknown-token handling, bag-of-words features, "
                "bigrams, and a suitable binary classifier configuration."
            ),

            "difficulty": DifficultyLevel.beginner,

            "skill_tested": [
                "text-standardization",
                "tokenization",
                "vocabulary",
                "bag-of-words",
                "ngrams",
                "binary-text-classification",
            ],
        },

        {
            "id": "M14.L01.EX02",

            "title": "Design a Pretrained Sequence Classifier",

            "lesson_code": "M14.L01",

            "section_id": "pretraining",

            "placement": "after_section",

            "description": (
                "Practice designing an ordered text classifier using token "
                "sequences, embeddings, masking, LSTMs, and embedding pretraining."
            ),

            "instructions": (
                "You have 15,000 labeled support messages and 200,000 unlabeled "
                "messages from the same domain.\n\n"
                "You want to classify each labeled message as satisfied or "
                "unsatisfied.\n\n"
                "1. Choose character, word, or subword tokenization and explain "
                "your choice.\n"
                "2. Explain why inputs in the same batch need a compatible "
                "sequence length.\n"
                "3. Explain the roles of truncation and `[PAD]`.\n"
                "4. Explain why you would prefer a learned embedding over "
                "30,000-dimensional one-hot token vectors.\n"
                "5. Explain what `mask_zero=True` accomplishes.\n"
                "6. Design a conceptual embedding → bidirectional LSTM → "
                "classifier architecture.\n"
                "7. Explain how the 200,000 unlabeled examples could be used "
                "for embedding pretraining.\n"
                "8. Describe the CBOW objective in your own words.\n"
                "9. Explain which learned parameters would then be transferred "
                "to the sentiment classifier.\n"
                "10. Explain why you would still compare the final model "
                "against a bag-of-words or bigram baseline."
            ),

            "expected_output": (
                "A complete sequence-classification design describing "
                "tokenization, padding, embedding, masking, bidirectional LSTM "
                "classification, unsupervised pretraining, parameter transfer, "
                "and baseline comparison."
            ),

            "difficulty": DifficultyLevel.beginner,

            "skill_tested": [
                "sequence-modeling",
                "word-embeddings",
                "masking",
                "bidirectional-lstm",
                "pretraining",
                "cbow",
                "transfer-learning",
            ],
        },
    ],


    # =======================================================================
    # LESSON QUIZ
    # =======================================================================

    "quiz": {
        "id": "M14.L01.QZ01",

        "title": "Text Classification — Knowledge Check",

        "lesson_code": "M14.L01",

        "placement": "lesson_end",

        "questions": [
            {
                "id": "M14.L01.Q01",

                "section_id": "text-preprocessing",

                "question": (
                    "Which sequence correctly describes the core text "
                    "preprocessing stages introduced in the lesson?"
                ),

                "options": [
                    "Indexing → training → standardization",
                    "Standardization → splitting → indexing",
                    "Embedding → padding → splitting",
                    "Splitting → gradient descent → indexing",
                ],

                "correct": 1,

                "explanation": (
                    "Text is first standardized, then divided into tokens, and "
                    "those tokens are mapped to integer IDs using a vocabulary."
                ),
            },

            {
                "id": "M14.L01.Q02",

                "section_id": "set-models",

                "question": (
                    "What additional information can a bigram model capture "
                    "that a unigram bag-of-words model cannot directly capture?"
                ),

                "options": [
                    "Image color information",
                    "Pairs of adjacent tokens and limited local word order",
                    "The full grammatical structure of arbitrarily long documents",
                    "Continuous numerical sensor measurements",
                ],

                "correct": 1,

                "explanation": (
                    "Bigrams treat adjacent token pairs as features, preserving "
                    "a small amount of local ordering such as the phrase "
                    "`not bad`."
                ),
            },

            {
                "id": "M14.L01.Q03",

                "section_id": "sequence-models",

                "question": (
                    "Why is an Embedding layer generally more efficient than "
                    "one-hot encoding each token from a 30,000-word vocabulary?"
                ),

                "options": [
                    "Embeddings remove the need for tokenization",
                    "Embeddings map each token to a much smaller learned dense vector",
                    "Embeddings guarantee perfect semantic understanding",
                    "Embeddings eliminate all model parameters",
                ],

                "correct": 1,

                "explanation": (
                    "Instead of representing every word with a sparse vector "
                    "containing one dimension per vocabulary term, an Embedding "
                    "layer learns a compact dense representation such as 64 "
                    "values per token."
                ),
            },

            {
                "id": "M14.L01.Q04",

                "section_id": "sequence-models",

                "question": (
                    "What is the purpose of `mask_zero=True` in the Embedding "
                    "layer used in this lesson?"
                ),

                "options": [
                    "It makes all embedding weights equal to zero",
                    "It marks token ID zero as padding so compatible sequence layers can ignore those positions",
                    "It removes unknown words from the vocabulary",
                    "It prevents the classifier from predicting class zero",
                ],

                "correct": 1,

                "explanation": (
                    "Padded positions exist only to create equal-length batch "
                    "tensors. Masking tells later sequence layers not to treat "
                    "those padding timesteps as meaningful text."
                ),
            },

            {
                "id": "M14.L01.Q05",

                "section_id": "pretraining",

                "type": "open",

                "question": (
                    "You have a small labeled text-classification dataset and "
                    "a much larger collection of unlabeled text from the same "
                    "domain. Describe a complete strategy based on this lesson: "
                    "choose a tokenizer, build a simple baseline, construct "
                    "sequence inputs, use embeddings and masking, pretrain an "
                    "embedding from unlabeled text, transfer it into a sequence "
                    "classifier, and explain how you would determine whether "
                    "the extra complexity is actually worthwhile."
                ),
            },
        ],

        "passing_score": 70,
    },
}