"""M04.L01 — Linear Algebra.

One chapter -> one rich learner-facing Lesson + inline Images + inline Exercises + lesson Quiz.
Source: Chapter 4, "Linear Algebra".
Instructor-authored curriculum adaptation.
"""

from app.models.learning import DifficultyLevel

LESSON_CODE = "M04.L01"
MODULE_ORDER = 4
MODULE_TITLE = "Linear Algebra, Probability, and Numerical Foundations"
MODULE_DESCRIPTION = (
    "Build the mathematical and numerical foundation for vectors, matrices, tensors, "
    "matrix operations and decompositions, probability distributions, random sampling, "
    "normality testing, and masked arrays."
)
SOURCE_CHAPTER = 4
SOURCE_PAGES = "Not provided in supplied source extract"

TOPIC = {
    "title": "Linear Algebra",
    "slug": "python-data-analysis-m04-l01",
    "description": (
        "A complete learner-facing lesson covering linear algebra structures, polynomial "
        "fitting, matrix operations, eigen analysis, decompositions, probability distributions, "
        "random-number generation, normality tests, and masked arrays."
    ),
    "order": 1,
    "difficulty": DifficultyLevel.beginner,
    "estimated_hours": 7.0,
    "skill_tags": [
        "linear-algebra",
        "numpy",
        "scipy",
        "vectors",
        "matrices",
        "tensors",
        "polynomial-fitting",
        "eigenvalues",
        "svd",
        "lu",
        "qr",
        "probability-distributions",
        "random-numbers",
        "normality-testing",
        "masked-arrays",
        "module-04",
    ],
    "prerequisite_ids": ["M03.L01"],
    "lesson": {
        "title": "Linear Algebra",
        "content": (
            "# Linear Algebra\n"
            "\n"
            "> **Course:** Python for Data Analysis Foundations  \n"
            "> **Lesson:** M04.L01  \n"
            "> **Module:** Linear Algebra, Probability, and Numerical Foundations  \n"
            "> **Source alignment:** Chapter 4, “Linear Algebra.”  \n"
            "> This lesson is an instructor-authored curriculum adaptation based on the supplied chapter.\n"
            "\n"
            "---\n"
            "\n"
            "## Why this lesson matters\n"
            "\n"
            "Linear algebra gives data science a mathematical language for representing and transforming information.\n"
            "\n"
            "Many common data objects can be viewed as vectors, matrices, or higher-dimensional tensors:\n"
            "\n"
            "```text\n"
            "tabular data   → matrix-like\n"
            "image          → matrix / tensor of pixel values\n"
            "text features  → vectors or matrices\n"
            "embeddings     → vectors\n"
            "video          → higher-dimensional tensor\n"
            "```\n"
            "\n"
            "The chapter connects linear algebra directly to:\n"
            "\n"
            "- machine learning,\n"
            "- neural networks,\n"
            "- natural language processing,\n"
            "- computer vision,\n"
            "- generative AI,\n"
            "- dimensionality reduction,\n"
            "- optimization,\n"
            "- regression,\n"
            "- image transformation.\n"
            "\n"
            "The chapter then extends beyond matrix operations into probability distributions, random-number generation, normality tests, and masked arrays. These are included here because they are part of the supplied chapter's learning sequence.\n"
            "\n"
            "A useful mental map is:\n"
            "\n"
            "```text\n"
            "Scalar / Vector / Matrix / Tensor\n"
            "                ↓\n"
            "        Basic operations\n"
            "                ↓\n"
            "     Polynomial approximation\n"
            "                ↓\n"
            "    Matrix properties + solving\n"
            "                ↓\n"
            "Eigenvalues / Eigenvectors / Decomposition\n"
            "                ↓\n"
            "     Probability distributions\n"
            "                ↓\n"
            "       Random simulation\n"
            "                ↓\n"
            "        Normality testing\n"
            "                ↓\n"
            "     Masked image arrays\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "## Learning outcomes\n"
            "\n"
            "By the end of this lesson, you should be able to:\n"
            "\n"
            "- Explain why linear algebra matters in data science.\n"
            "- Distinguish scalars, vectors, matrices, and tensors by dimensionality.\n"
            "- Compute vector dot products and norms.\n"
            "- Perform matrix multiplication and transposition.\n"
            "- Explain polynomial fitting and the role of `polyfit()`, `polyval()`, and `linspace()`.\n"
            "- Explain underfitting and overfitting in the chapter's polynomial example.\n"
            "- Calculate and interpret matrix determinant and rank.\n"
            "- State the conditions required for a matrix inverse.\n"
            "- Solve a system of linear equations with `numpy.linalg.solve()`.\n"
            "- Explain eigenvectors and eigenvalues conceptually.\n"
            "- Explain why eigen methods matter for PCA, SVD, image transformations, and related methods.\n"
            "- Describe SVD, LU, and QR decomposition.\n"
            "- Distinguish PMF, PDF, and CDF.\n"
            "- Distinguish discrete and continuous probability distributions.\n"
            "- Explain Bernoulli, Binomial, Poisson, Geometric, Uniform, Normal, Log-normal, and Exponential distributions.\n"
            "- Generate random values using NumPy and SciPy.\n"
            "- Explain the role of histograms in visually assessing normality.\n"
            "- Interpret Shapiro–Wilk, Anderson–Darling, and D’Agostino–Pearson normality tests as presented in the chapter.\n"
            "- Explain how a NumPy masked array can hide selected image pixels while preserving array operations.\n"
            "\n"
            "---\n"
            "\n"
            "## 1. What is linear algebra?\n"
            "\n"
            "The chapter presents linear algebra as the mathematical foundation for representing and manipulating structured data.\n"
            "\n"
            "Vectors and matrices appear throughout data science because many datasets can naturally be represented as rectangular or multidimensional numerical structures.\n"
            "\n"
            "Examples from the chapter include:\n"
            "\n"
            "### Tabular data\n"
            "\n"
            "A dataset with rows and columns can be represented as a matrix:\n"
            "\n"
            "```text\n"
            "rows    → observations\n"
            "columns → attributes/features\n"
            "```\n"
            "\n"
            "### Images\n"
            "\n"
            "An image is represented numerically through pixel values.\n"
            "\n"
            "A grayscale image can be modeled as a 2D matrix.\n"
            "\n"
            "A color image may require additional dimensions or channels.\n"
            "\n"
            "### Text\n"
            "\n"
            "Text can be transformed into numerical vector/matrix representations through methods such as:\n"
            "\n"
            "- Bag of Words,\n"
            "- TF-IDF,\n"
            "- Word2Vec,\n"
            "- BERT embeddings.\n"
            "\n"
            "The important idea is:\n"
            "\n"
            "> Models do not directly manipulate words, pixels, or business concepts. They operate on numerical representations.\n"
            "\n"
            "---\n"
            "\n"
            "### 1.1 Linear algebra in machine learning\n"
            "\n"
            "The source links linear algebra with methods such as:\n"
            "\n"
            "- linear regression,\n"
            "- logistic regression,\n"
            "- neural networks,\n"
            "- PCA,\n"
            "- SVD,\n"
            "- gradient-based optimization.\n"
            "\n"
            "For example, a model may represent the input data as:\n"
            "\n"
            "```text\n"
            "X = data matrix\n"
            "w = parameter vector\n"
            "```\n"
            "\n"
            "and then perform a matrix-vector operation.\n"
            "\n"
            "The chapter does not derive those algorithms here, but it establishes the mathematical language they depend on.\n"
            "\n"
            "---\n"
            "\n"
            "### 1.2 Linear algebra in image processing\n"
            "\n"
            "The source connects matrix operations to transformations such as:\n"
            "\n"
            "- translation,\n"
            "- scaling,\n"
            "- rotation,\n"
            "- reflection,\n"
            "- shearing,\n"
            "- projection.\n"
            "\n"
            "The main lesson is that geometric transformations can be represented mathematically instead of manipulating each pixel manually.\n"
            "\n"
            "---\n"
            "\n"
            "### 1.3 NumPy and SciPy\n"
            "\n"
            "The chapter uses:\n"
            "\n"
            "```python\n"
            "numpy.linalg\n"
            "```\n"
            "\n"
            "and:\n"
            "\n"
            "```python\n"
            "scipy.linalg\n"
            "```\n"
            "\n"
            "for hands-on linear algebra.\n"
            "\n"
            "These libraries expose operations such as:\n"
            "\n"
            "- determinant,\n"
            "- rank,\n"
            "- inverse,\n"
            "- solving linear systems,\n"
            "- eigen analysis,\n"
            "- matrix decomposition.\n"
            "\n"
            "---\n"
            "\n"
            "## 2. Scalars, vectors, matrices, and tensors\n"
            "\n"
            "These structures differ mainly in dimensionality.\n"
            "\n"
            "A useful hierarchy is:\n"
            "\n"
            "```text\n"
            "scalar → 0D\n"
            "vector → 1D\n"
            "matrix → 2D\n"
            "tensor → 3D or higher in this chapter's examples\n"
            "```\n"
            "\n"
            "[[IMAGE_NEEDED: Scalar vector matrix tensor hierarchy | Show a single number, a 1D vector, a 2D grid, and a 3D stack of grids with dimension labels 0D, 1D, 2D, 3D | Learner should connect dimensionality with data structure complexity]]\n"
            "\n"
            "---\n"
            "\n"
            "### 2.1 Scalar\n"
            "\n"
            "A scalar is a single value.\n"
            "\n"
            "Example:\n"
            "\n"
            "```python\n"
            "scalar = np.array(5)\n"
            "\n"
            "print(scalar)\n"
            "print(scalar.shape)\n"
            "```\n"
            "\n"
            "Output:\n"
            "\n"
            "```text\n"
            "5\n"
            "()\n"
            "```\n"
            "\n"
            "The empty shape:\n"
            "\n"
            "```text\n"
            "()\n"
            "```\n"
            "\n"
            "represents a zero-dimensional NumPy object.\n"
            "\n"
            "A scalar has magnitude but no direction in the chapter's geometric framing.\n"
            "\n"
            "---\n"
            "\n"
            "### 2.2 Vector\n"
            "\n"
            "A vector is an ordered one-dimensional collection.\n"
            "\n"
            "Example:\n"
            "\n"
            "```python\n"
            "vector = np.array([1, 2, 3])\n"
            "\n"
            "print(vector)\n"
            "print(vector.shape)\n"
            "```\n"
            "\n"
            "Output:\n"
            "\n"
            "```text\n"
            "[1 2 3]\n"
            "(3,)\n"
            "```\n"
            "\n"
            "A vector can be visualized as either:\n"
            "\n"
            "```text\n"
            "row vector\n"
            "[1 2 3]\n"
            "```\n"
            "\n"
            "or conceptually as a column:\n"
            "\n"
            "```text\n"
            "[1]\n"
            "[2]\n"
            "[3]\n"
            "```\n"
            "\n"
            "Vectors can be:\n"
            "\n"
            "- added,\n"
            "- scaled by a number,\n"
            "- compared geometrically through operations such as dot products and norms.\n"
            "\n"
            "---\n"
            "\n"
            "### 2.3 Matrix\n"
            "\n"
            "A matrix is a two-dimensional array.\n"
            "\n"
            "Example:\n"
            "\n"
            "```python\n"
            "matrix = np.array([\n"
            "    [1, 2],\n"
            "    [3, 4]\n"
            "])\n"
            "\n"
            "print(matrix.shape)\n"
            "```\n"
            "\n"
            "Output:\n"
            "\n"
            "```text\n"
            "(2, 2)\n"
            "```\n"
            "\n"
            "Interpretation:\n"
            "\n"
            "```text\n"
            "2 rows\n"
            "2 columns\n"
            "```\n"
            "\n"
            "Matrices are useful for:\n"
            "\n"
            "- tables,\n"
            "- images,\n"
            "- transformations,\n"
            "- systems of equations.\n"
            "\n"
            "---\n"
            "\n"
            "### 2.4 Tensor\n"
            "\n"
            "The chapter uses tensor to describe a generalized multidimensional array.\n"
            "\n"
            "Example:\n"
            "\n"
            "```python\n"
            "tensor = np.array([\n"
            "    [[1, 2], [3, 4]],\n"
            "    [[5, 6], [7, 8]]\n"
            "])\n"
            "\n"
            "print(tensor.shape)\n"
            "```\n"
            "\n"
            "Output:\n"
            "\n"
            "```text\n"
            "(2, 2, 2)\n"
            "```\n"
            "\n"
            "You can think of it as two 2×2 matrices stacked together.\n"
            "\n"
            "The chapter connects tensors with:\n"
            "\n"
            "- multidimensional images,\n"
            "- video,\n"
            "- deep learning,\n"
            "- higher-dimensional scientific data.\n"
            "\n"
            "---\n"
            "\n"
            "### 2.5 Relationship between the structures\n"
            "\n"
            "A useful conceptual progression:\n"
            "\n"
            "```text\n"
            "Scalar\n"
            "5\n"
            "\n"
            "Vector\n"
            "[1, 2, 3]\n"
            "\n"
            "Matrix\n"
            "[[1, 2],\n"
            " [3, 4]]\n"
            "\n"
            "Tensor\n"
            "[\n"
            "  [[1, 2],\n"
            "   [3, 4]],\n"
            "\n"
            "  [[5, 6],\n"
            "   [7, 8]]\n"
            "]\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "## 3. Basic vector and matrix operations\n"
            "\n"
            "The chapter introduces:\n"
            "\n"
            "- dot product,\n"
            "- norm,\n"
            "- matrix multiplication,\n"
            "- transpose.\n"
            "\n"
            "These operations reappear throughout machine learning.\n"
            "\n"
            "---\n"
            "\n"
            "### 3.1 Vector dot product\n"
            "\n"
            "Create:\n"
            "\n"
            "```python\n"
            "v1 = np.array([1, 2])\n"
            "v2 = np.array([3, 4])\n"
            "```\n"
            "\n"
            "Compute:\n"
            "\n"
            "```python\n"
            "np.dot(v1, v2)\n"
            "```\n"
            "\n"
            "Calculation:\n"
            "\n"
            "```text\n"
            "1×3 + 2×4\n"
            "= 3 + 8\n"
            "= 11\n"
            "```\n"
            "\n"
            "Output:\n"
            "\n"
            "```text\n"
            "11\n"
            "```\n"
            "\n"
            "The dot product combines two vectors into a scalar.\n"
            "\n"
            "---\n"
            "\n"
            "### 3.2 Vector norm\n"
            "\n"
            "The source uses:\n"
            "\n"
            "```python\n"
            "np.linalg.norm(v1)\n"
            "```\n"
            "\n"
            "for:\n"
            "\n"
            "```text\n"
            "v1 = [1, 2]\n"
            "```\n"
            "\n"
            "Result:\n"
            "\n"
            "```text\n"
            "≈ 2.2361\n"
            "```\n"
            "\n"
            "This corresponds to the vector's magnitude:\n"
            "\n"
            "```text\n"
            "√(1² + 2²)\n"
            "= √5\n"
            "≈ 2.2361\n"
            "```\n"
            "\n"
            "Conceptually:\n"
            "\n"
            "> The norm tells you the size or length of a vector.\n"
            "\n"
            "---\n"
            "\n"
            "### 3.3 Matrix multiplication\n"
            "\n"
            "Create:\n"
            "\n"
            "```python\n"
            "A = np.array([\n"
            "    [1, 2],\n"
            "    [3, 4]\n"
            "])\n"
            "\n"
            "B = np.array([\n"
            "    [5, 6],\n"
            "    [7, 8]\n"
            "])\n"
            "```\n"
            "\n"
            "Then:\n"
            "\n"
            "```python\n"
            "np.dot(A, B)\n"
            "```\n"
            "\n"
            "produces:\n"
            "\n"
            "```text\n"
            "[[19 22]\n"
            " [43 50]]\n"
            "```\n"
            "\n"
            "This is not element-by-element multiplication.\n"
            "\n"
            "The first result element is:\n"
            "\n"
            "```text\n"
            "1×5 + 2×7 = 19\n"
            "```\n"
            "\n"
            "The second is:\n"
            "\n"
            "```text\n"
            "1×6 + 2×8 = 22\n"
            "```\n"
            "\n"
            "The row of the first matrix combines with the column of the second.\n"
            "\n"
            "[[IMAGE_NEEDED: Matrix multiplication row by column | Two 2×2 matrices with the first row of A and first column of B highlighted, showing 1×5 + 2×7 = 19 | Learner should understand how each output cell is constructed]]\n"
            "\n"
            "---\n"
            "\n"
            "### 3.4 Transpose\n"
            "\n"
            "The transpose swaps rows and columns.\n"
            "\n"
            "```python\n"
            "A.T\n"
            "```\n"
            "\n"
            "For:\n"
            "\n"
            "```text\n"
            "[[1 2]\n"
            " [3 4]]\n"
            "```\n"
            "\n"
            "the transpose is:\n"
            "\n"
            "```text\n"
            "[[1 3]\n"
            " [2 4]]\n"
            "```\n"
            "\n"
            "Mental model:\n"
            "\n"
            "```text\n"
            "rows ↔ columns\n"
            "```\n"
            "\n"
            "Transpose operations appear throughout:\n"
            "\n"
            "- matrix decomposition,\n"
            "- least squares,\n"
            "- machine learning,\n"
            "- coordinate transformations.\n"
            "\n"
            "{{exercise:M04.L01.EX01}}\n"
            "\n"
            "---\n"
            "\n"
            "## 4. Fitting polynomials with NumPy\n"
            "\n"
            "The chapter introduces polynomial fitting as an example of numerical modeling.\n"
            "\n"
            "A polynomial can have different degrees.\n"
            "\n"
            "Examples:\n"
            "\n"
            "```text\n"
            "degree 1 → linear\n"
            "degree 2 → quadratic\n"
            "degree 3 → cubic\n"
            "degree 4 → quartic\n"
            "```\n"
            "\n"
            "A quadratic has the form:\n"
            "\n"
            "```text\n"
            "f(x) = ax² + bx + c\n"
            "```\n"
            "\n"
            "Polynomial fitting tries to choose coefficients that approximate observed data.\n"
            "\n"
            "---\n"
            "\n"
            "### 4.1 Least-squares idea\n"
            "\n"
            "The source explains polynomial fitting through the least-squares principle:\n"
            "\n"
            "> Choose coefficients that reduce the squared differences between observed and predicted values.\n"
            "\n"
            "Conceptually:\n"
            "\n"
            "```text\n"
            "actual y\n"
            "   ↕ error\n"
            "predicted y from polynomial\n"
            "```\n"
            "\n"
            "The fitting method searches for coefficients that make those errors collectively small.\n"
            "\n"
            "---\n"
            "\n"
            "### 4.2 `np.polyfit()`\n"
            "\n"
            "General pattern:\n"
            "\n"
            "```python\n"
            "np.polyfit(x, y, degree)\n"
            "```\n"
            "\n"
            "Inputs:\n"
            "\n"
            "```text\n"
            "x      → input coordinates\n"
            "y      → observed outputs\n"
            "degree → polynomial degree\n"
            "```\n"
            "\n"
            "Output:\n"
            "\n"
            "```text\n"
            "polynomial coefficients\n"
            "```\n"
            "\n"
            "Example:\n"
            "\n"
            "```python\n"
            "degree = 3\n"
            "coefs = np.polyfit(v1, v2, degree)\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "### 4.3 `np.polyval()`\n"
            "\n"
            "After fitting the coefficients:\n"
            "\n"
            "```python\n"
            "polynomial_values = np.polyval(\n"
            "    coefs,\n"
            "    sequence\n"
            ")\n"
            "```\n"
            "\n"
            "`polyval()` evaluates the fitted polynomial at supplied x-values.\n"
            "\n"
            "So the workflow is:\n"
            "\n"
            "```text\n"
            "data points\n"
            "   ↓\n"
            "polyfit()\n"
            "   ↓\n"
            "coefficients\n"
            "   ↓\n"
            "polyval()\n"
            "   ↓\n"
            "predicted curve values\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "### 4.4 `np.linspace()`\n"
            "\n"
            "The chapter uses:\n"
            "\n"
            "```python\n"
            "sequence = np.linspace(\n"
            "    v1.min(),\n"
            "    v1.max(),\n"
            "    num=200\n"
            ")\n"
            "```\n"
            "\n"
            "This creates evenly spaced points across a closed interval.\n"
            "\n"
            "Why?\n"
            "\n"
            "If we evaluated only at the original 10 x-values, a plotted curve might look coarse.\n"
            "\n"
            "A denser sequence gives a smoother visualization.\n"
            "\n"
            "---\n"
            "\n"
            "### 4.5 Complete source workflow\n"
            "\n"
            "The chapter generates two random vectors:\n"
            "\n"
            "```python\n"
            "v1 = np.random.rand(10)\n"
            "v2 = np.random.rand(10)\n"
            "```\n"
            "\n"
            "Then:\n"
            "\n"
            "```python\n"
            "sequence = np.linspace(\n"
            "    v1.min(),\n"
            "    v1.max(),\n"
            "    num=200\n"
            ")\n"
            "\n"
            "coefs = np.polyfit(v1, v2, 3)\n"
            "poly_vals = np.polyval(coefs, sequence)\n"
            "```\n"
            "\n"
            "Finally, Matplotlib plots:\n"
            "\n"
            "- original points,\n"
            "- fitted polynomial curve.\n"
            "\n"
            "[[IMAGE_NEEDED: Polynomial curve fitting | Scatter points with cubic fitted curve overlaid and labels indicating original observations versus fitted curve | Learner should see fitting as approximation rather than interpolation of every point]]\n"
            "\n"
            "---\n"
            "\n"
            "### 4.6 Underfitting and overfitting\n"
            "\n"
            "The chapter compares degrees:\n"
            "\n"
            "```text\n"
            "3\n"
            "5\n"
            "7\n"
            "```\n"
            "\n"
            "and warns that degree selection matters.\n"
            "\n"
            "#### Degree too low\n"
            "\n"
            "The curve may be too simple.\n"
            "\n"
            "This is **underfitting**.\n"
            "\n"
            "It may miss meaningful structure.\n"
            "\n"
            "#### Degree too high\n"
            "\n"
            "The curve may follow noise or random fluctuations too closely.\n"
            "\n"
            "This is **overfitting**.\n"
            "\n"
            "The key idea:\n"
            "\n"
            "```text\n"
            "too simple  ← useful complexity → too complex\n"
            "underfit                         overfit\n"
            "```\n"
            "\n"
            "The best degree is not simply “the highest one.”\n"
            "\n"
            "---\n"
            "\n"
            "## 5. Determinant and matrix rank\n"
            "\n"
            "The chapter now moves into `numpy.linalg`.\n"
            "\n"
            "---\n"
            "\n"
            "### 5.1 Determinant\n"
            "\n"
            "The determinant is a scalar computed from a square matrix.\n"
            "\n"
            "For:\n"
            "\n"
            "```text\n"
            "A = [[a, b],\n"
            "     [c, d]]\n"
            "```\n"
            "\n"
            "the 2×2 determinant is:\n"
            "\n"
            "```text\n"
            "det(A) = ad - bc\n"
            "```\n"
            "\n"
            "Source example:\n"
            "\n"
            "```python\n"
            "mat = np.mat([\n"
            "    [2, 4],\n"
            "    [5, 7]\n"
            "])\n"
            "\n"
            "det = np.linalg.det(mat)\n"
            "```\n"
            "\n"
            "Result:\n"
            "\n"
            "```text\n"
            "-6.0\n"
            "```\n"
            "\n"
            "The source connects determinant with:\n"
            "\n"
            "- image transformations,\n"
            "- scaling,\n"
            "- rotation,\n"
            "- shearing,\n"
            "- feature-related operations.\n"
            "\n"
            "Within this chapter, the most important immediate use is also determining whether a matrix can be inverted.\n"
            "\n"
            "---\n"
            "\n"
            "### 5.2 Matrix rank\n"
            "\n"
            "The rank is the number of independent rows or columns.\n"
            "\n"
            "The source connects rank with:\n"
            "\n"
            "- redundancy,\n"
            "- multicollinearity,\n"
            "- feature dependence.\n"
            "\n"
            "Example:\n"
            "\n"
            "```python\n"
            "mat = np.array([\n"
            "    [5, 3, 1],\n"
            "    [5, 3, 1],\n"
            "    [1, 0, 5]\n"
            "])\n"
            "\n"
            "np.linalg.matrix_rank(mat)\n"
            "```\n"
            "\n"
            "Output:\n"
            "\n"
            "```text\n"
            "2\n"
            "```\n"
            "\n"
            "Why not 3?\n"
            "\n"
            "The first two rows are identical.\n"
            "\n"
            "They do not contribute two independent directions.\n"
            "\n"
            "### Rank bound\n"
            "\n"
            "For an `m × n` matrix:\n"
            "\n"
            "```text\n"
            "rank(A) ≤ min(m, n)\n"
            "```\n"
            "\n"
            "The rank therefore summarizes how much independent linear information the matrix contains.\n"
            "\n"
            "[[IMAGE_NEEDED: Matrix rank and redundant rows | A 3×3 matrix where row 1 and row 2 are identical, visually bracket them as redundant, and annotate rank=2 | Learner should connect rank with independent information]]\n"
            "\n"
            "---\n"
            "\n"
            "## 6. Matrix inverse and systems of equations\n"
            "\n"
            "---\n"
            "\n"
            "### 6.1 Matrix inverse\n"
            "\n"
            "The inverse of a square matrix `A` is written:\n"
            "\n"
            "```text\n"
            "A⁻¹\n"
            "```\n"
            "\n"
            "The source requires two conditions:\n"
            "\n"
            "1. the matrix must be square,\n"
            "2. the determinant must be non-zero.\n"
            "\n"
            "The defining relationship is:\n"
            "\n"
            "```text\n"
            "A × A⁻¹ = I\n"
            "```\n"
            "\n"
            "where `I` is the identity matrix.\n"
            "\n"
            "For a 2×2 matrix:\n"
            "\n"
            "```text\n"
            "A = [[a, b],\n"
            "     [c, d]]\n"
            "```\n"
            "\n"
            "the inverse is based on:\n"
            "\n"
            "```text\n"
            "1 / (ad - bc)\n"
            "```\n"
            "\n"
            "so a zero determinant would make the inverse invalid.\n"
            "\n"
            "NumPy:\n"
            "\n"
            "```python\n"
            "inverse = np.linalg.inv(mat)\n"
            "```\n"
            "\n"
            "The source example:\n"
            "\n"
            "```python\n"
            "mat = np.mat([\n"
            "    [2, 4],\n"
            "    [5, 7]\n"
            "])\n"
            "```\n"
            "\n"
            "gives approximately:\n"
            "\n"
            "```text\n"
            "[[-1.17  0.67]\n"
            " [ 0.83 -0.33]]\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "### 6.2 Singular/non-square matrices\n"
            "\n"
            "The chapter notes that invalid matrices can raise:\n"
            "\n"
            "```text\n"
            "LinAlgError\n"
            "```\n"
            "\n"
            "Examples include:\n"
            "\n"
            "- non-square matrix for an operation requiring a square matrix,\n"
            "- singular matrix for inversion.\n"
            "\n"
            "The important idea:\n"
            "\n"
            "> Mathematical preconditions matter; a library call cannot make an undefined inverse exist.\n"
            "\n"
            "---\n"
            "\n"
            "### 6.3 Solving linear systems\n"
            "\n"
            "The chapter represents a system as:\n"
            "\n"
            "```text\n"
            "Ax = B\n"
            "```\n"
            "\n"
            "where:\n"
            "\n"
            "```text\n"
            "A → coefficient matrix\n"
            "x → unknown vector\n"
            "B → result vector\n"
            "```\n"
            "\n"
            "Source equations:\n"
            "\n"
            "```text\n"
            "x₁ + x₂ = 200\n"
            "3x₁ + 2x₂ = 450\n"
            "```\n"
            "\n"
            "Convert to:\n"
            "\n"
            "```python\n"
            "A = np.mat([\n"
            "    [1, 1],\n"
            "    [3, 2]\n"
            "])\n"
            "\n"
            "B = np.array([200, 450])\n"
            "```\n"
            "\n"
            "Solve:\n"
            "\n"
            "```python\n"
            "solution = np.linalg.solve(A, B)\n"
            "```\n"
            "\n"
            "Output:\n"
            "\n"
            "```text\n"
            "[50. 150.]\n"
            "```\n"
            "\n"
            "So:\n"
            "\n"
            "```text\n"
            "x₁ = 50\n"
            "x₂ = 150\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "### 6.4 Verifying the solution\n"
            "\n"
            "The chapter checks:\n"
            "\n"
            "```python\n"
            "np.dot(A, solution)\n"
            "```\n"
            "\n"
            "and gets:\n"
            "\n"
            "```text\n"
            "[[200. 450.]]\n"
            "```\n"
            "\n"
            "which reproduces `B`.\n"
            "\n"
            "This is an excellent numerical habit:\n"
            "\n"
            "```text\n"
            "solve\n"
            "  ↓\n"
            "substitute / recompute\n"
            "  ↓\n"
            "verify\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "## 7. Eigenvalues and eigenvectors\n"
            "\n"
            "Eigenvectors and eigenvalues describe special directions under a linear transformation.\n"
            "\n"
            "The source relationship is:\n"
            "\n"
            "```text\n"
            "A v = λ v\n"
            "```\n"
            "\n"
            "where:\n"
            "\n"
            "```text\n"
            "A → square matrix / transformation\n"
            "v → non-zero eigenvector\n"
            "λ → eigenvalue\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "### 7.1 Eigenvector intuition\n"
            "\n"
            "An eigenvector changes in magnitude under the transformation but not in direction according to the chapter's simplified geometric description.\n"
            "\n"
            "If a transformation stretches an eigenvector:\n"
            "\n"
            "```text\n"
            "v → 3v\n"
            "```\n"
            "\n"
            "then:\n"
            "\n"
            "```text\n"
            "λ = 3\n"
            "```\n"
            "\n"
            "If it reverses direction and scales:\n"
            "\n"
            "```text\n"
            "v → -2v\n"
            "```\n"
            "\n"
            "then:\n"
            "\n"
            "```text\n"
            "λ = -2\n"
            "```\n"
            "\n"
            "The eigenvalue captures the scaling behavior.\n"
            "\n"
            "[[IMAGE_NEEDED: Eigenvector transformation intuition | Show a transformation applied to several vectors where one special vector stays on the same line but changes length; label it eigenvector v and scaling λ | Learner should understand “direction preserved, magnitude scaled”]]\n"
            "\n"
            "---\n"
            "\n"
            "### 7.2 Why eigen analysis matters\n"
            "\n"
            "The chapter connects eigen methods to:\n"
            "\n"
            "- PCA,\n"
            "- SVD,\n"
            "- spectral clustering,\n"
            "- image transformation.\n"
            "\n"
            "The learning goal here is not yet to derive PCA.\n"
            "\n"
            "It is to recognize that eigen analysis identifies mathematically important directions in transformations.\n"
            "\n"
            "---\n"
            "\n"
            "### 7.3 NumPy functions\n"
            "\n"
            "The chapter introduces:\n"
            "\n"
            "```python\n"
            "np.linalg.eig(A)\n"
            "```\n"
            "\n"
            "which returns:\n"
            "\n"
            "```text\n"
            "eigenvalues\n"
            "eigenvectors\n"
            "```\n"
            "\n"
            "and:\n"
            "\n"
            "```python\n"
            "np.linalg.eigvals(A)\n"
            "```\n"
            "\n"
            "which returns only eigenvalues.\n"
            "\n"
            "### Source-code note\n"
            "\n"
            "The supplied chapter first creates a matrix named `mat` but later calls:\n"
            "\n"
            "```python\n"
            "np.linalg.eig(A)\n"
            "```\n"
            "\n"
            "and:\n"
            "\n"
            "```python\n"
            "np.linalg.eigvals(A)\n"
            "```\n"
            "\n"
            "without re-establishing `A` in that exact subsection. Treat the example as illustrating the functions and outputs, but note that the variable naming is inconsistent in the supplied source.\n"
            "\n"
            "---\n"
            "\n"
            "## 8. Matrix decomposition\n"
            "\n"
            "Matrix decomposition breaks one complex matrix into simpler component matrices.\n"
            "\n"
            "The source introduces:\n"
            "\n"
            "- SVD,\n"
            "- LU,\n"
            "- QR,\n"
            "- Cholesky by name.\n"
            "\n"
            "It gives worked examples for:\n"
            "\n"
            "- SVD,\n"
            "- LU,\n"
            "- QR.\n"
            "\n"
            "This lesson does not invent a Cholesky walkthrough because the supplied chapter does not provide one.\n"
            "\n"
            "---\n"
            "\n"
            "### 8.1 Why decompose matrices?\n"
            "\n"
            "The chapter connects decomposition with:\n"
            "\n"
            "- solving systems,\n"
            "- dimensionality reduction,\n"
            "- latent semantic analysis,\n"
            "- recommendation systems,\n"
            "- numerical stability,\n"
            "- scientific computation.\n"
            "\n"
            "Mental model:\n"
            "\n"
            "```text\n"
            "complex matrix A\n"
            "        ↓ factorization\n"
            "simpler structured matrices\n"
            "        ↓\n"
            "easier computation / interpretation\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "## 9. Singular Value Decomposition (SVD)\n"
            "\n"
            "The source presents:\n"
            "\n"
            "```text\n"
            "A = U Σ Vᵀ\n"
            "```\n"
            "\n"
            "The components are:\n"
            "\n"
            "```text\n"
            "U  → left singular vectors\n"
            "Σ  → singular values\n"
            "Vᵀ → transpose of right singular-vector matrix\n"
            "```\n"
            "\n"
            "The chapter links SVD with:\n"
            "\n"
            "- signal processing,\n"
            "- climate,\n"
            "- astronomy,\n"
            "- computer vision,\n"
            "- NLP,\n"
            "- machine learning,\n"
            "- recommendation systems,\n"
            "- dimensionality reduction.\n"
            "\n"
            "---\n"
            "\n"
            "### 9.1 SciPy example\n"
            "\n"
            "```python\n"
            "from scipy.linalg import svd\n"
            "\n"
            "mat = np.array([\n"
            "    [5, 3, 1],\n"
            "    [5, 3, 0],\n"
            "    [1, 0, 5]\n"
            "])\n"
            "\n"
            "U, Sigma, V_transpose = svd(mat)\n"
            "```\n"
            "\n"
            "The source shows:\n"
            "\n"
            "- a left singular matrix,\n"
            "- singular values,\n"
            "- a right singular matrix.\n"
            "\n"
            "A useful interpretation is:\n"
            "\n"
            "> SVD describes the original matrix using structured directions and corresponding strengths.\n"
            "\n"
            "The lesson does not add a full dimensionality-reduction derivation because the chapter only introduces the decomposition and its applications.\n"
            "\n"
            "[[IMAGE_NEEDED: SVD decomposition | Show matrix A splitting into U × Sigma × V-transpose, with Sigma highlighted as diagonal singular strengths | Learner should remember the three-factor structure]]\n"
            "\n"
            "---\n"
            "\n"
            "## 10. LU and QR decomposition\n"
            "\n"
            "---\n"
            "\n"
            "### 10.1 LU decomposition\n"
            "\n"
            "LU means:\n"
            "\n"
            "```text\n"
            "Lower–Upper\n"
            "```\n"
            "\n"
            "The chapter presents:\n"
            "\n"
            "```text\n"
            "A = L U\n"
            "```\n"
            "\n"
            "while SciPy's practical output also includes a permutation matrix:\n"
            "\n"
            "```python\n"
            "P, L, U = lu(A)\n"
            "```\n"
            "\n"
            "The components:\n"
            "\n"
            "```text\n"
            "P → permutation matrix\n"
            "L → lower triangular matrix\n"
            "U → upper triangular matrix\n"
            "```\n"
            "\n"
            "A lower triangular matrix has zeros above its diagonal.\n"
            "\n"
            "An upper triangular matrix has zeros below its diagonal.\n"
            "\n"
            "The source links LU with:\n"
            "\n"
            "- solving linear equations,\n"
            "- determinants,\n"
            "- matrix inverses,\n"
            "- efficient numerical computation.\n"
            "\n"
            "---\n"
            "\n"
            "### 10.2 Source example\n"
            "\n"
            "```python\n"
            "A = np.array([\n"
            "    [1, 3, 4],\n"
            "    [5, 6, 9],\n"
            "    [1, 2, 3]\n"
            "])\n"
            "\n"
            "P, L, U = lu(A)\n"
            "```\n"
            "\n"
            "The returned matrices expose a structured factorization of `A`.\n"
            "\n"
            "---\n"
            "\n"
            "### 10.3 QR decomposition\n"
            "\n"
            "QR factorizes:\n"
            "\n"
            "```text\n"
            "A = Q R\n"
            "```\n"
            "\n"
            "where:\n"
            "\n"
            "```text\n"
            "Q → orthogonal matrix\n"
            "R → upper triangular matrix\n"
            "```\n"
            "\n"
            "The chapter states that QR:\n"
            "\n"
            "- is not restricted to square matrices like the LU framing in the chapter,\n"
            "- is useful in least squares,\n"
            "- supports linear-system solving,\n"
            "- supports eigenvalue computation,\n"
            "- is numerically stable in scientific computation.\n"
            "\n"
            "---\n"
            "\n"
            "### 10.4 NumPy example\n"
            "\n"
            "```python\n"
            "Q, R = np.linalg.qr(A)\n"
            "```\n"
            "\n"
            "The chapter verifies the decomposition by reconstructing:\n"
            "\n"
            "```python\n"
            "A_original = Q @ R\n"
            "```\n"
            "\n"
            "If the decomposition is correct:\n"
            "\n"
            "```text\n"
            "Q @ R ≈ A\n"
            "```\n"
            "\n"
            "This is the same verification mindset used earlier with linear systems.\n"
            "\n"
            "---\n"
            "\n"
            "### 10.5 Decomposition comparison\n"
            "\n"
            "| Decomposition | Chapter structure | Key use ideas |\n"
            "|---|---|---|\n"
            "| SVD | `A = UΣVᵀ` | dimensionality reduction, NLP, recommendations |\n"
            "| LU | lower + upper triangular components | efficient solving, determinants, inverses |\n"
            "| QR | orthogonal `Q` + upper triangular `R` | least squares, systems, eigen computations |\n"
            "\n"
            "{{exercise:M04.L01.EX02}}\n"
            "\n"
            "---\n"
            "\n"
            "## 11. Probability distributions: PMF, PDF, and CDF\n"
            "\n"
            "The chapter then shifts from linear algebra into probability distributions.\n"
            "\n"
            "A probability distribution describes how possible values of a random variable are distributed.\n"
            "\n"
            "The source introduces three important functions:\n"
            "\n"
            "```text\n"
            "PMF\n"
            "PDF\n"
            "CDF\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "### 11.1 Random variable\n"
            "\n"
            "A random variable receives its value from a random process.\n"
            "\n"
            "Examples:\n"
            "\n"
            "```text\n"
            "coin toss outcome\n"
            "dice result\n"
            "number of calls in an hour\n"
            "waiting time between events\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "### 11.2 PMF\n"
            "\n"
            "**Probability Mass Function** applies to discrete random variables.\n"
            "\n"
            "It assigns probability to countable outcomes.\n"
            "\n"
            "Example:\n"
            "\n"
            "```text\n"
            "coin:\n"
            "P(head) = 0.5\n"
            "P(tail) = 0.5\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "### 11.3 PDF\n"
            "\n"
            "**Probability Density Function** describes continuous distributions.\n"
            "\n"
            "The chapter explains it as representing how likelihood is distributed across a continuous range.\n"
            "\n"
            "Important intuition:\n"
            "\n"
            "> For a continuous variable, probability is associated with intervals/areas rather than treating one exact point like a discrete PMF outcome.\n"
            "\n"
            "---\n"
            "\n"
            "### 11.4 CDF\n"
            "\n"
            "**Cumulative Distribution Function** gives cumulative probability up to a value.\n"
            "\n"
            "Conceptually:\n"
            "\n"
            "```text\n"
            "CDF(x) = P(X ≤ x)\n"
            "```\n"
            "\n"
            "The source states its value ranges from:\n"
            "\n"
            "```text\n"
            "0 to 1\n"
            "```\n"
            "\n"
            "and grows as `x` moves through the distribution.\n"
            "\n"
            "[[IMAGE_NEEDED: PMF PDF CDF comparison | Discrete bars for PMF, continuous bell-shaped density for PDF, and cumulative rising curve from 0 to 1 for CDF | Learner should distinguish probability mass, density, and cumulative probability]]\n"
            "\n"
            "---\n"
            "\n"
            "## 12. Discrete probability distributions\n"
            "\n"
            "The chapter covers:\n"
            "\n"
            "- Bernoulli,\n"
            "- Binomial,\n"
            "- Poisson,\n"
            "- Geometric.\n"
            "\n"
            "---\n"
            "\n"
            "### 12.1 Bernoulli distribution\n"
            "\n"
            "Bernoulli represents one experiment with two outcomes:\n"
            "\n"
            "```text\n"
            "success\n"
            "failure\n"
            "```\n"
            "\n"
            "Common coding representation:\n"
            "\n"
            "```text\n"
            "1 → success\n"
            "0 → failure\n"
            "```\n"
            "\n"
            "The source examples include:\n"
            "\n"
            "- coin toss,\n"
            "- match result,\n"
            "- exam result,\n"
            "- whether an LED bulb works.\n"
            "\n"
            "Probability structure:\n"
            "\n"
            "```text\n"
            "P(X=1) = p\n"
            "P(X=0) = 1-p\n"
            "```\n"
            "\n"
            "SciPy:\n"
            "\n"
            "```python\n"
            "from scipy.stats import bernoulli\n"
            "\n"
            "data = bernoulli.rvs(\n"
            "    size=1000,\n"
            "    p=0.8\n"
            ")\n"
            "```\n"
            "\n"
            "The generated data contains only:\n"
            "\n"
            "```text\n"
            "0\n"
            "1\n"
            "```\n"
            "\n"
            "[[IMAGE_NEEDED: Bernoulli distribution | Two bars at 0 and 1 with probabilities 1-p and p | Learner should connect Bernoulli with a single binary trial]]\n"
            "\n"
            "---\n"
            "\n"
            "### 12.2 Binomial distribution\n"
            "\n"
            "Binomial models the number of successes across multiple independent Bernoulli trials.\n"
            "\n"
            "Examples in the source:\n"
            "\n"
            "- heads in repeated coin tosses,\n"
            "- number of spam emails,\n"
            "- fraudulent transactions,\n"
            "- successful basketball free throws.\n"
            "\n"
            "Parameters:\n"
            "\n"
            "```text\n"
            "n → number of trials\n"
            "p → probability of success\n"
            "k → number of successes\n"
            "```\n"
            "\n"
            "SciPy:\n"
            "\n"
            "```python\n"
            "from scipy.stats import binom\n"
            "\n"
            "data = binom.rvs(\n"
            "    n=20,\n"
            "    p=0.7,\n"
            "    size=10000\n"
            ")\n"
            "```\n"
            "\n"
            "Difference from Bernoulli:\n"
            "\n"
            "```text\n"
            "Bernoulli\n"
            "→ one binary trial\n"
            "\n"
            "Binomial\n"
            "→ number of successes across n trials\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "### 12.3 Binomial simulation: gambling game\n"
            "\n"
            "The chapter models a game with:\n"
            "\n"
            "```text\n"
            "9 fair coins\n"
            "win if heads ≥ 5\n"
            "lose otherwise\n"
            "```\n"
            "\n"
            "Generate:\n"
            "\n"
            "```python\n"
            "samples = np.random.binomial(\n"
            "    9,\n"
            "    0.5,\n"
            "    size=len(cash_balance)\n"
            ")\n"
            "```\n"
            "\n"
            "Then update money:\n"
            "\n"
            "```text\n"
            "success threshold met → +1\n"
            "otherwise             → -1\n"
            "```\n"
            "\n"
            "This demonstrates that a probability distribution can drive a simulation over time.\n"
            "\n"
            "---\n"
            "\n"
            "### 12.4 Poisson distribution\n"
            "\n"
            "Poisson models event counts within an interval.\n"
            "\n"
            "Examples:\n"
            "\n"
            "- calls per hour,\n"
            "- store arrivals,\n"
            "- website visitors per hour,\n"
            "- radioactive decay events.\n"
            "\n"
            "Parameter:\n"
            "\n"
            "```text\n"
            "λ → average event rate\n"
            "```\n"
            "\n"
            "SciPy:\n"
            "\n"
            "```python\n"
            "from scipy.stats import poisson\n"
            "\n"
            "data = poisson.rvs(\n"
            "    mu=7,\n"
            "    size=1000\n"
            ")\n"
            "```\n"
            "\n"
            "Mental model:\n"
            "\n"
            "> “How many events occur in the interval?”\n"
            "\n"
            "---\n"
            "\n"
            "### 12.5 Geometric distribution\n"
            "\n"
            "The geometric distribution models the number of Bernoulli trials needed until the first success.\n"
            "\n"
            "Examples:\n"
            "\n"
            "```text\n"
            "coin flips until first head\n"
            "weeks until first network failure\n"
            "```\n"
            "\n"
            "Parameters:\n"
            "\n"
            "```text\n"
            "p → success probability\n"
            "k → trial where first success occurs\n"
            "```\n"
            "\n"
            "SciPy:\n"
            "\n"
            "```python\n"
            "from scipy.stats import geom\n"
            "\n"
            "data = geom.rvs(\n"
            "    0.6,\n"
            "    size=1000\n"
            ")\n"
            "```\n"
            "\n"
            "Mental model:\n"
            "\n"
            "> “How long do I wait in repeated trials until success first occurs?”\n"
            "\n"
            "---\n"
            "\n"
            "### 12.6 Discrete-distribution comparison\n"
            "\n"
            "| Distribution | Question |\n"
            "|---|---|\n"
            "| Bernoulli | Did one binary trial succeed? |\n"
            "| Binomial | How many successes in `n` trials? |\n"
            "| Poisson | How many events occur in an interval? |\n"
            "| Geometric | On which trial does the first success occur? |\n"
            "\n"
            "---\n"
            "\n"
            "## 13. Continuous probability distributions\n"
            "\n"
            "The chapter covers:\n"
            "\n"
            "- Uniform,\n"
            "- Normal,\n"
            "- Log-normal,\n"
            "- Exponential.\n"
            "\n"
            "---\n"
            "\n"
            "### 13.1 Uniform distribution\n"
            "\n"
            "Uniform means values across a specified range are equally likely in the chapter's continuous example.\n"
            "\n"
            "Parameters are described through lower/upper range concepts.\n"
            "\n"
            "SciPy:\n"
            "\n"
            "```python\n"
            "from scipy.stats import uniform\n"
            "\n"
            "data = uniform.rvs(\n"
            "    size=10000,\n"
            "    loc=5,\n"
            "    scale=10\n"
            ")\n"
            "```\n"
            "\n"
            "The chapter visualizes the resulting distribution as approximately rectangular.\n"
            "\n"
            "Mental model:\n"
            "\n"
            "```text\n"
            "no region of the interval is preferred\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "### 13.2 Normal distribution\n"
            "\n"
            "Normal/Gaussian distribution is symmetric around the mean.\n"
            "\n"
            "The source associates it with examples such as:\n"
            "\n"
            "- adult heights,\n"
            "- test scores,\n"
            "- IQ scores,\n"
            "- birthweight,\n"
            "- blood pressure,\n"
            "- shoe size.\n"
            "\n"
            "Parameters:\n"
            "\n"
            "```text\n"
            "μ → mean\n"
            "σ → standard deviation\n"
            "σ² → variance\n"
            "```\n"
            "\n"
            "For a normal distribution, the chapter states:\n"
            "\n"
            "```text\n"
            "mean = median = mode\n"
            "```\n"
            "\n"
            "A **standard normal distribution** uses:\n"
            "\n"
            "```text\n"
            "μ = 0\n"
            "σ = 1\n"
            "```\n"
            "\n"
            "NumPy:\n"
            "\n"
            "```python\n"
            "data = np.random.normal(\n"
            "    mean,\n"
            "    std_dev,\n"
            "    size\n"
            ")\n"
            "```\n"
            "\n"
            "The chapter visualizes it as a bell-shaped histogram.\n"
            "\n"
            "[[IMAGE_NEEDED: Normal distribution anatomy | Bell curve centered at mean μ, showing symmetry and standard-deviation distances on both sides | Learner should associate the normal distribution with symmetry around μ]]\n"
            "\n"
            "---\n"
            "\n"
            "### 13.3 Log-normal distribution\n"
            "\n"
            "A variable is log-normally distributed when its logarithm is normally distributed, according to the source.\n"
            "\n"
            "The chapter connects it with multiplicative growth and examples such as:\n"
            "\n"
            "- stock prices,\n"
            "- tumor sizes,\n"
            "- income distributions.\n"
            "\n"
            "NumPy:\n"
            "\n"
            "```python\n"
            "data = np.random.lognormal(\n"
            "    mean,\n"
            "    std_dev,\n"
            "    size\n"
            ")\n"
            "```\n"
            "\n"
            "The chapter emphasizes its positive/right skew.\n"
            "\n"
            "It also demonstrates SciPy's:\n"
            "\n"
            "```python\n"
            "lognorm.pdf(...)\n"
            "```\n"
            "\n"
            "with different shape parameter `s` values to show changing skew/spread.\n"
            "\n"
            "---\n"
            "\n"
            "### 13.4 Exponential distribution\n"
            "\n"
            "The exponential distribution models waiting time between events in a Poisson process.\n"
            "\n"
            "Examples:\n"
            "\n"
            "- time between calls,\n"
            "- time between radioactive decays,\n"
            "- time between earthquakes.\n"
            "\n"
            "Parameter:\n"
            "\n"
            "```text\n"
            "λ → rate\n"
            "```\n"
            "\n"
            "SciPy example:\n"
            "\n"
            "```python\n"
            "from scipy.stats import expon\n"
            "\n"
            "data_expon = expon.rvs(\n"
            "    scale=20,\n"
            "    loc=0,\n"
            "    size=10000\n"
            ")\n"
            "```\n"
            "\n"
            "The chapter's visualization is right-skewed.\n"
            "\n"
            "Mental model:\n"
            "\n"
            "> Poisson often asks “how many events in an interval?” while Exponential asks “how much time between events?”\n"
            "\n"
            "---\n"
            "\n"
            "### 13.5 Continuous-distribution comparison\n"
            "\n"
            "| Distribution | Chapter intuition |\n"
            "|---|---|\n"
            "| Uniform | all values in a range equally likely |\n"
            "| Normal | symmetric bell-shaped distribution |\n"
            "| Log-normal | positive/skewed multiplicative-type behavior |\n"
            "| Exponential | waiting time between events |\n"
            "\n"
            "{{exercise:M04.L01.EX03}}\n"
            "\n"
            "---\n"
            "\n"
            "## 14. Generating random numbers\n"
            "\n"
            "The chapter discusses random numbers in contexts such as:\n"
            "\n"
            "- sampling,\n"
            "- surveys,\n"
            "- Monte Carlo simulation,\n"
            "- gaming,\n"
            "- cryptography,\n"
            "- machine learning,\n"
            "- stochastic processes.\n"
            "\n"
            "It also notes that most software uses **pseudo-random** number generation.\n"
            "\n"
            "The source mentions the Mersenne Twister algorithm in this context.\n"
            "\n"
            "---\n"
            "\n"
            "### 14.1 NumPy random matrix\n"
            "\n"
            "Example:\n"
            "\n"
            "```python\n"
            "random_matrix = np.random.random(\n"
            "    (3, 3)\n"
            ")\n"
            "```\n"
            "\n"
            "This produces a 3×3 matrix of random floating-point values.\n"
            "\n"
            "The chapter connects random-number generation with probability distributions:\n"
            "\n"
            "```text\n"
            "Uniform\n"
            "Normal\n"
            "Binomial\n"
            "...\n"
            "```\n"
            "\n"
            "So random generation is not only:\n"
            "\n"
            "```text\n"
            "“give me arbitrary numbers”\n"
            "```\n"
            "\n"
            "It is often:\n"
            "\n"
            "```text\n"
            "“sample values according to a chosen distribution”\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "## 15. Visual normality assessment\n"
            "\n"
            "The chapter next tests whether sample data appears normally distributed.\n"
            "\n"
            "It generates three samples:\n"
            "\n"
            "```python\n"
            "small_sample = np.random.normal(\n"
            "    loc=100,\n"
            "    scale=60,\n"
            "    size=15\n"
            ")\n"
            "\n"
            "medium_sample = np.random.normal(\n"
            "    loc=100,\n"
            "    scale=60,\n"
            "    size=100\n"
            ")\n"
            "\n"
            "large_sample = np.random.normal(\n"
            "    loc=100,\n"
            "    scale=60,\n"
            "    size=1000\n"
            ")\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "### 15.1 Histogram\n"
            "\n"
            "A histogram:\n"
            "\n"
            "- divides values into bins,\n"
            "- counts observations in each bin,\n"
            "- shows the distribution shape.\n"
            "\n"
            "The chapter uses:\n"
            "\n"
            "```python\n"
            "sns.histplot(\n"
            "    data=small_sample,\n"
            "    kde=True\n"
            ")\n"
            "```\n"
            "\n"
            "and repeats it for medium and large samples.\n"
            "\n"
            "The source reports that larger generated samples look more bell-shaped visually.\n"
            "\n"
            "### Important source-framing note\n"
            "\n"
            "The samples are generated directly from a normal distribution. Therefore, the visual demonstration is illustrating how empirical histograms from the same distribution can look unstable when sample size is small and smoother with larger samples.\n"
            "\n"
            "This should not be interpreted as proving that arbitrary raw data becomes normal merely because you collect more observations.\n"
            "\n"
            "[[IMAGE_NEEDED: Sample-size effect on normal histogram | Three histograms labeled n=15, n=100, n=1000 generated from the same normal distribution; small looks irregular, large looks smooth and bell-shaped | Learner should see sampling variability in histogram shape]]\n"
            "\n"
            "---\n"
            "\n"
            "## 16. Shapiro–Wilk normality test\n"
            "\n"
            "The chapter states:\n"
            "\n"
            "```text\n"
            "H₀: sample follows a normal distribution\n"
            "H₁: sample does not follow a normal distribution\n"
            "```\n"
            "\n"
            "Decision rule used:\n"
            "\n"
            "```text\n"
            "p > 0.05 → fail to reject H₀\n"
            "p < 0.05 → reject H₀\n"
            "```\n"
            "\n"
            "SciPy:\n"
            "\n"
            "```python\n"
            "from scipy.stats import shapiro\n"
            "\n"
            "shapiro(small_sample)\n"
            "shapiro(medium_sample)\n"
            "shapiro(large_sample)\n"
            "```\n"
            "\n"
            "Source p-values:\n"
            "\n"
            "```text\n"
            "small  ≈ 0.6608\n"
            "medium ≈ 0.9043\n"
            "large  ≈ 0.7929\n"
            "```\n"
            "\n"
            "All are above:\n"
            "\n"
            "```text\n"
            "0.05\n"
            "```\n"
            "\n"
            "so the source concludes:\n"
            "\n"
            "```text\n"
            "fail to reject H₀\n"
            "```\n"
            "\n"
            "for all three samples.\n"
            "\n"
            "Remember the wording:\n"
            "\n"
            "> Fail to reject normality does not mathematically prove that the population is normal; it means this test did not produce enough evidence against the normality null at the chosen threshold.\n"
            "\n"
            "---\n"
            "\n"
            "## 17. Anderson–Darling and D’Agostino–Pearson tests\n"
            "\n"
            "---\n"
            "\n"
            "### 17.1 Anderson–Darling\n"
            "\n"
            "The source describes Anderson–Darling as a normality test that pays particular attention to deviations in distribution tails.\n"
            "\n"
            "SciPy:\n"
            "\n"
            "```python\n"
            "from scipy.stats import anderson\n"
            "\n"
            "anderson(small_sample)\n"
            "anderson(medium_sample)\n"
            "anderson(large_sample)\n"
            "```\n"
            "\n"
            "Unlike a simple p-value comparison in the chapter's Shapiro section, the output includes:\n"
            "\n"
            "- test statistic,\n"
            "- critical values,\n"
            "- significance levels.\n"
            "\n"
            "The chapter interprets the statistic relative to the critical value at the desired significance level.\n"
            "\n"
            "For the supplied examples, the source says all three statistics are below the 5% critical values, so it does not reject normality.\n"
            "\n"
            "---\n"
            "\n"
            "### 17.2 D’Agostino–Pearson\n"
            "\n"
            "The source says this test combines information from:\n"
            "\n"
            "- skewness,\n"
            "- kurtosis.\n"
            "\n"
            "SciPy:\n"
            "\n"
            "```python\n"
            "from scipy.stats import normaltest\n"
            "\n"
            "normaltest(small_sample)\n"
            "normaltest(medium_sample)\n"
            "normaltest(large_sample)\n"
            "```\n"
            "\n"
            "Source p-values:\n"
            "\n"
            "```text\n"
            "small  ≈ 0.3964\n"
            "medium ≈ 0.8303\n"
            "large  ≈ 0.0449\n"
            "```\n"
            "\n"
            "Using the chapter's threshold:\n"
            "\n"
            "```text\n"
            "α = 0.05\n"
            "```\n"
            "\n"
            "decisions:\n"
            "\n"
            "```text\n"
            "small  → fail to reject H₀\n"
            "medium → fail to reject H₀\n"
            "large  → reject H₀\n"
            "```\n"
            "\n"
            "This is useful because it shows that different tests can produce different outcomes on finite random samples, even when data was generated by `np.random.normal()`.\n"
            "\n"
            "The chapter notes that visual tools such as box plots and QQ plots can also help assess normality, but it does not develop those methods here.\n"
            "\n"
            "---\n"
            "\n"
            "### 17.3 Comparing the normality approaches\n"
            "\n"
            "| Approach | Main idea in chapter |\n"
            "|---|---|\n"
            "| Histogram + KDE | visual shape inspection |\n"
            "| Shapiro–Wilk | statistic + p-value |\n"
            "| Anderson–Darling | statistic compared with critical values |\n"
            "| D’Agostino–Pearson | skewness + kurtosis based normality test |\n"
            "\n"
            "{{exercise:M04.L01.EX04}}\n"
            "\n"
            "---\n"
            "\n"
            "## 18. Masked arrays and image processing\n"
            "\n"
            "The final technical section uses NumPy masked arrays with an image.\n"
            "\n"
            "The source emphasizes that images are numerical arrays of pixels.\n"
            "\n"
            "A mask can mark selected elements so later computations treat them differently.\n"
            "\n"
            "---\n"
            "\n"
            "### 18.1 Load an image\n"
            "\n"
            "The chapter uses:\n"
            "\n"
            "```python\n"
            "from skimage.data import astronaut\n"
            "from skimage.util import img_as_float\n"
            "\n"
            "face_image = img_as_float(\n"
            "    astronaut()\n"
            ")\n"
            "```\n"
            "\n"
            "The image becomes a floating-point array.\n"
            "\n"
            "---\n"
            "\n"
            "### 18.2 Create a Boolean mask\n"
            "\n"
            "```python\n"
            "mask_random_array = np.random.randint(\n"
            "    0,\n"
            "    2,\n"
            "    size=face_image.shape,\n"
            "    dtype=bool\n"
            ")\n"
            "```\n"
            "\n"
            "The mask has the same shape as the image.\n"
            "\n"
            "Conceptually:\n"
            "\n"
            "```text\n"
            "False → unmasked\n"
            "True  → masked\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "### 18.3 Create a masked array\n"
            "\n"
            "```python\n"
            "masked_image = np.ma.array(\n"
            "    face_image,\n"
            "    mask=mask_random_array\n"
            ")\n"
            "```\n"
            "\n"
            "Now the image data and masking information are combined in a NumPy masked array.\n"
            "\n"
            "---\n"
            "\n"
            "### 18.4 Apply a log transform\n"
            "\n"
            "The source applies:\n"
            "\n"
            "```python\n"
            "log_original = np.log1p(\n"
            "    face_image\n"
            ")\n"
            "\n"
            "log_masked = np.log1p(\n"
            "    masked_image\n"
            ")\n"
            "```\n"
            "\n"
            "Then it visualizes:\n"
            "\n"
            "1. original image,\n"
            "2. masked image,\n"
            "3. log transform of original,\n"
            "4. log transform of masked image.\n"
            "\n"
            "The teaching point is:\n"
            "\n"
            "> Matrix/array operations can still be performed while selected values remain masked.\n"
            "\n"
            "[[IMAGE_NEEDED: Masked image array comparison | Four-panel layout: original image, randomly masked image, log-transformed original, log-transformed masked image | Learner should see masking as metadata controlling which array elements participate normally in operations]]\n"
            "\n"
            "---\n"
            "\n"
            "## 19. How the chapter fits together\n"
            "\n"
            "At first, the chapter may feel like two separate subjects:\n"
            "\n"
            "```text\n"
            "linear algebra\n"
            "+\n"
            "probability/statistical distributions\n"
            "```\n"
            "\n"
            "But the source connects them through scientific computing.\n"
            "\n"
            "NumPy and SciPy provide numerical structures and functions for both.\n"
            "\n"
            "A useful conceptual flow is:\n"
            "\n"
            "```text\n"
            "Represent data\n"
            "vectors / matrices / tensors\n"
            "        ↓\n"
            "Transform data\n"
            "dot products / matrix multiplication / transpose\n"
            "        ↓\n"
            "Solve numerical problems\n"
            "determinant / rank / inverse / Ax=B\n"
            "        ↓\n"
            "Reveal structure\n"
            "eigenvectors / SVD / LU / QR\n"
            "        ↓\n"
            "Model uncertainty\n"
            "probability distributions\n"
            "        ↓\n"
            "Simulate\n"
            "random numbers\n"
            "        ↓\n"
            "Assess assumptions\n"
            "normality tests\n"
            "        ↓\n"
            "Apply array logic to rich data\n"
            "masked image arrays\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "## Important misconceptions\n"
            "\n"
            "### Misconception 1\n"
            "\n"
            "> “A matrix is just a table, so matrix multiplication must multiply corresponding cells.”\n"
            "\n"
            "Matrix multiplication combines rows and columns.\n"
            "\n"
            "Element-wise multiplication is a different operation.\n"
            "\n"
            "---\n"
            "\n"
            "### Misconception 2\n"
            "\n"
            "> “A scalar, vector, matrix, and tensor are completely unrelated structures.”\n"
            "\n"
            "The chapter presents them as a dimensional hierarchy of numerical structures.\n"
            "\n"
            "---\n"
            "\n"
            "### Misconception 3\n"
            "\n"
            "> “A higher polynomial degree always fits data better in a useful way.”\n"
            "\n"
            "A high degree can overfit noise.\n"
            "\n"
            "The chapter explicitly contrasts overfitting with underfitting.\n"
            "\n"
            "---\n"
            "\n"
            "### Misconception 4\n"
            "\n"
            "> “Every square matrix has an inverse.”\n"
            "\n"
            "The chapter requires:\n"
            "\n"
            "```text\n"
            "determinant ≠ 0\n"
            "```\n"
            "\n"
            "as well as square shape.\n"
            "\n"
            "---\n"
            "\n"
            "### Misconception 5\n"
            "\n"
            "> “Rank is simply the number of rows.”\n"
            "\n"
            "Rank counts independent rows or columns.\n"
            "\n"
            "Repeated/dependent rows can reduce rank.\n"
            "\n"
            "---\n"
            "\n"
            "### Misconception 6\n"
            "\n"
            "> “Eigenvectors are arbitrary vectors.”\n"
            "\n"
            "An eigenvector is special because the transformation preserves its direction in the chapter's geometric interpretation while scaling it by an eigenvalue.\n"
            "\n"
            "---\n"
            "\n"
            "### Misconception 7\n"
            "\n"
            "> “SVD, LU, and QR are different names for the same factorization.”\n"
            "\n"
            "They decompose matrices into different structured components for different numerical purposes.\n"
            "\n"
            "---\n"
            "\n"
            "### Misconception 8\n"
            "\n"
            "> “A PMF and PDF mean the same thing.”\n"
            "\n"
            "The chapter uses:\n"
            "\n"
            "```text\n"
            "PMF → discrete random variables\n"
            "PDF → continuous random variables\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "### Misconception 9\n"
            "\n"
            "> “Bernoulli and Binomial are the same distribution.”\n"
            "\n"
            "Bernoulli models one binary trial.\n"
            "\n"
            "Binomial models the count of successes across multiple trials.\n"
            "\n"
            "---\n"
            "\n"
            "### Misconception 10\n"
            "\n"
            "> “Poisson and Exponential answer the same question.”\n"
            "\n"
            "The chapter's intuition is:\n"
            "\n"
            "```text\n"
            "Poisson     → number of events in an interval\n"
            "Exponential → time between events\n"
            "```\n"
            "\n"
            "---\n"
            "\n"
            "### Misconception 11\n"
            "\n"
            "> “If a histogram is not perfectly bell-shaped, the underlying data cannot be normal.”\n"
            "\n"
            "Small random samples can look irregular.\n"
            "\n"
            "The source explicitly compares small, medium, and large simulated samples.\n"
            "\n"
            "---\n"
            "\n"
            "### Misconception 12\n"
            "\n"
            "> “A normality-test p-value greater than 0.05 proves normality.”\n"
            "\n"
            "It supports a **fail-to-reject** decision under that test and significance level.\n"
            "\n"
            "---\n"
            "\n"
            "### Misconception 13\n"
            "\n"
            "> “All normality tests must always agree.”\n"
            "\n"
            "The source itself gives Shapiro–Wilk results that fail to reject for all three generated samples, while D’Agostino–Pearson rejects the large sample in that run.\n"
            "\n"
            "---\n"
            "\n"
            "### Misconception 14\n"
            "\n"
            "> “Masking deletes pixels from the array.”\n"
            "\n"
            "A masked array retains the data structure while marking selected elements as masked.\n"
            "\n"
            "---\n"
            "\n"
            "## Source consistency notes\n"
            "\n"
            "The supplied chapter has a few details that should be read carefully.\n"
            "\n"
            "### Eigen example variable name\n"
            "\n"
            "The source creates:\n"
            "\n"
            "```python\n"
            "mat = ...\n"
            "```\n"
            "\n"
            "but later calls:\n"
            "\n"
            "```python\n"
            "np.linalg.eig(A)\n"
            "```\n"
            "\n"
            "and:\n"
            "\n"
            "```python\n"
            "np.linalg.eigvals(A)\n"
            "```\n"
            "\n"
            "inside that subsection.\n"
            "\n"
            "The conceptual intent is clear, but the exact variable naming is inconsistent.\n"
            "\n"
            "### Normality and sample size\n"
            "\n"
            "The source says that as sample size increases, “the distribution approaches normal distribution.” In the demonstrated section, however, all samples were already generated from `np.random.normal()`.\n"
            "\n"
            "The safe source-grounded interpretation is:\n"
            "\n"
            "> Larger simulated samples from the normal generator produce smoother empirical histograms that more clearly resemble the underlying bell shape.\n"
            "\n"
            "### Different normality-test results\n"
            "\n"
            "The chapter's D’Agostino–Pearson large-sample result has:\n"
            "\n"
            "```text\n"
            "p ≈ 0.0449\n"
            "```\n"
            "\n"
            "while Shapiro–Wilk for the same generated sample has:\n"
            "\n"
            "```text\n"
            "p ≈ 0.7929\n"
            "```\n"
            "\n"
            "The chapter reports both. Do not assume normality tests are guaranteed to return identical decisions on a specific finite sample.\n"
            "\n"
            "---\n"
            "\n"
            "## Key terminology\n"
            "\n"
            "| Term | Meaning |\n"
            "|---|---|\n"
            "| Scalar | single 0D value |\n"
            "| Vector | one-dimensional ordered numeric structure |\n"
            "| Matrix | two-dimensional rows × columns structure |\n"
            "| Tensor | generalized multidimensional structure |\n"
            "| Dot product | scalar result from combining corresponding vector components |\n"
            "| Norm | vector magnitude |\n"
            "| Transpose | rows and columns swapped |\n"
            "| Polynomial fit | polynomial approximation to observed points |\n"
            "| Least squares | minimize squared residual differences |\n"
            "| Determinant | scalar property of a square matrix |\n"
            "| Rank | number of independent rows/columns |\n"
            "| Inverse | matrix that multiplies with `A` to produce identity |\n"
            "| Identity matrix | diagonal ones, zeros elsewhere |\n"
            "| Linear system | equation of form `Ax=B` |\n"
            "| Eigenvector | non-zero direction preserved under transformation, up to scaling |\n"
            "| Eigenvalue | scalar scaling factor associated with eigenvector |\n"
            "| Matrix decomposition | factorization into simpler matrices |\n"
            "| SVD | `A = UΣVᵀ` |\n"
            "| LU | lower/upper triangular factorization |\n"
            "| QR | orthogonal × upper-triangular factorization |\n"
            "| Random variable | numerical outcome of random process |\n"
            "| PMF | discrete probability mass function |\n"
            "| PDF | continuous probability density function |\n"
            "| CDF | cumulative probability up to `x` |\n"
            "| Bernoulli | one binary trial |\n"
            "| Binomial | successes across repeated Bernoulli trials |\n"
            "| Poisson | count of events in interval |\n"
            "| Geometric | trials until first success |\n"
            "| Uniform | equal likelihood across range in chapter example |\n"
            "| Normal | symmetric Gaussian distribution |\n"
            "| Log-normal | positive variable whose logarithm is normal |\n"
            "| Exponential | waiting time between events |\n"
            "| Pseudo-random | algorithmically generated random-like sequence |\n"
            "| Shapiro–Wilk | normality hypothesis test |\n"
            "| Anderson–Darling | distribution-fit/normality test using statistic and critical values |\n"
            "| D’Agostino–Pearson | normality test based on skewness and kurtosis |\n"
            "| Masked array | array with selected elements marked as masked |\n"
            "\n"
            "---\n"
            "\n"
            "## Self-check\n"
            "\n"
            "Before continuing, make sure you can answer:\n"
            "\n"
            "1. Why is linear algebra important for data science?\n"
            "2. How can an image be represented numerically?\n"
            "3. What is the difference between a scalar and vector?\n"
            "4. What does shape `(3,)` mean?\n"
            "5. What does shape `(2,2,2)` mean?\n"
            "6. How is a vector dot product calculated?\n"
            "7. What does vector norm represent?\n"
            "8. How does matrix multiplication differ from element-wise multiplication?\n"
            "9. What does matrix transpose do?\n"
            "10. What does `np.polyfit()` return?\n"
            "11. Why does `np.polyval()` come after `polyfit()`?\n"
            "12. Why does the chapter use `linspace()` for plotting a polynomial?\n"
            "13. What is underfitting?\n"
            "14. What is overfitting?\n"
            "15. What does the determinant represent in the chapter?\n"
            "16. What does matrix rank measure?\n"
            "17. Why does a repeated row reduce independence?\n"
            "18. What two conditions does the chapter give for invertibility?\n"
            "19. What identity does an inverse satisfy?\n"
            "20. What does `np.linalg.solve(A,B)` compute?\n"
            "21. How can you verify a linear-system solution?\n"
            "22. What equation defines an eigenvector/eigenvalue relationship?\n"
            "23. What does an eigenvalue represent?\n"
            "24. What does `np.linalg.eig()` return?\n"
            "25. What does `np.linalg.eigvals()` return?\n"
            "26. What is matrix decomposition?\n"
            "27. What three components appear in SVD?\n"
            "28. What do L and U mean in LU decomposition?\n"
            "29. What do Q and R mean in QR decomposition?\n"
            "30. How does the chapter verify QR decomposition?\n"
            "31. What is a random variable?\n"
            "32. When do you use a PMF?\n"
            "33. When do you use a PDF?\n"
            "34. What does a CDF tell you?\n"
            "35. What is the difference between discrete and continuous distributions?\n"
            "36. What are the two outcomes in Bernoulli?\n"
            "37. How does Binomial extend Bernoulli?\n"
            "38. What question does Poisson answer?\n"
            "39. What question does Geometric answer?\n"
            "40. What is the central idea of a Uniform distribution?\n"
            "41. What properties define the chapter's Normal distribution?\n"
            "42. What is the standard normal distribution?\n"
            "43. Why is Log-normal right-skewed in the chapter?\n"
            "44. What real-world quantity can Exponential model?\n"
            "45. What is a pseudo-random number?\n"
            "46. What is the purpose of generating random values from a named distribution?\n"
            "47. Why can a small normal sample's histogram look irregular?\n"
            "48. What are the Shapiro–Wilk null and alternative hypotheses?\n"
            "49. What does `p > 0.05` mean in the chapter's normality-test logic?\n"
            "50. How does Anderson–Darling use critical values?\n"
            "51. What two shape measures are combined by D’Agostino–Pearson?\n"
            "52. Why can different normality tests disagree on one finite sample?\n"
            "53. What is a Boolean mask?\n"
            "54. What does `np.ma.array()` create?\n"
            "55. What happens when the chapter applies `np.log1p()` to a masked array?\n"
            "\n"
            "---\n"
            "\n"
            "## Retain this idea\n"
            "\n"
            "**Linear algebra is the structural language of numerical data: vectors and matrices represent information, matrix operations transform it, decompositions reveal structure, and NumPy/SciPy turn those mathematical ideas into practical computation. The chapter then extends that numerical toolkit to uncertainty through probability distributions, simulation, normality testing, and masked arrays.**\n"
        ),
        "estimated_minutes": 420,
        "has_code_examples": True,
        "has_manual_image_requests": True,
        "sections": [
            {"id": "why-linear-algebra", "title": "What is linear algebra?", "order": 1},
            {"id": "scalars-vectors-matrices-tensors", "title": "Scalars, vectors, matrices, and tensors", "order": 2},
            {"id": "vector-matrix-operations", "title": "Basic vector and matrix operations", "order": 3},
            {"id": "polynomial-fitting", "title": "Fitting polynomials with NumPy", "order": 4},
            {"id": "determinant-rank", "title": "Determinant and matrix rank", "order": 5},
            {"id": "inverse-linear-systems", "title": "Matrix inverse and systems of equations", "order": 6},
            {"id": "eigen", "title": "Eigenvalues and eigenvectors", "order": 7},
            {"id": "matrix-decomposition", "title": "Matrix decomposition", "order": 8},
            {"id": "svd", "title": "Singular Value Decomposition (SVD)", "order": 9},
            {"id": "lu-qr", "title": "LU and QR decomposition", "order": 10},
            {"id": "probability-framework", "title": "Probability distributions: PMF, PDF, and CDF", "order": 11},
            {"id": "discrete-distributions", "title": "Discrete probability distributions", "order": 12},
            {"id": "continuous-distributions", "title": "Continuous probability distributions", "order": 13},
            {"id": "random-generation", "title": "Generating random numbers", "order": 14},
            {"id": "normality-visual", "title": "Visual normality assessment", "order": 15},
            {"id": "shapiro", "title": "Shapiro–Wilk normality test", "order": 16},
            {"id": "anderson-dagostino", "title": "Anderson–Darling and D’Agostino–Pearson tests", "order": 17},
            {"id": "masked-arrays", "title": "Masked arrays and image processing", "order": 18},
        ],
    },
    "exercises": [
        {
            "id": "M04.L01.EX01",
            "title": "Work with Vectors and Matrices",
            "lesson_code": "M04.L01",
            "section_id": "vector-matrix-operations",
            "placement": "after_section",
            "description": (
                "Practice dimensionality, dot products, norms, matrix multiplication, and transpose."
            ),
            "instructions": (
                "1. Create vectors v1=[2,3] and v2=[4,5].\n"
                "2. Compute their dot product and the norm of v1.\n"
                "3. Create two 2x2 matrices and multiply them with np.dot() or @.\n"
                "4. Transpose the first matrix.\n"
                "5. Explain why matrix multiplication is not element-wise multiplication."
            ),
            "expected_output": (
                "Executable NumPy code, numeric outputs, and a brief explanation of the geometry/shape of each operation."
            ),
            "difficulty": DifficultyLevel.beginner,
            "skill_tested": [
                "vectors",
                "dot-product",
                "norm",
                "matrix-multiplication",
                "transpose",
            ],
        },
        {
            "id": "M04.L01.EX02",
            "title": "Analyze and Factorize a Matrix",
            "lesson_code": "M04.L01",
            "section_id": "lu-qr",
            "placement": "after_section",
            "description": (
                "Connect determinant, rank, inverse, solving, eigen analysis, and decomposition."
            ),
            "instructions": (
                "Use A = [[2,1],[1,2]].\n"
                "1. Compute determinant and rank.\n"
                "2. Compute the inverse and verify A @ A_inv is approximately identity.\n"
                "3. Solve Ax=b for b=[3,3].\n"
                "4. Compute eigenvalues/eigenvectors.\n"
                "5. Perform SVD.\n"
                "6. Explain what each result tells you about A."
            ),
            "expected_output": (
                "A compact NumPy/SciPy notebook-style solution with verification steps and interpretations."
            ),
            "difficulty": DifficultyLevel.intermediate,
            "skill_tested": [
                "determinant",
                "rank",
                "inverse",
                "linear-system",
                "eigen",
                "svd",
            ],
        },
        {
            "id": "M04.L01.EX03",
            "title": "Match Problems to Probability Distributions",
            "lesson_code": "M04.L01",
            "section_id": "continuous-distributions",
            "placement": "after_section",
            "description": (
                "Practice selecting the distributions introduced in the chapter."
            ),
            "instructions": (
                "Choose Bernoulli, Binomial, Poisson, Geometric, Uniform, Normal, Log-normal, or Exponential:\n"
                "1. Whether one bulb works.\n"
                "2. Number of heads in 20 tosses.\n"
                "3. Calls received in one hour.\n"
                "4. Tosses needed to get first head.\n"
                "5. A value equally likely anywhere within an interval.\n"
                "6. Symmetric bell-shaped measurement.\n"
                "7. Positively skewed multiplicative variable.\n"
                "8. Waiting time between arrivals.\n"
                "For each, justify the choice in one sentence."
            ),
            "expected_output": (
                "An eight-row table containing scenario, chosen distribution, discrete/continuous classification, and justification."
            ),
            "difficulty": DifficultyLevel.beginner,
            "skill_tested": [
                "bernoulli",
                "binomial",
                "poisson",
                "geometric",
                "uniform",
                "normal",
                "lognormal",
                "exponential",
            ],
        },
        {
            "id": "M04.L01.EX04",
            "title": "Assess Normality with Multiple Methods",
            "lesson_code": "M04.L01",
            "section_id": "anderson-dagostino",
            "placement": "after_section",
            "description": (
                "Use visual and statistical methods to assess a generated sample."
            ),
            "instructions": (
                "1. Generate 200 values with np.random.normal().\n"
                "2. Plot a histogram with KDE.\n"
                "3. Run Shapiro-Wilk.\n"
                "4. Run Anderson-Darling.\n"
                "5. Run D'Agostino-Pearson.\n"
                "6. Interpret each result using the chapter's decision logic.\n"
                "7. State whether all methods agree."
            ),
            "expected_output": (
                "Python code, the histogram, test outputs, and a careful comparison of the three normality assessments."
            ),
            "difficulty": DifficultyLevel.intermediate,
            "skill_tested": [
                "normal-distribution",
                "histogram",
                "shapiro",
                "anderson",
                "normaltest",
                "statistical-interpretation",
            ],
        },
    ],
    "quiz": {
        "id": "M04.L01.QZ01",
        "title": "Linear Algebra — Knowledge Check",
        "lesson_code": "M04.L01",
        "placement": "lesson_end",
        "questions": [
            {
                "id": "M04.L01.Q01",
                "section_id": "scalars-vectors-matrices-tensors",
                "question": "What dimensional structure is a matrix in the chapter?",
                "options": ["0D", "1D", "2D", "Always 4D"],
                "correct": 2,
                "explanation": "A matrix is represented as a two-dimensional rows-by-columns numerical structure."
            },
            {
                "id": "M04.L01.Q02",
                "section_id": "vector-matrix-operations",
                "question": "For v1=[1,2] and v2=[3,4], what is their dot product?",
                "options": ["7", "10", "11", "14"],
                "correct": 2,
                "explanation": "1×3 + 2×4 = 3 + 8 = 11."
            },
            {
                "id": "M04.L01.Q03",
                "section_id": "polynomial-fitting",
                "question": "What risk does the chapter associate with choosing an excessively high polynomial degree?",
                "options": ["Underfitting only", "Overfitting noise", "Matrix singularity only", "No predicted values"],
                "correct": 1,
                "explanation": "The chapter warns that a high-degree curve can follow noise instead of the underlying trend."
            },
            {
                "id": "M04.L01.Q04",
                "section_id": "inverse-linear-systems",
                "question": "Which condition is required for the inverse in the chapter?",
                "options": [
                    "The matrix must contain only positive values",
                    "The determinant must be non-zero",
                    "The matrix must have exactly three rows",
                    "The rank must always be one",
                ],
                "correct": 1,
                "explanation": "The chapter requires a square, non-singular matrix, meaning its determinant is not zero."
            },
            {
                "id": "M04.L01.Q05",
                "section_id": "eigen",
                "question": "In Av = λv, what does λ represent?",
                "options": ["Matrix rank", "Eigenvalue", "Probability density", "Vector dimension"],
                "correct": 1,
                "explanation": "λ is the scalar eigenvalue associated with eigenvector v."
            },
            {
                "id": "M04.L01.Q06",
                "section_id": "svd",
                "question": "Which factorization matches the SVD structure used in the chapter?",
                "options": ["A = QR", "A = LU", "A = UΣVᵀ", "A = A⁻¹I"],
                "correct": 2,
                "explanation": "SVD decomposes A into left singular vectors, singular values, and right singular-vector transpose."
            },
            {
                "id": "M04.L01.Q07",
                "section_id": "probability-framework",
                "question": "Which function is associated with a discrete random variable?",
                "options": ["PMF", "PDF only", "Transpose", "SVD"],
                "correct": 0,
                "explanation": "The chapter uses a probability mass function for discrete random variables."
            },
            {
                "id": "M04.L01.Q08",
                "section_id": "discrete-distributions",
                "question": "Which distribution models the number of successes in repeated Bernoulli trials?",
                "options": ["Geometric", "Binomial", "Exponential", "Uniform"],
                "correct": 1,
                "explanation": "The Binomial distribution counts successes across a fixed number of Bernoulli trials."
            },
            {
                "id": "M04.L01.Q09",
                "section_id": "continuous-distributions",
                "question": "Which distribution models waiting time between events in a Poisson process?",
                "options": ["Bernoulli", "Binomial", "Exponential", "Geometric"],
                "correct": 2,
                "explanation": "The chapter uses Exponential for time between successive events."
            },
            {
                "id": "M04.L01.Q10",
                "section_id": "shapiro",
                "question": "Under the chapter's Shapiro-Wilk rule, what do you do if p=0.60 and alpha=0.05?",
                "options": ["Reject H0", "Fail to reject H0", "Set p to 0.05", "Reject the sample"],
                "correct": 1,
                "explanation": "Because p is greater than alpha, the chapter's logic says to fail to reject the normality null."
            },
            {
                "id": "M04.L01.Q11",
                "section_id": "anderson-dagostino",
                "question": "What does the chapter say D'Agostino-Pearson combines?",
                "options": [
                    "Mean and median",
                    "Skewness and kurtosis",
                    "Rank and determinant",
                    "PMF and CDF",
                ],
                "correct": 1,
                "explanation": "The source describes the test as combining information from skewness and kurtosis."
            },
            {
                "id": "M04.L01.Q12",
                "section_id": "masked-arrays",
                "type": "open",
                "question": (
                    "Explain what a masked array is doing in the chapter's image example and why "
                    "the log transform can still be applied to the masked array."
                ),
            },
        ],
        "passing_score": 70,
    },
}
