COURSE_MANIFEST = {'course_id': 'COURSE-010',
 'course_title': 'AI Service Engineering with FastAPI',
 'source': 'BOOK-010',
 'book_title': 'Building Generative AI Services with FastAPI',
 'author': 'Alireza Parandeh',
 'edition': 'SOURCE INFORMATION MISSING',
 'status': 'curriculum_design_finalized / course-folder seed export generated',
 'finalization_status': 'finished_by_user',
 'approval_status': 'not_explicitly_approved',
 'source_review': 'complete',
 'chapters_processed': '12/12',
 'level': 'Intermediate → Advanced',
 'modules': 9,
 'lessons': 84,
 'guided_minutes': 4260,
 'guided_time': '71h 00m',
 'lesson_id_range': 'L010-001..L010-084',
 'module_id_range': 'M010-01..M010-09',
 'manual_visual_references': 29,
 'professional_capability': 'Design, implement, secure, test, optimize, and deploy production-oriented '
                            'backend services for AI applications using FastAPI, typed contracts, model '
                            'lifecycle management, asynchronous workloads, streaming, databases, '
                            'identity/access controls, runtime security, testing, and containerization.',
 'learning_loop': 'Learn → Practice → Build → Debug → Evaluate → Operate',
 'prerequisites': ['COURSE-005 — Applied LLM Engineering', 'COURSE-006 — Production AI Engineering'],
 'supporting_context': ['COURSE-007 — Advanced LLM Systems & Application Architecture',
                        'COURSE-008 — Vision-Language & Multimodal AI Engineering',
                        'COURSE-009 — Enterprise RAG Engineering'],
 'tracks': [{'track': 'Data Analyst', 'role': 'Optional'},
            {'track': 'ML Engineer', 'role': 'Supporting'},
            {'track': 'AI Developer', 'role': 'Core'},
            {'track': 'MLOps Engineer', 'role': 'Supporting / Service-Layer Prerequisite'},
            {'track': 'AI Engineer', 'role': 'Core'}],
 'modules_detail': [{'module_id': 'M010-01',
                     'title': 'AI Service Architecture & FastAPI Foundations',
                     'objective': 'Design the service boundary, create a maintainable FastAPI application, '
                                  'and organize backend responsibilities before adding advanced AI '
                                  'workloads.',
                     'lessons': 10,
                     'guided_minutes': 435,
                     'lesson_ids': ['L010-001',
                                    'L010-002',
                                    'L010-003',
                                    'L010-004',
                                    'L010-005',
                                    'L010-006',
                                    'L010-007',
                                    'L010-008',
                                    'L010-009',
                                    'L010-010'],
                     'project': {'title': 'AI Service Architecture & FastAPI Scaffold',
                                 'description': 'Create the initial FastAPI service skeleton with layered '
                                                'boundaries, dependency injection, health/info endpoints, '
                                                'and reproducible tooling.',
                                 'objectives': ['Establish service boundaries',
                                                'Run and document the FastAPI scaffold',
                                                'Apply layered project structure',
                                                'Pass basic quality checks'],
                                 'tech_stack': ['Python', 'FastAPI', 'Ruff', 'pytest'],
                                 'estimated_hours': 5}},
                    {'module_id': 'M010-02',
                     'title': 'Model Integration, Lifecycle & Type-Safe API Contracts',
                     'objective': 'Integrate AI providers behind stable interfaces, manage model resources '
                                  'safely, and enforce typed request, response, configuration, and media '
                                  'contracts.',
                     'lessons': 14,
                     'guided_minutes': 630,
                     'lesson_ids': ['L010-011',
                                    'L010-012',
                                    'L010-013',
                                    'L010-014',
                                    'L010-015',
                                    'L010-016',
                                    'L010-017',
                                    'L010-018',
                                    'L010-019',
                                    'L010-020',
                                    'L010-021',
                                    'L010-022',
                                    'L010-023',
                                    'L010-024'],
                     'project': {'title': 'Pluggable Typed AI Model Gateway',
                                 'description': 'Build a provider-neutral AI gateway with lifespan-managed '
                                                'resources, typed contracts, media responses, settings, and '
                                                'monitoring middleware.',
                                 'objectives': ['Swap providers without changing routes',
                                                'Validate requests/responses',
                                                'Manage model lifecycle',
                                                'Record safe request telemetry'],
                                 'tech_stack': ['FastAPI', 'Pydantic v2', 'provider adapter', 'pytest'],
                                 'estimated_hours': 7}},
                    {'module_id': 'M010-03',
                     'title': 'Async AI Workloads, Concurrency & Background Processing',
                     'objective': 'Classify workloads, protect the event loop, coordinate concurrent I/O, '
                                  'isolate heavy inference, and hand off long-running work safely.',
                     'lessons': 8,
                     'guided_minutes': 435,
                     'lesson_ids': ['L010-025',
                                    'L010-026',
                                    'L010-027',
                                    'L010-028',
                                    'L010-029',
                                    'L010-030',
                                    'L010-031',
                                    'L010-032'],
                     'project': {'title': 'Concurrent Multi-User AI Service',
                                 'description': 'Remove blocking paths, add bounded async provider calls, '
                                                'isolate heavy inference, and expose a background-job '
                                                'workflow.',
                                 'objectives': ['Protect event loop',
                                                'Bound external concurrency',
                                                'Separate inference tier',
                                                'Implement job status flow'],
                                 'tech_stack': ['FastAPI', 'asyncio', 'HTTPX', 'optional worker queue'],
                                 'estimated_hours': 7}},
                    {'module_id': 'M010-04',
                     'title': 'Streaming & Real-Time AI Communication',
                     'objective': 'Select and implement polling, SSE, and WebSocket patterns with '
                                  'provider-neutral streaming, connection lifecycle management, and '
                                  'backpressure awareness.',
                     'lessons': 7,
                     'guided_minutes': 370,
                     'lesson_ids': ['L010-033',
                                    'L010-034',
                                    'L010-035',
                                    'L010-036',
                                    'L010-037',
                                    'L010-038',
                                    'L010-039'],
                     'project': {'title': 'Real-Time Streaming AI Gateway',
                                 'description': 'Expose the provider-neutral stream through SSE and '
                                                'WebSocket while handling cancellation, disconnects, and '
                                                'slow consumers.',
                                 'objectives': ['Implement SSE',
                                                'Implement WebSocket',
                                                'Share provider stream abstraction',
                                                'Handle lifecycle/backpressure'],
                                 'tech_stack': ['FastAPI', 'SSE', 'WebSocket', 'asyncio'],
                                 'estimated_hours': 7}},
                    {'module_id': 'M010-05',
                     'title': 'Persistence & Database Engineering for AI Services',
                     'objective': 'Add durable application state with async PostgreSQL/SQLAlchemy, clear '
                                  'service/repository boundaries, migrations, and safe persistence around AI '
                                  'streams.',
                     'lessons': 8,
                     'guided_minutes': 410,
                     'lesson_ids': ['L010-040',
                                    'L010-041',
                                    'L010-042',
                                    'L010-043',
                                    'L010-044',
                                    'L010-045',
                                    'L010-046',
                                    'L010-047'],
                     'project': {'title': 'Persistent Conversation Service',
                                 'description': 'Add async PostgreSQL persistence, repositories/services, '
                                                'migrations, conversation history, and safe persistence of '
                                                'streamed responses.',
                                 'objectives': ['Design durable entities',
                                                'Use async transactions',
                                                'Apply migrations',
                                                'Persist completed streams safely'],
                                 'tech_stack': ['PostgreSQL', 'SQLAlchemy 2.x', 'Alembic', 'FastAPI'],
                                 'estimated_hours': 7}},
                    {'module_id': 'M010-06',
                     'title': 'Authentication, Authorization & Secure Service Boundaries',
                     'objective': 'Protect AI services through identity, policy enforcement, guardrails, '
                                  'quotas, distributed rate limits, and safe input/output boundaries.',
                     'lessons': 14,
                     'guided_minutes': 740,
                     'lesson_ids': ['L010-048',
                                    'L010-049',
                                    'L010-050',
                                    'L010-051',
                                    'L010-052',
                                    'L010-053',
                                    'L010-054',
                                    'L010-055',
                                    'L010-056',
                                    'L010-057',
                                    'L010-058',
                                    'L010-059',
                                    'L010-060',
                                    'L010-061'],
                     'project': {'title': 'Hardened Identity & Security Boundary',
                                 'description': 'Add identity, authorization, OAuth/JWT-aware flows, '
                                                'guardrails, quotas, distributed rate limits, and '
                                                'tool/output validation.',
                                 'objectives': ['Authenticate principals',
                                                'Enforce ownership/roles/attributes',
                                                'Block unsafe input/output paths',
                                                'Protect service capacity'],
                                 'tech_stack': ['FastAPI security', 'JWT/OIDC concepts', 'Redis', 'Pydantic'],
                                 'estimated_hours': 9}},
                    {'module_id': 'M010-07',
                     'title': 'AI Service Performance & Optimization',
                     'objective': 'Measure service performance and reduce latency/cost through batching, '
                                  'exact and semantic caching, context caching, structured outputs, and '
                                  'evidence-based optimization.',
                     'lessons': 7,
                     'guided_minutes': 350,
                     'lesson_ids': ['L010-062',
                                    'L010-063',
                                    'L010-064',
                                    'L010-065',
                                    'L010-066',
                                    'L010-067',
                                    'L010-068'],
                     'project': {'title': 'Performance & Cost Optimization Lab',
                                 'description': 'Benchmark the service and apply batching, cache strategies, '
                                                'context reuse, and structured outputs without breaking '
                                                'correctness.',
                                 'objectives': ['Establish baseline metrics',
                                                'Implement safe caching',
                                                'Move bulk work offline',
                                                'Prove optimization with before/after evidence'],
                                 'tech_stack': ['Python',
                                                'Redis',
                                                'vector cache optional',
                                                'provider batch/context cache'],
                                 'estimated_hours': 6}},
                    {'module_id': 'M010-08',
                     'title': 'Testing & Reliability Engineering for AI APIs',
                     'objective': 'Build a maintainable release test suite spanning deterministic code, '
                                  'async integrations, probabilistic AI behavior, regression evaluation, and '
                                  'critical E2E workflows.',
                     'lessons': 8,
                     'guided_minutes': 425,
                     'lesson_ids': ['L010-069',
                                    'L010-070',
                                    'L010-071',
                                    'L010-072',
                                    'L010-073',
                                    'L010-074',
                                    'L010-075',
                                    'L010-076'],
                     'project': {'title': 'Release Reliability Test Suite',
                                 'description': 'Create the release gate with unit, integration, async, '
                                                'behavioral/regression, and focused E2E tests.',
                                 'objectives': ['Isolate deterministic logic',
                                                'Test real integration contracts',
                                                'Evaluate probabilistic behavior',
                                                'Automate critical workflows'],
                                 'tech_stack': ['pytest', 'HTTPX', 'AnyIO/pytest-asyncio', 'test DB/cache'],
                                 'estimated_hours': 8}},
                    {'module_id': 'M010-09',
                     'title': 'Containerized AI Service Deployment & Capstone',
                     'objective': 'Choose a deployment topology, package and harden the service with Docker, '
                                  'coordinate multi-container dependencies, and release the final '
                                  'production-oriented capstone.',
                     'lessons': 8,
                     'guided_minutes': 465,
                     'lesson_ids': ['L010-077',
                                    'L010-078',
                                    'L010-079',
                                    'L010-080',
                                    'L010-081',
                                    'L010-082',
                                    'L010-083',
                                    'L010-084'],
                     'project': {'title': 'Production-Ready AI Service with FastAPI',
                                 'description': 'Capstone: package the full COURSE-010 backend into a '
                                                'hardened, multi-container production candidate and verify '
                                                'it through the release gate and smoke tests.',
                                 'objectives': ['Build reproducible image',
                                                'Run private DB/cache network',
                                                'Apply migrations and runtime secrets',
                                                'Pass release and smoke checks',
                                                'Write production-readiness review'],
                                 'tech_stack': ['Docker',
                                                'Docker Compose',
                                                'FastAPI',
                                                'PostgreSQL',
                                                'Redis',
                                                'container registry'],
                                 'estimated_hours': 14}}],
 'course_capstone': {'title': 'Production-Ready AI Service with FastAPI',
                     'description': 'Capstone: package the full COURSE-010 backend into a hardened, '
                                    'multi-container production candidate and verify it through the release '
                                    'gate and smoke tests.',
                     'objectives': ['Build reproducible image',
                                    'Run private DB/cache network',
                                    'Apply migrations and runtime secrets',
                                    'Pass release and smoke checks',
                                    'Write production-readiness review'],
                     'tech_stack': ['Docker',
                                    'Docker Compose',
                                    'FastAPI',
                                    'PostgreSQL',
                                    'Redis',
                                    'container registry'],
                     'estimated_hours': 14},
 'protected_boundaries': ['Do not duplicate model/LLM/RAG/multimodal theory already owned by '
                          'COURSE-001..009.',
                          'General Kubernetes operations, CI/CD, IaC, registries, rollout infrastructure, '
                          'autoscaling, and platform incidents remain future MLOps / AI Platform '
                          'Engineering.',
                          'Provider-specific APIs and source-era numerical claims must be revalidated when '
                          'implementation code is integrated.']}
