import { copyNumber } from '@/features/home/strings'
import { directionFor, useLanguageStore } from '@/lib/language'

/** Project Lab copy, kept beside the feature (same approach as features/home/strings.ts) so the
 *  shared dictionaries in lib/i18n.ts are not edited in the middle. Technical terms, file names
 *  and code stay in English in both languages. */
const STRINGS = {
  en: {
    'lab.section.title': 'Guided projects',
    'lab.section.subtitle': 'Real analysis in a small workspace: edit files, run them, and check each step. Free — no credits.',
    'lab.card.milestones': '{n} milestones · {tasks} tasks',
    'lab.card.hours': 'About {n} h',
    'lab.card.start': 'Start project',
    'lab.card.view': 'View project',
    'lab.overview.kicker': 'Capstone project',
    'lab.overview.start': 'Start Project',
    'lab.overview.continue': 'Continue Project',
    'lab.overview.viewCompleted': 'View Completed Project',
    'lab.overview.back': 'Project overview',
    'lab.overview.role': 'Your role',
    'lab.overview.difficulty': 'Difficulty',
    'lab.overview.duration': 'Estimated duration',
    'lab.overview.structure': 'Structure',
    'lab.overview.hoursRange': '{min}–{max} hours',
    'lab.overview.level.beginner': 'Beginner',
    'lab.overview.level.intermediate': 'Intermediate',
    'lab.overview.level.advanced': 'Advanced',
    'lab.overview.readyToSubmit': 'Every task has passed — open the workspace to submit your project.',
    'lab.overview.scenario': 'The scenario',
    'lab.overview.deliverables': 'What you will produce',
    'lab.overview.skills': 'Skills you will use',
    'lab.overview.environment': 'How you will work',
    'lab.overview.environmentBody': 'Everything happens in the Masar Project Lab, in your browser. You can:',
    'lab.overview.env.edit': 'Edit the project files',
    'lab.overview.env.python': 'Run Python (pandas, NumPy, matplotlib)',
    'lab.overview.env.sql': 'Run SQL on the company data',
    'lab.overview.env.output': 'Inspect outputs, tables and charts',
    'lab.overview.env.check': 'Check each task as you go',
    'lab.overview.env.hints': 'Open progressive hints when stuck',
    'lab.overview.milestones': 'Project structure',
    'lab.overview.tasks': '{n} tasks',
    'lab.completion.status': 'Project Completed',
    'lab.completion.tasks': '{done} / {total} tasks completed',
    'lab.completion.role': 'Completed as: {role}',
    'lab.submit.viewSummary': 'View the project summary',
    'lab.card.continue': 'Continue project',
    'lab.card.review': 'Open project',
    'lab.card.progress': '{done} of {total} tasks complete',
    'lab.card.completed': 'Completed',
    'lab.card.free': 'Free',
    'lab.card.error': 'Could not start the project. Try again.',
    'lab.loading': 'Loading the project…',
    'lab.missing': 'This project is not available.',
    'lab.back': 'Back to challenges',
    'lab.start.title': 'Start this project',
    'lab.start.body': 'You get your own workspace with the project files. Your work is saved as you go.',
    'lab.progress': 'Progress',
    'lab.progress.count': '{done} of {total} tasks',
    'lab.milestones': 'Milestones',
    'lab.task.status.completed': 'Completed',
    'lab.task.status.in_progress': 'In progress',
    'lab.task.status.not_started': 'Not started',
    'lab.task.instructions': 'Instructions',
    'lab.task.openFile': 'Open {file}',
    'lab.files': 'Files',
    'lab.files.readOnly': 'Read-only',
    'lab.files.modified': 'Edited',
    'lab.editor.label': 'Editor: {file}',
    'lab.editor.readOnly': 'This file is read-only.',
    'lab.editor.saved': 'Saved',
    'lab.editor.unsaved': 'Unsaved changes',
    'lab.editor.saving': 'Saving…',
    'lab.editor.saveFailed': 'Could not save. Your changes are still here; try again.',
    'lab.editor.noFile': 'Choose a file to open it.',
    'lab.csv.rows': 'Showing {shown} of {total} rows',
    'lab.action.save': 'Save',
    'lab.action.run': 'Run',
    'lab.action.running': 'Running…',
    'lab.action.check': 'Check Step',
    'lab.action.checking': 'Checking…',
    'lab.action.reset': 'Reset File',
    'lab.reset.title': 'Reset {file}?',
    'lab.reset.body': 'This replaces your version of this file with the original project file. Your other files and your progress are not affected. This cannot be undone.',
    'lab.reset.confirm': 'Reset file',
    'lab.reset.cancel': 'Cancel',
    'lab.panel.output': 'Output',
    'lab.panel.checks': 'Checks',
    'lab.panel.artifacts': 'Artifacts',
    'lab.panel.hints': 'Hints',
    'lab.output.empty': 'Run a Python or SQL file to see its output here.',
    'lab.output.noOutput': 'Finished with no output.',
    'lab.output.stdout': 'Output',
    'lab.output.stderr': 'Errors',
    'lab.output.ms': '{ms} ms',
    'lab.run.success': 'Ran successfully',
    'lab.run.error': 'Your code stopped with an error',
    'lab.run.timeout': 'Stopped: it took too long',
    'lab.run.infrastructure_error': 'Could not run right now — this is not a problem with your code. Try again shortly.',
    'lab.run.failed': 'Could not reach the server. Try again.',
    'lab.checks.empty': 'Press Check Step when you think the current task is done.',
    'lab.checks.task': 'Task: {task}',
    'lab.checks.pass': 'Step complete',
    'lab.checks.passAgain': 'Step already complete — still passing',
    'lab.checks.fail': 'Not yet — {passed} of {total} checks pass',
    'lab.checks.error.execution': 'Your file could not run',
    'lab.checks.error.infrastructure': 'Check unavailable',
    'lab.checks.passed': 'Passed',
    'lab.checks.failed': 'Not yet',
    'lab.checks.pending': 'Waiting for the checks above',
    'lab.submit.show': 'View summary',
    'lab.submit.hide': 'Hide summary',
    'lab.checks.failedRequest': 'Could not reach the server. Try again.',
    'lab.artifacts.empty': 'Charts your scripts save (charts/*.png) appear here after a run, and stay available for your report.',
    'lab.artifacts.truncated': 'Your program created more files than the project keeps; only the first ones are shown.',
    'lab.request.busy': 'Another Run or Check Step is still in progress for your account (perhaps in another tab). Wait for it to finish, then try again.',
    'lab.output.rowsTruncated': 'Only the first 500 rows are shown. Aggregate or add LIMIT to see a complete result.',
    'lab.output.stdoutTruncated': 'Output was cut: your program printed more than the project shows.',
    'lab.output.stderrTruncated': 'Error output was cut: it was longer than the project shows.',
    'lab.hints.intro': 'Hints are free and open one at a time — each one more specific than the last.',
    'lab.editor.edit': 'Edit',
    'lab.editor.preview': 'Preview',
    'lab.preview.loading': 'Loading the chart…',
    'lab.preview.missingChart': '{file} has not been generated yet. Run the script that saves it.',
    'lab.preview.externalImage': 'Only charts generated in this project can be shown here.',
    'lab.milestone.count': '{done}/{total}',
    'lab.submit.title': 'Every task has passed',
    'lab.submit.doneTitle': 'Project submitted',
    'lab.submit.body': 'Submit your project to record your final submission. You can keep improving your files afterwards.',
    'lab.submit.button': 'Submit project',
    'lab.submit.submitting': 'Submitting…',
    'lab.submit.failed': 'Could not submit. Try again.',
    'lab.submit.submittedOn': 'Submitted on {date}',
    'lab.submit.overall': '{percent}% complete',
    'lab.submit.milestones': 'Completed milestones',
    'lab.submit.skills': 'Validated skills',
    'lab.submit.artifacts': 'Project artifacts',
    'lab.hints.empty': 'This task has no hints.',
    'lab.hints.show': 'Show hint {n}',
    'lab.hints.label': 'Hint {n}',
    'lab.view.task': 'Task',
    'lab.view.code': 'Code',
    'lab.view.output': 'Output',
    'lab.view.label': 'Project Lab view',
  },
  ar: {
    'lab.section.title': 'مشاريع موجّهة',
    'lab.section.subtitle': 'تحليل حقيقي في مساحة عمل صغيرة: عدّل الملفات وشغّلها وتحقق من كل خطوة. مجانًا — دون رصيد.',
    'lab.card.milestones': 'المراحل: {n} · المهام: {tasks}',
    'lab.card.hours': 'نحو {n} ساعة',
    'lab.card.start': 'ابدأ المشروع',
    'lab.card.view': 'اعرض المشروع',
    'lab.overview.kicker': 'مشروع تخرّج',
    'lab.overview.start': 'ابدأ المشروع',
    'lab.overview.continue': 'تابع المشروع',
    'lab.overview.viewCompleted': 'اعرض المشروع المكتمل',
    'lab.overview.back': 'نظرة عامة على المشروع',
    'lab.overview.role': 'دورك',
    'lab.overview.difficulty': 'المستوى',
    'lab.overview.duration': 'المدة التقديرية',
    'lab.overview.structure': 'البنية',
    'lab.overview.hoursRange': '{min}–{max} ساعة',
    'lab.overview.level.beginner': 'مبتدئ',
    'lab.overview.level.intermediate': 'متوسط',
    'lab.overview.level.advanced': 'متقدم',
    'lab.overview.readyToSubmit': 'نجحت كل المهام — افتح مساحة العمل لتسليم مشروعك.',
    'lab.overview.scenario': 'السيناريو',
    'lab.overview.deliverables': 'ما الذي ستنتجه',
    'lab.overview.skills': 'المهارات التي ستستخدمها',
    'lab.overview.environment': 'كيف ستعمل',
    'lab.overview.environmentBody': 'يجري كل شيء في مختبر مشاريع مسار داخل متصفحك. يمكنك:',
    'lab.overview.env.edit': 'تعديل ملفات المشروع',
    'lab.overview.env.python': 'تشغيل Python ‏(pandas وNumPy وmatplotlib)',
    'lab.overview.env.sql': 'تشغيل SQL على بيانات الشركة',
    'lab.overview.env.output': 'فحص المخرجات والجداول والرسوم',
    'lab.overview.env.check': 'التحقق من كل مهمة أولًا بأول',
    'lab.overview.env.hints': 'فتح تلميحات متدرّجة عند الحاجة',
    'lab.overview.milestones': 'بنية المشروع',
    'lab.overview.tasks': 'المهام: {n}',
    'lab.completion.status': 'اكتمل المشروع',
    'lab.completion.tasks': 'المهام المكتملة: {done} / {total}',
    'lab.completion.role': 'أُنجز بدور: {role}',
    'lab.submit.viewSummary': 'اعرض ملخص المشروع',
    'lab.card.continue': 'تابع المشروع',
    'lab.card.review': 'افتح المشروع',
    'lab.card.progress': 'المهام المكتملة: {done} من {total}',
    'lab.card.completed': 'مكتمل',
    'lab.card.free': 'مجاني',
    'lab.card.error': 'تعذّر بدء المشروع. حاول مرة أخرى.',
    'lab.loading': 'جارٍ تحميل المشروع…',
    'lab.missing': 'هذا المشروع غير متاح.',
    'lab.back': 'العودة إلى التحديات',
    'lab.start.title': 'ابدأ هذا المشروع',
    'lab.start.body': 'ستحصل على مساحة عمل خاصة بك فيها ملفات المشروع، ويُحفظ عملك أولًا بأول.',
    'lab.progress': 'التقدّم',
    'lab.progress.count': 'المهام: {done} من {total}',
    'lab.milestones': 'المراحل',
    'lab.task.status.completed': 'مكتملة',
    'lab.task.status.in_progress': 'قيد التنفيذ',
    'lab.task.status.not_started': 'لم تبدأ',
    'lab.task.instructions': 'التعليمات',
    'lab.task.openFile': 'افتح {file}',
    'lab.files': 'الملفات',
    'lab.files.readOnly': 'للقراءة فقط',
    'lab.files.modified': 'معدّل',
    'lab.editor.label': 'المحرر: {file}',
    'lab.editor.readOnly': 'هذا الملف للقراءة فقط.',
    'lab.editor.saved': 'محفوظ',
    'lab.editor.unsaved': 'تغييرات غير محفوظة',
    'lab.editor.saving': 'جارٍ الحفظ…',
    'lab.editor.saveFailed': 'تعذّر الحفظ. ما زالت تغييراتك هنا؛ حاول مرة أخرى.',
    'lab.editor.noFile': 'اختر ملفًا لفتحه.',
    'lab.csv.rows': 'عرض {shown} من {total} صفًا',
    'lab.action.save': 'حفظ',
    'lab.action.run': 'تشغيل',
    'lab.action.running': 'جارٍ التشغيل…',
    'lab.action.check': 'تحقق من الخطوة',
    'lab.action.checking': 'جارٍ التحقق…',
    'lab.action.reset': 'إعادة الملف',
    'lab.reset.title': 'إعادة {file}؟',
    'lab.reset.body': 'سيستبدل هذا نسختك من الملف بملف المشروع الأصلي. لن تتأثر ملفاتك الأخرى ولا تقدّمك. لا يمكن التراجع عن ذلك.',
    'lab.reset.confirm': 'إعادة الملف',
    'lab.reset.cancel': 'إلغاء',
    'lab.panel.output': 'المخرجات',
    'lab.panel.checks': 'الفحوص',
    'lab.panel.artifacts': 'الملفات الناتجة',
    'lab.panel.hints': 'تلميحات',
    'lab.output.empty': 'شغّل ملف Python أو SQL لترى مخرجاته هنا.',
    'lab.output.noOutput': 'انتهى التشغيل دون مخرجات.',
    'lab.output.stdout': 'المخرجات',
    'lab.output.stderr': 'الأخطاء',
    'lab.output.ms': '{ms} ms',
    'lab.run.success': 'تم التشغيل بنجاح',
    'lab.run.error': 'توقف الكود بسبب خطأ',
    'lab.run.timeout': 'توقف: استغرق وقتًا أطول من المسموح',
    'lab.run.infrastructure_error': 'تعذّر التشغيل الآن — المشكلة ليست في الكود. حاول بعد قليل.',
    'lab.run.failed': 'تعذّر الوصول إلى الخادم. حاول مرة أخرى.',
    'lab.checks.empty': 'اضغط «تحقق من الخطوة» عندما تظن أن المهمة الحالية انتهت.',
    'lab.checks.task': 'المهمة: {task}',
    'lab.checks.pass': 'اكتملت الخطوة',
    'lab.checks.passAgain': 'الخطوة مكتملة مسبقًا — وما زالت ناجحة',
    'lab.checks.fail': 'ليس بعد — نجح {passed} من {total} فحوص',
    'lab.checks.error.execution': 'تعذّر تشغيل ملفك',
    'lab.checks.error.infrastructure': 'التحقق غير متاح الآن',
    'lab.checks.passed': 'ناجح',
    'lab.checks.failed': 'ليس بعد',
    'lab.checks.pending': 'بانتظار الفحوص السابقة',
    'lab.submit.show': 'اعرض الملخص',
    'lab.submit.hide': 'أخفِ الملخص',
    'lab.checks.failedRequest': 'تعذّر الوصول إلى الخادم. حاول مرة أخرى.',
    'lab.artifacts.empty': 'تظهر هنا الرسوم التي يحفظها برنامجك (charts/*.png) بعد التشغيل، وتبقى متاحة لتقريرك.',
    'lab.artifacts.truncated': 'أنشأ برنامجك ملفات أكثر مما يحتفظ به المشروع؛ تظهر الملفات الأولى فقط.',
    'lab.request.busy': 'ما زال تشغيل أو تحقق آخر قيد التنفيذ لحسابك (ربما في تبويب آخر). انتظر حتى ينتهي ثم حاول مرة أخرى.',
    'lab.output.rowsTruncated': 'تظهر أول 500 صف فقط. جمّع النتائج أو أضف LIMIT لترى نتيجة كاملة.',
    'lab.output.stdoutTruncated': 'تم قطع المخرجات: طبع برنامجك أكثر مما يعرضه المشروع.',
    'lab.output.stderrTruncated': 'تم قطع مخرجات الأخطاء: كانت أطول مما يعرضه المشروع.',
    'lab.hints.intro': 'التلميحات مجانية وتُفتح واحدًا تلو الآخر — كل تلميح أوضح من سابقه.',
    'lab.editor.edit': 'تحرير',
    'lab.editor.preview': 'معاينة',
    'lab.preview.loading': 'جارٍ تحميل الرسم…',
    'lab.preview.missingChart': 'لم يُولَّد {file} بعد. شغّل البرنامج الذي يحفظه.',
    'lab.preview.externalImage': 'لا يمكن هنا عرض إلا الرسوم التي وُلّدت في هذا المشروع.',
    'lab.milestone.count': '{done}/{total}',
    'lab.submit.title': 'نجحت كل المهام',
    'lab.submit.doneTitle': 'تم تسليم المشروع',
    'lab.submit.body': 'سلّم مشروعك لتسجيل تسليمك النهائي. يمكنك متابعة تحسين ملفاتك بعد ذلك.',
    'lab.submit.button': 'سلّم المشروع',
    'lab.submit.submitting': 'جارٍ التسليم…',
    'lab.submit.failed': 'تعذّر التسليم. حاول مرة أخرى.',
    'lab.submit.submittedOn': 'سُلّم في {date}',
    'lab.submit.overall': 'اكتمل {percent}٪',
    'lab.submit.milestones': 'المراحل المكتملة',
    'lab.submit.skills': 'المهارات التي تم التحقق منها',
    'lab.submit.artifacts': 'ملفات المشروع الناتجة',
    'lab.hints.empty': 'لا توجد تلميحات لهذه المهمة.',
    'lab.hints.show': 'اعرض التلميح {n}',
    'lab.hints.label': 'تلميح {n}',
    'lab.view.task': 'المهمة',
    'lab.view.code': 'الكود',
    'lab.view.output': 'المخرجات',
    'lab.view.label': 'عرض مختبر المشروع',
  },
} as const

export type LabStringKey = keyof (typeof STRINGS)['en']

export function useLabI18n() {
  const language = useLanguageStore((s) => s.language)
  const table = STRINGS[language]
  const n = (value: number) => copyNumber(value, language)
  return {
    language,
    dir: directionFor(language),
    t: (key: LabStringKey) => table[key],
    /** `t` with {placeholders}; numbers are written in the reader's digits. */
    tf: (key: LabStringKey, vars: Record<string, string | number> = {}) =>
      table[key].replace(/\{(\w+)\}/g, (m, name) =>
        Object.prototype.hasOwnProperty.call(vars, name)
          ? typeof vars[name] === 'number' ? n(vars[name] as number) : String(vars[name])
          : m,
      ),
    n,
    /** The Arabic field when the reader reads Arabic and it exists, else the English one. */
    pick: (en: string, ar?: string | null) => (language === 'ar' && ar ? ar : en),
  }
}

export const LAB_STRINGS = STRINGS
