"""Masar curriculum seed — L011-035."""

LESSON_META = {'lesson_id': 'L011-035', 'course_id': 'COURSE-011', 'module_id': 'M011-03', 'title': 'Scheduled Jobs, Parameters & Backfills', 'slug': 'scheduled-jobs-parameters-and-backfills', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply scheduled jobs, parameters & backfills concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['cron schedules', 'manual triggers', 'runtime parameters', 'historical backfills', 'repeatable operational jobs']

SOURCE_REFERENCES = ['BOOK-011 Chapters 11, 12, 13']

FIGURE_REFERENCES = [{'source_figure': 'Figure 11-5', 'title': 'Jenkins schedule and shell commands', 'priority': 'required', 'suggested_path': 'assets/m011-03/fig-11-5-jenkins-schedule.png'}]

LESSON_MARKDOWN = '# L011-035 — Scheduled Jobs, Parameters & Backfills\n\n## Learning objective\n\nApply scheduled jobs, parameters & backfills concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- cron schedules\n- manual triggers\n- runtime parameters\n- historical backfills\n- repeatable operational jobs\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n\n## Manual visual references\n- `Figure 11-5` — Jenkins schedule and shell commands (required); add manually at `assets/m011-03/fig-11-5-jenkins-schedule.png`.\n'

EXERCISES = [{'id': 'L011-035-EX1', 'title': 'Apply Scheduled Jobs, Parameters & Backfills', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: cron schedules, manual triggers, runtime parameters. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-035-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to scheduled jobs, parameters & backfills. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-035-Q1', 'type': 'short_answer', 'question': 'What production problem is scheduled jobs, parameters & backfills intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: cron schedules, manual triggers, runtime parameters.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-035-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-035-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Scheduled Jobs, Parameters & Backfills.', 'answer': 'cron schedules, manual triggers', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
