"""Masar curriculum seed — L011-031."""

LESSON_META = {'lesson_id': 'L011-031', 'course_id': 'COURSE-011', 'module_id': 'M011-03', 'title': 'Jenkins as a Deployment & Operations Automation Server', 'slug': 'jenkins-as-a-deployment-and-operations-automation-server', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply jenkins as a deployment & operations automation server concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['Jenkins jobs', 'repeatable automation', 'build steps', 'scheduled and manual execution', 'workspace and logs']

SOURCE_REFERENCES = ['BOOK-011 Chapters 11, 12, 13']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-031 — Jenkins as a Deployment & Operations Automation Server\n\n## Learning objective\n\nApply jenkins as a deployment & operations automation server concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- Jenkins jobs\n- repeatable automation\n- build steps\n- scheduled and manual execution\n- workspace and logs\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-031-EX1', 'title': 'Apply Jenkins as a Deployment & Operations Automation Server', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: Jenkins jobs, repeatable automation, build steps. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-031-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to jenkins as a deployment & operations automation server. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-031-Q1', 'type': 'short_answer', 'question': 'What production problem is jenkins as a deployment & operations automation server intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: Jenkins jobs, repeatable automation, build steps.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-031-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-031-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Jenkins as a Deployment & Operations Automation Server.', 'answer': 'Jenkins jobs, repeatable automation', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
