"""Masar curriculum seed — L011-038."""

LESSON_META = {'lesson_id': 'L011-038', 'course_id': 'COURSE-011', 'module_id': 'M011-03', 'title': 'Connecting Containers to External Cloud Services', 'slug': 'connecting-containers-to-external-cloud-services', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply connecting containers to external cloud services concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['runtime credentials', 'environment variables', 'mounted credential files', 'cloud SDK access', 'externalizing durable state']

SOURCE_REFERENCES = ['BOOK-011 Chapters 11, 12, 13']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-038 — Connecting Containers to External Cloud Services\n\n## Learning objective\n\nApply connecting containers to external cloud services concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- runtime credentials\n- environment variables\n- mounted credential files\n- cloud SDK access\n- externalizing durable state\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-038-EX1', 'title': 'Apply Connecting Containers to External Cloud Services', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: runtime credentials, environment variables, mounted credential files. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-038-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to connecting containers to external cloud services. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-038-Q1', 'type': 'short_answer', 'question': 'What production problem is connecting containers to external cloud services intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: runtime credentials, environment variables, mounted credential files.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-038-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-038-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Connecting Containers to External Cloud Services.', 'answer': 'runtime credentials, environment variables', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
