"""Masar curriculum seed — L011-039."""

LESSON_META = {'lesson_id': 'L011-039', 'course_id': 'COURSE-011', 'module_id': 'M011-03', 'title': 'Production Application Server Architecture', 'slug': 'production-application-server-architecture', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply production application server architecture concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['development vs production server', 'Gunicorn-style process management', 'workers and concurrency', 'request timeouts', 'container entry points']

SOURCE_REFERENCES = ['BOOK-011 Chapters 11, 12, 13']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-039 — Production Application Server Architecture\n\n## Learning objective\n\nApply production application server architecture concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- development vs production server\n- Gunicorn-style process management\n- workers and concurrency\n- request timeouts\n- container entry points\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-039-EX1', 'title': 'Apply Production Application Server Architecture', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: development vs production server, Gunicorn-style process management, workers and concurrency. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-039-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to production application server architecture. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-039-Q1', 'type': 'short_answer', 'question': 'What production problem is production application server architecture intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: development vs production server, Gunicorn-style process management, workers and concurrency.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-039-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-039-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Production Application Server Architecture.', 'answer': 'development vs production server, Gunicorn-style process management', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
