"""Masar curriculum seed — L011-033."""

LESSON_META = {'lesson_id': 'L011-033', 'course_id': 'COURSE-011', 'module_id': 'M011-03', 'title': 'Cloud Object Storage as a Production Dependency', 'slug': 'cloud-object-storage-as-a-production-dependency', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply cloud object storage as a production dependency concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['AWS S3', 'Google Cloud Storage', 'durable data outside containers', 'read/write permissions', 'object storage for artifacts and outputs']

SOURCE_REFERENCES = ['BOOK-011 Chapters 11, 12, 13']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-033 — Cloud Object Storage as a Production Dependency\n\n## Learning objective\n\nApply cloud object storage as a production dependency concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- AWS S3\n- Google Cloud Storage\n- durable data outside containers\n- read/write permissions\n- object storage for artifacts and outputs\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-033-EX1', 'title': 'Apply Cloud Object Storage as a Production Dependency', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: AWS S3, Google Cloud Storage, durable data outside containers. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-033-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to cloud object storage as a production dependency. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-033-Q1', 'type': 'short_answer', 'question': 'What production problem is cloud object storage as a production dependency intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: AWS S3, Google Cloud Storage, durable data outside containers.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-033-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-033-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Cloud Object Storage as a Production Dependency.', 'answer': 'AWS S3, Google Cloud Storage', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
