"""Masar curriculum seed — L011-034."""

LESSON_META = {'lesson_id': 'L011-034', 'course_id': 'COURSE-011', 'module_id': 'M011-03', 'title': 'Cross-Cloud Automation from One Workload', 'slug': 'cross-cloud-automation-from-one-workload', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply cross-cloud automation from one workload concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['provider SDKs', 'runtime provider selection', 'portable automation logic', 'cross-cloud credentials', 'avoiding hard-coded provider assumptions']

SOURCE_REFERENCES = ['BOOK-011 Chapters 11, 12, 13']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-034 — Cross-Cloud Automation from One Workload\n\n## Learning objective\n\nApply cross-cloud automation from one workload concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- provider SDKs\n- runtime provider selection\n- portable automation logic\n- cross-cloud credentials\n- avoiding hard-coded provider assumptions\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-034-EX1', 'title': 'Apply Cross-Cloud Automation from One Workload', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: provider SDKs, runtime provider selection, portable automation logic. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-034-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to cross-cloud automation from one workload. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-034-Q1', 'type': 'short_answer', 'question': 'What production problem is cross-cloud automation from one workload intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: provider SDKs, runtime provider selection, portable automation logic.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-034-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-034-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Cross-Cloud Automation from One Workload.', 'answer': 'provider SDKs, runtime provider selection', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
