COURSE_MANIFEST = {'course_id': 'COURSE-009',
 'course_title': 'Enterprise RAG Engineering',
 'source_id': 'BOOK-009',
 'book_title': 'SOURCE INFORMATION MISSING',
 'edition': 'SOURCE INFORMATION MISSING',
 'status': 'Curriculum design finalized / course-folder seed export generated',
 'approval_status': 'Not explicitly approved',
 'source_review': 'Complete — Chapters 1–10 processed',
 'modules': 10,
 'lessons': 80,
 'guided_minutes': 4335,
 'guided_time': '72h 15m',
 'lesson_id_range': 'L009-001..L009-080',
 'module_id_range': 'M009-01..M009-10',
 'level': 'Advanced',
 'learning_loop': 'Learn → Practice → Build → Debug → Evaluate → Operate',
 'professional_capability': 'Engineer production RAG systems that combine high-precision '
                            'retrieval, enterprise data ingestion, grounding and hallucination '
                            'control, rigorous evaluation, agentic and multimodal retrieval, '
                            'knowledge-graph enhancement, latency/cost optimization, '
                            'observability, governance, and production resiliency.',
 'prerequisites': ['COURSE-005 — Applied LLM Engineering',
                   'COURSE-006 — Production AI Engineering',
                   'COURSE-007 — Advanced LLM Systems & Application Architecture',
                   'COURSE-008 — Vision-Language & Multimodal AI Engineering (specialized '
                   'supporting background)'],
 'track_roles': {'Data Analyst': 'Optional',
                 'ML Engineer': 'Core',
                 'AI Developer': 'Core',
                 'MLOps Engineer': 'Core',
                 'AI Engineer': 'Core'},
 'modules_detail': [{'module_id': 'M009-01',
                     'title': 'Production RAG Architecture & Failure Analysis',
                     'objective': 'Diagnose the gap between a RAG demo and an enterprise '
                                  'production system.',
                     'lessons': 4,
                     'guided_minutes': 170,
                     'lesson_ids': ['L009-001', 'L009-002', 'L009-003', 'L009-004'],
                     'project': {'title': 'Production Readiness Audit',
                                 'description': 'Audit an intentionally simplistic RAG application '
                                                'and produce a prioritized production-hardening '
                                                'plan.',
                                 'objectives': ['Map failure surfaces',
                                                'Define measurable requirements',
                                                'Prioritize quality, security, latency, freshness, '
                                                'and observability work'],
                                 'tech_stack': ['Python',
                                                'architecture diagrams',
                                                'RAG system traces'],
                                 'estimated_hours': 4}},
                    {'module_id': 'M009-02',
                     'title': 'Enterprise Data Ingestion & Document Engineering',
                     'objective': 'Build ingestion pipelines that preserve structure, metadata, '
                                  'freshness, and retrievability.',
                     'lessons': 8,
                     'guided_minutes': 435,
                     'lesson_ids': ['L009-005',
                                    'L009-006',
                                    'L009-007',
                                    'L009-008',
                                    'L009-009',
                                    'L009-010',
                                    'L009-011',
                                    'L009-012'],
                     'project': {'title': 'Versioned Enterprise Ingestion Pipeline',
                                 'description': 'Build an idempotent ingestion workflow with '
                                                'document IDs, versions, metadata validation, '
                                                'staging index tests, and safe promotion.',
                                 'objectives': ['Preserve provenance',
                                                'Detect malformed extraction',
                                                'Handle updates/deletes',
                                                'Prove retrievability before promotion'],
                                 'tech_stack': ['Python', 'document parser', 'vector store'],
                                 'estimated_hours': 6}},
                    {'module_id': 'M009-03',
                     'title': 'High-Precision Retrieval: Hybrid Search & Reranking',
                     'objective': 'Engineer retrieval systems for precision, recall, ranking '
                                  'quality, and scale.',
                     'lessons': 8,
                     'guided_minutes': 435,
                     'lesson_ids': ['L009-013',
                                    'L009-014',
                                    'L009-015',
                                    'L009-016',
                                    'L009-017',
                                    'L009-018',
                                    'L009-019',
                                    'L009-077'],
                     'project': {'title': 'Retrieval Quality Tournament',
                                 'description': 'Compare dense, lexical, hybrid, reranked, and '
                                                'late-interaction retrieval on a fixed evaluation '
                                                'set.',
                                 'objectives': ['Measure recall/precision',
                                                'Tune candidate depth',
                                                'Quantify reranker value',
                                                'Compare quality/latency/storage trade-offs'],
                                 'tech_stack': ['Python', 'BM25', 'vector DB', 'reranker'],
                                 'estimated_hours': 7}},
                    {'module_id': 'M009-04',
                     'title': 'Agentic Retrieval & Agentic RAG',
                     'objective': 'Use goal-driven retrieval, tools, memory, and controlled agent '
                                  'loops when one-shot retrieval is insufficient.',
                     'lessons': 8,
                     'guided_minutes': 440,
                     'lesson_ids': ['L009-051',
                                    'L009-052',
                                    'L009-053',
                                    'L009-054',
                                    'L009-055',
                                    'L009-056',
                                    'L009-057',
                                    'L009-058'],
                     'project': {'title': 'Budgeted Agentic Research Retriever',
                                 'description': 'Build a retrieval agent with explicit tool '
                                                'schemas, retry logic, trace capture, evidence '
                                                'checks, and hard execution budgets.',
                                 'objectives': ['Control tool use',
                                                'Prevent runaway loops',
                                                'Trace retrieval decisions',
                                                'Compare agentic vs one-shot retrieval'],
                                 'tech_stack': ['Python',
                                                'agent framework',
                                                'retrieval tools',
                                                'tracing'],
                                 'estimated_hours': 7}},
                    {'module_id': 'M009-05',
                     'title': 'Grounding, Hallucination Control & RAG Guardrails',
                     'objective': 'Detect unsupported answers, enforce evidence sufficiency, '
                                  'verify citations, and design safe fallbacks.',
                     'lessons': 6,
                     'guided_minutes': 330,
                     'lesson_ids': ['L009-020',
                                    'L009-021',
                                    'L009-022',
                                    'L009-023',
                                    'L009-024',
                                    'L009-025'],
                     'project': {'title': 'Evidence Gate & Citation Verifier',
                                 'description': 'Create an answerability and evidence-sufficiency '
                                                'layer that verifies claims and citations before '
                                                'an answer is released.',
                                 'objectives': ['Detect unsupported claims',
                                                'Abstain safely',
                                                'Verify citations',
                                                'Implement fallbacks'],
                                 'tech_stack': ['Python', 'LLM', 'retrieval pipeline'],
                                 'estimated_hours': 6}},
                    {'module_id': 'M009-06',
                     'title': 'RAG Evaluation Engineering',
                     'objective': 'Measure retrieval, generation, end-to-end quality, consistency, '
                                  'safety, and production health.',
                     'lessons': 10,
                     'guided_minutes': 545,
                     'lesson_ids': ['L009-041',
                                    'L009-042',
                                    'L009-043',
                                    'L009-044',
                                    'L009-045',
                                    'L009-046',
                                    'L009-047',
                                    'L009-048',
                                    'L009-049',
                                    'L009-050'],
                     'project': {'title': 'RAG Evaluation Harness',
                                 'description': 'Build a repeatable evaluation suite covering '
                                                'retrieval, faithfulness, citations, consistency, '
                                                'latency, and cost.',
                                 'objectives': ['Create a versioned benchmark',
                                                'Implement deterministic metrics',
                                                'Add judge-based metrics',
                                                'Enforce release gates'],
                                 'tech_stack': ['Python',
                                                'pytest',
                                                'evaluation framework',
                                                'RAG traces'],
                                 'estimated_hours': 8}},
                    {'module_id': 'M009-07',
                     'title': 'Multimodal Enterprise RAG',
                     'objective': 'Integrate tables, images, audio, and video into enterprise '
                                  'retrieval without duplicating VLM foundations.',
                     'lessons': 9,
                     'guided_minutes': 495,
                     'lesson_ids': ['L009-059',
                                    'L009-060',
                                    'L009-061',
                                    'L009-062',
                                    'L009-063',
                                    'L009-064',
                                    'L009-065',
                                    'L009-066',
                                    'L009-067'],
                     'project': {'title': 'Multimodal Enterprise Knowledge Retriever',
                                 'description': 'Ingest text plus tables/images or audio/video '
                                                'while preserving structured/spatial/temporal '
                                                'provenance.',
                                 'objectives': ['Preserve modality alignment',
                                                'Return media citations',
                                                'Evaluate multimodal retrieval',
                                                'Trace extraction failures'],
                                 'tech_stack': ['Python',
                                                'Docling or equivalent',
                                                'VLM/ASR',
                                                'vector store'],
                                 'estimated_hours': 8}},
                    {'module_id': 'M009-08',
                     'title': 'Knowledge-Enhanced RAG',
                     'objective': 'Use knowledge graphs, graph enrichment, and graph-hybrid '
                                  'retrieval where relationship-aware retrieval adds measurable '
                                  'value.',
                     'lessons': 9,
                     'guided_minutes': 495,
                     'lesson_ids': ['L009-068',
                                    'L009-069',
                                    'L009-070',
                                    'L009-071',
                                    'L009-072',
                                    'L009-073',
                                    'L009-074',
                                    'L009-075',
                                    'L009-076'],
                     'project': {'title': 'Knowledge-Enhanced RAG Pilot',
                                 'description': 'Add graph enrichment or graph-hybrid retrieval to '
                                                'a dataset with real relationship-heavy queries '
                                                'and prove its value with evals.',
                                 'objectives': ['Build a focused ontology/schema',
                                                'Link entities',
                                                'Run graph-assisted queries',
                                                'Measure ROI vs standard RAG'],
                                 'tech_stack': ['Python',
                                                'Neo4j/Kuzu or equivalent',
                                                'vector store'],
                                 'estimated_hours': 8}},
                    {'module_id': 'M009-09',
                     'title': 'Production Performance, Governance, Observability & Resiliency',
                     'objective': 'Operate RAG under latency, security, cost, availability, '
                                  'provenance, and lifecycle constraints.',
                     'lessons': 9,
                     'guided_minutes': 490,
                     'lesson_ids': ['L009-026',
                                    'L009-027',
                                    'L009-028',
                                    'L009-029',
                                    'L009-030',
                                    'L009-031',
                                    'L009-032',
                                    'L009-033',
                                    'L009-034'],
                     'project': {'title': 'Production RAG Operations Lab',
                                 'description': 'Instrument a RAG service with stage-level '
                                                'latency, cost, permission, cache, error, and '
                                                'quality telemetry and run failure drills.',
                                 'objectives': ['Find bottlenecks',
                                                'Test cache invalidation',
                                                'Exercise permission boundaries',
                                                'Define operational alerts'],
                                 'tech_stack': ['Python',
                                                'FastAPI',
                                                'Redis',
                                                'OpenTelemetry-compatible tracing'],
                                 'estimated_hours': 8}},
                    {'module_id': 'M009-10',
                     'title': 'Enterprise RAG Evolution, System Integration & Capstone',
                     'objective': 'Choose platform/deployment patterns, federate enterprise data, '
                                  'engineer context, and integrate the full system.',
                     'lessons': 9,
                     'guided_minutes': 500,
                     'lesson_ids': ['L009-035',
                                    'L009-036',
                                    'L009-037',
                                    'L009-038',
                                    'L009-039',
                                    'L009-040',
                                    'L009-078',
                                    'L009-079',
                                    'L009-080'],
                     'project': {'title': 'Production Enterprise Knowledge Assistant',
                                 'description': 'Capstone: integrate heterogeneous ingestion, '
                                                'high-precision retrieval, grounding controls, '
                                                'evaluation, observability, federation, and '
                                                'production decision records.',
                                 'objectives': ['Ship an evaluated architecture',
                                                'Document evidence/provenance',
                                                'Meet defined latency/cost/quality budgets',
                                                'Produce a production-readiness review'],
                                 'tech_stack': ['Python',
                                                'RAG stack',
                                                'evaluation harness',
                                                'observability',
                                                'optional graph/agent tools'],
                                 'estimated_hours': 14}}],
 'visual_assets': [{'chapter': 1,
                    'figure': 'Figure 1-2',
                    'title': 'The RAG stack',
                    'lesson_id': 'L009-002',
                    'filename': 'fig_01_02_rag_stack.png'},
                   {'chapter': 4,
                    'figure': 'Figure 4-1',
                    'title': 'Cascading model approach via LLM router',
                    'lesson_id': 'L009-033',
                    'filename': 'fig_04_01_model_cascade.png'},
                   {'chapter': 4,
                    'figure': 'Figure 4-2',
                    'title': 'Example production architecture for RAG',
                    'lesson_id': 'L009-028',
                    'filename': 'fig_04_02_production_rag_architecture.png'},
                   {'chapter': 5,
                    'figure': 'Figure 5-1',
                    'title': 'Centralized RAG platform governance',
                    'lesson_id': 'L009-038',
                    'filename': 'fig_05_01_rag_platform_governance.png'},
                   {'chapter': 6,
                    'figure': 'Figure 6-1',
                    'title': 'Open Evaluation interface',
                    'lesson_id': 'L009-050',
                    'filename': 'fig_06_01_open_evaluation.png'},
                   {'chapter': 7,
                    'figure': 'Figure 7-2',
                    'title': 'The agentic stack',
                    'lesson_id': 'L009-051',
                    'filename': 'fig_07_02_agentic_stack.png'},
                   {'chapter': 7,
                    'figure': 'Figure 7-4',
                    'title': 'Orchestrator-worker multi-agent pattern',
                    'lesson_id': 'L009-052',
                    'filename': 'fig_07_04_orchestrator_worker.png'},
                   {'chapter': 7,
                    'figure': 'Figure 7-5',
                    'title': 'Model Context Protocol architecture',
                    'lesson_id': 'L009-055',
                    'filename': 'fig_07_05_mcp_architecture.png'},
                   {'chapter': 8,
                    'figure': 'Figure 8-2',
                    'title': 'Table processing flow in RAG',
                    'lesson_id': 'L009-061',
                    'filename': 'fig_08_02_table_rag_flow.png'},
                   {'chapter': 8,
                    'figure': 'Figure 8-5',
                    'title': 'Shared embedding space for text and images',
                    'lesson_id': 'L009-063',
                    'filename': 'fig_08_05_shared_embedding_space.png'},
                   {'chapter': 8,
                    'figure': 'Figure 8-8',
                    'title': 'Aligned chunk vs orphan chunk',
                    'lesson_id': 'L009-066',
                    'filename': 'fig_08_08_modality_alignment.png'},
                   {'chapter': 9,
                    'figure': 'Figure 9-2',
                    'title': 'Chunk enrichment workflow',
                    'lesson_id': 'L009-071',
                    'filename': 'fig_09_02_chunk_enrichment.png'},
                   {'chapter': 9,
                    'figure': 'Figure 9-3',
                    'title': 'Graph query generation in a RAG pipeline',
                    'lesson_id': 'L009-072',
                    'filename': 'fig_09_03_graph_hybrid_retrieval.png'},
                   {'chapter': 10,
                    'figure': 'Figure 10-1',
                    'title': 'RAG filtering for long-context models',
                    'lesson_id': 'L009-079',
                    'filename': 'fig_10_01_context_filtering.png'}]}
