"""Masar COURSE-013 lesson seed.

This file is intentionally plain-Python and framework-neutral so it can be
adapted to the application seeding layer without assuming unprovided DB fields.
"""

LESSON_META = {'lesson_id': 'L013-002', 'module_id': 'M013-01', 'title': 'Choosing a Data Analysis Methodology', 'slug': 'choosing-a-data-analysis-methodology', 'learning_objective': 'Choose and apply an analysis methodology that keeps business goals, data work, and iteration aligned.', 'concepts': ['CRISP-DM', 'analysis methodology', 'iteration', 'stakeholder alignment'], 'source_references': [{'source_id': 'BOOK-013', 'chapter': 1}], 'difficulty': 'Beginner', 'estimated_minutes': 45, 'prerequisites': ['L013-001'], 'practice': {'type': 'guided_lab', 'description': 'Use a realistic analyst dataset to practice choosing a data analysis methodology, document assumptions, and validate the result.', 'deliverable': 'A reproducible notebook or script plus a short analytical interpretation.'}, 'assessment': {'type': 'applied_check', 'description': 'Complete a scenario-based task demonstrating correct use of choosing a data analysis methodology and explain the decision or result.'}, 'status': 'curriculum_finalized_content_seed'}

TOPIC = {'lesson_id': 'L013-002', 'module_id': 'M013-01', 'slug': 'choosing-a-data-analysis-methodology', 'title': 'Choosing a Data Analysis Methodology', 'content_markdown': ('# L013-002 — Choosing a Data Analysis Methodology\n'
                                                                                                                                                                                '\n'
                                                                                                                                                                                '## Learning objective\n'
                                                                                                                                                                                'Choose and apply an analysis methodology that keeps business goals, data work, and iteration aligned.\n'
                                                                                                                                                                                '\n'
                                                                                                                                                                                '## Why this matters\n'
                                                                                                                                                                                'This lesson develops a practical Data Analyst capability inside **Data Analysis Workflow, Roles & Python Workspace**. The focus is correct method selection, reproducible implementation, validation, and clear interpretation rather than memorizing APIs.\n'
                                                                                                                                                                                '\n'
                                                                                                                                                                                '## Core concepts\n'
                                                                                                                                                                                '- CRISP-DM\n'
                                                                                                                                                                                '- analysis methodology\n'
                                                                                                                                                                                '- iteration\n'
                                                                                                                                                                                '- stakeholder alignment\n'
                                                                                                                                                                                '\n'
                                                                                                                                                                                '## Source mapping\n'
                                                                                                                                                                                '- BOOK-013 — Chapter 1\n'
                                                                                                                                                                                '\n'
                                                                                                                                                                                '## Learn\n'
                                                                                                                                                                                'Work through the concepts using a realistic business dataset. Explain what the method does, what assumptions or data conditions matter, and what can go wrong if it is applied mechanically.\n'
                                                                                                                                                                                '\n'
                                                                                                                                                                                '{{figure:crisp-dm}}\n'
                                                                                                                                                                                '\n'
                                                                                                                                                                                '## Practice\n'
                                                                                                                                                                                'Use a realistic analyst dataset to practice choosing a data analysis methodology, document assumptions, and validate the result.\n'
                                                                                                                                                                                '\n'
                                                                                                                                                                                '**Deliverable:** A reproducible notebook or script plus a short analytical interpretation.\n'
                                                                                                                                                                                '\n'
                                                                                                                                                                                '## Analyst checks\n'
                                                                                                                                                                                '- State the business/analytical objective before applying the technique.\n'
                                                                                                                                                                                '- Inspect and validate inputs before trusting outputs.\n'
                                                                                                                                                                                '- Keep transformations reproducible.\n'
                                                                                                                                                                                '- Protect raw data and final evaluation data when relevant.\n'
                                                                                                                                                                                '- Separate observed evidence from causal or business conclusions.\n'
                                                                                                                                                                                '\n'
                                                                                                                                                                                '## Assessment\n'
                                                                                                                                                                                'Complete a scenario-based task demonstrating correct use of choosing a data analysis methodology and explain the decision or result.\n'), 'exercises': [{'title': 'Guided practice — Choosing a Data Analysis Methodology', 'instructions': 'Apply CRISP-DM, analysis methodology, iteration to a small realistic dataset. Record assumptions and validate the output.', 'expected_output': 'Working code/notebook with a concise interpretation.'}, {'title': 'Analyst decision challenge', 'instructions': 'Given a changed business scenario, choose the appropriate method, justify it, and identify one failure mode or limitation.', 'expected_output': 'A short written decision plus any supporting code or calculation.'}], 'quiz': [{'question': 'What is the primary purpose of CRISP-DM in this lesson?', 'options': ['Support the analytical objective', 'Replace validation', 'Guarantee causality', 'Remove the need for data quality checks'], 'answer': 'Support the analytical objective', 'explanation': 'CRISP-DM is useful only when it supports the analytical objective and is validated in context.'}, {'question': 'Which statement best reflects good practice when using analysis methodology?', 'options': ['Apply it deliberately and validate assumptions', 'Always use the default without checking', 'Use it only after the test set is inspected', 'Treat it as proof of causality'], 'answer': 'Apply it deliberately and validate assumptions', 'explanation': 'Masar emphasizes explicit assumptions, validation, and business context rather than mechanical defaults.'}, {'question': 'Which workflow principle applies throughout COURSE-013?', 'options': ['Keep the work reproducible and document decisions', 'Overwrite raw data to save space', 'Evaluate on the training set only', 'Hide assumptions from stakeholders'], 'answer': 'Keep the work reproducible and document decisions', 'explanation': 'Reproducibility, transparent assumptions, and protected raw data are recurring course standards.'}], 'project_contribution': 'Analyst Workspace & Business Problem Framing Sprint'}
