"""M01.L02 — End-to-End Machine Learning Project.

One source chapter -> one complete learner-facing lesson + inline Images +
inline Exercises + lesson Quiz.

Source alignment: Chapter 2 supplied by the course author.
Instructor-authored curriculum adaptation.
"""

from app.models.learning import DifficultyLevel


# ---------------------------------------------------------------------------
# Lesson metadata
# ---------------------------------------------------------------------------

LESSON_CODE = "M01.L02"

MODULE_ORDER = 1

MODULE_TITLE = "Building a Machine Learning System"

MODULE_DESCRIPTION = (
    "Learn the complete machine learning workflow by taking a real regression "
    "project from business framing and data inspection through preprocessing, "
    "model selection, tuning, final evaluation, deployment, and monitoring."
)

SOURCE_CHAPTER = 2

SOURCE_PAGES = "Not provided in the supplied chapter extract"


# ---------------------------------------------------------------------------
# Topic
# ---------------------------------------------------------------------------

TOPIC = {
    "title": "End-to-End Machine Learning Project",

    "slug": "machine-learning-foundations-m01-l02",

    "description": (
        "A complete project-driven lesson using the California housing dataset "
        "to teach problem framing, safe dataset splitting, exploratory analysis, "
        "feature engineering, Scikit-Learn preprocessing pipelines, model "
        "evaluation, hyperparameter tuning, final testing, deployment, and MLOps."
    ),

    "order": 2,

    "difficulty": DifficultyLevel.beginner,

    "estimated_hours": 4.5,

    "skill_tags": [
        "machine-learning",
        "end-to-end-ml",
        "regression",
        "data-preparation",
        "feature-engineering",
        "scikit-learn",
        "pipelines",
        "cross-validation",
        "hyperparameter-tuning",
        "mlops",
    ],

    "prerequisite_ids": [
        "M01.L01",
    ],


    # =======================================================================
    # INLINE IMAGE RULES
    # =======================================================================
    #
    # Only figures from the supplied Chapter 2 that materially improve
    # understanding are requested below. Decorative screenshots and figures
    # that merely repeat simple table/code output are intentionally omitted.
    #
    # Every request includes the original source figure number and a stable
    # key for later manual linking.
    #
    # =======================================================================
    # LESSON
    # =======================================================================

    "lesson": {
        "title": "End-to-End Machine Learning Project",

        "content": (
            "# End-to-End Machine Learning Project\n"
            "\n"
            "> **Course:** Applied Machine Learning with Scikit-Learn  \n"
            "> **Lesson:** M01.L02  \n"
            "> **Module:** Building a Machine Learning System  \n"
            "> **Source alignment:** Chapter 2, “End-to-End Machine Learning Project,” supplied by the course author. Page numbers were not included in the supplied extract. This lesson is an instructor-authored curriculum adaptation rather than a reproduction of the source text.\n"
            "\n"
            "---\n"
            "\n"
            "## Learning outcomes\n"
            "\n"
            "By the end of this lesson, you should be able to:\n"
            "\n"
            "- Translate a business objective into a well-framed machine learning problem.\n"
            "- Choose an appropriate learning setup and regression performance measure.\n"
            "- Load, inspect, split, explore, and visualize a real dataset without leaking information from the test set.\n"
            "- Explain why stratified sampling can produce a more representative test set than purely random sampling.\n"
            "- Identify useful relationships, data quirks, skewed distributions, and promising engineered features during exploratory data analysis.\n"
            "- Build reproducible preprocessing steps for missing values, categorical features, feature scaling, skewed features, and custom transformations.\n"
            "- Use Scikit-Learn estimators, transformers, pipelines, and column transformers correctly.\n"
            "- Train baseline models and diagnose underfitting or overfitting using training performance and cross-validation.\n"
            "- Fine-tune a model using grid search or randomized search without contaminating the final test set.\n"
            "- Inspect feature importance and model errors before final evaluation.\n"
            "- Evaluate the final model on the test set and communicate uncertainty and limitations.\n"
            "- Explain the basic production lifecycle: serialization, serving, monitoring, retraining, rollback, and data/model versioning.\n"
            "\n"
            "---\n"
            "\n"
            "## 1. Start with the problem, not the algorithm\n"
            "\n"
            "A real machine learning project should not begin with:\n"
            "\n"
            "> “Which model should I train?”\n"
            "\n"
            "It should begin with:\n"
            "\n"
            "> **“What problem are we solving, how will the prediction be used, and what does success mean?”**\n"
            "\n"
            "The chapter uses a California housing project. The goal is to predict the **median house value of a district** from other information about that district, such as location, population, housing age, and median income.\n"
            "\n"
            "This may sound like a straightforward prediction task, but the business context matters. The prediction is not the final business decision. It becomes an input to a downstream investment-analysis system.\n"
            "\n"
            "That changes how seriously we should think about:\n"
            "\n"
            "- prediction accuracy,\n"
            "- failure modes,\n"
            "- update frequency,\n"
            "- reproducibility,\n"
            "- interfaces between components,\n"
            "- and monitoring.\n"
            "\n"
            "{{image:housing-business-ml-pipeline}}\n"
            "\n"
            "### Frame the learning problem\n"
            "\n"
            "Ask the main ML classification questions:\n"
            "\n"
            "**Is it supervised?**\n"
            "\n"
            "Yes. Each district has input features and a known target, `median_house_value`.\n"
            "\n"
            "**Classification or regression?**\n"
            "\n"
            "Regression, because the target is a numeric value.\n"
            "\n"
            "**Single or multiple input features?**\n"
            "\n"
            "Multiple features are used, so this is **multiple regression**.\n"
            "\n"
            "**One or multiple targets?**\n"
            "\n"
            "Only one value is predicted for each district, so it is a **univariate regression** problem.\n"
            "\n"
            "**Batch or online learning?**\n"
            "\n"
            "The data is small enough to fit in memory, there is no continuous high-speed stream, and rapid adaptation is not required. A batch-learning approach is reasonable.\n"
            "\n"
            "This simple classification immediately narrows the design space.\n"
            "\n"
            "### Understand the current solution\n"
            "\n"
            "Before replacing an existing process, understand it.\n"
            "\n"
            "In the chapter, experts manually estimate district prices and can be wrong by more than 30%. That gives us:\n"
            "\n"
            "- a business baseline,\n"
            "- a reason to automate,\n"
            "- and a rough reference for whether the ML solution is valuable.\n"
            "\n"
            "A machine learning model does not need to be academically impressive to be useful. It needs to improve the real workflow enough to justify its cost and risk.\n"
            "\n"
            "### Pipelines are part of the system\n"
            "\n"
            "A **data pipeline** is a sequence of processing components.\n"
            "\n"
            "Conceptually:\n"
            "\n"
            "```text\n"
            "raw data\n"
            "   |\n"
            "ingestion\n"
            "   |\n"
            "validation\n"
            "   |\n"
            "preprocessing\n"
            "   |\n"
            "model\n"
            "   |\n"
            "prediction\n"
            "   |\n"
            "downstream application\n"
            "```\n"
            "\n"
            "Pipeline components are often separated so different teams can develop and operate them independently.\n"
            "\n"
            "This can make a system robust, but it creates a danger: a broken upstream component may keep producing stale or corrupted outputs while downstream components continue running.\n"
            "\n"
            "So a pipeline without monitoring is not truly reliable.\n"
            "\n"
            "### Choose the performance measure before training\n"
            "\n"
            "For a regression task, the chapter focuses on **root mean squared error (RMSE)**.\n"
            "\n"
            "For predictions `ŷ(i)` and true targets `y(i)`:\n"
            "\n"
            "```text\n"
            "RMSE = sqrt(\n"
            "    average of (prediction - target)^2\n"
            ")\n"
            "```\n"
            "\n"
            "RMSE penalizes larger errors more heavily because errors are squared.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "true price      = $200,000\n"
            "predicted price = $230,000\n"
            "error           = $30,000\n"
            "```\n"
            "\n"
            "If several predictions have very large errors, RMSE rises sharply.\n"
            "\n"
            "Another common measure is **mean absolute error (MAE)**:\n"
            "\n"
            "```text\n"
            "MAE = average of |prediction - target|\n"
            "```\n"
            "\n"
            "MAE is generally less sensitive to large outliers.\n"
            "\n"
            "A practical interpretation:\n"
            "\n"
            "```text\n"
            "RMSE -> care more strongly about large mistakes\n"
            "MAE  -> treat error magnitude more linearly\n"
            "```\n"
            "\n"
            "The source connects RMSE with the `L2` norm and MAE with the `L1` norm. You do not need to memorize all norm notation yet, but you should understand the practical difference: **the choice of metric changes what the model is rewarded or punished for.**\n"
            "\n"
            "### Check assumptions before coding\n"
            "\n"
            "Suppose the downstream system only needs three categories:\n"
            "\n"
            "```text\n"
            "cheap\n"
            "medium\n"
            "expensive\n"
            "```\n"
            "\n"
            "Then building a highly precise regression system may be unnecessary. The project might be better framed as classification.\n"
            "\n"
            "That is why assumptions must be verified with stakeholders before months of modeling work.\n"
            "\n"
            "A technically correct solution to the wrong problem is still a failed project.\n"
            "\n"
            "---\n"
            "\n"
            "## 2. Get the data, inspect it, and create the test set early\n"
            "\n"
            "The project uses a real housing dataset rather than a toy dataset. That matters because real data contains:\n"
            "\n"
            "- missing values,\n"
            "- categorical fields,\n"
            "- unusual distributions,\n"
            "- capped values,\n"
            "- different feature scales,\n"
            "- and relationships you do not know in advance.\n"
            "\n"
            "### Automate data loading\n"
            "\n"
            "Instead of manually downloading files, make data acquisition reproducible.\n"
            "\n"
            "A simplified version of the chapter’s loader is:\n"
            "\n"
            "```python\n"
            "from pathlib import Path\n"
            "import pandas as pd\n"
            "import tarfile\n"
            "import urllib.request\n"
            "\n"
            "def load_housing_data():\n"
            "    tarball_path = Path(\"datasets/housing.tgz\")\n"
            "\n"
            "    if not tarball_path.is_file():\n"
            "        Path(\"datasets\").mkdir(parents=True, exist_ok=True)\n"
            "\n"
            "        url = \"https://github.com/ageron/data/raw/main/housing.tgz\"\n"
            "        urllib.request.urlretrieve(url, tarball_path)\n"
            "\n"
            "        with tarfile.open(tarball_path) as housing_tarball:\n"
            "            housing_tarball.extractall(path=\"datasets\", filter=\"data\")\n"
            "\n"
            "    return pd.read_csv(Path(\"datasets/housing/housing.csv\"))\n"
            "\n"
            "housing_full = load_housing_data()\n"
            "```\n"
            "\n"
            "Why automate this?\n"
            "\n"
            "Because the same process may need to run:\n"
            "\n"
            "- on another machine,\n"
            "- after the dataset changes,\n"
            "- in a scheduled training job,\n"
            "- or in production.\n"
            "\n"
            "Reproducibility starts before model training.\n"
            "\n"
            "### Inspect the schema before doing serious analysis\n"
            "\n"
            "Useful first commands include:\n"
            "\n"
            "```python\n"
            "housing_full.head()\n"
            "housing_full.info()\n"
            "housing_full.describe()\n"
            "housing_full[\"ocean_proximity\"].value_counts()\n"
            "```\n"
            "\n"
            "From `info()` you learn:\n"
            "\n"
            "- number of rows,\n"
            "- column names,\n"
            "- data types,\n"
            "- missing-value counts.\n"
            "\n"
            "The source dataset has `20,640` districts and ten attributes. One feature, `total_bedrooms`, has missing values.\n"
            "\n"
            "The `ocean_proximity` field is text and repeats a small number of values, so it is a **categorical feature** rather than arbitrary free text.\n"
            "\n"
            "`describe()` helps reveal:\n"
            "\n"
            "- mean,\n"
            "- standard deviation,\n"
            "- minimum,\n"
            "- maximum,\n"
            "- quartiles.\n"
            "\n"
            "These are not just statistics for a report. They help you find problems before modeling.\n"
            "\n"
            "### Plot distributions\n"
            "\n"
            "Histograms reveal things that summary statistics can hide.\n"
            "\n"
            "```python\n"
            "import matplotlib.pyplot as plt\n"
            "\n"
            "housing_full.hist(bins=50, figsize=(12, 8))\n"
            "plt.show()\n"
            "```\n"
            "\n"
            "The chapter notices several important issues:\n"
            "\n"
            "- `median_income` has already been scaled and capped.\n"
            "- `housing_median_age` is capped.\n"
            "- the target `median_house_value` is capped.\n"
            "- numerical features have very different scales.\n"
            "- many features are strongly right-skewed.\n"
            "\n"
            "{{image:housing-feature-histograms}}\n"
            "\n"
            "A capped target is especially important.\n"
            "\n"
            "If the training data says:\n"
            "\n"
            "```text\n"
            "all values above a threshold -> exactly the same capped target\n"
            "```\n"
            "\n"
            "then the model cannot learn the true relationship above that threshold.\n"
            "\n"
            "You need to ask whether the production system requires accurate predictions beyond the cap.\n"
            "\n"
            "### Create the test set before deep exploration\n"
            "\n"
            "This is one of the most important habits in the chapter.\n"
            "\n"
            "If you deeply inspect the full dataset before creating the test set, your own decisions may adapt to patterns that should have remained unseen.\n"
            "\n"
            "This is **data snooping bias**.\n"
            "\n"
            "A simple split is:\n"
            "\n"
            "```python\n"
            "from sklearn.model_selection import train_test_split\n"
            "\n"
            "train_set, test_set = train_test_split(\n"
            "    housing_full,\n"
            "    test_size=0.2,\n"
            "    random_state=42,\n"
            ")\n"
            "```\n"
            "\n"
            "The `random_state` makes the split reproducible.\n"
            "\n"
            "But reproducibility alone does not guarantee representativeness.\n"
            "\n"
            "### Why a stable split matters\n"
            "\n"
            "If a new random test set is created every time the program runs, then over repeated experimentation you may effectively expose yourself to most of the dataset.\n"
            "\n"
            "For datasets that evolve over time, a stable immutable identifier can be hashed to decide whether an instance belongs in the test set.\n"
            "\n"
            "The core idea is:\n"
            "\n"
            "```text\n"
            "same instance ID\n"
            "    ->\n"
            "same deterministic split decision\n"
            "```\n"
            "\n"
            "That allows the dataset to grow without constantly moving old training examples into the test set or vice versa.\n"
            "\n"
            "### Stratified sampling\n"
            "\n"
            "Purely random sampling can accidentally create a test set with distorted proportions, especially when the dataset is not extremely large.\n"
            "\n"
            "If domain knowledge says `median_income` is particularly important, the test set should represent the income distribution well.\n"
            "\n"
            "The chapter first creates income categories:\n"
            "\n"
            "```python\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "\n"
            "housing_full[\"income_cat\"] = pd.cut(\n"
            "    housing_full[\"median_income\"],\n"
            "    bins=[0.0, 1.5, 3.0, 4.5, 6.0, np.inf],\n"
            "    labels=[1, 2, 3, 4, 5],\n"
            ")\n"
            "```\n"
            "\n"
            "Then it performs a stratified split:\n"
            "\n"
            "```python\n"
            "strat_train_set, strat_test_set = train_test_split(\n"
            "    housing_full,\n"
            "    test_size=0.2,\n"
            "    stratify=housing_full[\"income_cat\"],\n"
            "    random_state=42,\n"
            ")\n"
            "```\n"
            "\n"
            "The purpose is not to create an “income model.” The temporary income categories are used only to ensure the train/test split preserves important proportions.\n"
            "\n"
            "{{image:stratified-vs-random-sampling}}\n"
            "\n"
            "After splitting, remove the temporary stratification feature if it is not meant to be a real model input.\n"
            "\n"
            "### Rule to remember\n"
            "\n"
            "**Create and protect the test set before exploratory decisions start influencing the project.**\n"
            "\n"
            "You can explore the **training set** deeply. The final test set should stay untouched until the end.\n"
            "\n"
            "{{exercise:M01.L02.EX01}}\n"
            "\n"
            "---\n"
            "\n"
            "## 3. Explore the training data and engineer useful features\n"
            "\n"
            "Once the test set is protected, exploratory data analysis can begin on a copy of the training set.\n"
            "\n"
            "```python\n"
            "housing = strat_train_set.copy()\n"
            "```\n"
            "\n"
            "The goal is not to make every possible plot.\n"
            "\n"
            "The goal is to discover information that changes what you do next.\n"
            "\n"
            "### Visualize geographic structure\n"
            "\n"
            "Latitude and longitude make a geographic scatterplot natural:\n"
            "\n"
            "```python\n"
            "housing.plot(\n"
            "    kind=\"scatter\",\n"
            "    x=\"longitude\",\n"
            "    y=\"latitude\",\n"
            "    alpha=0.2,\n"
            "    grid=True,\n"
            ")\n"
            "plt.show()\n"
            "```\n"
            "\n"
            "The low `alpha` value makes dense regions appear darker.\n"
            "\n"
            "This reveals population concentration around major areas.\n"
            "\n"
            "But geography becomes much more useful when you encode additional information:\n"
            "\n"
            "```python\n"
            "housing.plot(\n"
            "    kind=\"scatter\",\n"
            "    x=\"longitude\",\n"
            "    y=\"latitude\",\n"
            "    s=housing[\"population\"] / 100,\n"
            "    c=\"median_house_value\",\n"
            "    cmap=\"jet\",\n"
            "    colorbar=True,\n"
            "    figsize=(10, 7),\n"
            ")\n"
            "plt.show()\n"
            "```\n"
            "\n"
            "Now:\n"
            "\n"
            "- position shows geography,\n"
            "- marker size approximates population,\n"
            "- color represents house value.\n"
            "\n"
            "{{image:california-housing-geographic-patterns}}\n"
            "\n"
            "A good visualization is not decoration. It should lead to hypotheses.\n"
            "\n"
            "For example:\n"
            "\n"
            "- location matters,\n"
            "- high-density areas matter,\n"
            "- ocean proximity may matter,\n"
            "- geographic clusters may become useful engineered features.\n"
            "\n"
            "### Correlation\n"
            "\n"
            "For numerical attributes:\n"
            "\n"
            "```python\n"
            "corr_matrix = housing.corr(numeric_only=True)\n"
            "\n"
            "corr_matrix[\"median_house_value\"].sort_values(\n"
            "    ascending=False\n"
            ")\n"
            "```\n"
            "\n"
            "A correlation coefficient near:\n"
            "\n"
            "```text\n"
            "+1 -> strong positive linear relationship\n"
            " 0 -> little linear relationship\n"
            "-1 -> strong negative linear relationship\n"
            "```\n"
            "\n"
            "In the chapter, `median_income` has the strongest simple positive correlation with the target.\n"
            "\n"
            "But correlation has an important limitation:\n"
            "\n"
            "**Pearson correlation measures linear association.**\n"
            "\n"
            "A relationship can be strong and nonlinear while its correlation coefficient is close to zero.\n"
            "\n"
            "{{image:correlation-linear-limitation}}\n"
            "\n"
            "### Inspect the most promising relationship\n"
            "\n"
            "Plotting income against house value shows more than a single correlation number:\n"
            "\n"
            "```python\n"
            "housing.plot(\n"
            "    kind=\"scatter\",\n"
            "    x=\"median_income\",\n"
            "    y=\"median_house_value\",\n"
            "    alpha=0.1,\n"
            "    grid=True,\n"
            ")\n"
            "plt.show()\n"
            "```\n"
            "\n"
            "The source observes:\n"
            "\n"
            "- a clear upward trend,\n"
            "- substantial noise,\n"
            "- the target-value cap,\n"
            "- additional horizontal artifacts.\n"
            "\n"
            "These artifacts may be learned by the model unless they are understood or cleaned.\n"
            "\n"
            "{{image:income-vs-house-value}}\n"
            "\n"
            "### Engineer features that represent the problem better\n"
            "\n"
            "Raw totals are not always meaningful.\n"
            "\n"
            "For example:\n"
            "\n"
            "```text\n"
            "total_rooms = 5,000\n"
            "```\n"
            "\n"
            "means something very different in a district with 100 households than in a district with 2,000 households.\n"
            "\n"
            "Useful combinations include:\n"
            "\n"
            "```python\n"
            "housing[\"rooms_per_house\"] = (\n"
            "    housing[\"total_rooms\"] / housing[\"households\"]\n"
            ")\n"
            "\n"
            "housing[\"bedrooms_ratio\"] = (\n"
            "    housing[\"total_bedrooms\"] / housing[\"total_rooms\"]\n"
            ")\n"
            "\n"
            "housing[\"people_per_house\"] = (\n"
            "    housing[\"population\"] / housing[\"households\"]\n"
            ")\n"
            "```\n"
            "\n"
            "The chapter finds that some of these ratios correlate with the target better than the original raw totals.\n"
            "\n"
            "This is **feature engineering**: creating representations that express the structure of the problem more directly.\n"
            "\n"
            "### Feature engineering is not automatically beneficial\n"
            "\n"
            "New features can also create problems.\n"
            "\n"
            "For example, highly redundant linear combinations can introduce **collinearity**, which can be troublesome for some models such as linear regression.\n"
            "\n"
            "So every engineered feature should have a reason:\n"
            "\n"
            "```text\n"
            "What information does this feature express?\n"
            "Why might that information matter?\n"
            "Does it duplicate another feature?\n"
            "Does validation performance improve?\n"
            "```\n"
            "\n"
            "EDA is iterative. You will often return to it after seeing model errors.\n"
            "\n"
            "---\n"
            "\n"
            "## 4. Prepare data with reusable transformations\n"
            "\n"
            "Do not manually clean a dataset once and hope you can repeat the process later.\n"
            "\n"
            "Machine learning preprocessing should be:\n"
            "\n"
            "- reproducible,\n"
            "- reusable,\n"
            "- applied consistently to training and future data,\n"
            "- compatible with validation/test sets,\n"
            "- and preferably part of a pipeline.\n"
            "\n"
            "First separate inputs from labels:\n"
            "\n"
            "```python\n"
            "housing = strat_train_set.drop(\n"
            "    \"median_house_value\",\n"
            "    axis=1,\n"
            ")\n"
            "\n"
            "housing_labels = strat_train_set[\n"
            "    \"median_house_value\"\n"
            "].copy()\n"
            "```\n"
            "\n"
            "### Missing values and imputation\n"
            "\n"
            "The dataset contains missing `total_bedrooms` values.\n"
            "\n"
            "Three basic strategies are:\n"
            "\n"
            "```text\n"
            "1. remove affected rows\n"
            "2. remove the feature\n"
            "3. fill the missing values\n"
            "```\n"
            "\n"
            "Filling missing values is called **imputation**.\n"
            "\n"
            "A robust Scikit-Learn approach:\n"
            "\n"
            "```python\n"
            "from sklearn.impute import SimpleImputer\n"
            "import numpy as np\n"
            "\n"
            "housing_num = housing.select_dtypes(include=[np.number])\n"
            "\n"
            "imputer = SimpleImputer(strategy=\"median\")\n"
            "imputer.fit(housing_num)\n"
            "\n"
            "X = imputer.transform(housing_num)\n"
            "```\n"
            "\n"
            "The key is that the imputer **learns medians from the training data** and stores them.\n"
            "\n"
            "Then the same learned values can be applied to:\n"
            "\n"
            "- validation data,\n"
            "- test data,\n"
            "- future production data.\n"
            "\n"
            "Do not independently recompute preprocessing statistics on the test set.\n"
            "\n"
            "That would leak test information into the system.\n"
            "\n"
            "### Understand Scikit-Learn’s API\n"
            "\n"
            "The chapter emphasizes several design patterns.\n"
            "\n"
            "**Estimator**\n"
            "\n"
            "An object that learns parameters from data using:\n"
            "\n"
            "```python\n"
            "estimator.fit(X, y)\n"
            "```\n"
            "\n"
            "or, for unsupervised transformations:\n"
            "\n"
            "```python\n"
            "estimator.fit(X)\n"
            "```\n"
            "\n"
            "**Transformer**\n"
            "\n"
            "An estimator that can transform input:\n"
            "\n"
            "```python\n"
            "X_transformed = transformer.transform(X)\n"
            "```\n"
            "\n"
            "Many transformers provide:\n"
            "\n"
            "```python\n"
            "transformer.fit_transform(X)\n"
            "```\n"
            "\n"
            "**Predictor**\n"
            "\n"
            "An estimator that can generate predictions:\n"
            "\n"
            "```python\n"
            "predictions = model.predict(X_new)\n"
            "```\n"
            "\n"
            "### Learned attributes versus hyperparameters\n"
            "\n"
            "A useful Scikit-Learn convention:\n"
            "\n"
            "```text\n"
            "constructor argument       -> hyperparameter\n"
            "attribute ending in \"_\"    -> learned/fitted attribute\n"
            "```\n"
            "\n"
            "Examples:\n"
            "\n"
            "```python\n"
            "imputer.strategy       # hyperparameter\n"
            "imputer.statistics_    # learned from training data\n"
            "```\n"
            "\n"
            "This distinction becomes very useful when debugging pipelines.\n"
            "\n"
            "### Categorical variables\n"
            "\n"
            "`ocean_proximity` is categorical.\n"
            "\n"
            "An **ordinal encoding** maps categories to integers, but this can falsely imply an order:\n"
            "\n"
            "```text\n"
            "category 0 is closer to category 1\n"
            "than to category 4\n"
            "```\n"
            "\n"
            "That is inappropriate for unordered categories.\n"
            "\n"
            "A safer choice here is **one-hot encoding**:\n"
            "\n"
            "```python\n"
            "from sklearn.preprocessing import OneHotEncoder\n"
            "\n"
            "cat_encoder = OneHotEncoder(\n"
            "    handle_unknown=\"ignore\"\n"
            ")\n"
            "\n"
            "housing_cat_1hot = cat_encoder.fit_transform(\n"
            "    housing[[\"ocean_proximity\"]]\n"
            ")\n"
            "```\n"
            "\n"
            "One-hot encoding creates one binary feature per category.\n"
            "\n"
            "Why use `OneHotEncoder` rather than independently generating dummy columns on every dataset?\n"
            "\n"
            "Because the fitted encoder remembers the categories learned from the training data and keeps a stable output schema.\n"
            "\n"
            "That is essential in production.\n"
            "\n"
            "### Sparse matrices\n"
            "\n"
            "One-hot features contain mostly zeros.\n"
            "\n"
            "Instead of storing:\n"
            "\n"
            "```text\n"
            "0 0 0 1 0 0 0 0 ...\n"
            "```\n"
            "\n"
            "as a full dense matrix, Scikit-Learn can use a **sparse matrix** that stores mostly the nonzero values and their locations.\n"
            "\n"
            "This saves memory when categorical cardinality is large.\n"
            "\n"
            "### Feature scaling\n"
            "\n"
            "Many algorithms behave poorly when numerical features operate on very different scales.\n"
            "\n"
            "Two common approaches are:\n"
            "\n"
            "**Min-max scaling**\n"
            "\n"
            "```text\n"
            "shift and rescale values into a chosen range\n"
            "```\n"
            "\n"
            "**Standardization**\n"
            "\n"
            "```text\n"
            "subtract mean\n"
            "divide by standard deviation\n"
            "```\n"
            "\n"
            "With Scikit-Learn:\n"
            "\n"
            "```python\n"
            "from sklearn.preprocessing import StandardScaler\n"
            "\n"
            "std_scaler = StandardScaler()\n"
            "housing_num_scaled = std_scaler.fit_transform(\n"
            "    housing_num\n"
            ")\n"
            "```\n"
            "\n"
            "Again:\n"
            "\n"
            "> **Fit the scaler on the training set only.**\n"
            "\n"
            "Use only `transform()` on validation, test, and production data.\n"
            "\n"
            "### Handle skewed distributions before scaling\n"
            "\n"
            "Scaling does not automatically fix a badly skewed distribution.\n"
            "\n"
            "For positive right-skewed features, transformations such as:\n"
            "\n"
            "```text\n"
            "square root\n"
            "logarithm\n"
            "```\n"
            "\n"
            "may make the distribution more symmetric.\n"
            "\n"
            "The source uses population as an example.\n"
            "\n"
            "{{image:log-transform-skewed-feature}}\n"
            "\n"
            "Other options include:\n"
            "\n"
            "- bucketizing heavy-tailed values,\n"
            "- treating multimodal ranges as categories,\n"
            "- or creating similarity features around meaningful modes.\n"
            "\n"
            "### Gaussian RBF similarity features\n"
            "\n"
            "A **radial basis function (RBF)** can convert “distance from a reference value” into a smooth similarity score.\n"
            "\n"
            "For example:\n"
            "\n"
            "```python\n"
            "from sklearn.metrics.pairwise import rbf_kernel\n"
            "\n"
            "age_simil_35 = rbf_kernel(\n"
            "    housing[[\"housing_median_age\"]],\n"
            "    [[35]],\n"
            "    gamma=0.1,\n"
            ")\n"
            "```\n"
            "\n"
            "The similarity is highest around age `35` and falls as distance increases.\n"
            "\n"
            "This can help a model learn effects around important modes without assuming a simple straight-line relationship.\n"
            "\n"
            "### Transforming the target\n"
            "\n"
            "Sometimes the target itself needs transformation.\n"
            "\n"
            "For example, you may want to standardize or log-transform a target before model fitting, but predictions still need to be returned in the original unit.\n"
            "\n"
            "Scikit-Learn’s `TransformedTargetRegressor` can manage that mapping:\n"
            "\n"
            "```python\n"
            "from sklearn.compose import TransformedTargetRegressor\n"
            "from sklearn.linear_model import LinearRegression\n"
            "from sklearn.preprocessing import StandardScaler\n"
            "\n"
            "model = TransformedTargetRegressor(\n"
            "    LinearRegression(),\n"
            "    transformer=StandardScaler(),\n"
            ")\n"
            "\n"
            "model.fit(\n"
            "    housing[[\"median_income\"]],\n"
            "    housing_labels,\n"
            ")\n"
            "```\n"
            "\n"
            "This is safer than manually remembering when to transform and inverse-transform the target.\n"
            "\n"
            "---\n"
            "\n"
            "## 5. Build preprocessing pipelines instead of disconnected steps\n"
            "\n"
            "As preprocessing grows, manually applying every transformation in the right order becomes fragile.\n"
            "\n"
            "A **Pipeline** packages a sequence of transformations.\n"
            "\n"
            "```python\n"
            "from sklearn.pipeline import make_pipeline\n"
            "from sklearn.impute import SimpleImputer\n"
            "from sklearn.preprocessing import StandardScaler\n"
            "\n"
            "num_pipeline = make_pipeline(\n"
            "    SimpleImputer(strategy=\"median\"),\n"
            "    StandardScaler(),\n"
            ")\n"
            "```\n"
            "\n"
            "Conceptually:\n"
            "\n"
            "```text\n"
            "raw numerical features\n"
            "        |\n"
            "imputation\n"
            "        |\n"
            "scaling\n"
            "        |\n"
            "prepared features\n"
            "```\n"
            "\n"
            "When you call:\n"
            "\n"
            "```python\n"
            "num_pipeline.fit_transform(X_train)\n"
            "```\n"
            "\n"
            "each step learns only from the training data, and the output flows into the next step.\n"
            "\n"
            "When you later call:\n"
            "\n"
            "```python\n"
            "num_pipeline.transform(X_new)\n"
            "```\n"
            "\n"
            "the already-learned preprocessing is reused.\n"
            "\n"
            "This reduces data leakage and training/serving mismatch.\n"
            "\n"
            "### ColumnTransformer\n"
            "\n"
            "Numerical and categorical columns need different preprocessing.\n"
            "\n"
            "`ColumnTransformer` lets one object route different columns through different pipelines.\n"
            "\n"
            "```python\n"
            "from sklearn.compose import ColumnTransformer\n"
            "from sklearn.pipeline import make_pipeline\n"
            "from sklearn.preprocessing import OneHotEncoder\n"
            "\n"
            "num_attribs = [\n"
            "    \"longitude\",\n"
            "    \"latitude\",\n"
            "    \"housing_median_age\",\n"
            "    \"total_rooms\",\n"
            "    \"total_bedrooms\",\n"
            "    \"population\",\n"
            "    \"households\",\n"
            "    \"median_income\",\n"
            "]\n"
            "\n"
            "cat_attribs = [\"ocean_proximity\"]\n"
            "\n"
            "cat_pipeline = make_pipeline(\n"
            "    SimpleImputer(strategy=\"most_frequent\"),\n"
            "    OneHotEncoder(handle_unknown=\"ignore\"),\n"
            ")\n"
            "\n"
            "preprocessing = ColumnTransformer([\n"
            "    (\"num\", num_pipeline, num_attribs),\n"
            "    (\"cat\", cat_pipeline, cat_attribs),\n"
            "])\n"
            "```\n"
            "\n"
            "Now one transformer handles the entire input table consistently.\n"
            "\n"
            "### Custom transformations\n"
            "\n"
            "You are not limited to built-in transformers.\n"
            "\n"
            "For transformations that do not need training, `FunctionTransformer` is convenient:\n"
            "\n"
            "```python\n"
            "import numpy as np\n"
            "from sklearn.preprocessing import FunctionTransformer\n"
            "\n"
            "log_transformer = FunctionTransformer(\n"
            "    np.log,\n"
            "    inverse_func=np.exp,\n"
            ")\n"
            "```\n"
            "\n"
            "For trainable custom transformations, implement the Scikit-Learn interface.\n"
            "\n"
            "At minimum, a transformer generally needs:\n"
            "\n"
            "```text\n"
            "fit()\n"
            "transform()\n"
            "```\n"
            "\n"
            "`TransformerMixin` can provide `fit_transform()`.\n"
            "\n"
            "`BaseEstimator` helps with parameter inspection and hyperparameter tuning.\n"
            "\n"
            "### Geographic cluster-similarity features\n"
            "\n"
            "The chapter creates a useful custom idea:\n"
            "\n"
            "1. learn geographic cluster centers using k-means,\n"
            "2. measure each district’s RBF similarity to each center,\n"
            "3. add those similarities as new features.\n"
            "\n"
            "This converts raw latitude/longitude into features describing proximity to learned population centers.\n"
            "\n"
            "{{image:geographic-cluster-similarity}}\n"
            "\n"
            "The important idea is broader than this exact transformer:\n"
            "\n"
            "> **A good transformation converts raw measurements into representations that make useful structure easier for a model to learn.**\n"
            "\n"
            "### The complete preprocessing design\n"
            "\n"
            "The chapter’s full preprocessing pipeline performs several tasks:\n"
            "\n"
            "```text\n"
            "missing numerical values\n"
            "    -> median imputation\n"
            "\n"
            "missing categorical values\n"
            "    -> most-frequent imputation\n"
            "\n"
            "categorical values\n"
            "    -> one-hot encoding\n"
            "\n"
            "raw totals\n"
            "    -> ratio features\n"
            "\n"
            "right-skewed features\n"
            "    -> log transformation\n"
            "\n"
            "latitude/longitude\n"
            "    -> cluster-similarity features\n"
            "\n"
            "numerical features\n"
            "    -> standardization\n"
            "```\n"
            "\n"
            "This is a much stronger engineering pattern than scattered notebook cells.\n"
            "\n"
            "It means the same preprocessing logic can travel with the model.\n"
            "\n"
            "---\n"
            "\n"
            "## 6. Train baselines, then evaluate with cross-validation\n"
            "\n"
            "After problem framing, splitting, EDA, and preprocessing, model training is surprisingly short.\n"
            "\n"
            "### Start with a simple baseline\n"
            "\n"
            "```python\n"
            "from sklearn.linear_model import LinearRegression\n"
            "from sklearn.pipeline import make_pipeline\n"
            "\n"
            "lin_reg = make_pipeline(\n"
            "    preprocessing,\n"
            "    LinearRegression(),\n"
            ")\n"
            "\n"
            "lin_reg.fit(housing, housing_labels)\n"
            "```\n"
            "\n"
            "Evaluate it using RMSE:\n"
            "\n"
            "```python\n"
            "from sklearn.metrics import root_mean_squared_error\n"
            "\n"
            "housing_predictions = lin_reg.predict(housing)\n"
            "\n"
            "lin_rmse = root_mean_squared_error(\n"
            "    housing_labels,\n"
            "    housing_predictions,\n"
            ")\n"
            "```\n"
            "\n"
            "The source obtains a training RMSE around `$68,973`.\n"
            "\n"
            "That is not satisfactory for the target range, suggesting the linear model **underfits**.\n"
            "\n"
            "Possible reasons:\n"
            "\n"
            "- the model is too simple,\n"
            "- the features are not expressive enough.\n"
            "\n"
            "### Try a more flexible model\n"
            "\n"
            "A decision tree can model nonlinear relationships.\n"
            "\n"
            "```python\n"
            "from sklearn.tree import DecisionTreeRegressor\n"
            "\n"
            "tree_reg = make_pipeline(\n"
            "    preprocessing,\n"
            "    DecisionTreeRegressor(random_state=42),\n"
            ")\n"
            "\n"
            "tree_reg.fit(housing, housing_labels)\n"
            "```\n"
            "\n"
            "On the training set, its RMSE becomes:\n"
            "\n"
            "```text\n"
            "0.0\n"
            "```\n"
            "\n"
            "That does **not** mean the model is perfect.\n"
            "\n"
            "It is a warning sign.\n"
            "\n"
            "The tree may have memorized the training set.\n"
            "\n"
            "### Do not use the test set to diagnose this\n"
            "\n"
            "The test set is still reserved for the final system.\n"
            "\n"
            "Instead, use validation.\n"
            "\n"
            "### k-fold cross-validation\n"
            "\n"
            "In **k-fold cross-validation**:\n"
            "\n"
            "1. split the training set into `k` folds,\n"
            "2. train on `k - 1` folds,\n"
            "3. validate on the remaining fold,\n"
            "4. repeat until every fold has served as validation once,\n"
            "5. summarize the scores.\n"
            "\n"
            "{{image:k-fold-cross-validation}}\n"
            "\n"
            "With Scikit-Learn:\n"
            "\n"
            "```python\n"
            "from sklearn.model_selection import cross_val_score\n"
            "\n"
            "tree_rmses = -cross_val_score(\n"
            "    tree_reg,\n"
            "    housing,\n"
            "    housing_labels,\n"
            "    scoring=\"neg_root_mean_squared_error\",\n"
            "    cv=10,\n"
            ")\n"
            "```\n"
            "\n"
            "Why the minus sign?\n"
            "\n"
            "Scikit-Learn’s scoring convention expects “higher is better,” so error metrics may be represented as negative scores. Negating the result gives ordinary positive RMSE values.\n"
            "\n"
            "Cross-validation reveals that the decision tree’s validation RMSE is around `$66,574` even though its training error is zero.\n"
            "\n"
            "That is classic overfitting.\n"
            "\n"
            "### Compare several candidate models\n"
            "\n"
            "The chapter also evaluates a random forest:\n"
            "\n"
            "```python\n"
            "from sklearn.ensemble import RandomForestRegressor\n"
            "\n"
            "forest_reg = make_pipeline(\n"
            "    preprocessing,\n"
            "    RandomForestRegressor(random_state=42),\n"
            ")\n"
            "\n"
            "forest_rmses = -cross_val_score(\n"
            "    forest_reg,\n"
            "    housing,\n"
            "    housing_labels,\n"
            "    scoring=\"neg_root_mean_squared_error\",\n"
            "    cv=10,\n"
            ")\n"
            "```\n"
            "\n"
            "The mean validation RMSE drops substantially, to around `$47,038`.\n"
            "\n"
            "But the training RMSE remains far lower than validation RMSE, so some overfitting is still present.\n"
            "\n"
            "The right response is not to spend days polishing the first model that looks decent.\n"
            "\n"
            "A good workflow is:\n"
            "\n"
            "```text\n"
            "train several reasonable model families\n"
            "        |\n"
            "evaluate consistently\n"
            "        |\n"
            "shortlist a few promising candidates\n"
            "        |\n"
            "fine-tune only those\n"
            "```\n"
            "\n"
            "This saves time and reduces attachment to one approach.\n"
            "\n"
            "---\n"
            "\n"
            "## 7. Fine-tune the system and analyze its errors\n"
            "\n"
            "Once you have a shortlist of promising models, tune their hyperparameters systematically.\n"
            "\n"
            "### Grid search\n"
            "\n"
            "`GridSearchCV` evaluates predefined combinations.\n"
            "\n"
            "```python\n"
            "from sklearn.model_selection import GridSearchCV\n"
            "from sklearn.ensemble import RandomForestRegressor\n"
            "from sklearn.pipeline import Pipeline\n"
            "\n"
            "full_pipeline = Pipeline([\n"
            "    (\"preprocessing\", preprocessing),\n"
            "    (\n"
            "        \"random_forest\",\n"
            "        RandomForestRegressor(random_state=42),\n"
            "    ),\n"
            "])\n"
            "\n"
            "param_grid = [\n"
            "    {\n"
            "        \"preprocessing__geo__n_clusters\": [5, 8, 10],\n"
            "        \"random_forest__max_features\": [4, 6, 8],\n"
            "    },\n"
            "    {\n"
            "        \"preprocessing__geo__n_clusters\": [10, 15],\n"
            "        \"random_forest__max_features\": [6, 8, 10],\n"
            "    },\n"
            "]\n"
            "\n"
            "grid_search = GridSearchCV(\n"
            "    full_pipeline,\n"
            "    param_grid,\n"
            "    cv=3,\n"
            "    scoring=\"neg_root_mean_squared_error\",\n"
            ")\n"
            "\n"
            "grid_search.fit(housing, housing_labels)\n"
            "```\n"
            "\n"
            "Notice something powerful:\n"
            "\n"
            "```text\n"
            "preprocessing__geo__n_clusters\n"
            "```\n"
            "\n"
            "refers to a hyperparameter deep inside the preprocessing pipeline.\n"
            "\n"
            "So preprocessing and model hyperparameters can be tuned together.\n"
            "\n"
            "That matters because they interact.\n"
            "\n"
            "For example, the ideal number of geographic clusters may depend on how much capacity the model has to use them.\n"
            "\n"
            "### Grid search cost\n"
            "\n"
            "If the grid contains:\n"
            "\n"
            "```text\n"
            "15 parameter combinations\n"
            "x\n"
            "3 CV folds\n"
            "```\n"
            "\n"
            "then the system performs:\n"
            "\n"
            "```text\n"
            "45 training runs\n"
            "```\n"
            "\n"
            "Hyperparameter tuning can become expensive very quickly.\n"
            "\n"
            "### Randomized search\n"
            "\n"
            "When the search space is large, `RandomizedSearchCV` is often more efficient.\n"
            "\n"
            "Instead of evaluating every combination, it samples a chosen number of configurations.\n"
            "\n"
            "```python\n"
            "from scipy.stats import randint\n"
            "from sklearn.model_selection import RandomizedSearchCV\n"
            "\n"
            "param_distribs = {\n"
            "    \"preprocessing__geo__n_clusters\": randint(\n"
            "        low=3,\n"
            "        high=50,\n"
            "    ),\n"
            "    \"random_forest__max_features\": randint(\n"
            "        low=2,\n"
            "        high=20,\n"
            "    ),\n"
            "}\n"
            "\n"
            "rnd_search = RandomizedSearchCV(\n"
            "    full_pipeline,\n"
            "    param_distributions=param_distribs,\n"
            "    n_iter=10,\n"
            "    cv=3,\n"
            "    scoring=\"neg_root_mean_squared_error\",\n"
            "    random_state=42,\n"
            ")\n"
            "\n"
            "rnd_search.fit(housing, housing_labels)\n"
            "```\n"
            "\n"
            "Why randomized search is useful:\n"
            "\n"
            "- it can explore many distinct values for continuous hyperparameters,\n"
            "- unimportant hyperparameters do not multiply the full grid cost,\n"
            "- you choose the computational budget directly using `n_iter`.\n"
            "\n"
            "The chapter also mentions successive-halving search strategies, which begin with many candidates using limited resources and progressively allocate more resources to the best ones.\n"
            "\n"
            "### Ensemble methods\n"
            "\n"
            "Combining strong but diverse models can outperform one model alone if their errors differ.\n"
            "\n"
            "The chapter only introduces the concept here; ensemble learning is covered later in more depth.\n"
            "\n"
            "The takeaway is:\n"
            "\n"
            "```text\n"
            "diverse useful models\n"
            "        +\n"
            "uncorrelated errors\n"
            "        ->\n"
            "potentially better combined prediction\n"
            "```\n"
            "\n"
            "### Inspect feature importance\n"
            "\n"
            "Tuning is not the end.\n"
            "\n"
            "A strong model should be investigated.\n"
            "\n"
            "For a random forest:\n"
            "\n"
            "```python\n"
            "final_model = rnd_search.best_estimator_\n"
            "\n"
            "feature_importances = (\n"
            "    final_model[\"random_forest\"]\n"
            "    .feature_importances_\n"
            ")\n"
            "```\n"
            "\n"
            "The source finds `median_income` particularly influential, along with engineered geographic and ratio features.\n"
            "\n"
            "Feature importance can help you:\n"
            "\n"
            "- understand what the model relies on,\n"
            "- identify nearly useless features,\n"
            "- design better features,\n"
            "- detect suspicious behavior.\n"
            "\n"
            "### Analyze actual errors\n"
            "\n"
            "Do not inspect only average RMSE.\n"
            "\n"
            "Study specific cases where predictions are poor.\n"
            "\n"
            "Ask:\n"
            "\n"
            "```text\n"
            "Are errors concentrated in a geographic region?\n"
            "Do expensive districts fail more often?\n"
            "Are there outliers?\n"
            "Are some feature values missing or unreliable?\n"
            "Does one category receive systematically worse predictions?\n"
            "```\n"
            "\n"
            "This can send you back to:\n"
            "\n"
            "- data cleaning,\n"
            "- feature engineering,\n"
            "- model selection,\n"
            "- or data collection.\n"
            "\n"
            "### Fairness and subgroup performance\n"
            "\n"
            "A model can have acceptable average performance and still fail badly for a subgroup.\n"
            "\n"
            "The chapter recommends checking categories such as:\n"
            "\n"
            "- rural versus urban,\n"
            "- rich versus poor,\n"
            "- different geographic areas,\n"
            "- relevant demographic groups.\n"
            "\n"
            "The general principle is:\n"
            "\n"
            "> **Evaluate where the model fails, not only how much it fails on average.**\n"
            "\n"
            "---\n"
            "\n"
            "## 8. Test once, communicate the result, and prepare for production\n"
            "\n"
            "After model selection and tuning are complete, evaluate the final pipeline on the untouched test set.\n"
            "\n"
            "```python\n"
            "X_test = strat_test_set.drop(\n"
            "    \"median_house_value\",\n"
            "    axis=1,\n"
            ")\n"
            "\n"
            "y_test = strat_test_set[\n"
            "    \"median_house_value\"\n"
            "].copy()\n"
            "\n"
            "final_predictions = final_model.predict(X_test)\n"
            "\n"
            "final_rmse = root_mean_squared_error(\n"
            "    y_test,\n"
            "    final_predictions,\n"
            ")\n"
            "\n"
            "print(final_rmse)\n"
            "```\n"
            "\n"
            "The source’s final model produces an RMSE of roughly:\n"
            "\n"
            "```text\n"
            "$41,446\n"
            "```\n"
            "\n"
            "That is the final generalization estimate for this development cycle.\n"
            "\n"
            "### Do not tune after looking at test performance\n"
            "\n"
            "If the test result is disappointing, it is tempting to adjust hyperparameters until the test number improves.\n"
            "\n"
            "Do not do that.\n"
            "\n"
            "Once test results affect model choices, the test set becomes part of the development loop and loses its role as an independent estimate.\n"
            "\n"
            "If you genuinely begin a new model-development cycle, you may eventually need a new untouched test set.\n"
            "\n"
            "### Point estimate versus uncertainty\n"
            "\n"
            "One RMSE value does not tell you how uncertain the estimate is.\n"
            "\n"
            "The chapter computes a 95% confidence interval using bootstrap resampling.\n"
            "\n"
            "Conceptually:\n"
            "\n"
            "```text\n"
            "test predictions\n"
            "      |\n"
            "resample prediction errors many times\n"
            "      |\n"
            "recompute RMSE\n"
            "      |\n"
            "estimate plausible range\n"
            "```\n"
            "\n"
            "This is particularly useful when two systems have similar measured performance.\n"
            "\n"
            "A difference of a few hundred dollars may not be meaningful if the uncertainty around the estimates is much larger.\n"
            "\n"
            "### Present the solution\n"
            "\n"
            "A strong ML engineer does not merely report:\n"
            "\n"
            "```text\n"
            "RMSE = 41,445.53\n"
            "```\n"
            "\n"
            "The presentation should explain:\n"
            "\n"
            "- the business objective,\n"
            "- how the problem was framed,\n"
            "- important data findings,\n"
            "- which models were evaluated,\n"
            "- what worked and what did not,\n"
            "- final performance,\n"
            "- assumptions,\n"
            "- uncertainty,\n"
            "- limitations,\n"
            "- and risks.\n"
            "\n"
            "Make the explanation appropriate for the audience.\n"
            "\n"
            "Technical peers may need pipeline details and validation methodology.\n"
            "\n"
            "Business stakeholders may care more about:\n"
            "\n"
            "- whether the system is better than the current process,\n"
            "- how it changes operations,\n"
            "- and what kinds of errors remain.\n"
            "\n"
            "### Make results reproducible\n"
            "\n"
            "Useful reproducibility practices from the chapter include:\n"
            "\n"
            "- keep the code accessible,\n"
            "- provide a clear README,\n"
            "- document the environment,\n"
            "- pin library versions,\n"
            "- make notebooks understandable,\n"
            "- use deterministic seeds when possible,\n"
            "- record preprocessing and model configuration.\n"
            "\n"
            "This is not bureaucracy. It is what allows someone else—or future you—to reproduce the result.\n"
            "\n"
            "---\n"
            "\n"
            "## 9. Deployment is the beginning of the operational lifecycle\n"
            "\n"
            "A model that works in a notebook is not yet a production system.\n"
            "\n"
            "### Save the complete fitted model\n"
            "\n"
            "Because preprocessing and prediction are packaged together, the fitted pipeline can be serialized:\n"
            "\n"
            "```python\n"
            "import joblib\n"
            "\n"
            "joblib.dump(\n"
            "    final_model,\n"
            "    \"my_california_housing_model.pkl\",\n"
            ")\n"
            "```\n"
            "\n"
            "Later:\n"
            "\n"
            "```python\n"
            "final_model_reloaded = joblib.load(\n"
            "    \"my_california_housing_model.pkl\"\n"
            ")\n"
            "\n"
            "predictions = final_model_reloaded.predict(\n"
            "    new_data\n"
            ")\n"
            "```\n"
            "\n"
            "Saving the **whole pipeline** is important because production inputs must receive the same transformations as training data.\n"
            "\n"
            "### Serve predictions\n"
            "\n"
            "One architecture is to expose the model as a web service.\n"
            "\n"
            "Conceptually:\n"
            "\n"
            "```text\n"
            "user\n"
            " |\n"
            "web application\n"
            " |\n"
            "prediction request\n"
            " |\n"
            "model service\n"
            " |\n"
            "prediction response\n"
            " |\n"
            "web application\n"
            "```\n"
            "\n"
            "{{image:model-web-service-deployment}}\n"
            "\n"
            "The model should normally be loaded once when the service starts, not reloaded from disk for every prediction.\n"
            "\n"
            "### Monitor live performance\n"
            "\n"
            "Deployment does not freeze the world.\n"
            "\n"
            "Performance may degrade because:\n"
            "\n"
            "- the data distribution changes,\n"
            "- user behavior changes,\n"
            "- an upstream feature becomes stale,\n"
            "- a sensor or data source breaks,\n"
            "- new categories appear,\n"
            "- missing-value rates increase.\n"
            "\n"
            "This is why production ML requires **monitoring**.\n"
            "\n"
            "Possible signals include:\n"
            "\n"
            "```text\n"
            "model-quality metric\n"
            "downstream business metric\n"
            "input missing-value rate\n"
            "feature mean/std drift\n"
            "new categorical values\n"
            "prediction distribution\n"
            "latency\n"
            "error rate\n"
            "```\n"
            "\n"
            "Sometimes ground-truth labels arrive late or not at all. In those cases, downstream business metrics or human review may help estimate quality.\n"
            "\n"
            "### Human evaluation may be part of monitoring\n"
            "\n"
            "Some problems cannot be monitored reliably from automatic metrics alone.\n"
            "\n"
            "A sample of predictions may need expert or human review.\n"
            "\n"
            "The important idea is that the monitoring plan should be designed for the actual task, not copied mechanically from another system.\n"
            "\n"
            "### Automate retraining carefully\n"
            "\n"
            "If data changes continuously, the chapter recommends automating much of the lifecycle:\n"
            "\n"
            "```text\n"
            "collect fresh data\n"
            "      |\n"
            "validate / label\n"
            "      |\n"
            "train candidate model\n"
            "      |\n"
            "tune\n"
            "      |\n"
            "evaluate against current model\n"
            "      |\n"
            "deploy only if acceptable\n"
            "```\n"
            "\n"
            "Automatic retraining must not mean automatic blind deployment.\n"
            "\n"
            "A new model can be worse.\n"
            "\n"
            "### Monitor inputs as well as outputs\n"
            "\n"
            "Waiting until final model accuracy collapses may be too late.\n"
            "\n"
            "Input monitoring can detect problems earlier.\n"
            "\n"
            "Examples:\n"
            "\n"
            "- sudden increase in missing fields,\n"
            "- feature mean or standard deviation drifts,\n"
            "- an upstream source stops updating,\n"
            "- a categorical feature contains unseen categories.\n"
            "\n"
            "This is often the first sign that the system is moving away from its training conditions.\n"
            "\n"
            "### Keep model and dataset versions\n"
            "\n"
            "Keep backups of:\n"
            "\n"
            "- trained models,\n"
            "- configuration,\n"
            "- evaluation results,\n"
            "- datasets,\n"
            "- preprocessing logic.\n"
            "\n"
            "Why?\n"
            "\n"
            "Because you may need to answer:\n"
            "\n"
            "```text\n"
            "Which model was running last week?\n"
            "Which dataset trained it?\n"
            "What changed?\n"
            "Can we roll back immediately?\n"
            "Can we compare the new model against the old data?\n"
            "```\n"
            "\n"
            "Rollback is an operational requirement, not an afterthought.\n"
            "\n"
            "### MLOps\n"
            "\n"
            "All of these concerns—training automation, deployment, monitoring, versioning, rollback, reproducibility, and reliable data/model pipelines—belong to the broader area of **MLOps**.\n"
            "\n"
            "One of the chapter’s most important lessons is that the learning algorithm is only a fraction of the real system.\n"
            "\n"
            "---\n"
            "\n"
            "## Important misconceptions\n"
            "\n"
            "### Misconception 1\n"
            "\n"
            "> The first step of an ML project is choosing an algorithm.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "The business objective and downstream use determine how the problem should be framed, what metric matters, what data is required, and even whether machine learning is appropriate.\n"
            "\n"
            "### Misconception 2\n"
            "\n"
            "> I can explore the test set as long as I do not train directly on it.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Human decisions can overfit too. Looking at test-set patterns may influence feature engineering, model selection, and hyperparameter choices, producing data snooping bias.\n"
            "\n"
            "### Misconception 3\n"
            "\n"
            "> A training RMSE of zero means the model is perfect.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "It may mean the model memorized the training set. Validation or cross-validation is needed to determine whether the model generalizes.\n"
            "\n"
            "### Misconception 4\n"
            "\n"
            "> Scaling and fixing skewed distributions are the same operation.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Scaling changes the numerical scale. A log, square-root, bucket, or other distributional transformation changes the shape or representation of the feature. You may need both.\n"
            "\n"
            "### Misconception 5\n"
            "\n"
            "> Preprocessing can be written as separate ad-hoc code for training and production.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Duplicated preprocessing easily creates training-serving mismatches. A fitted pipeline keeps transformations and the model together and ensures new data follows the learned preprocessing.\n"
            "\n"
            "### Misconception 6\n"
            "\n"
            "> Once the final model is deployed, the project is finished.\n"
            "\n"
            "### Why this is wrong\n"
            "\n"
            "Production models need monitoring, retraining strategies, data-quality checks, versioning, rollback, and sometimes human evaluation.\n"
            "\n"
            "---\n"
            "\n"
            "## Key terminology\n"
            "\n"
            "| Term | Meaning |\n"
            "|---|---|\n"
            "| Business objective | The real organizational outcome the ML system is intended to improve |\n"
            "| Multiple regression | Regression using multiple input features |\n"
            "| Univariate regression | Regression predicting one target value per instance |\n"
            "| RMSE | Root mean squared error; a regression error metric that penalizes large errors strongly |\n"
            "| MAE | Mean absolute error; average absolute prediction error |\n"
            "| Data snooping bias | Overly optimistic evaluation caused by letting test information influence development decisions |\n"
            "| Stratified sampling | Sampling that preserves important subgroup proportions |\n"
            "| EDA | Exploratory data analysis: inspecting and visualizing training data to discover structure and problems |\n"
            "| Correlation | A measure of association; Pearson correlation specifically measures linear association |\n"
            "| Feature engineering | Creating or transforming features to represent the problem more usefully |\n"
            "| Imputation | Replacing missing values using a defined strategy |\n"
            "| One-hot encoding | Representing each category with its own binary feature |\n"
            "| Sparse matrix | Memory-efficient representation that stores mostly nonzero values and their positions |\n"
            "| Standardization | Rescaling by subtracting the mean and dividing by standard deviation |\n"
            "| Min-max scaling | Rescaling a feature to a specified range |\n"
            "| Transformer | Scikit-Learn estimator that converts one representation of data into another |\n"
            "| Estimator | Object that learns parameters from data using `fit()` |\n"
            "| Predictor | Estimator capable of generating predictions |\n"
            "| Pipeline | Ordered sequence of transformations and optionally a final estimator |\n"
            "| ColumnTransformer | Transformer that applies different preprocessing to different columns |\n"
            "| RBF | Radial basis function; similarity function based on distance from reference points |\n"
            "| Cross-validation | Repeated training/validation across different folds of the training set |\n"
            "| Grid search | Exhaustive evaluation of listed hyperparameter combinations |\n"
            "| Randomized search | Evaluation of a chosen number of randomly sampled hyperparameter combinations |\n"
            "| Feature importance | Estimate of how much a fitted model relies on different features |\n"
            "| Model serialization | Saving a fitted model/pipeline for later loading |\n"
            "| Data drift | Change in production data that can reduce model performance |\n"
            "| Rollback | Reverting quickly to a previously known-good model or dataset |\n"
            "| MLOps | Practices for reliably deploying, monitoring, retraining, versioning, and operating ML systems |\n"
            "\n"
            "---\n"
            "\n"
            "## Self-check\n"
            "\n"
            "Before continuing, make sure you can answer:\n"
            "\n"
            "1. Why should a machine learning project begin with the business objective rather than model selection?\n"
            "2. Why is the housing project framed as supervised, multiple, univariate regression with batch learning?\n"
            "3. When would MAE be more attractive than RMSE?\n"
            "4. What is data snooping bias, and why should the test set be created early?\n"
            "5. Why might stratified sampling be preferable to a purely random train/test split?\n"
            "6. What can a histogram reveal that `describe()` alone may not?\n"
            "7. Why can Pearson correlation miss an important relationship?\n"
            "8. Why must imputers and scalers be fit only on training data?\n"
            "9. Why is one-hot encoding appropriate for an unordered category such as `ocean_proximity`?\n"
            "10. What problem do Scikit-Learn pipelines solve?\n"
            "11. Why does zero training error for a decision tree not prove that it is a good model?\n"
            "12. What does cross-validation tell you that a single training score cannot?\n"
            "13. When is randomized search preferable to grid search?\n"
            "14. Why should the final test set not be used for repeated hyperparameter tuning?\n"
            "15. What should be monitored after an ML model is deployed?\n"
            "\n"
            "---\n"
            "\n"
            "## Retain this idea\n"
            "\n"
            "**A successful machine learning project is an end-to-end system, not a training command. Frame the right problem, protect your evaluation data, understand and transform the data carefully, automate preprocessing, compare models honestly, tune only with validation evidence, test once at the end, and design deployment, monitoring, retraining, and rollback before calling the system complete.**\n"
        ),

        "estimated_minutes": 270,

        "has_code_examples": True,

        "has_manual_image_requests": True,

        "sections": [
            {
                "id": "frame-project",
                "title": "Start with the problem, not the algorithm",
                "order": 1,
            },
            {
                "id": "get-split-data",
                "title": "Get the data, inspect it, and create the test set early",
                "order": 2,
            },
            {
                "id": "explore-data",
                "title": "Explore the training data and engineer useful features",
                "order": 3,
            },
            {
                "id": "prepare-data",
                "title": "Prepare data with reusable transformations",
                "order": 4,
            },
            {
                "id": "pipelines-transformers",
                "title": "Build preprocessing pipelines instead of disconnected steps",
                "order": 5,
            },
            {
                "id": "train-evaluate",
                "title": "Train baselines, then evaluate with cross-validation",
                "order": 6,
            },
            {
                "id": "fine-tune",
                "title": "Fine-tune the system and analyze its errors",
                "order": 7,
            },
            {
                "id": "test-present",
                "title": "Test once, communicate the result, and prepare for production",
                "order": 8,
            },
            {
                "id": "deploy-monitor",
                "title": "Deployment is the beginning of the operational lifecycle",
                "order": 9,
            },
        ],
    },


    # =======================================================================
    # INLINE EXERCISES
    # =======================================================================

    "exercises": [
        {
            "id": "M01.L02.EX01",

            "title": "Design a Safe Train/Test Split",

            "lesson_code": "M01.L02",

            "section_id": "get-split-data",

            "placement": "after_section",

            "description": (
                "Practice protecting the test set and deciding when stratified "
                "sampling is more appropriate than a purely random split."
            ),

            "instructions": (
                "You are building a regression model for apartment prices. The "
                "dataset contains 18,000 rows, and domain experts tell you that "
                "neighborhood price tier is strongly related to the target.\n\n"
                "1. Explain why you should create the test set before doing deep "
                "exploratory analysis.\n"
                "2. Describe one problem with generating a different random test "
                "set every time the notebook runs.\n"
                "3. Propose a temporary categorical feature that could be used "
                "for stratified sampling.\n"
                "4. Write a short Scikit-Learn code snippet using "
                "train_test_split(..., stratify=...).\n"
                "5. State what you should do with the temporary stratification "
                "feature after the split if it is not intended to be a model "
                "input."
            ),

            "expected_output": (
                "A short explanation of data snooping and split stability, plus "
                "a valid stratified train/test split snippet and a statement "
                "that any temporary stratification-only column should be removed "
                "after splitting."
            ),

            "difficulty": DifficultyLevel.beginner,

            "skill_tested": [
                "train-test-split",
                "data-snooping",
                "stratified-sampling",
                "scikit-learn",
                "reasoning",
            ],
        },

        {
            "id": "M01.L02.EX02",

            "title": "Build and Diagnose an End-to-End Regression Pipeline",

            "lesson_code": "M01.L02",

            "section_id": "deploy-monitor",

            "placement": "after_section",

            "description": (
                "Connect preprocessing, cross-validation, tuning, final testing, "
                "and production monitoring into one coherent workflow."
            ),

            "instructions": (
                "Suppose a regression dataset contains numerical columns, one "
                "categorical column, missing numerical values, and a strongly "
                "right-skewed positive feature.\n\n"
                "1. Describe a preprocessing pipeline that handles all four "
                "conditions.\n"
                "2. Explain why every learned preprocessing step must be fitted "
                "only on training data.\n"
                "3. Your decision tree has training RMSE = 0 but 5-fold CV RMSE "
                "= 62,000. Diagnose the result.\n"
                "4. Explain whether you would use GridSearchCV or "
                "RandomizedSearchCV for a large search space and why.\n"
                "5. State when the final test set should be evaluated.\n"
                "6. Name four things you would monitor after deployment and one "
                "rollback artifact you must keep."
            ),

            "expected_output": (
                "A compact end-to-end design containing imputation, categorical "
                "encoding, skew transformation and scaling, a correct overfitting "
                "diagnosis, validation-based tuning, one final untouched test "
                "evaluation, and a practical monitoring/rollback plan."
            ),

            "difficulty": DifficultyLevel.beginner,

            "skill_tested": [
                "preprocessing-pipelines",
                "data-leakage",
                "cross-validation",
                "overfitting",
                "hyperparameter-search",
                "production-monitoring",
            ],
        },
    ],


    # =======================================================================
    # LESSON QUIZ
    # =======================================================================

    "quiz": {
        "id": "M01.L02.QZ01",

        "title": "End-to-End Machine Learning Project — Knowledge Check",

        "lesson_code": "M01.L02",

        "placement": "lesson_end",

        "questions": [
            {
                "id": "M01.L02.Q01",

                "section_id": "frame-project",

                "question": (
                    "Why should you understand how a model's prediction will be "
                    "used before selecting algorithms?"
                ),

                "options": [
                    "Because every downstream system requires neural networks.",
                    "Because the business use determines problem framing, metrics, assumptions, and required accuracy.",
                    "Because model selection must happen before data collection.",
                    "Because deployment architecture determines the training labels automatically.",
                ],

                "correct": 1,

                "explanation": (
                    "The real objective and downstream use shape the ML problem, "
                    "the metric, the acceptable errors, and the level of effort "
                    "required."
                ),
            },

            {
                "id": "M01.L02.Q02",

                "section_id": "frame-project",

                "question": (
                    "Why is RMSE generally more sensitive to large prediction "
                    "errors than MAE?"
                ),

                "options": [
                    "RMSE ignores small errors.",
                    "RMSE squares errors before averaging, increasing the influence of large errors.",
                    "MAE always converts targets into categories.",
                    "RMSE uses fewer examples.",
                ],

                "correct": 1,

                "explanation": (
                    "Squaring the errors gives large errors disproportionate "
                    "weight before the mean and square root are computed."
                ),
            },

            {
                "id": "M01.L02.Q03",

                "section_id": "get-split-data",

                "question": (
                    "What is the main purpose of stratified sampling in the "
                    "housing example?"
                ),

                "options": [
                    "To increase the size of the dataset.",
                    "To ensure important income groups are represented in similar proportions in the test set.",
                    "To remove missing values.",
                    "To turn regression into classification.",
                ],

                "correct": 1,

                "explanation": (
                    "Income categories are temporarily used as strata so the test "
                    "set better represents the overall distribution of this "
                    "important attribute."
                ),
            },

            {
                "id": "M01.L02.Q04",

                "section_id": "explore-data",

                "question": (
                    "What important limitation should you remember when using "
                    "Pearson correlation?"
                ),

                "options": [
                    "It only works for categorical variables.",
                    "It measures linear association and can miss strong nonlinear relationships.",
                    "It is always positive.",
                    "It can only be computed after model training.",
                ],

                "correct": 1,

                "explanation": (
                    "Pearson's r summarizes linear association. A nonlinear "
                    "relationship may be highly informative even when its "
                    "correlation is close to zero."
                ),
            },

            {
                "id": "M01.L02.Q05",

                "section_id": "prepare-data",

                "question": (
                    "Why should a SimpleImputer or StandardScaler be fitted only "
                    "on the training set?"
                ),

                "options": [
                    "Scikit-Learn cannot transform test data.",
                    "Fitting on validation or test data would leak information from those sets into model development.",
                    "The test set always contains different columns.",
                    "Scalers cannot store learned values.",
                ],

                "correct": 1,

                "explanation": (
                    "Preprocessing parameters such as medians, means, and standard "
                    "deviations are learned information. They must come only from "
                    "training data to keep evaluation honest."
                ),
            },

            {
                "id": "M01.L02.Q06",

                "section_id": "pipelines-transformers",

                "question": (
                    "What is a major advantage of putting preprocessing and the "
                    "model into a Scikit-Learn pipeline?"
                ),

                "options": [
                    "It guarantees zero test error.",
                    "It applies the same ordered learned transformations consistently during training and prediction.",
                    "It eliminates the need for validation.",
                    "It automatically collects new labels in production.",
                ],

                "correct": 1,

                "explanation": (
                    "Pipelines reduce mismatches and leakage by packaging the "
                    "ordered preprocessing steps and estimator into one reusable "
                    "object."
                ),
            },

            {
                "id": "M01.L02.Q07",

                "section_id": "train-evaluate",

                "question": (
                    "A decision tree has training RMSE = 0 but much worse "
                    "cross-validation RMSE. What is the most likely explanation?"
                ),

                "options": [
                    "The tree is underfitting.",
                    "The tree is strongly overfitting the training data.",
                    "The test set is too easy.",
                    "RMSE cannot evaluate decision trees.",
                ],

                "correct": 1,

                "explanation": (
                    "Perfect training performance combined with much worse "
                    "validation performance is a strong sign that the model "
                    "memorized training-specific patterns."
                ),
            },

            {
                "id": "M01.L02.Q08",

                "section_id": "fine-tune",

                "question": (
                    "Why is RandomizedSearchCV often preferable to GridSearchCV "
                    "for a very large hyperparameter space?"
                ),

                "options": [
                    "It never needs cross-validation.",
                    "It can explore a controlled number of sampled configurations without evaluating the full Cartesian grid.",
                    "It always finds the global optimum in one iteration.",
                    "It tunes only preprocessing parameters.",
                ],

                "correct": 1,

                "explanation": (
                    "Randomized search lets you set a computational budget while "
                    "sampling broadly from large or continuous search spaces."
                ),
            },

            {
                "id": "M01.L02.Q09",

                "section_id": "test-present",

                "type": "open",

                "question": (
                    "Explain why a team should not change hyperparameters after "
                    "seeing the final test-set result merely to make that test "
                    "score look better."
                ),
            },

            {
                "id": "M01.L02.Q10",

                "section_id": "deploy-monitor",

                "type": "open",

                "question": (
                    "After deployment, name at least four things you would monitor "
                    "and explain why keeping previous model and dataset versions "
                    "is operationally important."
                ),
            },
        ],

        "passing_score": 70,
    },
}
