"""Masar curriculum seed — L011-053."""

LESSON_META = {'lesson_id': 'L011-053', 'course_id': 'COURSE-011', 'module_id': 'M011-04', 'title': 'Professional Git Workflow for Production AI Repositories', 'slug': 'professional-git-workflow-for-production-ai-repositories', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply professional git workflow for production ai repositories concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['status before changes', 'meaningful commits', 'pull before push', 'no direct main commits', 'feature branch to PR lifecycle']

SOURCE_REFERENCES = ['Secondary DevOps source (source ID not provided) — Chapter 3: Mastering Version Control with Git and GitHub']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-053 — Professional Git Workflow for Production AI Repositories\n\n## Learning objective\n\nApply professional git workflow for production ai repositories concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- status before changes\n- meaningful commits\n- pull before push\n- no direct main commits\n- feature branch to PR lifecycle\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-053-EX1', 'title': 'Apply Professional Git Workflow for Production AI Repositories', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: status before changes, meaningful commits, pull before push. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-053-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to professional git workflow for production ai repositories. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-053-Q1', 'type': 'short_answer', 'question': 'What production problem is professional git workflow for production ai repositories intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: status before changes, meaningful commits, pull before push.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-053-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-053-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Professional Git Workflow for Production AI Repositories.', 'answer': 'status before changes, meaningful commits', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
