"""Masar curriculum seed — L011-054."""

LESSON_META = {'lesson_id': 'L011-054', 'course_id': 'COURSE-011', 'module_id': 'M011-04', 'title': 'Git & GitHub Integration Lab for an AI Service', 'slug': 'git-and-github-integration-lab-for-an-ai-service', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply git & github integration lab for an ai service concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['existing AI service repository', 'feature branch', 'deployment-related change', 'pull request', 'simulated conflict and clean merge']

SOURCE_REFERENCES = ['Secondary DevOps source (source ID not provided) — Chapter 3: Mastering Version Control with Git and GitHub']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-054 — Git & GitHub Integration Lab for an AI Service\n\n## Learning objective\n\nApply git & github integration lab for an ai service concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- existing AI service repository\n- feature branch\n- deployment-related change\n- pull request\n- simulated conflict and clean merge\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-054-EX1', 'title': 'Apply Git & GitHub Integration Lab for an AI Service', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: existing AI service repository, feature branch, deployment-related change. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-054-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to git & github integration lab for an ai service. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-054-Q1', 'type': 'short_answer', 'question': 'What production problem is git & github integration lab for an ai service intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: existing AI service repository, feature branch, deployment-related change.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-054-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-054-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Git & GitHub Integration Lab for an AI Service.', 'answer': 'existing AI service repository, feature branch', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = {'id': 'M011-04-PROJECT', 'title': 'Git & GitHub Integration Lab for an AI Service', 'brief': "Integrate the module's lessons into a coherent AI-engineering deliverable for git & github workflow for ai deployment.", 'requirements': ['Use an existing AI workload rather than rebuilding FastAPI/LLM/RAG/Agent fundamentals.', 'Document architecture and security boundaries.', 'Demonstrate a working validation path.', 'Include at least one failure/recovery or rollback scenario.', 'Preserve stable course/module/lesson identifiers in any generated artifacts.']}
