"""Masar curriculum seed — L011-051."""

LESSON_META = {'lesson_id': 'L011-051', 'course_id': 'COURSE-011', 'module_id': 'M011-04', 'title': 'Protected Main Branches & CI Merge Gates', 'slug': 'protected-main-branches-and-ci-merge-gates', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply protected main branches & ci merge gates concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['branch protection', 'required reviews', 'required status checks', 'CI merge gates', 'keeping main deployable']

SOURCE_REFERENCES = ['Secondary DevOps source (source ID not provided) — Chapter 3: Mastering Version Control with Git and GitHub']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-051 — Protected Main Branches & CI Merge Gates\n\n## Learning objective\n\nApply protected main branches & ci merge gates concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- branch protection\n- required reviews\n- required status checks\n- CI merge gates\n- keeping main deployable\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-051-EX1', 'title': 'Apply Protected Main Branches & CI Merge Gates', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: branch protection, required reviews, required status checks. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-051-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to protected main branches & ci merge gates. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-051-Q1', 'type': 'short_answer', 'question': 'What production problem is protected main branches & ci merge gates intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: branch protection, required reviews, required status checks.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-051-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-051-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Protected Main Branches & CI Merge Gates.', 'answer': 'branch protection, required reviews', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
