"""Masar curriculum seed — L011-048."""

LESSON_META = {'lesson_id': 'L011-048', 'course_id': 'COURSE-011', 'module_id': 'M011-04', 'title': 'Branching for AI Service Development & Deployment', 'slug': 'branching-for-ai-service-development-and-deployment', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply branching for ai service development & deployment concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['branch isolation', 'main branch stability', 'feature/fix/release/hotfix branches', 'GitFlow concepts', 'simpler deployment-oriented branching awareness']

SOURCE_REFERENCES = ['Secondary DevOps source (source ID not provided) — Chapter 3: Mastering Version Control with Git and GitHub']

FIGURE_REFERENCES = [{'source_figure': 'Figure 3.2', 'title': 'GitFlow model', 'priority': 'required', 'suggested_path': 'assets/m011-04/fig-3-2-gitflow.png'}]

LESSON_MARKDOWN = '# L011-048 — Branching for AI Service Development & Deployment\n\n## Learning objective\n\nApply branching for ai service development & deployment concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- branch isolation\n- main branch stability\n- feature/fix/release/hotfix branches\n- GitFlow concepts\n- simpler deployment-oriented branching awareness\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n\n## Manual visual references\n- `Figure 3.2` — GitFlow model (required); add manually at `assets/m011-04/fig-3-2-gitflow.png`.\n'

EXERCISES = [{'id': 'L011-048-EX1', 'title': 'Apply Branching for AI Service Development & Deployment', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: branch isolation, main branch stability, feature/fix/release/hotfix branches. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-048-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to branching for ai service development & deployment. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-048-Q1', 'type': 'short_answer', 'question': 'What production problem is branching for ai service development & deployment intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: branch isolation, main branch stability, feature/fix/release/hotfix branches.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-048-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-048-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Branching for AI Service Development & Deployment.', 'answer': 'branch isolation, main branch stability', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
