"""Masar curriculum seed — L011-050."""

LESSON_META = {'lesson_id': 'L011-050', 'course_id': 'COURSE-011', 'module_id': 'M011-04', 'title': 'Code Review for AI Infrastructure Changes', 'slug': 'code-review-for-ai-infrastructure-changes', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply code review for ai infrastructure changes concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['reviewing Docker/deployment config', 'security review', 'architectural consistency', 'diff inspection', 'deployment safety']

SOURCE_REFERENCES = ['Secondary DevOps source (source ID not provided) — Chapter 3: Mastering Version Control with Git and GitHub']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-050 — Code Review for AI Infrastructure Changes\n\n## Learning objective\n\nApply code review for ai infrastructure changes concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- reviewing Docker/deployment config\n- security review\n- architectural consistency\n- diff inspection\n- deployment safety\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-050-EX1', 'title': 'Apply Code Review for AI Infrastructure Changes', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: reviewing Docker/deployment config, security review, architectural consistency. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-050-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to code review for ai infrastructure changes. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-050-Q1', 'type': 'short_answer', 'question': 'What production problem is code review for ai infrastructure changes intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: reviewing Docker/deployment config, security review, architectural consistency.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-050-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-050-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Code Review for AI Infrastructure Changes.', 'answer': 'reviewing Docker/deployment config, security review', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
