"""Masar curriculum seed — L011-070."""

LESSON_META = {'lesson_id': 'L011-070', 'course_id': 'COURSE-011', 'module_id': 'M011-06', 'title': 'Infrastructure as Code in the Delivery Pipeline', 'slug': 'infrastructure-as-code-in-the-delivery-pipeline', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply infrastructure as code in the delivery pipeline concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['Infrastructure as Code', 'Terraform', 'pipeline-managed infrastructure', 'centralized execution', 'repeatable provisioning']

SOURCE_REFERENCES = ['Secondary DevOps source (source ID not provided) — Chapter 7: Automating Infrastructure with Terraform and CI/CD']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-070 — Infrastructure as Code in the Delivery Pipeline\n\n## Learning objective\n\nApply infrastructure as code in the delivery pipeline concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- Infrastructure as Code\n- Terraform\n- pipeline-managed infrastructure\n- centralized execution\n- repeatable provisioning\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-070-EX1', 'title': 'Apply Infrastructure as Code in the Delivery Pipeline', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: Infrastructure as Code, Terraform, pipeline-managed infrastructure. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-070-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to infrastructure as code in the delivery pipeline. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-070-Q1', 'type': 'short_answer', 'question': 'What production problem is infrastructure as code in the delivery pipeline intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: Infrastructure as Code, Terraform, pipeline-managed infrastructure.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-070-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-070-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Infrastructure as Code in the Delivery Pipeline.', 'answer': 'Infrastructure as Code, Terraform', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
