"""Masar curriculum seed — L011-085."""

LESSON_META = {'lesson_id': 'L011-085', 'course_id': 'COURSE-011', 'module_id': 'M011-06', 'title': 'GitOps Infrastructure Delivery Project', 'slug': 'gitops-infrastructure-delivery-project', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply gitops infrastructure delivery project concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['version-controlled Terraform', 'automated staging apply', 'remote state', 'production manual approval', 'separate production state', 'failure and backend debugging']

SOURCE_REFERENCES = ['Secondary DevOps source (source ID not provided) — Chapter 7: Automating Infrastructure with Terraform and CI/CD']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-085 — GitOps Infrastructure Delivery Project\n\n## Learning objective\n\nApply gitops infrastructure delivery project concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- version-controlled Terraform\n- automated staging apply\n- remote state\n- production manual approval\n- separate production state\n- failure and backend debugging\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-085-EX1', 'title': 'Apply GitOps Infrastructure Delivery Project', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: version-controlled Terraform, automated staging apply, remote state. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-085-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to gitops infrastructure delivery project. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-085-Q1', 'type': 'short_answer', 'question': 'What production problem is gitops infrastructure delivery project intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: version-controlled Terraform, automated staging apply, remote state.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-085-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-085-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by GitOps Infrastructure Delivery Project.', 'answer': 'version-controlled Terraform, automated staging apply', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = {'id': 'M011-06-PROJECT', 'title': 'GitOps Infrastructure Delivery Project', 'brief': "Integrate the module's lessons into a coherent AI-engineering deliverable for automated infrastructure delivery for ai systems.", 'requirements': ['Use an existing AI workload rather than rebuilding FastAPI/LLM/RAG/Agent fundamentals.', 'Document architecture and security boundaries.', 'Demonstrate a working validation path.', 'Include at least one failure/recovery or rollback scenario.', 'Preserve stable course/module/lesson identifiers in any generated artifacts.']}
