"""Masar curriculum seed — L011-078."""

LESSON_META = {'lesson_id': 'L011-078', 'course_id': 'COURSE-011', 'module_id': 'M011-06', 'title': 'Troubleshooting Terraform Backend & Permission Failures', 'slug': 'troubleshooting-terraform-backend-and-permission-failures', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply troubleshooting terraform backend & permission failures concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['AccessDenied', 'NoSuchBucket', 'region mismatch', 'stale locks', 'backend troubleshooting from workflow logs']

SOURCE_REFERENCES = ['Secondary DevOps source (source ID not provided) — Chapter 7: Automating Infrastructure with Terraform and CI/CD']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-078 — Troubleshooting Terraform Backend & Permission Failures\n\n## Learning objective\n\nApply troubleshooting terraform backend & permission failures concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- AccessDenied\n- NoSuchBucket\n- region mismatch\n- stale locks\n- backend troubleshooting from workflow logs\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-078-EX1', 'title': 'Apply Troubleshooting Terraform Backend & Permission Failures', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: AccessDenied, NoSuchBucket, region mismatch. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-078-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to troubleshooting terraform backend & permission failures. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-078-Q1', 'type': 'short_answer', 'question': 'What production problem is troubleshooting terraform backend & permission failures intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: AccessDenied, NoSuchBucket, region mismatch.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-078-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-078-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Troubleshooting Terraform Backend & Permission Failures.', 'answer': 'AccessDenied, NoSuchBucket', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
