"""Masar curriculum seed — L011-079."""

LESSON_META = {'lesson_id': 'L011-079', 'course_id': 'COURSE-011', 'module_id': 'M011-06', 'title': 'Separating Staging & Production Infrastructure', 'slug': 'separating-staging-and-production-infrastructure', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply separating staging & production infrastructure concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['environment isolation', 'separate state keys', 'staging vs production variables', 'tfvars', 'preventing shared-state accidents']

SOURCE_REFERENCES = ['Secondary DevOps source (source ID not provided) — Chapter 7: Automating Infrastructure with Terraform and CI/CD']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-079 — Separating Staging & Production Infrastructure\n\n## Learning objective\n\nApply separating staging & production infrastructure concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- environment isolation\n- separate state keys\n- staging vs production variables\n- tfvars\n- preventing shared-state accidents\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-079-EX1', 'title': 'Apply Separating Staging & Production Infrastructure', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: environment isolation, separate state keys, staging vs production variables. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-079-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to separating staging & production infrastructure. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-079-Q1', 'type': 'short_answer', 'question': 'What production problem is separating staging & production infrastructure intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: environment isolation, separate state keys, staging vs production variables.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-079-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-079-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Separating Staging & Production Infrastructure.', 'answer': 'environment isolation, separate state keys', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
