"""Masar curriculum seed — L011-084."""

LESSON_META = {'lesson_id': 'L011-084', 'course_id': 'COURSE-011', 'module_id': 'M011-06', 'title': 'AI-Assisted Infrastructure Review', 'slug': 'ai-assisted-infrastructure-review', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply ai-assisted infrastructure review concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['AI-assisted Terraform authoring', 'plan summarization', 'destructive-change flags', 'security/best-practice review', 'drift analysis']

SOURCE_REFERENCES = ['Secondary DevOps source (source ID not provided) — Chapter 7: Automating Infrastructure with Terraform and CI/CD']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-084 — AI-Assisted Infrastructure Review\n\n## Learning objective\n\nApply ai-assisted infrastructure review concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- AI-assisted Terraform authoring\n- plan summarization\n- destructive-change flags\n- security/best-practice review\n- drift analysis\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-084-EX1', 'title': 'Apply AI-Assisted Infrastructure Review', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: AI-assisted Terraform authoring, plan summarization, destructive-change flags. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-084-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to ai-assisted infrastructure review. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-084-Q1', 'type': 'short_answer', 'question': 'What production problem is ai-assisted infrastructure review intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: AI-assisted Terraform authoring, plan summarization, destructive-change flags.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-084-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-084-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by AI-Assisted Infrastructure Review.', 'answer': 'AI-assisted Terraform authoring, plan summarization', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
