"""Masar curriculum seed — L011-080."""

LESSON_META = {'lesson_id': 'L011-080', 'course_id': 'COURSE-011', 'module_id': 'M011-06', 'title': 'Protected Production Environments in GitHub Actions', 'slug': 'protected-production-environments-in-github-actions', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply protected production environments in github actions concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['GitHub Environments', 'environment: production', 'required reviewers', 'deployment protection', 'human-in-the-loop control']

SOURCE_REFERENCES = ['Secondary DevOps source (source ID not provided) — Chapter 7: Automating Infrastructure with Terraform and CI/CD']

FIGURE_REFERENCES = [{'source_figure': 'Figure 7.2', 'title': 'Creating a GitHub environment', 'priority': 'optional', 'suggested_path': 'assets/m011-06/fig-7-2-github-environment.png'}]

LESSON_MARKDOWN = '# L011-080 — Protected Production Environments in GitHub Actions\n\n## Learning objective\n\nApply protected production environments in github actions concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- GitHub Environments\n- environment: production\n- required reviewers\n- deployment protection\n- human-in-the-loop control\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n\n## Manual visual references\n- `Figure 7.2` — Creating a GitHub environment (optional); add manually at `assets/m011-06/fig-7-2-github-environment.png`.\n'

EXERCISES = [{'id': 'L011-080-EX1', 'title': 'Apply Protected Production Environments in GitHub Actions', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: GitHub Environments, environment: production, required reviewers. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-080-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to protected production environments in github actions. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-080-Q1', 'type': 'short_answer', 'question': 'What production problem is protected production environments in github actions intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: GitHub Environments, environment: production, required reviewers.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-080-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-080-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by Protected Production Environments in GitHub Actions.', 'answer': 'GitHub Environments, environment: production', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
