"""Masar curriculum seed — L011-071."""

LESSON_META = {'lesson_id': 'L011-071', 'course_id': 'COURSE-011', 'module_id': 'M011-06', 'title': 'GitOps for Cloud Infrastructure', 'slug': 'gitops-for-cloud-infrastructure', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply gitops for cloud infrastructure concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['Git as desired-state source', 'auditability', 'pull-request infrastructure changes', 'consistent execution', 'infrastructure traceability']

SOURCE_REFERENCES = ['Secondary DevOps source (source ID not provided) — Chapter 7: Automating Infrastructure with Terraform and CI/CD']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-071 — GitOps for Cloud Infrastructure\n\n## Learning objective\n\nApply gitops for cloud infrastructure concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- Git as desired-state source\n- auditability\n- pull-request infrastructure changes\n- consistent execution\n- infrastructure traceability\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-071-EX1', 'title': 'Apply GitOps for Cloud Infrastructure', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: Git as desired-state source, auditability, pull-request infrastructure changes. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-071-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to gitops for cloud infrastructure. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-071-Q1', 'type': 'short_answer', 'question': 'What production problem is gitops for cloud infrastructure intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: Git as desired-state source, auditability, pull-request infrastructure changes.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-071-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-071-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by GitOps for Cloud Infrastructure.', 'answer': 'Git as desired-state source, auditability', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = None
