"""Masar curriculum seed — L011-069."""

LESSON_META = {'lesson_id': 'L011-069', 'course_id': 'COURSE-011', 'module_id': 'M011-05', 'title': 'GitHub Actions CI/CD Integration Project', 'slug': 'github-actions-ci-cd-integration-project', 'status': 'approved', 'difficulty': 'intermediate-to-advanced', 'estimated_minutes': None, 'learning_objective': 'Apply github actions ci/cd integration project concepts to the deployment and operation of an existing production-oriented AI service.'}

TOPICS = ['PR-triggered CI', 'protected main', 'push-to-main CD', 'ECR publication', 'Terraform-integrated staging deployment', 'failure logs and verification']

SOURCE_REFERENCES = ['Secondary DevOps source (source ID not provided) — Chapter 6: Constructing Your First CI/CD Pipeline']

FIGURE_REFERENCES = []

LESSON_MARKDOWN = '# L011-069 — GitHub Actions CI/CD Integration Project\n\n## Learning objective\n\nApply github actions ci/cd integration project concepts to the deployment and operation of an existing production-oriented AI service.\n\n## Core topics\n\n- PR-triggered CI\n- protected main\n- push-to-main CD\n- ECR publication\n- Terraform-integrated staging deployment\n- failure logs and verification\n\n## AI-engineering context\n\nUse these concepts to deploy or operate an **existing** FastAPI, LLM, RAG, or AI Agent service. Do not re-teach the application-domain fundamentals in this course.\n\n## Practice\n\nApply the lesson to a production-oriented AI backend and document the configuration, security boundary, validation method, and failure behavior relevant to this topic.\n\n## Assessment focus\n\nThe learner should be able to explain the purpose of the topic, configure or review the relevant deployment artifact, and diagnose a realistic failure without relying on trial-and-error console clicking.\n\n'

EXERCISES = [{'id': 'L011-069-EX1', 'title': 'Apply GitHub Actions CI/CD Integration Project', 'prompt': "Apply the lesson's concepts to an existing AI service. Cover at least: PR-triggered CI, protected main, push-to-main CD. Record the configuration or architecture decision and how you would validate it."}, {'id': 'L011-069-EX2', 'title': 'Failure and recovery exercise', 'prompt': 'Create or analyze one realistic failure related to github actions ci/cd integration project. Identify the observable symptom, likely cause, safe correction, and post-fix validation step.'}]

QUIZ = [{'id': 'L011-069-Q1', 'type': 'short_answer', 'question': 'What production problem is github actions ci/cd integration project intended to solve in an AI-service deployment?', 'answer': 'It addresses the deployment/operations concerns represented by: PR-triggered CI, protected main, push-to-main CD.', 'explanation': 'A correct answer should connect the concept to deployment reliability, security, repeatability, scalability, or operability rather than re-explaining AI application fundamentals.'}, {'id': 'L011-069-Q2', 'type': 'true_false', 'question': 'This lesson should be applied without considering security boundaries, failure behavior, or validation.', 'answer': False, 'explanation': 'Production deployment decisions must include security, failure handling, and verification.'}, {'id': 'L011-069-Q3', 'type': 'short_answer', 'question': 'Name two concrete topics covered by GitHub Actions CI/CD Integration Project.', 'answer': 'PR-triggered CI, protected main', 'explanation': "The answer should use the lesson's declared core topics."}]

PROJECT = {'id': 'M011-05-PROJECT', 'title': 'GitHub Actions CI/CD Integration Project', 'brief': "Integrate the module's lessons into a coherent AI-engineering deliverable for automated ci/cd for ai services.", 'requirements': ['Use an existing AI workload rather than rebuilding FastAPI/LLM/RAG/Agent fundamentals.', 'Document architecture and security boundaries.', 'Demonstrate a working validation path.', 'Include at least one failure/recovery or rollback scenario.', 'Preserve stable course/module/lesson identifiers in any generated artifacts.']}
