"""
app/content/vocabulary_seed_terms.py

Curated additions to the AI Vocabulary dictionary, beyond the 65 legacy terms
already in `ai_terms.json` (those are migrated as-is by `seeds/seed_vocabulary.py`).

Each entry is authored, not extracted: a term only belongs here once someone
has actually written its Arabic explanation, decided its category and
difficulty, and picked which existing terms it should link to. This is
deliberately a *seed* of high-value cross-course concepts (the ones curriculum
courses 8-15 lean on heavily and the legacy dictionary never covered — vision-
language, agents, voice AI, retrieval infrastructure, and the engineering
vocabulary — reranking, quantization, observability — that shows up across
almost every advanced course) rather than an attempt to enumerate every
concept string in every lesson; `related` lists reference other slugs in this
file or in the legacy dictionary and are resolved by slug at seed time.
"""

TERMS = [
    {
        "slug": "retrieval_augmented_generation",
        "term_en": "Retrieval-Augmented Generation",
        "term_ar": "التوليد المعزَّز بالاسترجاع",
        "acronym": "RAG",
        "aliases": ["retrieval augmented generation", "rag"],
        "category": "RAG",
        "difficulty": "intermediate",
        "tags": ["retrieval", "generation", "grounding"],
        "definition_en": "An architecture that retrieves relevant documents from an external store and passes them to a language model as context, so its answer is grounded in that content instead of only in what it memorized during training.",
        "definition_ar": "بنية تسترجع مستندات ذات صلة من مخزن خارجي وتمررها كسياق إلى نموذج لغوي، بحيث تكون إجابته مستندة إلى هذا المحتوى بدلاً من الاعتماد فقط على ما حفظه النموذج أثناء التدريب.",
        "explanation_simple_ar": "بدل أن يعتمد النموذج على ذاكرته فقط، يبحث أولاً في مصدر بيانات حقيقي، ثم يبني إجابته على ما وجده.",
        "why_it_matters_ar": "تقلل RAG من الهلوسة وتتيح للنموذج الإجابة عن معلومات محدّثة أو خاصة بمؤسسة معينة دون إعادة تدريبه.",
        "example_ar": "روبوت دعم فني يبحث في وثائق المنتج قبل الرد على سؤال العميل.",
        "related": ["dense_retrieval", "vector_database", "embedding", "reranking", "grounding", "chunking"],
    },
    {
        "slug": "embedding",
        "term_en": "Embedding",
        "term_ar": "التمثيل المتجهي",
        "acronym": None,
        "aliases": ["embeddings", "vector embedding"],
        "category": "Representation Learning",
        "difficulty": "beginner",
        "tags": ["representation", "vectors"],
        "definition_en": "A numerical vector representation of text, images or other data such that semantically similar inputs are mapped to nearby points in the vector space.",
        "definition_ar": "تمثيل رقمي يحوّل النص أو الصورة أو بيانات أخرى إلى متجه من الأرقام، بحيث تكون العناصر المتشابهة في المعنى قريبة من بعضها في الفضاء المتجهي.",
        "explanation_simple_ar": "طريقة لتحويل الكلمات أو الجمل إلى أرقام تحافظ على معناها، فتصبح مقارنة \"التشابه\" بين نصّين عملية حسابية.",
        "why_it_matters_ar": "الـ Embedding هو الأساس الذي يقوم عليه البحث الدلالي، والتوصية، وأنظمة RAG بالكامل.",
        "example_ar": "جملتا \"سيارة سريعة\" و\"مركبة عالية السرعة\" تحصلان على متجهات قريبة من بعضها.",
        "related": ["semantic_similarity", "vector_search", "dense_retrieval", "vector_database"],
    },
    {
        "slug": "vector_database",
        "term_en": "Vector Database",
        "term_ar": "قاعدة بيانات متجهية",
        "acronym": None,
        "aliases": ["vector store", "vector db"],
        "category": "RAG",
        "difficulty": "intermediate",
        "tags": ["retrieval", "infrastructure"],
        "definition_en": "A database purpose-built to store embedding vectors and answer nearest-neighbor similarity queries efficiently at scale.",
        "definition_ar": "قاعدة بيانات مصمّمة خصيصاً لتخزين المتجهات (embeddings) والإجابة بكفاءة عن استعلامات \"أقرب الجيران\" على نطاق واسع.",
        "explanation_simple_ar": "مكان لتخزين ملايين المتجهات بحيث يمكن إيجاد الأقرب إلى متجه معين في أجزاء من الثانية.",
        "why_it_matters_ar": "بدون قاعدة بيانات متجهية، يصبح البحث الدلالي على كميات كبيرة من البيانات بطيئاً جداً ليكون عملياً.",
        "example_ar": "Qdrant وPinecone وpgvector أمثلة على قواعد بيانات متجهية.",
        "related": ["embedding", "vector_search", "dense_retrieval"],
    },
    {
        "slug": "vector_search",
        "term_en": "Vector Search",
        "term_ar": "البحث المتجهي",
        "acronym": None,
        "aliases": ["nearest neighbor search", "similarity search"],
        "category": "RAG",
        "difficulty": "intermediate",
        "tags": ["retrieval"],
        "definition_en": "Finding the items whose embedding vectors are closest to a query vector, typically by cosine similarity or another distance metric.",
        "definition_ar": "إيجاد العناصر التي تكون متجهاتها الأقرب إلى متجه الاستعلام، عادةً باستخدام التشابه الجيبي (cosine) أو مقياس مسافة آخر.",
        "explanation_simple_ar": "بحث لا يعتمد على تطابق الكلمات، بل على تشابه المعنى بين المتجهات.",
        "why_it_matters_ar": "هو ما يمكّن الأنظمة من إيجاد \"أقرب معنى\" بدلاً من \"أقرب نص حرفي\".",
        "example_ar": "البحث عن \"كيف أعيد كلمة السر\" يعثر على مستند بعنوان \"إعادة تعيين حساب المستخدم\" لأن معناهما قريب.",
        "related": ["embedding", "dense_retrieval", "semantic_similarity"],
    },
    {
        "slug": "dense_retrieval",
        "term_en": "Dense Retrieval",
        "term_ar": "الاسترجاع الكثيف",
        "acronym": None,
        "aliases": ["dense retrieval", "dense passage retrieval"],
        "category": "RAG",
        "difficulty": "advanced",
        "tags": ["retrieval"],
        "definition_en": "Retrieval that ranks documents by embedding similarity rather than exact keyword overlap, as opposed to sparse methods like BM25.",
        "definition_ar": "استرجاع يرتّب المستندات بحسب تشابه المتجهات لا بحسب تطابق الكلمات المفتاحية الحرفي، على عكس الطرق التقليدية مثل BM25.",
        "explanation_simple_ar": "يبحث عن المعنى القريب حتى لو لم تتطابق الكلمات نفسها.",
        "why_it_matters_ar": "يحسّن جودة الاسترجاع في الحالات التي تُصاغ فيها الأسئلة بكلمات مختلفة عن المستند الصحيح.",
        "example_ar": "سؤال \"سعر الاشتراك السنوي\" يجد مستنداً يتحدث عن \"تكلفة الباقة لمدة عام\" دون تطابق كلمات.",
        "related": ["vector_search", "embedding", "reranking"],
    },
    {
        "slug": "reranking",
        "term_en": "Reranking",
        "term_ar": "إعادة الترتيب",
        "acronym": None,
        "aliases": ["re-ranking", "rerank"],
        "category": "RAG",
        "difficulty": "advanced",
        "tags": ["retrieval", "ranking"],
        "definition_en": "A second, more expensive scoring pass over an initial set of retrieved candidates, using a model that jointly evaluates the query and each candidate, to push the truly best matches to the top.",
        "definition_ar": "مرحلة تقييم ثانية أكثر دقة (وأعلى تكلفة) تُطبّق على مجموعة أولية من النتائج المسترجعة، باستخدام نموذج يقيّم الاستعلام والنتيجة معاً لدفع أفضل التطابقات إلى القمة.",
        "explanation_simple_ar": "بعد جلب مجموعة أولية من النتائج بسرعة، تعاد ترتيبها بدقة أكبر لاختيار الأفضل فعلاً.",
        "why_it_matters_ar": "الاسترجاع الأولي سريع لكنه تقريبي؛ إعادة الترتيب ترفع دقة أفضل النتائج قبل عرضها أو تمريرها للنموذج.",
        "example_ar": "استرجاع 50 مستنداً بسرعة، ثم إعادة ترتيبها لاختيار أفضل 5 لتمريرها للنموذج.",
        "related": ["dense_retrieval", "retrieval_augmented_generation", "chunking"],
    },
    {
        "slug": "grounding",
        "term_en": "Grounding",
        "term_ar": "التأسيس على مصدر",
        "acronym": None,
        "aliases": ["grounded generation"],
        "category": "RAG",
        "difficulty": "intermediate",
        "tags": ["reliability", "generation"],
        "definition_en": "Constraining a model's output to be verifiably supported by retrieved or provided source material, rather than generated purely from parametric memory.",
        "definition_ar": "تقييد إجابة النموذج بحيث تكون مستندة بشكل يمكن التحقق منه إلى مصدر مسترجَع أو مُعطى، بدلاً من توليدها كلياً من ذاكرة النموذج الداخلية.",
        "explanation_simple_ar": "جعل إجابة النموذج \"مرتبطة\" بمصدر حقيقي بدل أن تكون تخمينية.",
        "why_it_matters_ar": "التأسيس الجيد هو ما يفرّق بين إجابة موثوقة وإجابة قد تكون هلوسة.",
        "example_ar": "الإجابة مع ذكر رقم الفقرة في الوثيقة التي استُخرجت منها المعلومة.",
        "related": ["retrieval_augmented_generation", "hallucination"],
    },
    {
        "slug": "hallucination",
        "term_en": "Hallucination",
        "term_ar": "الهلوسة",
        "acronym": None,
        "aliases": ["model hallucination"],
        "category": "LLM",
        "difficulty": "beginner",
        "tags": ["reliability"],
        "definition_en": "A confident but factually incorrect or unsupported output produced by a generative model.",
        "definition_ar": "إجابة يقدّمها النموذج بثقة لكنها غير صحيحة واقعياً أو غير مدعومة بأي مصدر.",
        "explanation_simple_ar": "النموذج \"يختلق\" معلومة تبدو منطقية لكنها غير صحيحة.",
        "why_it_matters_ar": "فهم الهلوسة ضروري لتصميم أنظمة تتحقق من إجاباتها بدلاً من الثقة بها دون تدقيق.",
        "example_ar": "نموذج يذكر مرجعاً علمياً غير موجود بالفعل.",
        "related": ["grounding", "retrieval_augmented_generation"],
    },
    {
        "slug": "agent",
        "term_en": "Agent",
        "term_ar": "الوكيل الذكي",
        "acronym": None,
        "aliases": ["ai agent", "llm agent"],
        "category": "Agents",
        "difficulty": "intermediate",
        "tags": ["agents", "reasoning"],
        "definition_en": "A system that uses a language model to decide, in a loop, which actions or tools to take to accomplish a goal, rather than producing a single one-shot response.",
        "definition_ar": "نظام يستخدم نموذجاً لغوياً ليقرر، عبر حلقة تكرارية، أي إجراءات أو أدوات يستخدمها لتحقيق هدف معيّن، بدلاً من إعطاء استجابة واحدة فقط.",
        "explanation_simple_ar": "برنامج يفكّر بخطوات متعددة ويستخدم أدوات لإتمام مهمة، بدلاً من الرد مرة واحدة فقط.",
        "why_it_matters_ar": "الوكلاء هم ما يحوّل نموذج المحادثة إلى نظام يمكنه تنفيذ مهام حقيقية متعددة الخطوات.",
        "example_ar": "وكيل يبحث في الإنترنت، ثم يلخّص النتائج، ثم يرسل بريداً إلكترونياً بالنتيجة.",
        "related": ["tool_calling", "agentic_workflow"],
    },
    {
        "slug": "tool_calling",
        "term_en": "Tool Calling",
        "term_ar": "استدعاء الأدوات",
        "acronym": None,
        "aliases": ["function calling", "tool use"],
        "category": "Agents",
        "difficulty": "intermediate",
        "tags": ["agents"],
        "definition_en": "A model's ability to emit a structured request to invoke an external function or API, with arguments, so the surrounding system executes it and returns the result back to the model.",
        "definition_ar": "قدرة النموذج على إصدار طلب منظّم لاستدعاء دالة أو واجهة برمجية خارجية مع الوسائط المطلوبة، بحيث ينفّذها النظام المحيط ويعيد النتيجة إلى النموذج.",
        "explanation_simple_ar": "النموذج \"يطلب\" من البرنامج تنفيذ عملية محددة، مثل البحث أو حساب رياضي، ثم يستخدم النتيجة.",
        "why_it_matters_ar": "بدون استدعاء الأدوات، يبقى النموذج محصوراً بما يعرفه فقط، دون القدرة على التصرف في العالم الخارجي.",
        "example_ar": "النموذج يستدعي دالة get_weather(city) للحصول على حالة الطقس الحالية.",
        "related": ["agent", "agentic_workflow"],
    },
    {
        "slug": "agentic_workflow",
        "term_en": "Agentic Workflow",
        "term_ar": "سير العمل الوكيلي",
        "acronym": None,
        "aliases": ["multi-step agent workflow", "agent orchestration", "multi-step execution", "agent loop"],
        "category": "Agents",
        "difficulty": "advanced",
        "tags": ["agents", "orchestration"],
        "definition_en": "A defined sequence or graph of reasoning/tool steps an agent follows, including branching, retries and handoffs between sub-agents, to complete a multi-step task reliably.",
        "definition_ar": "تسلسل أو مخطط محدّد من خطوات التفكير واستخدام الأدوات يتبعه الوكيل، بما يشمل التفريع وإعادة المحاولة والتسليم بين وكلاء فرعيين، لإتمام مهمة متعددة الخطوات بشكل موثوق.",
        "explanation_simple_ar": "خطة منظمة لكيفية تنقّل الوكيل بين الخطوات المختلفة لإنهاء مهمة معقدة.",
        "why_it_matters_ar": "المهام الحقيقية نادراً ما تُحل بخطوة واحدة؛ سير العمل الوكيلي هو ما يجعل تنفيذها موثوقاً وقابلاً للتصحيح.",
        "example_ar": "وكيل يخطط، ثم ينفّذ، ثم يراجع نتيجته، ثم يعيد المحاولة إذا فشلت الخطوة.",
        "related": ["agent", "tool_calling"],
    },
    {
        "slug": "quantization",
        "term_en": "Quantization",
        "term_ar": "التكميم",
        "acronym": None,
        "aliases": ["model quantization"],
        "category": "Serving",
        "difficulty": "advanced",
        "tags": ["efficiency", "deployment"],
        "definition_en": "Reducing the numerical precision of a model's weights (e.g. from 16-bit to 4-bit) to shrink its memory footprint and speed up inference, at some cost to accuracy.",
        "definition_ar": "تقليل الدقة العددية لوزن النموذج (مثلاً من 16 بت إلى 4 بت) لتصغير حجمه في الذاكرة وزيادة سرعة الاستدلال، مع تكلفة محدودة في الدقة.",
        "explanation_simple_ar": "ضغط النموذج بتقليل عدد الأرقام المستخدمة لتمثيل كل وزن فيه.",
        "why_it_matters_ar": "التكميم يجعل تشغيل نماذج ضخمة ممكناً على عتاد أصغر وبتكلفة أقل.",
        "example_ar": "تشغيل نموذج بحجم 4 بت على هاتف محمول بدلاً من خادم ضخم.",
        "related": [],
    },
    {
        "slug": "latency",
        "term_en": "Latency",
        "term_ar": "زمن الاستجابة",
        "acronym": None,
        "aliases": ["response latency", "inference latency"],
        "category": "Systems",
        "difficulty": "beginner",
        "tags": ["performance"],
        "definition_en": "The time between a request being sent and its response being received; in AI systems, often broken into time-to-first-token and total generation time.",
        "definition_ar": "الوقت الفاصل بين إرسال الطلب واستلام الاستجابة؛ في أنظمة الذكاء الاصطناعي، غالباً ما يُقسَّم إلى زمن أول رمز وزمن التوليد الكامل.",
        "explanation_simple_ar": "المدة التي ينتظرها المستخدم قبل أن يبدأ يرى الرد.",
        "why_it_matters_ar": "زمن الاستجابة العالي يجعل التجربة تبدو بطيئة حتى لو كانت الإجابة النهائية صحيحة.",
        "example_ar": "مساعد صوتي يجب أن يرد في أقل من ثانية ليبدو طبيعياً في المحادثة.",
        "related": ["observability"],
    },
    {
        "slug": "observability",
        "term_en": "Observability",
        "term_ar": "قابلية الرصد",
        "acronym": None,
        "aliases": ["llm observability", "ai observability"],
        "category": "Systems",
        "difficulty": "intermediate",
        "tags": ["monitoring", "production"],
        "definition_en": "The ability to understand a running system's internal behavior — traces, prompts, token usage, latency, errors — from what it emits, rather than by guessing.",
        "definition_ar": "القدرة على فهم السلوك الداخلي لنظام قيد التشغيل — التتبع، الأوامر المرسلة، استهلاك الرموز، زمن الاستجابة، الأخطاء — من خلال ما يصدره النظام نفسه، بدل التخمين.",
        "explanation_simple_ar": "مراقبة ما يحدث داخل النظام أثناء عمله لفهم أسباب أي مشكلة.",
        "why_it_matters_ar": "بدون قابلية رصد جيدة، يصعب معرفة سبب فشل استجابة أو ارتفاع كلفة نموذج في الإنتاج.",
        "example_ar": "لوحة تعرض كل استدعاء لنموذج، وكلفته، وزمنه، وهل نجح أو فشل.",
        "related": ["latency"],
    },
    {
        "slug": "authentication",
        "term_en": "Authentication",
        "term_ar": "التحقق من الهوية",
        "acronym": None,
        "aliases": ["auth", "user authentication"],
        "category": "Systems",
        "difficulty": "beginner",
        "tags": ["security"],
        "definition_en": "Verifying that a user or system is who it claims to be, typically via credentials such as a password or token.",
        "definition_ar": "التحقق من أن المستخدم أو النظام هو من يقول أنه هو، عادةً من خلال بيانات اعتماد مثل كلمة مرور أو رمز وصول.",
        "explanation_simple_ar": "إثبات هوية الشخص قبل السماح له بالدخول.",
        "why_it_matters_ar": "هي الخطوة الأولى لحماية أي نظام قبل تقرير ما يُسمح للمستخدم بفعله.",
        "example_ar": "تسجيل الدخول باسم المستخدم وكلمة المرور.",
        "related": ["authorization"],
    },
    {
        "slug": "authorization",
        "term_en": "Authorization",
        "term_ar": "تفويض الصلاحيات",
        "acronym": None,
        "aliases": ["access control"],
        "category": "Systems",
        "difficulty": "beginner",
        "tags": ["security"],
        "definition_en": "Determining what an already-authenticated user or system is permitted to do.",
        "definition_ar": "تحديد ما يُسمح لمستخدم أو نظام تم التحقق من هويته مسبقاً بفعله.",
        "explanation_simple_ar": "بعد التأكد من هوية المستخدم، تحديد الصلاحيات المسموحة له.",
        "why_it_matters_ar": "التحقق من الهوية وحده لا يكفي؛ يجب أيضاً تحديد حدود ما يستطيع كل مستخدم فعله.",
        "example_ar": "مستخدم عادي لا يمكنه حذف حسابات مستخدمين آخرين، بخلاف المسؤول.",
        "related": ["authentication"],
    },
    {
        "slug": "websocket",
        "term_en": "WebSocket",
        "term_ar": "بروتوكول WebSocket",
        "acronym": None,
        "aliases": ["websockets", "ws"],
        "category": "Systems",
        "difficulty": "intermediate",
        "tags": ["networking", "real-time"],
        "definition_en": "A network protocol providing a persistent, full-duplex connection between client and server, used for real-time streaming such as live transcription or token-by-token generation.",
        "definition_ar": "بروتوكول شبكي يوفّر اتصالاً مستمراً وثنائي الاتجاه بين العميل والخادم، يُستخدم للبث اللحظي مثل النصوص الصوتية المباشرة أو توليد النص رمزاً برمز.",
        "explanation_simple_ar": "قناة اتصال تبقى مفتوحة بين المتصفح والخادم لتبادل البيانات لحظياً دون إعادة الاتصال كل مرة.",
        "why_it_matters_ar": "هو ما يجعل التطبيقات الصوتية والمحادثات المباشرة تبدو سريعة وسلسة.",
        "example_ar": "ظهور كلمات إجابة النموذج واحدة تلو الأخرى بدل انتظار الرد كاملاً.",
        "related": [],
    },
    {
        "slug": "voice_activity_detection",
        "term_en": "Voice Activity Detection",
        "term_ar": "كشف النشاط الصوتي",
        "acronym": "VAD",
        "aliases": ["vad"],
        "category": "Voice AI",
        "difficulty": "advanced",
        "tags": ["voice", "audio"],
        "definition_en": "Detecting, from an audio stream, the segments where a person is actually speaking versus silence or background noise.",
        "definition_ar": "اكتشاف الأجزاء التي يتحدث فيها شخص فعلياً ضمن تدفق صوتي، مقابل الصمت أو الضجيج الخلفي.",
        "explanation_simple_ar": "تمييز الأجزاء التي فيها كلام حقيقي عن الأجزاء الصامتة في الصوت.",
        "why_it_matters_ar": "هو الأساس الذي تعتمد عليه أنظمة الصوت لمعرفة متى يبدأ المستخدم بالكلام ومتى ينتهي.",
        "example_ar": "مساعد صوتي يبدأ التسجيل فقط عندما يكتشف أن المستخدم بدأ يتكلم.",
        "related": ["turn_detection", "endpointing", "barge_in"],
    },
    {
        "slug": "turn_detection",
        "term_en": "Turn Detection",
        "term_ar": "كشف نهاية الدور",
        "acronym": None,
        "aliases": [],
        "category": "Voice AI",
        "difficulty": "advanced",
        "tags": ["voice"],
        "definition_en": "Deciding when a speaker has finished their conversational turn and it is the system's turn to respond.",
        "definition_ar": "تحديد اللحظة التي ينتهي فيها المتحدث من دوره في المحادثة ويصبح دور النظام للرد.",
        "explanation_simple_ar": "معرفة متى انتهى المستخدم من الكلام ليبدأ النظام بالرد.",
        "why_it_matters_ar": "توقيت خاطئ يجعل النظام يقاطع المستخدم أو يتأخر بشكل غير طبيعي.",
        "example_ar": "توقف المستخدم عن الكلام لثانيتين فيبدأ النظام بالرد.",
        "related": ["voice_activity_detection", "endpointing", "barge_in"],
    },
    {
        "slug": "endpointing",
        "term_en": "Endpointing",
        "term_ar": "تحديد نقطة الانتهاء",
        "acronym": None,
        "aliases": ["end-of-speech detection"],
        "category": "Voice AI",
        "difficulty": "advanced",
        "tags": ["voice"],
        "definition_en": "The specific mechanism that decides the precise moment speech has ended, feeding into turn detection.",
        "definition_ar": "الآلية المحدّدة التي تقرر اللحظة الدقيقة لانتهاء الكلام، وتُغذّي عملية كشف نهاية الدور.",
        "explanation_simple_ar": "تحديد اللحظة الدقيقة التي توقف فيها الصوت.",
        "why_it_matters_ar": "دقة تحديد نقطة الانتهاء تقلل من زمن الاستجابة دون قطع كلام المستخدم.",
        "example_ar": "ضبط حساسية النظام لاعتبار صمت 300 مللي ثانية نهاية للكلام.",
        "related": ["turn_detection", "voice_activity_detection"],
    },
    {
        "slug": "barge_in",
        "term_en": "Barge-In",
        "term_ar": "المقاطعة الصوتية",
        "acronym": None,
        "aliases": ["barge in"],
        "category": "Voice AI",
        "difficulty": "advanced",
        "tags": ["voice"],
        "definition_en": "Allowing a user to interrupt the system's spoken response mid-playback, and having the system stop and listen.",
        "definition_ar": "السماح للمستخدم بمقاطعة رد النظام الصوتي في منتصف تشغيله، وجعل النظام يتوقف ويستمع.",
        "explanation_simple_ar": "قدرة المستخدم على مقاطعة النظام أثناء حديثه ليأخذ دوره في الكلام.",
        "why_it_matters_ar": "بدون هذه القدرة تصبح المحادثة الصوتية غير طبيعية، لأن الإنسان يقاطع في المحادثات العادية.",
        "example_ar": "المستخدم يقول \"توقف\" في منتصف رد المساعد الصوتي فيتوقف فوراً.",
        "related": ["turn_detection", "voice_activity_detection"],
    },
    {
        "slug": "semantic_similarity",
        "term_en": "Semantic Similarity",
        "term_ar": "التشابه الدلالي",
        "acronym": None,
        "aliases": [],
        "category": "Representation Learning",
        "difficulty": "beginner",
        "tags": ["representation"],
        "definition_en": "A measure of how close two pieces of content are in meaning, typically computed as the distance or cosine similarity between their embeddings.",
        "definition_ar": "مقياس لمدى قرب معنى محتويين من بعضهما، يُحسب عادةً كمسافة أو تشابه جيبي بين متجهيهما.",
        "explanation_simple_ar": "مدى تقارب معنى نصّين، حتى لو اختلفت كلماتهما.",
        "why_it_matters_ar": "هي الفكرة الأساسية التي يقوم عليها البحث الدلالي والتوصية.",
        "example_ar": "\"طبيب\" و\"مستشفى\" أقرب دلالياً من \"طبيب\" و\"سيارة\".",
        "related": ["embedding", "vector_search"],
    },
    {
        "slug": "clip",
        "term_en": "CLIP",
        "term_ar": "نموذج CLIP",
        "acronym": "CLIP",
        "aliases": ["contrastive language-image pretraining"],
        "category": "Vision-Language",
        "difficulty": "advanced",
        "tags": ["multimodal", "vision"],
        "definition_en": "A model trained to align images and text captions in a shared embedding space, so an image and its correct description end up close together as vectors.",
        "definition_ar": "نموذج مدرَّب لمحاذاة الصور ونصوص وصفها في فضاء متجهي مشترك، بحيث تكون الصورة ووصفها الصحيح قريبين من بعضهما كمتجهين.",
        "explanation_simple_ar": "يتعلّم النموذج أن يربط بين الصورة والجملة التي تصفها بشكل صحيح.",
        "why_it_matters_ar": "CLIP هو الأساس الذي بُنيت عليه كثير من أنظمة البحث بالصور والنماذج متعددة الوسائط.",
        "example_ar": "البحث عن صورة \"قطة بيضاء على أريكة\" باستخدام جملة نصية فقط.",
        "related": ["embedding", "vision_language_model"],
    },
    {
        "slug": "vision_language_model",
        "term_en": "Vision-Language Model",
        "term_ar": "نموذج الرؤية واللغة",
        "acronym": "VLM",
        "aliases": ["vlm", "vision language model"],
        "category": "Vision-Language",
        "difficulty": "advanced",
        "tags": ["multimodal", "vision"],
        "definition_en": "A model that jointly processes images (or video) and text, able to answer questions about an image, describe it, or reason over both modalities together.",
        "definition_ar": "نموذج يعالج الصور (أو الفيديو) والنص معاً، قادر على الإجابة عن أسئلة حول صورة، أو وصفها، أو التفكير في كليهما معاً.",
        "explanation_simple_ar": "نموذج يفهم الصور والنص في نفس الوقت، لا النص فقط.",
        "why_it_matters_ar": "يفتح الباب لتطبيقات مثل وصف الصور تلقائياً أو الإجابة عن أسئلة بصرية.",
        "example_ar": "رفع صورة فاتورة وسؤال النموذج \"كم الإجمالي؟\".",
        "related": ["clip", "embedding"],
    },
]
