"""
app/content/vocabulary_seed_terms_expansion.py

Curriculum-driven expansion of the AI Vocabulary dictionary (second pass).

Every term here was selected by inspecting the real curriculum: the
extraction candidates in `_vocab_extraction_raw.json` (lesson `concepts`
fields, courses 004/005/007/008/009/010/012/013/014) and, for the six
courses that carry no structured `concepts` field (001, 002, 003, 006, 011,
015), the real lesson titles and bodies read directly via
`load_all_courses()`. Generic words, Python/library API names ("DatasetDict",
"AutoModel", "dataset.map"), one-off implementation details and duplicate
variants of terms already in `ai_terms.json` or `vocabulary_seed_terms.py`
were rejected - see `docs` note in each course's selection in the PR/session
notes. What remains is durable, cross-course-relevant industry terminology.

Aliases only ever join genuinely equivalent surface forms of ONE concept
(acronym, full name, common misspelling/spacing). Related concepts that are
NOT the same thing (Dense Retrieval vs. Vector Search, Speech Recognition vs.
Speech-to-Speech) are kept as separate terms, linked instead through
`related`.
"""

TERMS = [
    # ── Classical ML (COURSE-001) ───────────────────────────────────────
    {
        "slug": "k_nearest_neighbors", "term_en": "k-Nearest Neighbors", "term_ar": "خوارزمية أقرب الجيران",
        "acronym": "kNN", "aliases": ["knn", "k-nn", "nearest neighbors"],
        "category": "Machine Learning", "difficulty": "beginner", "tags": ["classification", "regression"],
        "definition_en": "A model that predicts a point's label or value from the majority vote or average of its k closest points in the training data, with no explicit training phase.",
        "definition_ar": "نموذج يتنبأ بتصنيف نقطة أو قيمتها بالاعتماد على تصويت الأغلبية أو المتوسط بين أقرب k نقطة لها في بيانات التدريب، دون مرحلة تدريب صريحة.",
        "explanation_simple_ar": "بدل بناء نموذج معقد، ينظر الخوارزم إلى أقرب الأمثلة المشابهة ويقرر بناءً عليها.",
        "why_it_matters_ar": "هي أبسط نقطة انطلاق لفهم التصنيف، وتكشف مبكراً أهمية اختيار المقياس وتحجيم الميزات.",
        "example_ar": "تصنيف نوع زهرة بالاعتماد على أقرب 5 أزهار مشابهة في القياسات.",
        "related": [],
    },
    {
        "slug": "random_forest", "term_en": "Random Forest", "term_ar": "الغابة العشوائية",
        "acronym": None, "aliases": ["random forests"],
        "category": "Machine Learning", "difficulty": "intermediate", "tags": ["ensemble"],
        "definition_en": "An ensemble of decision trees, each trained on a random subset of data and features, whose predictions are averaged or voted to reduce overfitting.",
        "definition_ar": "مجموعة من أشجار القرار، كل منها مدرَّب على عينة عشوائية من البيانات والميزات، ويُجمَع تنبؤها بالتصويت أو المتوسط لتقليل فرط التخصيص.",
        "explanation_simple_ar": "بدل الاعتماد على شجرة قرار واحدة، تُبنى أشجار كثيرة مختلفة قليلاً ويُؤخذ رأي الأغلبية.",
        "why_it_matters_ar": "من أقوى النماذج الكلاسيكية أداءً وأقلها حساسية لضبط المعاملات.",
        "example_ar": "التنبؤ بتسرب العملاء من عشرات الأشجار المبنية على عينات مختلفة من بيانات العملاء.",
        "related": ["gradient_boosting"],
    },
    {
        "slug": "gradient_boosting", "term_en": "Gradient Boosting", "term_ar": "التعزيز التدرّجي",
        "acronym": None, "aliases": ["gradient boosted trees", "gbm"],
        "category": "Machine Learning", "difficulty": "intermediate", "tags": ["ensemble"],
        "definition_en": "An ensemble method that builds trees sequentially, each one correcting the errors of the trees before it by fitting to the residual gradient of the loss.",
        "definition_ar": "طريقة تجميعية تبني الأشجار تباعاً، بحيث تصحّح كل شجرة أخطاء ما قبلها عبر ملاءمة تدرّج الخطأ المتبقي.",
        "explanation_simple_ar": "كل شجرة جديدة تتعلم من أخطاء الأشجار السابقة بدلاً من البدء من الصفر.",
        "why_it_matters_ar": "من أكثر الخوارزميات فوزاً في مسابقات البيانات الجدولية وتطبيقاتها الصناعية.",
        "example_ar": "XGBoost وLightGBM من أشهر تطبيقات التعزيز التدرّجي.",
        "related": ["random_forest"],
    },
    {
        "slug": "support_vector_machine", "term_en": "Support Vector Machine", "term_ar": "آلة المتجهات الداعمة",
        "acronym": "SVM", "aliases": ["svm", "support vector machines"],
        "category": "Machine Learning", "difficulty": "intermediate", "tags": ["classification"],
        "definition_en": "A classifier that finds the hyperplane maximizing the margin between classes, optionally using a kernel to separate data that is not linearly separable.",
        "definition_ar": "مصنّف يبحث عن المستوى الفاصل الذي يعظّم الهامش بين الفئات، ويمكن أن يستخدم دالة نواة لفصل بيانات غير قابلة للفصل الخطي.",
        "explanation_simple_ar": "يرسم الحد الفاصل الأبعد الممكن بين مجموعتين من النقاط.",
        "why_it_matters_ar": "مثال قوي على كيفية تحويل مشكلة تصنيف إلى مشكلة هندسية قابلة للحل الرياضي.",
        "example_ar": "فصل رسائل البريد المزعج عن الرسائل العادية بخط فاصل بأقصى هامش أمان.",
        "related": [],
    },
    {
        "slug": "principal_component_analysis", "term_en": "Principal Component Analysis", "term_ar": "تحليل المكوّنات الرئيسية",
        "acronym": "PCA", "aliases": ["pca"],
        "category": "Machine Learning", "difficulty": "intermediate", "tags": ["dimensionality-reduction"],
        "definition_en": "A technique that projects data onto a smaller set of orthogonal directions (principal components) that capture the most variance, reducing dimensionality while preserving structure.",
        "definition_ar": "تقنية تسقط البيانات على مجموعة أصغر من الاتجاهات المتعامدة (المكوّنات الرئيسية) التي تلتقط أكبر قدر من التباين، فتقلل الأبعاد مع الحفاظ على البنية.",
        "explanation_simple_ar": "تختصر عدد الأعمدة/الميزات في البيانات مع خسارة أقل قدر ممكن من المعلومة.",
        "why_it_matters_ar": "أساسي لتصور البيانات عالية الأبعاد وتسريع نماذج أخرى.",
        "example_ar": "تصغير بيانات بها 200 عمود إلى بعدين لعرضها على رسم بياني.",
        "related": [],
    },
    {
        "slug": "k_means_clustering", "term_en": "k-Means Clustering", "term_ar": "تجميع k-Means",
        "acronym": None, "aliases": ["k-means", "kmeans"],
        "category": "Machine Learning", "difficulty": "beginner", "tags": ["clustering", "unsupervised"],
        "definition_en": "An unsupervised algorithm that partitions data into k clusters by iteratively assigning points to the nearest cluster center and recomputing centers.",
        "definition_ar": "خوارزمية غير مُشرَفة تقسّم البيانات إلى k مجموعات عبر تكرار إسناد كل نقطة لأقرب مركز مجموعة، ثم إعادة حساب المراكز.",
        "explanation_simple_ar": "تجميع نقاط متشابهة مع بعضها في k مجموعات دون معرفة مسبقة بتصنيفها.",
        "why_it_matters_ar": "أبسط وأشهر طريقة لاكتشاف بنية طبيعية في بيانات غير موسومة.",
        "example_ar": "تقسيم عملاء متجر إلى 4 شرائح شرائية دون تصنيف مسبق.",
        "related": [],
    },
    {
        "slug": "cross_validation", "term_en": "Cross-Validation", "term_ar": "التحقق المتقاطع",
        "acronym": None, "aliases": ["k-fold cross-validation", "cross validation"],
        "category": "Machine Learning", "difficulty": "beginner", "tags": ["evaluation"],
        "definition_en": "A model-evaluation method that splits data into multiple folds, training on some and validating on the rest in rotation, to get a more reliable estimate of generalization than a single split.",
        "definition_ar": "طريقة تقييم تقسّم البيانات إلى عدة أجزاء (folds) وتتدرّب على بعضها وتختبر على الباقي بالتناوب، لإعطاء تقدير أكثر موثوقية لأداء النموذج على بيانات جديدة من تقسيم واحد فقط.",
        "explanation_simple_ar": "بدل تقسيم البيانات مرة واحدة، تُقسَّم عدة مرات ويُؤخذ متوسط الأداء.",
        "why_it_matters_ar": "يكشف ما إذا كان أداء النموذج الجيد صدفة تقسيم البيانات أو أداءً حقيقياً.",
        "example_ar": "تقسيم البيانات 5 مرات (5-fold) وأخذ متوسط الدقة عبر التقسيمات الخمسة.",
        "related": [],
    },
    {
        "slug": "one_hot_encoding", "term_en": "One-Hot Encoding", "term_ar": "الترميز الأحادي الفعّال",
        "acronym": None, "aliases": ["one hot encoding"],
        "category": "Machine Learning", "difficulty": "beginner", "tags": ["feature-engineering"],
        "definition_en": "Representing a categorical variable as a binary vector with one entry set to 1 for the active category and 0 elsewhere, so a model sees no false ordering between categories.",
        "definition_ar": "تمثيل متغيّر فئوي كمتجه ثنائي تكون فيه خانة واحدة فقط تساوي 1 للفئة الحالية والباقي أصفار، بحيث لا يفترض النموذج ترتيباً وهمياً بين الفئات.",
        "explanation_simple_ar": "تحويل فئة نصية مثل \"أحمر/أزرق/أخضر\" إلى أعمدة رقمية منفصلة بدل رقم واحد قد يوحي بترتيب غير موجود.",
        "why_it_matters_ar": "ضروري لأن معظم النماذج لا تتعامل مباشرة مع نصوص فئوية.",
        "example_ar": "تحويل عمود \"المدينة\" إلى عمود منفصل لكل مدينة يحمل 0 أو 1.",
        "related": [],
    },
    {
        "slug": "tf_idf", "term_en": "TF-IDF", "term_ar": "تردد المصطلح - التردد العكسي للمستند",
        "acronym": "TF-IDF", "aliases": ["term frequency-inverse document frequency"],
        "category": "NLP", "difficulty": "intermediate", "tags": ["text", "search"],
        "definition_en": "A text-weighting scheme that scores a word higher when it appears often in a document but rarely across the whole corpus, highlighting words distinctive to that document.",
        "definition_ar": "مخطط لوزن الكلمات في النص يمنح الكلمة وزناً أعلى إذا تكررت كثيراً في مستند معيّن لكنها نادرة في بقية المستندات، فيبرز الكلمات المميّزة لذلك المستند.",
        "explanation_simple_ar": "يعطي وزناً أكبر للكلمات المهمة والمميزة، ووزناً أقل للكلمات الشائعة في كل النصوص.",
        "why_it_matters_ar": "كان الأساس التقليدي للبحث النصي قبل انتشار التمثيل المتجهي، وما يزال مفيداً كأساس مقارنة.",
        "example_ar": "كلمة \"عقد\" تحصل على وزن عالٍ في مستند قانوني ووزن منخفض عبر أخبار عامة.",
        "related": ["embedding"],
    },
    {
        "slug": "roc_auc", "term_en": "ROC-AUC", "term_ar": "المساحة تحت منحنى ROC",
        "acronym": "AUC", "aliases": ["roc curve", "auc", "area under the curve"],
        "category": "Evaluation", "difficulty": "intermediate", "tags": ["classification", "metrics"],
        "definition_en": "A classification metric that plots true-positive rate against false-positive rate across thresholds and summarizes it as the area under that curve; 1.0 is perfect, 0.5 is random.",
        "definition_ar": "مقياس تصنيف يرسم معدل الإيجابيات الصحيحة مقابل معدل الإيجابيات الخاطئة عبر عتبات مختلفة، ويلخّصه كمساحة تحت هذا المنحنى؛ 1.0 يعني أداءً مثالياً و0.5 يعني أداءً عشوائياً.",
        "explanation_simple_ar": "رقم واحد يلخّص جودة نموذج التصنيف بغض النظر عن العتبة المختارة.",
        "why_it_matters_ar": "مفيد بشكل خاص عندما تكون الفئات غير متوازنة ولا تكفي الدقة (accuracy) وحدها.",
        "example_ar": "نموذج كشف احتيال بمساحة AUC تساوي 0.92 يعتبر جيداً جداً.",
        "related": ["confusion_matrix"],
    },
    {
        "slug": "confusion_matrix", "term_en": "Confusion Matrix", "term_ar": "مصفوفة الالتباس",
        "acronym": None, "aliases": ["confusion matrices"],
        "category": "Evaluation", "difficulty": "beginner", "tags": ["classification", "metrics"],
        "definition_en": "A table breaking down a classifier's predictions into true/false positives and negatives, the basis for precision, recall and F1.",
        "definition_ar": "جدول يفصّل تنبؤات المصنّف إلى إيجابيات وسلبيات صحيحة وخاطئة، وهو الأساس الذي تُحسب منه الدقة والاستدعاء ومقياس F1.",
        "explanation_simple_ar": "جدول يوضح أين أصاب النموذج وأين أخطأ بالتفصيل، لا رقماً واحداً فقط.",
        "why_it_matters_ar": "يكشف أنواع الأخطاء التي تهم فعلياً (مثل تفويت حالة مرضية) لا مجرد نسبة الدقة الإجمالية.",
        "example_ar": "معرفة أن النموذج يخطئ في تصنيف الرسائل المهمة كمزعجة أكثر من العكس.",
        "related": ["roc_auc", "precision", "recall", "f1_score"],
    },
    {
        "slug": "data_leakage", "term_en": "Data Leakage", "term_ar": "تسرّب البيانات",
        "acronym": None, "aliases": ["leakage"],
        "category": "Machine Learning", "difficulty": "intermediate", "tags": ["evaluation", "pitfalls"],
        "definition_en": "When information that would not be available at prediction time (often from the future, or from the test set) leaks into training, producing evaluation results that look better than the model will actually perform.",
        "definition_ar": "عندما تتسرّب إلى التدريب معلومات لن تكون متاحة وقت التنبؤ فعلياً (غالباً من المستقبل، أو من بيانات الاختبار)، فتُنتج نتائج تقييم أفضل مما سيحققه النموذج فعلياً في الواقع.",
        "explanation_simple_ar": "غش غير مقصود يجعل النموذج يبدو ممتازاً في الاختبار لكنه يفشل في الواقع.",
        "why_it_matters_ar": "من أكثر الأخطاء شيوعاً وخداعاً في مشاريع تعلّم الآلة الحقيقية.",
        "example_ar": "تحجيم البيانات (scaling) قبل تقسيمها إلى تدريب واختبار بدل بعده.",
        "related": [],
    },
    {
        "slug": "crisp_dm", "term_en": "CRISP-DM", "term_ar": "منهجية CRISP-DM",
        "acronym": "CRISP-DM", "aliases": ["cross-industry standard process for data mining"],
        "category": "Data", "difficulty": "beginner", "tags": ["methodology"],
        "definition_en": "A widely used data-analysis methodology with six phases - business understanding, data understanding, data preparation, modeling, evaluation, deployment - followed iteratively rather than linearly.",
        "definition_ar": "منهجية تحليل بيانات منتشرة بست مراحل: فهم المشكلة، فهم البيانات، تجهيز البيانات، بناء النموذج، التقييم، والنشر - تُتّبع بشكل تكراري لا خطي.",
        "explanation_simple_ar": "خارطة طريق منظمة لأي مشروع تحليل بيانات، من فهم السؤال إلى تسليم الحل.",
        "why_it_matters_ar": "تمنع الوقوع في بناء نموذج دقيق لسؤال خاطئ.",
        "example_ar": "العودة من مرحلة النمذجة إلى فهم البيانات بعد اكتشاف مشكلة في الجودة.",
        "related": [],
    },
    {
        "slug": "rmse", "term_en": "RMSE", "term_ar": "جذر متوسط مربع الخطأ",
        "acronym": "RMSE", "aliases": ["root mean squared error"],
        "category": "Evaluation", "difficulty": "beginner", "tags": ["regression", "metrics"],
        "definition_en": "A regression error metric: the square root of the average squared difference between predicted and actual values, in the same units as the target.",
        "definition_ar": "مقياس خطأ للانحدار: الجذر التربيعي لمتوسط مربع الفرق بين القيم المتنبَّأ بها والفعلية، بنفس وحدة الهدف.",
        "explanation_simple_ar": "متوسط مقدار خطأ النموذج، مع تكبير تأثير الأخطاء الكبيرة أكثر من الصغيرة.",
        "why_it_matters_ar": "أشيع مقياس لتقييم نماذج الانحدار لأنه سهل التفسير بنفس وحدة القياس.",
        "example_ar": "RMSE يساوي 5000 جنيه في نموذج تنبؤ بأسعار الشقق.",
        "related": ["r_squared"],
    },
    {
        "slug": "r_squared", "term_en": "R² (Coefficient of Determination)", "term_ar": "معامل التحديد R²",
        "acronym": "R²", "aliases": ["r2", "coefficient of determination", "r-squared"],
        "category": "Evaluation", "difficulty": "beginner", "tags": ["regression", "metrics"],
        "definition_en": "The proportion of variance in the target variable that a regression model explains, ranging from 0 (no better than predicting the mean) to 1 (perfect fit).",
        "definition_ar": "نسبة التباين في المتغير الهدف التي يفسّرها نموذج الانحدار، وتتراوح من 0 (لا أفضل من التنبؤ بالمتوسط) إلى 1 (ملاءمة مثالية).",
        "explanation_simple_ar": "رقم من 0 إلى 1 يقول \"كم فسّر النموذج من التغيّر في البيانات\".",
        "why_it_matters_ar": "طريقة سريعة لمعرفة إن كان النموذج يضيف قيمة حقيقية أم لا.",
        "example_ar": "R² يساوي 0.85 يعني أن النموذج يفسّر 85% من التباين في السعر.",
        "related": ["rmse"],
    },
    {
        "slug": "iqr", "term_en": "Interquartile Range", "term_ar": "المدى الربيعي",
        "acronym": "IQR", "aliases": ["iqr"],
        "category": "Data", "difficulty": "beginner", "tags": ["statistics"],
        "definition_en": "The range between the 25th and 75th percentiles of a distribution, used to describe spread and to detect outliers robustly.",
        "definition_ar": "المدى بين الربيع الأول (25%) والربيع الثالث (75%) لتوزيع البيانات، يُستخدم لوصف التشتت وكشف القيم الشاذة بطريقة مقاومة للتطرف.",
        "explanation_simple_ar": "نطاق الـ 50% الأوسط من البيانات، بعيداً عن القيم المتطرفة في الطرفين.",
        "why_it_matters_ar": "أكثر مقاومة للقيم الشاذة من المدى الكامل أو الانحراف المعياري.",
        "example_ar": "أي قيمة أبعد من 1.5 ضعف المدى الربيعي عن الربيعين تُعتبر شاذة.",
        "related": [],
    },

    # ── Deep Learning (COURSE-002/003) ──────────────────────────────────
    {
        "slug": "backpropagation", "term_en": "Backpropagation", "term_ar": "الانتشار العكسي للخطأ",
        "acronym": None, "aliases": ["backprop"],
        "category": "Deep Learning", "difficulty": "intermediate", "tags": ["training"],
        "definition_en": "The algorithm that computes how much each weight in a neural network contributed to the error, by propagating the loss gradient backward through the computation graph via the chain rule.",
        "definition_ar": "الخوارزمية التي تحسب مدى مساهمة كل وزن في الشبكة العصبية في الخطأ، عبر نشر تدرّج الخطأ عكسياً خلال مخطط الحساب باستخدام قاعدة السلسلة.",
        "explanation_simple_ar": "طريقة الشبكة لمعرفة \"من المسؤول عن الخطأ\" بين كل الأوزان، حتى تعرف كيف تعدّلها.",
        "why_it_matters_ar": "هي الآلية التي يتعلم بها كل نموذج تعلّم عميق تقريباً.",
        "example_ar": "بعد كل تنبؤ خاطئ، تُحسب مساهمة كل طبقة في الخطأ وتُعدَّل أوزانها.",
        "related": ["gradient_descent"],
    },
    {
        "slug": "gradient_descent", "term_en": "Gradient Descent", "term_ar": "الانحدار التدرّجي",
        "acronym": None, "aliases": ["stochastic gradient descent", "sgd"],
        "category": "Deep Learning", "difficulty": "beginner", "tags": ["training", "optimization"],
        "definition_en": "An optimization algorithm that repeatedly adjusts a model's parameters in the direction that most reduces the loss, using the loss's gradient.",
        "definition_ar": "خوارزمية تحسين تعدّل معاملات النموذج تكراراً في الاتجاه الذي يقلّل الخطأ أكثر ما يمكن، بالاعتماد على تدرّج دالة الخطأ.",
        "explanation_simple_ar": "خطوات صغيرة متكررة تنزل بها نحو أقل قيمة ممكنة للخطأ، كمن ينزل جبلاً في الاتجاه الأكثر انحداراً.",
        "why_it_matters_ar": "الآلية الأساسية التي تُدرَّب بها كل الشبكات العصبية تقريباً.",
        "example_ar": "تعديل أوزان الشبكة قليلاً بعد كل دفعة بيانات باتجاه تقليل الخطأ.",
        "related": ["backpropagation"],
    },
    {
        "slug": "batch_normalization", "term_en": "Batch Normalization", "term_ar": "التسوية الدفعية",
        "acronym": "BatchNorm", "aliases": ["batchnorm"],
        "category": "Deep Learning", "difficulty": "intermediate", "tags": ["training"],
        "definition_en": "A layer that normalizes its inputs' mean and variance per mini-batch during training, stabilizing and speeding up training of deep networks.",
        "definition_ar": "طبقة تُسوّي متوسط وتباين مدخلاتها لكل دفعة صغيرة أثناء التدريب، مما يثبّت ويسرّع تدريب الشبكات العميقة.",
        "explanation_simple_ar": "تحافظ على أن تبقى القيم داخل الشبكة ضمن نطاق مستقر أثناء التدريب.",
        "why_it_matters_ar": "سهّلت تدريب شبكات أعمق بكثير مما كان ممكناً من قبل.",
        "example_ar": "إضافة طبقة BatchNorm بعد كل طبقة التفاف في شبكة تصنيف صور.",
        "related": ["dropout"],
    },
    {
        "slug": "dropout", "term_en": "Dropout", "term_ar": "الإسقاط العشوائي",
        "acronym": None, "aliases": [],
        "category": "Deep Learning", "difficulty": "beginner", "tags": ["regularization"],
        "definition_en": "A regularization technique that randomly disables a fraction of neurons during each training step, preventing the network from over-relying on any single path.",
        "definition_ar": "تقنية تنظيم تُعطّل عشوائياً جزءاً من الخلايا العصبية في كل خطوة تدريب، فتمنع الشبكة من الاعتماد المفرط على مسار واحد.",
        "explanation_simple_ar": "إجبار الشبكة على عدم الاعتماد على أي خلية واحدة بعينها، فتتعلم أنماطاً أكثر عمومية.",
        "why_it_matters_ar": "من أبسط وأنجح طرق تقليل فرط التخصيص في الشبكات العصبية.",
        "example_ar": "إسقاط 20% من الخلايا عشوائياً في كل خطوة تدريب.",
        "related": ["batch_normalization", "overfitting"],
    },
    {
        "slug": "residual_connection", "term_en": "Residual Connection", "term_ar": "الوصلة المتبقية",
        "acronym": None, "aliases": ["skip connection", "residual connections"],
        "category": "Deep Learning", "difficulty": "intermediate", "tags": ["architecture"],
        "definition_en": "A shortcut that adds a layer's input directly to its output, letting gradients flow through very deep networks without vanishing.",
        "definition_ar": "مسار مختصر يضيف مدخل الطبقة مباشرة إلى مخرجها، مما يسمح للتدرّج بالمرور عبر شبكات عميقة جداً دون أن يتلاشى.",
        "explanation_simple_ar": "طريق مختصر يتجاوز طبقة أو أكثر، فيسهّل على المعلومة والتدرّج المرور في شبكة عميقة.",
        "why_it_matters_ar": "هي ما جعل تدريب شبكات بمئات الطبقات (مثل ResNet) ممكناً.",
        "example_ar": "شبكة ResNet تستخدم وصلات متبقية بين كل بضع طبقات.",
        "related": [],
    },
    {
        "slug": "transfer_learning", "term_en": "Transfer Learning", "term_ar": "التعلّم بالنقل",
        "acronym": None, "aliases": ["fine-tuning"],
        "category": "Deep Learning", "difficulty": "beginner", "tags": ["adaptation"],
        "definition_en": "Reusing a model pretrained on one large task or dataset as the starting point for a new, often smaller, task instead of training from scratch.",
        "definition_ar": "إعادة استخدام نموذج تم تدريبه مسبقاً على مهمة أو بيانات كبيرة كنقطة انطلاق لمهمة جديدة، غالباً أصغر، بدلاً من التدريب من الصفر.",
        "explanation_simple_ar": "الاستفادة مما تعلّمه نموذج آخر بدل البدء من لا شيء.",
        "why_it_matters_ar": "يوفر وقتاً وبيانات هائلة، وهو السبب في نجاح كثير من التطبيقات العملية.",
        "example_ar": "أخذ نموذج مدرَّب على ملايين الصور وتكييفه للتعرف على أنواع نباتات محددة.",
        "related": [],
    },
    {
        "slug": "vision_transformer", "term_en": "Vision Transformer", "term_ar": "محوّل الرؤية",
        "acronym": "ViT", "aliases": ["vit"],
        "category": "Vision-Language", "difficulty": "advanced", "tags": ["architecture", "vision"],
        "definition_en": "A transformer architecture applied to images by splitting them into patches treated as a sequence of tokens, rather than using convolutions.",
        "definition_ar": "بنية محوّل (Transformer) تُطبَّق على الصور بتقسيمها إلى قطع صغيرة تُعامَل كسلسلة من الرموز، بدلاً من استخدام الالتفافات.",
        "explanation_simple_ar": "تعامل الصورة كأنها جملة من \"كلمات بصرية\" بدل مسحها بمرشحات كما في الشبكات الالتفافية.",
        "why_it_matters_ar": "قرّب معمارية معالجة الصور من معمارية معالجة اللغة، وفتح الباب أمام النماذج متعددة الوسائط.",
        "example_ar": "استخدام ViT كعمود فقري بصري في نموذج رؤية-لغة.",
        "related": ["clip"],
    },
    {
        "slug": "lstm", "term_en": "LSTM", "term_ar": "الذاكرة طويلة-قصيرة المدى",
        "acronym": "LSTM", "aliases": ["long short-term memory", "gru", "gated recurrent unit"],
        "category": "Deep Learning", "difficulty": "intermediate", "tags": ["architecture", "sequence"],
        "definition_en": "A recurrent neural network variant with gated memory cells that control what to keep, forget and output, letting it learn long-range dependencies in sequences.",
        "definition_ar": "نوع من الشبكات العصبية التكرارية بخلايا ذاكرة مضبوطة ببوابات تتحكم بما يُحفظ ويُنسى ويُخرَج، مما يتيح تعلّم اعتماديات بعيدة المدى في التسلسلات.",
        "explanation_simple_ar": "شبكة تتذكر معلومات مهمة من بداية جملة طويلة حتى نهايتها.",
        "why_it_matters_ar": "كانت المعيار لمعالجة النصوص والتسلسلات الزمنية قبل انتشار المحوّلات (Transformers).",
        "example_ar": "التنبؤ بالكلمة التالية في جملة طويلة بالاعتماد على سياق بعيد.",
        "related": ["transformer"],
    },
    {
        "slug": "diffusion_model", "term_en": "Diffusion Model", "term_ar": "نموذج الانتشار",
        "acronym": None, "aliases": ["diffusion models", "diffusion"],
        "category": "Deep Learning", "difficulty": "advanced", "tags": ["generative"],
        "definition_en": "A generative model that learns to reverse a gradual noising process, generating data by iteratively denoising from pure noise.",
        "definition_ar": "نموذج توليدي يتعلم عكس عملية إضافة ضوضاء تدريجية، فيولّد البيانات بإزالة الضوضاء تكرارياً بدءاً من ضوضاء عشوائية خالصة.",
        "explanation_simple_ar": "يبدأ من صورة مشوّشة تماماً وينظّفها خطوة بخطوة حتى تصبح صورة واضحة.",
        "why_it_matters_ar": "الأساس الذي تقوم عليه أغلب نماذج توليد الصور الحديثة.",
        "example_ar": "توليد صورة من وصف نصي عبر إزالة الضوضاء تدريجياً بدءاً من عشوائية كاملة.",
        # GAN and VAE both already point at Diffusion Model as the generative
        # approach that has largely superseded them — the reverse link was
        # missing, so a learner arriving directly at Diffusion Model never
        # saw the two classic alternatives it's usually compared against.
        "related": ["gan", "variational_autoencoder"],
    },
    {
        "slug": "variational_autoencoder", "term_en": "Variational Autoencoder", "term_ar": "المشفّر التلقائي التبايني",
        "acronym": "VAE", "aliases": ["vae"],
        "category": "Deep Learning", "difficulty": "advanced", "tags": ["generative"],
        "definition_en": "A generative model that learns to compress data into a probabilistic latent space and reconstruct it, enabling sampling of new, similar data.",
        "definition_ar": "نموذج توليدي يتعلم ضغط البيانات إلى فضاء كامن احتمالي وإعادة بنائها منه، مما يتيح توليد أمثلة جديدة مشابهة.",
        "explanation_simple_ar": "يضغط البيانات إلى تمثيل مبسّط عشوائي قليلاً، ثم يستخدمه لتوليد أمثلة جديدة شبيهة.",
        "why_it_matters_ar": "أحد الأسس المبكرة للنماذج التوليدية الحديثة قبل نماذج الانتشار.",
        "example_ar": "توليد وجوه جديدة غير موجودة بأخذ عيّنة من الفضاء الكامن المتعلَّم.",
        "related": ["diffusion_model"],
    },
    {
        "slug": "data_augmentation", "term_en": "Data Augmentation", "term_ar": "توسيع البيانات",
        "acronym": None, "aliases": ["augmentation"],
        "category": "Deep Learning", "difficulty": "beginner", "tags": ["training", "data"],
        "definition_en": "Artificially expanding a training set by applying label-preserving transformations (crops, rotations, noise, paraphrasing) to existing examples.",
        "definition_ar": "توسيع مجموعة التدريب اصطناعياً بتطبيق تحويلات لا تغيّر التصنيف الحقيقي (قص، تدوير، إضافة ضوضاء، إعادة صياغة) على أمثلة موجودة.",
        "explanation_simple_ar": "إنشاء نسخ معدَّلة قليلاً من البيانات الموجودة لزيادة تنوع التدريب.",
        "why_it_matters_ar": "يقلل فرط التخصيص خصوصاً عندما تكون البيانات الأصلية محدودة.",
        "example_ar": "تدوير وقص صور القطط عشوائياً لتوليد أمثلة تدريب إضافية.",
        "related": ["dropout"],
    },
    {
        "slug": "gan", "term_en": "Generative Adversarial Network", "term_ar": "الشبكة التوليدية التنافسية",
        "acronym": "GAN", "aliases": ["gans", "generative adversarial networks"],
        "category": "Deep Learning", "difficulty": "advanced", "tags": ["generative"],
        "definition_en": "A generative architecture where a generator network creates fake samples and a discriminator network learns to tell them from real ones, each improving through the competition.",
        "definition_ar": "بنية توليدية تتكون من شبكة مولّدة تنتج عينات مزيّفة وشبكة مميّزة تتعلم التفريق بينها وبين العينات الحقيقية، وتتحسن كلتاهما عبر هذه المنافسة.",
        "explanation_simple_ar": "شبكتان تتنافسان: واحدة تحاول التزييف والأخرى تحاول كشف التزييف، فتتحسنان معاً.",
        "why_it_matters_ar": "كانت الأساس الأول لتوليد صور واقعية للغاية قبل انتشار نماذج الانتشار.",
        "example_ar": "توليد وجوه بشرية غير حقيقية تبدو واقعية تماماً.",
        "related": ["diffusion_model"],
    },
    {
        "slug": "label_smoothing", "term_en": "Label Smoothing", "term_ar": "تنعيم التصنيفات",
        "acronym": None, "aliases": [],
        "category": "Deep Learning", "difficulty": "advanced", "tags": ["training", "regularization"],
        "definition_en": "A regularization trick that replaces hard 0/1 training labels with slightly softened values, discouraging the model from becoming overconfident.",
        "definition_ar": "أسلوب تنظيم يستبدل تصنيفات التدريب الحادة (0 أو 1) بقيم مخفَّفة قليلاً، فيمنع النموذج من أن يصبح مفرط الثقة في تنبؤاته.",
        "explanation_simple_ar": "بدل أن يقول النموذج \"متأكد 100%\"، يُشجَّع على قول \"متأكد 90%\" لتفادي الثقة الزائدة الخاطئة.",
        "why_it_matters_ar": "يحسّن معايرة النموذج ويقلل فرط التخصيص في مهام التصنيف.",
        "example_ar": "استبدال التصنيف [0,1] بـ [0.05, 0.95] أثناء التدريب.",
        "related": ["calibration"],
    },
    {
        "slug": "mel_spectrogram", "term_en": "Mel Spectrogram", "term_ar": "الطيف الترددي بمقياس ميل",
        "acronym": None, "aliases": ["mel spectrograms"],
        "category": "Voice AI", "difficulty": "intermediate", "tags": ["audio"],
        "definition_en": "A time-frequency representation of audio that maps frequencies onto the mel scale (matching human pitch perception), the standard input format for most speech and audio models.",
        "definition_ar": "تمثيل زمني-ترددي للصوت يُسقط الترددات على مقياس ميل (المطابق لإدراك الأذن البشرية للنغمة)، وهو صيغة الإدخال المعيارية لمعظم نماذج الصوت والكلام.",
        "explanation_simple_ar": "تحويل الصوت إلى صورة تُظهر الترددات عبر الزمن، بمقياس قريب من طريقة سماع الأذن البشرية.",
        "why_it_matters_ar": "هو الشكل الذي \"تراه\" معظم نماذج التعرف على الكلام وتوليده بدل الموجة الصوتية الخام.",
        "example_ar": "تحويل تسجيل صوتي إلى طيف ميل قبل تمريره لنموذج تعرّف على الكلام.",
        "related": ["voice_activity_detection"],
    },
    {
        "slug": "activation_checkpointing", "term_en": "Activation Checkpointing", "term_ar": "حفظ نقاط التنشيط",
        "acronym": None, "aliases": ["gradient checkpointing"],
        "category": "Systems", "difficulty": "advanced", "tags": ["training", "memory"],
        "definition_en": "A memory-saving technique that discards intermediate activations during the forward pass and recomputes them during backpropagation, trading extra compute for less GPU memory.",
        "definition_ar": "تقنية لتوفير الذاكرة تتخلص من نتائج التنشيط الوسيطة أثناء المرور الأمامي وتعيد حسابها أثناء الانتشار العكسي، فتضحّي بحساب إضافي مقابل ذاكرة GPU أقل.",
        "explanation_simple_ar": "بدل تخزين كل النتائج الوسيطة، يُعاد حسابها عند الحاجة لتوفير الذاكرة.",
        "why_it_matters_ar": "يتيح تدريب نماذج أكبر مما تسمح به ذاكرة العتاد المتاحة.",
        "example_ar": "تدريب نموذج كبير على GPU واحد بدل الحاجة لعدة وحدات.",
        "related": ["quantization"],
    },

    # ── NLP & Transformers (COURSE-004) ─────────────────────────────────
    {
        "slug": "seq2seq", "term_en": "Sequence-to-Sequence", "term_ar": "من تسلسل إلى تسلسل",
        "acronym": "Seq2Seq", "aliases": ["seq2seq", "encoder-decoder sequence model"],
        "category": "NLP", "difficulty": "intermediate", "tags": ["architecture"],
        "definition_en": "A model architecture that maps an input sequence to an output sequence of possibly different length, typically via an encoder that reads the input and a decoder that generates the output.",
        "definition_ar": "بنية نموذج تحوّل تسلسلاً مدخلاً إلى تسلسل مخرَج قد يختلف طوله، عادة عبر مشفّر يقرأ المدخل ومفكِّك يولّد المخرَج.",
        "explanation_simple_ar": "تحويل جملة إلى جملة أخرى، مثل الترجمة أو التلخيص.",
        "why_it_matters_ar": "الأساس الذي بُنيت عليه الترجمة الآلية الحديثة والمحوّلات لاحقاً.",
        "example_ar": "ترجمة جملة من الإنجليزية إلى العربية.",
        "related": ["encoder_decoder_architecture"],
    },
    {
        "slug": "encoder_decoder_architecture", "term_en": "Encoder-Decoder Architecture", "term_ar": "بنية المشفّر-المفكّك",
        "acronym": None, "aliases": ["encoder-decoder"],
        "category": "NLP", "difficulty": "intermediate", "tags": ["architecture"],
        "definition_en": "A two-part model design where an encoder builds a representation of the input and a decoder generates output from that representation, used in translation, summarization and speech.",
        "definition_ar": "تصميم نموذج من جزأين: مشفّر يبني تمثيلاً للمدخل، ومفكِّك يولّد المخرَج من ذلك التمثيل، ويُستخدم في الترجمة والتلخيص والكلام.",
        "explanation_simple_ar": "جزء يفهم المدخل وجزء آخر يبني منه المخرج.",
        "why_it_matters_ar": "نمط معماري متكرر عبر النصوص والصوت والصورة.",
        "example_ar": "نموذج ترجمة يشفّر الجملة الإنجليزية ثم يفكّكها إلى العربية.",
        "related": ["seq2seq", "transformer"],
    },
    {
        "slug": "beam_search", "term_en": "Beam Search", "term_ar": "البحث الشعاعي",
        "acronym": None, "aliases": [],
        "category": "NLP", "difficulty": "intermediate", "tags": ["decoding"],
        "definition_en": "A decoding strategy that keeps the top-k most probable partial sequences at each generation step instead of only the single best, improving output quality over greedy decoding.",
        "definition_ar": "استراتيجية توليد تحتفظ بأفضل k تسلسل جزئي احتمالاً في كل خطوة توليد بدل الاحتفاظ بالأفضل فقط، مما يحسّن جودة المخرج مقارنة بالفك الجشع.",
        "explanation_simple_ar": "بدل اختيار الكلمة الأفضل فقط في كل خطوة، تُجرَّب عدة مسارات محتملة ويُختار أفضلها في النهاية.",
        "why_it_matters_ar": "يوازن بين جودة المخرج وتكلفة الحساب في مهام التوليد.",
        "example_ar": "استخدام beam بعرض 5 في الترجمة الآلية لتحسين جودة الجملة الناتجة.",
        "related": ["greedy_decoding"],
    },
    {
        "slug": "greedy_decoding", "term_en": "Greedy Decoding", "term_ar": "الفك الجشع",
        "acronym": None, "aliases": ["greedy search"],
        "category": "NLP", "difficulty": "beginner", "tags": ["decoding"],
        "definition_en": "A decoding strategy that always picks the single most probable next token, fast but prone to locally optimal, sometimes repetitive output.",
        "definition_ar": "استراتيجية توليد تختار دائماً الرمز التالي الأكثر احتمالاً فقط، وهي سريعة لكنها قد تقع في حلول محلية وتكرار غير مرغوب.",
        "explanation_simple_ar": "اختيار الكلمة الأفضل فوراً في كل خطوة دون النظر للمستقبل.",
        "why_it_matters_ar": "أبسط طريقة توليد وأساس المقارنة مع طرق أكثر تعقيداً كالبحث الشعاعي.",
        "example_ar": "توليد نص متكرر لأن النموذج يختار دائماً الكلمة الأكثر احتمالاً محلياً.",
        "related": ["beam_search"],
    },
    {
        "slug": "perplexity", "term_en": "Perplexity", "term_ar": "الحيرة",
        "acronym": None, "aliases": [],
        "category": "NLP", "difficulty": "intermediate", "tags": ["evaluation", "language-modeling"],
        "definition_en": "A language-model evaluation metric measuring how surprised the model is by held-out text; lower perplexity means the model predicts the actual next tokens more confidently.",
        "definition_ar": "مقياس لتقييم نماذج اللغة يقيس مدى \"مفاجأة\" النموذج بنص لم يرَه من قبل؛ كلما قلّت الحيرة كان النموذج أكثر ثقة في التنبؤ بالرموز الفعلية التالية.",
        "explanation_simple_ar": "كلما كان الرقم أقل، كان النموذج أفضل في التنبؤ بالكلمة التالية في نص جديد.",
        "why_it_matters_ar": "من أقدم وأشيع مقاييس جودة نماذج اللغة قبل ظهور مقاييس أكثر تطبيقية.",
        "example_ar": "نموذج بحيرة منخفضة على نص عربي فصيح يعني تنبؤاً جيداً بالكلمة التالية.",
        "related": [],
    },
    {
        "slug": "causal_language_model", "term_en": "Causal Language Model", "term_ar": "نموذج اللغة السببي",
        "acronym": "Causal LM", "aliases": ["causal lm", "autoregressive language model"],
        "category": "NLP", "difficulty": "intermediate", "tags": ["language-modeling"],
        "definition_en": "A language model trained to predict the next token from only the tokens before it (never looking ahead), the architecture behind GPT-style generative models.",
        "definition_ar": "نموذج لغة يُدرَّب على التنبؤ بالرمز التالي بالاعتماد فقط على الرموز التي قبله (دون النظر إلى ما بعده)، وهي البنية التي تقوم عليها النماذج التوليدية من طراز GPT.",
        "explanation_simple_ar": "يكتب كلمة كلمة، ولا يرى أبداً ما سيأتي بعد الكلمة التي يكتبها الآن.",
        "why_it_matters_ar": "هي الآلية الأساسية وراء كل روبوتات المحادثة التوليدية الحديثة.",
        "example_ar": "GPT يولّد كل كلمة بالاعتماد فقط على ما كُتب قبلها.",
        "related": ["large_language_model"],
    },
    {
        "slug": "named_entity_recognition", "term_en": "Named Entity Recognition", "term_ar": "التعرّف على الكيانات المسمّاة",
        "acronym": "NER", "aliases": ["ner"],
        "category": "NLP", "difficulty": "intermediate", "tags": ["information-extraction"],
        "definition_en": "The task of locating and classifying spans of text into predefined categories such as person, organization, location or date.",
        "definition_ar": "مهمة تحديد مقاطع النص وتصنيفها إلى فئات محددة مسبقاً مثل شخص أو منظمة أو مكان أو تاريخ.",
        "explanation_simple_ar": "استخراج الأسماء والأماكن والتواريخ وغيرها تلقائياً من نص.",
        "why_it_matters_ar": "أساسي لاستخراج المعلومات المنظمة من نصوص حرة.",
        "example_ar": "استخراج \"القاهرة\" كمكان و\"2024\" كتاريخ من خبر صحفي.",
        "related": [],
    },
    {
        "slug": "knowledge_distillation", "term_en": "Knowledge Distillation", "term_ar": "تقطير المعرفة",
        "acronym": None, "aliases": ["teacher-student distillation", "model distillation"],
        "category": "Deep Learning", "difficulty": "advanced", "tags": ["efficiency"],
        "definition_en": "Training a smaller \"student\" model to mimic the outputs of a larger \"teacher\" model, transferring much of the teacher's performance at a fraction of the size and cost.",
        "definition_ar": "تدريب نموذج \"تلميذ\" أصغر ليحاكي مخرجات نموذج \"معلّم\" أكبر، فينقل جزءاً كبيراً من أداء المعلّم بحجم وتكلفة أقل بكثير.",
        "explanation_simple_ar": "نموذج صغير يتعلم من نموذج كبير كيف يقلّده بدل التعلم من الصفر.",
        "why_it_matters_ar": "طريقة رئيسية لتشغيل نماذج قوية على أجهزة أصغر وبتكلفة أقل.",
        "example_ar": "نموذج صغير مقطَّر من نموذج ضخم يحافظ على معظم دقته بحجم أصغر بكثير.",
        "related": ["quantization"],
    },
    {
        "slug": "domain_adaptation", "term_en": "Domain Adaptation", "term_ar": "التكيّف مع المجال",
        "acronym": None, "aliases": [],
        "category": "Machine Learning", "difficulty": "advanced", "tags": ["generalization"],
        "definition_en": "Adapting a model trained on data from one domain (e.g. news text) to perform well on a different but related domain (e.g. medical text) with limited target-domain data.",
        "definition_ar": "تكييف نموذج مدرَّب على بيانات من مجال معيّن (مثل الأخبار) ليعمل جيداً على مجال مختلف لكنه ذو صلة (مثل النصوص الطبية) ببيانات محدودة من المجال الجديد.",
        "explanation_simple_ar": "نقل نموذج تعلّم في مجال إلى مجال آخر قريب دون إعادة تدريبه بالكامل.",
        "why_it_matters_ar": "أداء النموذج غالباً ينخفض خارج المجال الذي تدرّب عليه؛ هذا هو الحل العملي.",
        "example_ar": "تكييف نموذج تحليل مشاعر مدرَّب على تغريدات ليعمل على مراجعات المنتجات.",
        "related": ["transfer_learning"],
    },
    {
        "slug": "byte_pair_encoding", "term_en": "Byte Pair Encoding", "term_ar": "ترميز أزواج البايت",
        "acronym": "BPE", "aliases": ["bpe"],
        "category": "NLP", "difficulty": "advanced", "tags": ["tokenization"],
        "definition_en": "A subword tokenization algorithm that iteratively merges the most frequent adjacent character/token pairs, balancing vocabulary size against sequence length.",
        "definition_ar": "خوارزمية ترميز إلى وحدات فرعية تدمج تكرارياً أكثر أزواج الأحرف/الرموز المتجاورة تكراراً، فتوازن بين حجم المفردات وطول التسلسل.",
        "explanation_simple_ar": "طريقة لتقسيم الكلمات إلى أجزاء أصغر متكررة بدل التعامل مع كل كلمة ككل واحد.",
        "why_it_matters_ar": "الأساس الذي تعمل به مُجزِّئات (tokenizers) أغلب نماذج اللغة الحديثة.",
        "example_ar": "تقسيم كلمة نادرة إلى مقاطع فرعية معروفة بدل اعتبارها كلمة \"مجهولة\".",
        "related": [],
    },
    {
        "slug": "positional_encoding", "term_en": "Positional Encoding", "term_ar": "الترميز الموضعي",
        "acronym": None, "aliases": ["positional embeddings"],
        "category": "NLP", "difficulty": "advanced", "tags": ["architecture", "transformer"],
        "definition_en": "A signal added to token embeddings in a transformer so the model can tell tokens' positions in the sequence, since attention alone has no inherent notion of order.",
        "definition_ar": "إشارة تُضاف إلى تمثيلات الرموز في المحوّل لتُعلم النموذج بموقع كل رمز في التسلسل، لأن آلية الانتباه وحدها لا تحمل مفهوماً متأصلاً للترتيب.",
        "explanation_simple_ar": "تخبر النموذج \"هذه الكلمة هي الثالثة في الجملة\" لأن آلية الانتباه لا تعرف الترتيب من تلقاء نفسها.",
        "why_it_matters_ar": "ضرورية لأن بنية المحوّل بلا ترميز موضعي لا تفرّق بين \"الكلب عض الرجل\" و\"الرجل عض الكلب\".",
        "example_ar": "إضافة قيمة جيبية لكل موضع في الجملة قبل تمريرها للمحوّل.",
        "related": ["transformer"],
    },
    {
        "slug": "mixture_of_experts", "term_en": "Mixture of Experts", "term_ar": "مزيج الخبراء",
        "acronym": "MoE", "aliases": ["moe"],
        "category": "LLM", "difficulty": "advanced", "tags": ["architecture", "efficiency"],
        "definition_en": "An architecture where many specialized sub-networks (\"experts\") exist, but a router activates only a few per input, scaling model capacity without proportionally scaling compute.",
        "definition_ar": "بنية تحتوي على عدد كبير من الشبكات الفرعية المتخصصة (\"الخبراء\")، لكن موجِّهاً يُفعّل قلة منها فقط لكل مدخل، فيزيد سعة النموذج دون زيادة الحساب بنفس النسبة.",
        "explanation_simple_ar": "نموذج ضخم مكوَّن من \"خبراء\" كثر، لكن يُستدعى قلة منهم فقط في كل مرة.",
        "why_it_matters_ar": "يتيح بناء نماذج بمليارات إضافية من المعاملات دون تكلفة استدلال مكافئة.",
        "example_ar": "نموذج بـ 8 خبراء يُفعّل 2 منهم فقط لكل رمز يُولَّد.",
        "related": ["large_language_model"],
    },

    # ── Applied LLM Engineering (COURSE-005) ────────────────────────────
    {
        "slug": "kv_cache", "term_en": "KV Cache", "term_ar": "ذاكرة المفاتيح والقيم",
        "acronym": "KV Cache", "aliases": ["key-value cache"],
        "category": "LLM", "difficulty": "advanced", "tags": ["inference", "efficiency"],
        "definition_en": "A cache of the attention key/value tensors computed for previous tokens, reused during autoregressive generation so each new token is not recomputed from scratch.",
        "definition_ar": "ذاكرة تخزّن متجهات المفاتيح والقيم المحسوبة للرموز السابقة في آلية الانتباه، تُعاد استخدامها أثناء التوليد التتابعي حتى لا يُعاد حساب كل شيء من الصفر مع كل رمز جديد.",
        "explanation_simple_ar": "يحتفظ النموذج بما حسبه سابقاً بدل إعادة حسابه من جديد مع كل كلمة يولّدها.",
        "why_it_matters_ar": "بدونها يصبح توليد النصوص الطويلة بطيئاً جداً وغير عملي.",
        "example_ar": "تسريع توليد رد طويل بإعادة استخدام حسابات الكلمات السابقة بدل إعادة حسابها.",
        "related": ["latency", "throughput"],
    },
    {
        "slug": "instruction_tuning", "term_en": "Instruction Tuning", "term_ar": "الضبط على التعليمات",
        "acronym": None, "aliases": ["supervised instruction fine-tuning", "sft"],
        "category": "LLM", "difficulty": "intermediate", "tags": ["fine-tuning"],
        "definition_en": "Fine-tuning a pretrained language model on examples of instructions paired with desired responses, so it learns to follow instructions rather than just continue text.",
        "definition_ar": "ضبط نموذج لغة مدرَّب مسبقاً على أمثلة من تعليمات مقترنة بالاستجابات المرغوبة، فيتعلم اتّباع التعليمات بدلاً من مجرد إكمال النص.",
        "explanation_simple_ar": "تدريب النموذج على أمثلة \"سؤال وجواب مثالي\" ليصبح مساعداً مطيعاً للتعليمات.",
        "why_it_matters_ar": "الخطوة التي حوّلت نماذج إكمال النص إلى مساعدات محادثة مفيدة.",
        "example_ar": "تدريب النموذج على آلاف الأمثلة \"تعليمة → إجابة جيدة\".",
        "related": ["preference_tuning"],
    },
    {
        "slug": "preference_tuning", "term_en": "Preference Tuning", "term_ar": "الضبط على التفضيلات",
        "acronym": None, "aliases": ["rlhf", "dpo", "direct preference optimization"],
        "category": "LLM", "difficulty": "advanced", "tags": ["fine-tuning", "alignment"],
        "definition_en": "Further training a model using human (or AI) preferences between candidate responses - via reinforcement learning (RLHF) or direct optimization (DPO) - to align its outputs with what people actually prefer.",
        "definition_ar": "تدريب إضافي للنموذج باستخدام تفضيلات بشرية (أو من نموذج آخر) بين استجابات مرشّحة - عبر التعلم المعزَّز (RLHF) أو التحسين المباشر (DPO) - لمواءمة مخرجاته مع ما يفضّله الناس فعلياً.",
        "explanation_simple_ar": "تعليم النموذج أي رد أفضل من رد آخر، لا فقط ما هو الرد الصحيح.",
        "why_it_matters_ar": "هي الخطوة التي تجعل رد النموذج مفيداً ومهذباً وآمناً، لا فقط صحيحاً لغوياً.",
        "example_ar": "اختيار الناس بين ردّين على نفس السؤال، ثم تدريب النموذج ليفضّل النمط الأفضل.",
        "related": ["instruction_tuning"],
    },
    {
        "slug": "cross_encoder", "term_en": "Cross-Encoder", "term_ar": "المشفّر المتقاطع",
        "acronym": None, "aliases": [],
        "category": "RAG", "difficulty": "advanced", "tags": ["retrieval", "reranking"],
        "definition_en": "A model that encodes a query and a candidate document together (not separately) to score their relevance jointly - more accurate than embedding similarity but too slow to run on a whole corpus, so used for reranking a short list.",
        "definition_ar": "نموذج يشفّر الاستعلام والمستند المرشّح معاً (لا كل على حدة) ليقيّم مدى صلتهما ببعض، وهو أدق من تشابه المتجهات لكنه أبطأ من أن يُطبَّق على كل المستندات، لذلك يُستخدم لإعادة ترتيب قائمة قصيرة فقط.",
        "explanation_simple_ar": "يقرأ السؤال والإجابة المحتملة معاً ليقرر مدى ملاءمتهما، بدقة أعلى لكن بسرعة أقل.",
        "why_it_matters_ar": "يرفع دقة أفضل النتائج بعد أن يجلبها استرجاع أسرع لكن أقل دقة.",
        "example_ar": "استخدام مشفّر متقاطع لإعادة ترتيب أفضل 20 نتيجة مسترجَعة بسرعة.",
        "related": ["reranking", "dense_retrieval"],
    },
    {
        "slug": "sentence_embeddings", "term_en": "Sentence Embeddings", "term_ar": "متجهات الجمل",
        "acronym": None, "aliases": ["document embeddings"],
        "category": "Representation Learning", "difficulty": "intermediate", "tags": ["embeddings"],
        "definition_en": "Embeddings computed for a whole sentence or document rather than a single word, designed so semantically similar sentences map to nearby vectors.",
        "definition_ar": "متجهات تُحسب لجملة أو مستند كامل بدل كلمة واحدة، مصمَّمة بحيث تكون الجمل المتشابهة في المعنى قريبة من بعضها كمتجهات.",
        "explanation_simple_ar": "تمثيل جملة كاملة كرقم واحد من الأرقام يحافظ على معناها العام.",
        "why_it_matters_ar": "الأساس العملي لأنظمة RAG والبحث الدلالي على مستوى الجمل والفقرات لا الكلمات فقط.",
        "example_ar": "تمثيل فقرة كاملة من مستند كمتجه واحد لمقارنته بالاستعلام.",
        "related": ["embedding", "vector_search"],
    },
    {
        "slug": "chat_template", "term_en": "Chat Template", "term_ar": "قالب المحادثة",
        "acronym": None, "aliases": ["chat templates"],
        "category": "LLM", "difficulty": "intermediate", "tags": ["prompting"],
        "definition_en": "The specific formatting a chat-tuned model expects for turns (system/user/assistant roles, special tokens) so its instruction-following behavior works as trained.",
        "definition_ar": "التنسيق المحدد الذي يتوقعه النموذج المضبوط للمحادثة لأدوار المحادثة (نظام/مستخدم/مساعد ورموز خاصة)، لكي يعمل سلوكه في اتّباع التعليمات كما تم تدريبه.",
        "explanation_simple_ar": "الشكل الدقيق الذي يجب تنسيق المحادثة به حتى يفهمه النموذج كما دُرِّب.",
        "why_it_matters_ar": "استخدام قالب خاطئ يجعل نموذجاً مدرَّباً جيداً يبدو أداؤه ضعيفاً دون سبب واضح.",
        "example_ar": "وضع كل رسالة بين رموز خاصة تحدد كونها من \"المستخدم\" أو \"المساعد\".",
        "related": ["system_prompt"],
    },
    {
        "slug": "grouped_query_attention", "term_en": "Grouped-Query Attention", "term_ar": "الانتباه المجمَّع للاستعلام",
        "acronym": "GQA", "aliases": ["gqa", "multi-query attention"],
        "category": "LLM", "difficulty": "advanced", "tags": ["architecture", "efficiency"],
        "definition_en": "An attention variant where multiple query heads share a smaller number of key/value heads, reducing the KV cache's memory footprint with little quality loss versus full multi-head attention.",
        "definition_ar": "نوع من آلية الانتباه تتشارك فيه عدة رؤوس استعلام عدداً أصغر من رؤوس المفاتيح والقيم، فيقلل حجم ذاكرة KV دون خسارة تُذكر في الجودة مقارنة بالانتباه متعدد الرؤوس الكامل.",
        "explanation_simple_ar": "تبسيط لآلية الانتباه يقلل الذاكرة المطلوبة دون التضحية بجودة النموذج تقريباً.",
        "why_it_matters_ar": "أحد أهم التحسينات الهندسية التي جعلت خدمة النماذج الكبيرة أرخص وأسرع.",
        "example_ar": "استخدام GQA بدل الانتباه متعدد الرؤوس الكامل لتقليل تكلفة الاستدلال.",
        "related": ["kv_cache"],
    },
    {
        "slug": "rope", "term_en": "Rotary Position Embedding", "term_ar": "الترميز الموضعي الدوراني",
        "acronym": "RoPE", "aliases": ["rope"],
        "category": "LLM", "difficulty": "advanced", "tags": ["architecture"],
        "definition_en": "A positional encoding method that rotates query/key vectors by an angle depending on position, giving transformers a relative sense of token distance that generalizes well to longer sequences.",
        "definition_ar": "طريقة ترميز موضعي تُدوِّر متجهات الاستعلام والمفتاح بزاوية تعتمد على الموضع، فتمنح المحوّل إحساساً نسبياً بالمسافة بين الرموز يعمّم جيداً على تسلسلات أطول.",
        "explanation_simple_ar": "طريقة حديثة لإخبار النموذج بترتيب الكلمات، تتعامل بشكل أفضل مع النصوص الطويلة.",
        "why_it_matters_ar": "يستخدمها معظم نماذج اللغة الكبيرة الحديثة لأنها تُحسّن التعميم على سياقات أطول.",
        "example_ar": "نموذج يستخدم RoPE يتعامل بشكل أفضل مع نصوص أطول مما رآه أثناء التدريب.",
        "related": ["positional_encoding"],
    },

    # ── Advanced LLM systems (cross-course; grouped under the former COURSE-007 until 2026-10) ──
    # COURSE-007 is now "AI Agents with MCP". Associations are derived from the
    # lesson text, so these terms attach to whichever lessons actually mention them.
    {
        "slug": "throughput", "term_en": "Throughput", "term_ar": "الإنتاجية",
        "acronym": None, "aliases": ["requests per second"],
        "category": "Systems", "difficulty": "intermediate", "tags": ["performance"],
        "definition_en": "The number of requests, tokens or jobs a system processes per unit of time, as opposed to latency which measures a single request's speed.",
        "definition_ar": "عدد الطلبات أو الرموز أو المهام التي يعالجها النظام في وحدة الزمن، على عكس زمن الاستجابة الذي يقيس سرعة طلب واحد فقط.",
        "explanation_simple_ar": "كم طلباً يستطيع النظام معالجته في الثانية، لا كم يستغرق طلب واحد.",
        "why_it_matters_ar": "نظام قد يكون سريعاً لطلب واحد لكن إنتاجيته منخفضة تحت الحمل الحقيقي.",
        "example_ar": "خادم يعالج 200 طلب في الثانية بمتوسط زمن استجابة معقول.",
        "related": ["latency"],
    },
    {
        "slug": "calibration", "term_en": "Calibration", "term_ar": "المعايرة",
        "acronym": None, "aliases": ["model calibration"],
        "category": "Evaluation", "difficulty": "advanced", "tags": ["reliability"],
        "definition_en": "How well a model's confidence scores match its actual accuracy - a well-calibrated model that says \"90% confident\" is right about 90% of the time.",
        "definition_ar": "مدى تطابق درجات ثقة النموذج مع دقته الفعلية - النموذج المعاير جيداً حين يقول \"واثق بنسبة 90%\" يكون محقاً بنسبة 90% تقريباً بالفعل.",
        "explanation_simple_ar": "هل ثقة النموذج بنفسه تعكس دقته الحقيقية أم لا.",
        "why_it_matters_ar": "نموذج مفرط الثقة في إجابات خاطئة خطر في التطبيقات الحساسة.",
        "example_ar": "نموذج يقول \"متأكد 99%\" لكنه مخطئ نصف الوقت هو نموذج سيئ المعايرة.",
        "related": ["label_smoothing"],
    },
    {
        "slug": "benchmark_contamination", "term_en": "Benchmark Contamination", "term_ar": "تلوّث معايير التقييم",
        "acronym": None, "aliases": ["data contamination", "test set contamination"],
        "category": "Evaluation", "difficulty": "advanced", "tags": ["evaluation", "pitfalls"],
        "definition_en": "When a model's training data accidentally includes benchmark questions or their answers, inflating its evaluation scores without real capability gains.",
        "definition_ar": "عندما تحتوي بيانات تدريب النموذج، عن غير قصد، على أسئلة معيار التقييم أو إجاباتها، فترتفع درجاته في التقييم دون تحسّن حقيقي في القدرة.",
        "explanation_simple_ar": "النموذج \"يغش\" دون قصد لأنه رأى أسئلة الاختبار أثناء التدريب.",
        "why_it_matters_ar": "يجعل مقارنة النماذج على المعايير العامة غير موثوقة أحياناً.",
        "example_ar": "نموذج يحقق درجة عالية على اختبار معياري لأن إجاباته كانت ضمن بيانات تدريبه.",
        "related": ["benchmark"],
    },
    {
        "slug": "human_evaluation", "term_en": "Human Evaluation", "term_ar": "التقييم البشري",
        "acronym": None, "aliases": ["human eval"],
        "category": "Evaluation", "difficulty": "intermediate", "tags": ["evaluation"],
        "definition_en": "Judging model outputs using human raters against criteria like helpfulness, accuracy or safety, when automated metrics cannot capture what actually matters.",
        "definition_ar": "الحكم على مخرجات النموذج باستخدام مقيّمين بشريين وفق معايير مثل الفائدة أو الدقة أو السلامة، عندما لا تستطيع المقاييس الآلية التقاط ما يهم فعلاً.",
        "explanation_simple_ar": "الاستعانة بأشخاص حقيقيين للحكم على جودة إجابة النموذج.",
        "why_it_matters_ar": "بعض جوانب الجودة (الأسلوب، الفائدة الفعلية) يصعب قياسها آلياً.",
        "example_ar": "طلب من مقيَّمين بشريين تفضيل أفضل رد من بين ردّين.",
        "related": ["llm_as_judge"],
    },
    {
        "slug": "model_routing", "term_en": "Model Routing", "term_ar": "توجيه النماذج",
        "acronym": None, "aliases": ["ai gateway", "llm gateway"],
        "category": "Systems", "difficulty": "advanced", "tags": ["production", "architecture"],
        "definition_en": "Directing each request to the most suitable model (by cost, capability or latency) among several available ones, often through a central gateway layer.",
        "definition_ar": "توجيه كل طلب إلى النموذج الأنسب (من حيث التكلفة أو القدرة أو زمن الاستجابة) من بين عدة نماذج متاحة، غالباً عبر طبقة بوابة مركزية.",
        "explanation_simple_ar": "اختيار أي نموذج يعالج كل طلب بحسب صعوبته وتكلفته.",
        "why_it_matters_ar": "يوازن التكلفة والجودة بدل استخدام أقوى (وأغلى) نموذج لكل طلب.",
        "example_ar": "توجيه الأسئلة البسيطة لنموذج صغير رخيص والمعقدة لنموذج أكبر.",
        "related": [],
    },

    # ── Vision-Language & Multimodal (COURSE-008) ───────────────────────
    {
        "slug": "frame_sampling", "term_en": "Frame Sampling", "term_ar": "أخذ عيّنات الإطارات",
        "acronym": None, "aliases": [],
        "category": "Vision-Language", "difficulty": "advanced", "tags": ["video"],
        "definition_en": "Selecting a subset of frames from a video to feed a model, since processing every frame is usually too expensive; the sampling strategy strongly affects what temporal information survives.",
        "definition_ar": "اختيار مجموعة فرعية من إطارات الفيديو لتغذية نموذج بها، لأن معالجة كل إطار عادة مكلفة جداً؛ واستراتيجية الاختيار تؤثر بقوة على أي معلومة زمنية تبقى متاحة.",
        "explanation_simple_ar": "اختيار لقطات قليلة ممثِّلة من فيديو طويل بدل تحليل كل لقطة فيه.",
        "why_it_matters_ar": "توازن بين تكلفة المعالجة والحفاظ على المعلومة الزمنية المهمة.",
        "example_ar": "أخذ إطار واحد كل ثانية من فيديو طويل بدل كل إطاراته.",
        "related": ["vision_language_model"],
    },
    {
        "slug": "continuous_batching", "term_en": "Continuous Batching", "term_ar": "التجميع المستمر للدفعات",
        "acronym": None, "aliases": ["in-flight batching"],
        "category": "Systems", "difficulty": "advanced", "tags": ["inference", "serving"],
        "definition_en": "A serving technique that dynamically adds new requests into a running batch as soon as a slot frees up, instead of waiting for a whole batch to finish, greatly improving GPU utilization for LLM inference.",
        "definition_ar": "تقنية تقديم تُضيف طلبات جديدة إلى دفعة قيد التشغيل بمجرد توفر مكان فيها، بدل انتظار انتهاء الدفعة بأكملها، مما يحسّن استغلال GPU بشكل كبير في استدلال نماذج اللغة.",
        "explanation_simple_ar": "بدل انتظار انتهاء كل الطلبات في مجموعة واحدة، تُضاف طلبات جديدة فور توفر مكان.",
        "why_it_matters_ar": "من أهم تقنيات خفض تكلفة تشغيل نماذج اللغة الكبيرة في الإنتاج.",
        "example_ar": "خادم استدلال يخدم عشرات المستخدمين في نفس الوقت دون انتظار دفعة كاملة.",
        "related": ["throughput", "kv_cache"],
    },

    # ── Enterprise RAG (COURSE-009) ──────────────────────────────────────
    {
        "slug": "rbac", "term_en": "Role-Based Access Control", "term_ar": "التحكم بالوصول المبني على الأدوار",
        "acronym": "RBAC", "aliases": ["rbac"],
        "category": "Systems", "difficulty": "intermediate", "tags": ["security"],
        "definition_en": "An authorization model where permissions are attached to roles (not individual users), and users are granted access by being assigned one or more roles.",
        "definition_ar": "نموذج تفويض تُربَط فيه الصلاحيات بأدوار (لا بمستخدمين أفراد)، ويُمنَح المستخدم الوصول عبر إسناده إلى دور أو أكثر.",
        "explanation_simple_ar": "بدل إعطاء صلاحيات لكل شخص على حدة، تُعطى لأدوار (مثل \"مسؤول\"، \"محرر\") ثم يُسند الأشخاص لها.",
        "why_it_matters_ar": "يبسّط إدارة الصلاحيات في أنظمة بها عدد كبير من المستخدمين.",
        "example_ar": "دور \"مسؤول\" يرى كل الوثائق، ودور \"موظف\" يرى وثائق قسمه فقط.",
        "related": ["authorization"],
    },
    {
        "slug": "recall_at_k", "term_en": "Recall@K", "term_ar": "الاستدعاء عند k",
        "acronym": "Recall@K", "aliases": ["recall at k", "precision@k"],
        "category": "RAG", "difficulty": "intermediate", "tags": ["retrieval", "metrics"],
        "definition_en": "A retrieval metric measuring whether (or how often) a relevant document appears among the top-k results returned, the standard way to evaluate a retriever's quality.",
        "definition_ar": "مقياس استرجاع يقيس ما إذا كان (وبأي معدل) المستند ذو الصلة يظهر ضمن أفضل k نتيجة مُعادة، وهو الطريقة المعيارية لتقييم جودة نظام الاسترجاع.",
        "explanation_simple_ar": "من بين أفضل k نتيجة أعادها النظام، هل كانت الإجابة الصحيحة من ضمنها؟",
        "why_it_matters_ar": "المقياس الأساسي للحكم على جودة أي نظام استرجاع قبل الحكم على جودة الإجابة النهائية.",
        "example_ar": "Recall@5 يساوي 0.9 يعني أن المستند الصحيح ظهر ضمن أفضل 5 نتائج في 90% من الحالات.",
        "related": ["dense_retrieval", "reranking"],
    },
    {
        "slug": "agentic_rag", "term_en": "Agentic RAG", "term_ar": "RAG الوكيلي",
        "acronym": None, "aliases": [],
        "category": "RAG", "difficulty": "advanced", "tags": ["retrieval", "agents"],
        "definition_en": "A RAG system where an agent decides, iteratively, whether and what to retrieve, re-query, or use additional tools - rather than always doing one fixed retrieve-then-generate pass.",
        "definition_ar": "نظام RAG يقرر فيه وكيل، بشكل تكراري، متى وماذا يسترجع أو يعيد الاستعلام أو يستخدم أدوات إضافية - بدلاً من تنفيذ خطوة استرجاع ثم توليد ثابتة دائماً.",
        "explanation_simple_ar": "نظام RAG \"يفكر\" في كيفية البحث، فقد يبحث أكثر من مرة أو يستخدم أدوات أخرى قبل الإجابة.",
        "why_it_matters_ar": "يتعامل مع أسئلة معقدة تحتاج بحثاً متعدد الخطوات، لا استرجاعاً واحداً بسيطاً.",
        "example_ar": "وكيل يبحث أولاً، يجد نتيجة غير كافية، فيعيد صياغة السؤال ويبحث مجدداً.",
        "related": ["retrieval_augmented_generation", "agent"],
    },
    {
        "slug": "provenance", "term_en": "Provenance", "term_ar": "تتبّع المصدر",
        "acronym": None, "aliases": ["source attribution", "citations"],
        "category": "RAG", "difficulty": "intermediate", "tags": ["reliability"],
        "definition_en": "Tracking and exposing which source document (and often which passage) an answer's claims came from, so a user can verify it.",
        "definition_ar": "تتبّع وإظهار أي مستند مصدر (وغالباً أي مقطع منه) جاءت منه ادعاءات الإجابة، بحيث يمكن للمستخدم التحقق منها.",
        "explanation_simple_ar": "معرفة \"من أين جاءت هذه المعلومة بالضبط\" في إجابة النموذج.",
        "why_it_matters_ar": "يبني الثقة ويتيح التحقق، خاصة في التطبيقات المؤسسية والقانونية والطبية.",
        "example_ar": "إجابة تُرفَق برقم الصفحة والمستند الذي استُخرجت منه.",
        "related": ["grounding"],
    },
    {
        "slug": "pii", "term_en": "Personally Identifiable Information", "term_ar": "المعلومات الشخصية المعرِّفة",
        "acronym": "PII", "aliases": ["pii"],
        "category": "Systems", "difficulty": "beginner", "tags": ["security", "privacy"],
        "definition_en": "Any data that could identify a specific individual (name, national id, phone, email, ...), which systems must detect, redact or protect according to privacy requirements.",
        "definition_ar": "أي بيانات يمكن أن تعرّف شخصاً بعينه (الاسم، الرقم القومي، الهاتف، البريد الإلكتروني، ...)، ويجب على الأنظمة كشفها أو إخفاؤها أو حمايتها وفق متطلبات الخصوصية.",
        "explanation_simple_ar": "أي معلومة يمكن أن تكشف هوية شخص محدد.",
        "why_it_matters_ar": "التعامل الخاطئ معها يخالف القانون ويعرّض المستخدمين للخطر.",
        "example_ar": "إخفاء رقم الهاتف والبريد الإلكتروني تلقائياً قبل تخزين سجل محادثة.",
        "related": ["authentication"],
    },

    # ── AI Service Engineering / FastAPI (COURSE-010) ───────────────────
    {
        "slug": "dependency_injection", "term_en": "Dependency Injection", "term_ar": "حقن الاعتماديات",
        "acronym": "DI", "aliases": ["di"],
        "category": "Systems", "difficulty": "intermediate", "tags": ["architecture", "backend"],
        "definition_en": "A design pattern where a component receives the objects it depends on from the outside (e.g. a framework) rather than creating them itself, making code easier to test and swap.",
        "definition_ar": "نمط تصميم يتلقى فيه المكوّن الكائنات التي يعتمد عليها من الخارج (مثل إطار العمل) بدل إنشائها بنفسه، مما يسهّل اختبار الكود واستبدال أجزائه.",
        "explanation_simple_ar": "بدل أن يصنع الكود اعتمادياته بنفسه، يستلمها جاهزة من الخارج.",
        "why_it_matters_ar": "يسهّل الاختبار (استبدال اعتمادية حقيقية بأخرى وهمية) وإعادة الاستخدام.",
        "example_ar": "دالة API تستلم اتصال قاعدة البيانات جاهزاً بدل فتحه بنفسها.",
        "related": [],
    },
    {
        "slug": "event_loop", "term_en": "Event Loop", "term_ar": "حلقة الأحداث",
        "acronym": None, "aliases": [],
        "category": "Systems", "difficulty": "intermediate", "tags": ["concurrency", "backend"],
        "definition_en": "The runtime mechanism behind async programming that continuously checks for and dispatches ready tasks (I/O completions, timers) on a single thread, enabling high concurrency without spawning many threads.",
        "definition_ar": "الآلية التي تعمل خلف البرمجة غير المتزامنة، وتفحص باستمرار المهام الجاهزة (اكتمال عمليات الإدخال/الإخراج، المؤقتات) وتنفّذها على خيط واحد، فتتيح تزامناً عالياً دون إنشاء خيوط كثيرة.",
        "explanation_simple_ar": "آلية تدير مهام كثيرة \"منتظرة\" في نفس الوقت على خيط تنفيذ واحد فقط.",
        "why_it_matters_ar": "الأساس الذي تقوم عليه خدمات الويب الحديثة عالية التزامن مثل FastAPI.",
        "example_ar": "خادم يخدم آلاف الاتصالات المتزامنة دون فتح ألف خيط تنفيذ.",
        "related": [],
    },
    {
        "slug": "cold_start", "term_en": "Cold Start", "term_ar": "البدء البارد",
        "acronym": None, "aliases": [],
        "category": "Systems", "difficulty": "intermediate", "tags": ["serverless", "performance"],
        "definition_en": "The extra latency incurred when a serverless function or container must be initialized from scratch before it can serve its first request, as opposed to a \"warm\" instance already running.",
        "explanation_simple_ar": "التأخير الإضافي الذي يحدث عند بدء تشغيل خدمة من الصفر قبل أن تستطيع خدمة أول طلب.",
        "definition_ar": "زمن الاستجابة الإضافي الذي يحدث عندما يجب تهيئة دالة أو حاوية بلا خادم من الصفر قبل أن تستطيع خدمة أول طلب، على عكس نسخة \"دافئة\" تعمل بالفعل.",
        "why_it_matters_ar": "يؤثر مباشرة على تجربة المستخدم الأولى في الأنظمة عديمة الخادم.",
        "example_ar": "أول طلب بعد فترة خمول يستغرق ثوانٍ إضافية لتشغيل الحاوية.",
        "related": [],
    },
    {
        "slug": "mfa", "term_en": "Multi-Factor Authentication", "term_ar": "التحقق متعدد العوامل",
        "acronym": "MFA", "aliases": ["mfa", "two-factor authentication", "2fa"],
        "category": "Systems", "difficulty": "beginner", "tags": ["security"],
        "definition_en": "Requiring two or more independent proofs of identity (password plus a code, device or biometric) before granting access, reducing risk from a single compromised credential.",
        "definition_ar": "اشتراط دليلين مستقلّين أو أكثر لإثبات الهوية (كلمة مرور بالإضافة إلى رمز، أو جهاز، أو بصمة) قبل منح الوصول، مما يقلل خطر اختراق بيانات اعتماد واحدة.",
        "explanation_simple_ar": "التحقق من الهوية بأكثر من طريقة واحدة، مثل كلمة مرور ثم رمز على الهاتف.",
        "why_it_matters_ar": "يحمي الحساب حتى لو سُرقت كلمة المرور وحدها.",
        "example_ar": "إدخال كلمة المرور ثم رمز يصل عبر تطبيق مصادقة.",
        "related": ["authentication"],
    },

    # ── AI Agents (COURSE-012) ─────────────────────────────────
    {
        "slug": "react_pattern", "term_en": "ReAct (Reason + Act)", "term_ar": "نمط التفكير والتصرّف",
        "acronym": "ReAct", "aliases": ["react"],
        "category": "Agents", "difficulty": "advanced", "tags": ["agents", "reasoning"],
        "definition_en": "An agent prompting pattern that interleaves explicit reasoning steps (\"thoughts\") with actions (tool calls), letting the model plan, act, observe the result and re-plan in a loop.",
        "definition_ar": "نمط توجيه للوكلاء يتناوب فيه التفكير الصريح (\"الأفكار\") مع التصرّف (استدعاء الأدوات)، بحيث يخطّط النموذج ويتصرف ويلاحظ النتيجة ويعيد التخطيط في حلقة مستمرة.",
        "explanation_simple_ar": "الوكيل \"يفكر بصوت عالٍ\" قبل كل خطوة تصرّف، ثم يلاحظ النتيجة ويكرر.",
        "why_it_matters_ar": "أحد أكثر أنماط تصميم الوكلاء انتشاراً وفاعلية للمهام متعددة الخطوات.",
        "example_ar": "\"أفكر: أحتاج معرفة الطقس. أتصرف: أستدعي أداة الطقس. ألاحظ: النتيجة. أفكر مجدداً...\"",
        "related": ["agent", "tool_calling"],
    },
    {
        "slug": "least_privilege", "term_en": "Least Privilege", "term_ar": "مبدأ أقل الصلاحيات",
        "acronym": None, "aliases": ["principle of least privilege"],
        "category": "Systems", "difficulty": "intermediate", "tags": ["security"],
        "definition_en": "A security principle: grant a user, service or agent only the minimum permissions it needs to do its job, nothing more.",
        "definition_ar": "مبدأ أمني: امنح المستخدم أو الخدمة أو الوكيل الحد الأدنى فقط من الصلاحيات اللازمة لأداء مهمته، لا أكثر.",
        "explanation_simple_ar": "لا تعطِ أي جهة صلاحيات أكثر مما تحتاجه فعلاً.",
        "why_it_matters_ar": "يحدّ الضرر عند حدوث خطأ أو اختراق، خصوصاً مع وكلاء ذكاء اصطناعي يتصرفون تلقائياً.",
        "example_ar": "وكيل يستطيع قراءة الطلبات فقط، لا حذف حسابات المستخدمين.",
        "related": ["authorization", "rbac"],
    },
    {
        "slug": "semantic_memory", "term_en": "Semantic Memory (Agents)", "term_ar": "الذاكرة الدلالية للوكيل",
        "acronym": None, "aliases": ["semantic memory"],
        "category": "Agents", "difficulty": "advanced", "tags": ["agents", "memory"],
        "definition_en": "An agent's persistent store of facts and learned knowledge (as opposed to the transient conversation state), typically retrieved by semantic similarity when relevant.",
        "definition_ar": "مخزن دائم لدى الوكيل للحقائق والمعرفة المكتسبة (بخلاف حالة المحادثة المؤقتة)، يُسترجَع عادة بالتشابه الدلالي عند الحاجة.",
        "explanation_simple_ar": "ما \"يتذكره\" الوكيل بشكل دائم عبر جلسات مختلفة، لا فقط في المحادثة الحالية.",
        "why_it_matters_ar": "يميّز بين وكيل ينسى كل شيء بعد كل محادثة ووكيل يبني معرفة تراكمية.",
        "example_ar": "وكيل يتذكر تفضيلات مستخدم من محادثة سابقة الشهر الماضي.",
        "related": ["agent"],
    },
    {
        "slug": "tool_discovery", "term_en": "Tool Discovery", "term_ar": "اكتشاف الأدوات",
        "acronym": None, "aliases": [],
        "category": "Agents", "difficulty": "advanced", "tags": ["agents"],
        "definition_en": "An agent's ability to find out, at runtime, which tools are available and what they do - rather than having a fixed, hardcoded tool list - important for large or dynamic tool ecosystems (e.g. MCP servers).",
        "definition_ar": "قدرة الوكيل على معرفة الأدوات المتاحة ووظيفتها وقت التشغيل، بدل الاعتماد على قائمة أدوات ثابتة ومبرمَجة مسبقاً - وهذا مهم في أنظمة الأدوات الكبيرة أو الديناميكية (مثل خوادم MCP).",
        "explanation_simple_ar": "الوكيل يسأل \"ما الأدوات المتاحة لي الآن؟\" بدل معرفتها مسبقاً فقط.",
        "why_it_matters_ar": "يتيح إضافة أدوات جديدة دون إعادة برمجة الوكيل نفسه.",
        "example_ar": "وكيل يستعلم عن قائمة الأدوات المتاحة من خادم MCP قبل التخطيط.",
        "related": ["tool_calling"],
    },
    {
        "slug": "multi_agent_collaboration", "term_en": "Multi-Agent Collaboration", "term_ar": "التعاون بين وكلاء متعددين",
        "acronym": None, "aliases": ["multi-agent systems"],
        "category": "Agents", "difficulty": "advanced", "tags": ["agents", "orchestration"],
        "definition_en": "A design where multiple specialized agents work together - dividing a task, handing off sub-problems, or checking each other's work - rather than one agent doing everything.",
        "definition_ar": "تصميم يعمل فيه عدة وكلاء متخصصين معاً - بتقسيم مهمة، أو تسليم مهام فرعية، أو مراجعة عمل بعضهم البعض - بدلاً من قيام وكيل واحد بكل شيء.",
        "explanation_simple_ar": "فريق من الوكلاء المتخصصين يعملون معاً بدل وكيل واحد يفعل كل شيء.",
        "why_it_matters_ar": "يحسّن الموثوقية والتخصص في المهام المعقدة متعددة الجوانب.",
        "example_ar": "وكيل بحث يجمع معلومات ثم يسلّمها لوكيل كتابة يصوغ التقرير النهائي.",
        "related": ["agent", "agentic_workflow"],
    },
    {
        "slug": "reasoning_budget", "term_en": "Reasoning Budget", "term_ar": "ميزانية التفكير",
        "acronym": None, "aliases": ["thinking budget"],
        "category": "Agents", "difficulty": "advanced", "tags": ["agents", "cost"],
        "definition_en": "A limit set on how much reasoning (tokens, steps or time) an agent may spend on a task, balancing answer quality against latency and cost.",
        "definition_ar": "حد يُوضع على مقدار التفكير (رموز أو خطوات أو وقت) المسموح للوكيل بإنفاقه على مهمة، لموازنة جودة الإجابة مقابل زمن الاستجابة والتكلفة.",
        "explanation_simple_ar": "تحديد سقف لمقدار \"التفكير\" الذي يُسمح للوكيل بإنفاقه قبل أن يجيب.",
        "why_it_matters_ar": "تفكير بلا حدود يعني تكلفة وزمن استجابة غير متوقَّعين.",
        "example_ar": "وكيل يُمنح 5 خطوات تفكير كحد أقصى قبل تقديم إجابته النهائية.",
        "related": ["latency"],
    },

    # ── Cloud / CI-CD (COURSE-011) ───────────────────────────────────────
    {
        "slug": "infrastructure_as_code", "term_en": "Infrastructure as Code", "term_ar": "البنية التحتية ككود",
        "acronym": "IaC", "aliases": ["iac", "terraform"],
        "category": "MLOps", "difficulty": "intermediate", "tags": ["deployment", "cloud"],
        "definition_en": "Managing and provisioning infrastructure (servers, networks, permissions) through versioned code and declarative configuration files instead of manual console clicks.",
        "definition_ar": "إدارة وتهيئة البنية التحتية (الخوادم، الشبكات، الصلاحيات) عبر كود مُدار بنظام تحكم بالإصدارات وملفات تكوين تعريفية، بدل النقر اليدوي في لوحة التحكم.",
        "explanation_simple_ar": "وصف البنية التحتية بملفات كود يمكن مراجعتها وتتبّع تغييراتها، بدل إعدادها يدوياً.",
        "why_it_matters_ar": "يجعل البنية التحتية قابلة للمراجعة والتكرار والاستعادة، لا اعتماداً على ذاكرة شخص.",
        "example_ar": "وصف خادم واستضافته بالكامل في ملف Terraform بدل إعداده يدوياً من لوحة تحكم السحابة.",
        "related": ["cicd"],
    },
    {
        "slug": "gitops", "term_en": "GitOps", "term_ar": "GitOps",
        "acronym": None, "aliases": [],
        "category": "MLOps", "difficulty": "advanced", "tags": ["deployment", "cloud"],
        "definition_en": "An operating model where a Git repository is the single source of truth for infrastructure and deployment state, and changes are applied automatically when the repository changes.",
        "definition_ar": "نموذج تشغيل يكون فيه مستودع Git هو المصدر الوحيد للحقيقة بخصوص حالة البنية التحتية والنشر، وتُطبَّق التغييرات تلقائياً عند تغيّر المستودع.",
        "explanation_simple_ar": "أي تغيير في المستودع البرمجي ينعكس تلقائياً على البنية التحتية الفعلية.",
        "why_it_matters_ar": "يجعل كل تغيير في الإنتاج موثَّقاً وقابلاً للمراجعة والتراجع عبر Git.",
        "example_ar": "دمج طلب سحب (pull request) يُشغّل تلقائياً نشر التغيير على السحابة.",
        "related": ["infrastructure_as_code", "cicd"],
    },
    {
        "slug": "cicd", "term_en": "Continuous Integration / Continuous Delivery", "term_ar": "التكامل المستمر والتسليم المستمر",
        "acronym": "CI/CD", "aliases": ["ci/cd", "continuous integration", "continuous delivery", "continuous deployment"],
        "category": "MLOps", "difficulty": "beginner", "tags": ["deployment"],
        "definition_en": "The practice of automatically building, testing (CI) and releasing (CD) code changes frequently and reliably, instead of large infrequent manual releases.",
        "definition_ar": "ممارسة بناء واختبار (CI) ونشر (CD) تغييرات الكود تلقائياً وبشكل متكرر وموثوق، بدلاً من إصدارات يدوية كبيرة ونادرة.",
        "explanation_simple_ar": "كل تغيير في الكود يُختبر ويُنشر تلقائياً بدل انتظار إصدار كبير كل فترة طويلة.",
        "why_it_matters_ar": "يقلل مخاطر النشر ويسرّع وصول التحسينات للمستخدمين.",
        "example_ar": "كل دفعة كود جديدة تشغّل اختبارات تلقائية، فإن نجحت تُنشر تلقائياً.",
        "related": ["infrastructure_as_code", "gitops", "data_pipeline", "deployment"],
    },
    {
        "slug": "autoscaling", "term_en": "Autoscaling", "term_ar": "التوسّع التلقائي",
        "acronym": None, "aliases": ["auto-scaling"],
        "category": "MLOps", "difficulty": "intermediate", "tags": ["deployment", "cloud"],
        "definition_en": "Automatically increasing or decreasing the number of running service instances based on load, so capacity matches demand without manual intervention.",
        "definition_ar": "زيادة أو تقليل عدد نسخ الخدمة العاملة تلقائياً بحسب الحمل، بحيث تتناسب السعة مع الطلب دون تدخل يدوي.",
        "explanation_simple_ar": "زيادة عدد الخوادم تلقائياً وقت الضغط، وتقليلها وقت الهدوء.",
        "why_it_matters_ar": "يوازن بين تحمّل الضغط وتوفير التكلفة دون مراقبة يدوية مستمرة.",
        "example_ar": "زيادة عدد نسخ الخدمة تلقائياً من 2 إلى 10 وقت ذروة الاستخدام.",
        "related": ["cold_start"],
    },
    {
        "slug": "backpressure", "term_en": "Backpressure", "term_ar": "الضغط الخلفي",
        "acronym": None, "aliases": [],
        "category": "Systems", "difficulty": "advanced", "tags": ["streaming", "reliability"],
        "definition_en": "A mechanism for a system to signal upstream that it cannot keep up, so the sender slows down instead of overwhelming it - critical in streaming and real-time pipelines.",
        "definition_ar": "آلية يشير بها نظام إلى ما قبله بأنه غير قادر على مواكبة التدفق، فيبطئ المرسِل بدل إغراقه - وهي حاسمة في أنظمة البث والأنابيب اللحظية.",
        "explanation_simple_ar": "إخبار الطرف المُرسِل \"أبطئ قليلاً\" بدل السماح بتراكم البيانات وانهيار النظام.",
        "why_it_matters_ar": "بدونها، نظام بث صوتي أو بياني سريع قد ينهار تحت الحمل الزائد.",
        "example_ar": "خدمة بث صوت تُبطئ إرسال البيانات عندما لا يستطيع المستقبل مواكبتها.",
        "related": ["latency"],
    },

    # ── Applied Data Analysis (COURSE-013, additions beyond ML section above) ─
    {
        "slug": "precision", "term_en": "Precision", "term_ar": "الدقة (Precision)",
        "acronym": None, "aliases": ["positive predictive value"],
        "category": "Evaluation", "difficulty": "beginner", "tags": ["classification", "metrics"],
        "definition_en": "Of everything a classifier labeled positive, the fraction that was actually positive - it penalizes false positives.",
        "definition_ar": "من بين كل ما صنّفه النموذج كـ\"إيجابي\"، ما هي نسبة ما كان إيجابياً فعلاً - يعاقب هذا المقياس الإيجابيات الخاطئة.",
        "explanation_simple_ar": "عندما يقول النموذج \"نعم\"، كم مرة يكون محقاً فعلاً؟",
        "why_it_matters_ar": "مهم عندما تكون تكلفة الإنذار الكاذب عالية، مثل تصنيف بريد مهم كمزعج.",
        "example_ar": "من بين 100 رسالة صنّفها النموذج كمزعجة، كانت 90 منها فعلاً مزعجة: الدقة 90%.",
        "related": ["recall", "confusion_matrix"],
    },
    {
        "slug": "recall", "term_en": "Recall", "term_ar": "الاستدعاء (Recall)",
        "acronym": None, "aliases": ["sensitivity", "true positive rate"],
        "category": "Evaluation", "difficulty": "beginner", "tags": ["classification", "metrics"],
        "definition_en": "Of everything that was actually positive, the fraction the classifier correctly found - it penalizes false negatives (missed cases).",
        "definition_ar": "من بين كل ما كان إيجابياً فعلاً، ما هي نسبة ما اكتشفه النموذج بشكل صحيح - يعاقب هذا المقياس الحالات الإيجابية التي فُوِّتت.",
        "explanation_simple_ar": "من بين كل الحالات الحقيقية، كم منها اكتشفها النموذج فعلاً؟",
        "why_it_matters_ar": "مهم عندما تكون تكلفة تفويت حالة حقيقية عالية، مثل تشخيص طبي.",
        "example_ar": "من بين 100 حالة احتيال حقيقية، اكتشف النموذج 80 منها: الاستدعاء 80%.",
        "related": ["precision", "confusion_matrix", "f1_score"],
    },
    {
        "slug": "f1_score", "term_en": "F1 Score", "term_ar": "مقياس F1",
        "acronym": "F1", "aliases": ["f1", "f-measure"],
        "category": "Evaluation", "difficulty": "beginner", "tags": ["classification", "metrics"],
        "definition_en": "The harmonic mean of precision and recall, giving one balanced score when both matter and neither should be optimized at the other's expense.",
        "definition_ar": "المتوسط التوافقي بين الدقة والاستدعاء، يعطي رقماً واحداً متوازناً حين يهم كلاهما ولا ينبغي تحسين أحدهما على حساب الآخر.",
        "explanation_simple_ar": "رقم واحد يوازن بين \"الدقة\" و\"الاستدعاء\" بدل النظر إليهما منفصلين.",
        "why_it_matters_ar": "مفيد جداً عند وجود عدم توازن بين الفئات حيث الدقة وحدها مضلِّلة.",
        "example_ar": "نموذج بدقة 90% واستدعاء 70% يحصل على F1 يوازن بينهما.",
        "related": ["precision", "recall"],
    },
    {
        "slug": "jwt", "term_en": "JSON Web Token", "term_ar": "رمز JWT",
        "acronym": "JWT", "aliases": ["jwt", "json web token"],
        "category": "Systems", "difficulty": "intermediate", "tags": ["security", "authentication"],
        "definition_en": "A compact, signed token format that encodes claims (such as user id and expiry) so a server can verify a request's identity without a database lookup on every call.",
        "definition_ar": "صيغة رمز مضغوطة وموقَّعة تحمل ادعاءات (مثل هوية المستخدم ووقت انتهاء الصلاحية)، بحيث يستطيع الخادم التحقق من هوية الطلب دون الحاجة لاستعلام قاعدة بيانات في كل مرة.",
        "explanation_simple_ar": "بطاقة هوية رقمية موقَّعة يحملها المستخدم مع كل طلب لإثبات هويته.",
        "why_it_matters_ar": "الأساس الذي تعمل به معظم أنظمة تسجيل الدخول والتحقق الحديثة على الويب.",
        "example_ar": "بعد تسجيل الدخول، يحمل المتصفح رمز JWT مع كل طلب لاحق لإثبات هوية المستخدم.",
        "related": ["authentication", "authorization"],
    },
    {
        "slug": "outlier_detection", "term_en": "Outlier Detection", "term_ar": "كشف القيم الشاذة",
        "acronym": None, "aliases": ["anomaly detection"],
        "category": "Data", "difficulty": "beginner", "tags": ["statistics"],
        "definition_en": "Identifying data points that deviate significantly from the rest of the distribution, which can be genuine rare events or data-quality errors.",
        "definition_ar": "تحديد نقاط البيانات التي تنحرف بشكل كبير عن بقية التوزيع، وقد تكون أحداثاً نادرة حقيقية أو أخطاء في جودة البيانات.",
        "explanation_simple_ar": "إيجاد القيم غير الطبيعية أو الغريبة داخل مجموعة بيانات.",
        "why_it_matters_ar": "قيمة شاذة واحدة يمكن أن تشوّه متوسطاً أو تُضلّل نموذجاً كاملاً.",
        "example_ar": "معاملة مالية بمبلغ غير معقول مقارنة بباقي معاملات الحساب.",
        "related": ["iqr"],
    },

    # ── Computer Vision (COURSE-014) ─────────────────────────────────────
    {
        "slug": "point_cloud", "term_en": "Point Cloud", "term_ar": "السحابة النقطية",
        "acronym": None, "aliases": ["point clouds"],
        "category": "Computer Vision", "difficulty": "advanced", "tags": ["3d"],
        "definition_en": "A set of points in 3D space, each with coordinates (and often color), used to represent the geometry of real-world scenes captured by depth sensors or LiDAR.",
        "definition_ar": "مجموعة من النقاط في فضاء ثلاثي الأبعاد، لكل منها إحداثيات (وغالباً لون)، تُستخدم لتمثيل هندسة مشاهد العالم الحقيقي الملتقَطة بأجهزة استشعار العمق أو الليدار.",
        "explanation_simple_ar": "تمثيل شكل جسم أو مشهد ثلاثي الأبعاد كملايين النقاط في الفضاء بدل صورة مسطحة.",
        "why_it_matters_ar": "أساسي في الروبوتات والقيادة الذاتية والواقع المعزز.",
        "example_ar": "مسح غرفة بمستشعر عمق لإنتاج سحابة نقطية لأثاثها.",
        "related": [],
    },
    {
        "slug": "semantic_segmentation", "term_en": "Semantic Segmentation", "term_ar": "التجزئة الدلالية",
        "acronym": None, "aliases": ["panoptic segmentation", "instance segmentation"],
        "category": "Computer Vision", "difficulty": "advanced", "tags": ["segmentation"],
        "definition_en": "Classifying every pixel of an image into a category, producing a dense per-pixel map rather than just a bounding box or a single label.",
        "definition_ar": "تصنيف كل بكسل في الصورة إلى فئة، فينتج خريطة كثيفة على مستوى البكسل بدلاً من مجرد صندوق إحاطة أو تصنيف واحد للصورة كاملة.",
        "explanation_simple_ar": "تلوين كل بكسل في الصورة بحسب الشيء الذي ينتمي إليه (سماء، طريق، سيارة...).",
        "why_it_matters_ar": "ضروري في القيادة الذاتية والتصوير الطبي حيث تهم الحدود الدقيقة للأشياء.",
        "example_ar": "تحديد كل بكسل ينتمي للطريق مقابل الأرصفة والسيارات في صورة شارع.",
        "related": ["promptable_segmentation"],
    },
    {
        "slug": "promptable_segmentation", "term_en": "Promptable Segmentation", "term_ar": "التجزئة الموجَّهة بمِحفِّز",
        "acronym": None, "aliases": ["sam", "segment anything"],
        "category": "Computer Vision", "difficulty": "advanced", "tags": ["segmentation"],
        "definition_en": "Segmentation models (like Segment Anything) that accept a point, box or text prompt at inference time to specify which object to segment, instead of being trained for fixed categories only.",
        "definition_ar": "نماذج تجزئة (مثل Segment Anything) تقبل نقطة أو صندوقاً أو محفّزاً نصياً وقت الاستدلال لتحديد أي جسم يُجزَّأ، بدل أن تكون مدرَّبة على فئات ثابتة فقط.",
        "explanation_simple_ar": "بدل تدريب النموذج على فئات محددة سلفاً، يشير له المستخدم بنقطة أو مربع على الجسم المطلوب تجزئته.",
        "why_it_matters_ar": "يعمّم على أي جسم دون الحاجة لإعادة تدريب لكل فئة جديدة.",
        "example_ar": "النقر على جسم في صورة ليقوم النموذج بتحديد حدوده بدقة.",
        "related": ["semantic_segmentation"],
    },
    {
        "slug": "homography", "term_en": "Homography", "term_ar": "التآلف الإسقاطي",
        "acronym": None, "aliases": [],
        "category": "Computer Vision", "difficulty": "advanced", "tags": ["geometry"],
        "definition_en": "A transformation that maps points from one planar perspective to another, used to correct perspective distortion or stitch images together.",
        "definition_ar": "تحويل يُسقط نقاطاً من منظور مستوٍ إلى آخر، يُستخدم لتصحيح تشوّه المنظور أو دمج صور متعددة معاً.",
        "explanation_simple_ar": "تحويل رياضي يعيد \"تسوية\" صورة مُلتقطة بزاوية مائلة كأنها مُلتقطة من الأمام مباشرة.",
        "why_it_matters_ar": "أساسي في تصحيح المنظور ودمج الصور البانورامية والقراءة الآلية للمستندات.",
        "example_ar": "تصحيح صورة مستند مُلتقطة بزاوية لتبدو مستوية تماماً.",
        "related": [],
    },
    {
        "slug": "canny_edge_detector", "term_en": "Canny Edge Detector", "term_ar": "كاشف حواف كاني",
        "acronym": None, "aliases": ["canny"],
        "category": "Computer Vision", "difficulty": "intermediate", "tags": ["classical-cv"],
        "definition_en": "A classical multi-stage algorithm (smoothing, gradient, non-maximum suppression, hysteresis thresholding) that finds clean, thin edges in an image.",
        "definition_ar": "خوارزمية كلاسيكية متعددة المراحل (تنعيم، تدرّج، كبت غير الأقصى، عتبة تباطؤية) تجد حواف نظيفة ورفيعة في الصورة.",
        "explanation_simple_ar": "طريقة تقليدية لإيجاد خطوط الحدود الواضحة بين أجسام مختلفة في صورة.",
        "why_it_matters_ar": "لا تزال أداة أساسية سريعة قبل اللجوء لنماذج تعلّم عميق أثقل.",
        "example_ar": "استخراج حواف الأشياء في صورة قبل تحليلها هندسياً.",
        "related": [],
    },
    {
        "slug": "nyquist_criterion", "term_en": "Nyquist Criterion", "term_ar": "معيار نايكويست",
        "acronym": None, "aliases": ["aliasing", "nyquist"],
        "category": "Computer Vision", "difficulty": "advanced", "tags": ["signal-processing"],
        "definition_en": "The rule that a signal must be sampled at more than twice its highest frequency to be reconstructed without distortion; violating it causes aliasing (false, misleading patterns).",
        "definition_ar": "قاعدة تقول إن الإشارة يجب أن تُعايَن بمعدل أكبر من ضعف أعلى تردد فيها لإعادة بنائها دون تشويه؛ ومخالفتها تسبب التعرّج (Aliasing) - أنماطاً زائفة ومضلِّلة.",
        "explanation_simple_ar": "إذا لم تُلتقط عيّنات كافية من إشارة (صوت أو صورة)، تظهر أنماط مزيّفة غير موجودة أصلاً.",
        "why_it_matters_ar": "يفسّر ظواهر تشويه شائعة في الصوت والصورة والفيديو الرقمي.",
        "example_ar": "عجلة سيارة تبدو وكأنها تدور للخلف في فيديو بسبب معدل تصوير غير كافٍ.",
        "related": [],
    },
    {
        "slug": "histogram_equalization", "term_en": "Histogram Equalization", "term_ar": "تسوية المدرج التكراري",
        "acronym": None, "aliases": ["clahe"],
        "category": "Computer Vision", "difficulty": "intermediate", "tags": ["classical-cv"],
        "definition_en": "A technique that redistributes an image's pixel intensity values to spread them more evenly, improving contrast in poorly lit or low-contrast images.",
        "definition_ar": "تقنية تعيد توزيع قيم شدة إضاءة بكسلات الصورة لتصبح أكثر انتشاراً، فتحسّن التباين في الصور ضعيفة الإضاءة أو منخفضة التباين.",
        "explanation_simple_ar": "تحسين وضوح صورة باهتة أو معتمة بإعادة توزيع درجات الإضاءة فيها.",
        "why_it_matters_ar": "خطوة تجهيز أولي شائعة قبل التحليل الآلي للصور الطبية والأمنية.",
        "example_ar": "توضيح تفاصيل صورة أشعة سينية منخفضة التباين.",
        "related": [],
    },

    # ── Voice AI (COURSE-015) ────────────────────────────────────────────
    {
        "slug": "speech_to_text", "term_en": "Speech-to-Text", "term_ar": "تحويل الكلام إلى نص",
        "acronym": "STT", "aliases": ["stt", "speech recognition", "automatic speech recognition", "asr"],
        "category": "Voice AI", "difficulty": "beginner", "tags": ["voice", "audio"],
        "definition_en": "Converting spoken audio into written text, typically streamed incrementally (interim results) rather than waiting for the speaker to finish.",
        "definition_ar": "تحويل الصوت المنطوق إلى نص مكتوب، وعادة يتم ذلك بشكل تدريجي (نتائج مؤقتة) بدل انتظار انتهاء المتحدث تماماً.",
        "explanation_simple_ar": "تحويل ما يقوله الشخص بصوته إلى كلمات مكتوبة.",
        "why_it_matters_ar": "الخطوة الأولى في أي نظام صوتي يفهم كلام المستخدم.",
        "example_ar": "تحويل \"أريد حجز موعد\" المنطوقة إلى نص مكتوب في الوقت الفعلي.",
        "related": ["text_to_speech", "voice_activity_detection"],
    },
    {
        "slug": "text_to_speech", "term_en": "Text-to-Speech", "term_ar": "تحويل النص إلى كلام",
        "acronym": "TTS", "aliases": ["tts", "speech synthesis"],
        "category": "Voice AI", "difficulty": "beginner", "tags": ["voice", "audio"],
        "definition_en": "Generating spoken audio from written text, ideally streamed incrementally as the text becomes available so playback can start before generation finishes.",
        "definition_ar": "توليد صوت منطوق من نص مكتوب، ويُفضَّل توليده تدريجياً مع توفر النص بحيث يبدأ التشغيل قبل انتهاء التوليد بالكامل.",
        "explanation_simple_ar": "تحويل نص مكتوب إلى صوت منطوق يسمعه المستخدم.",
        "why_it_matters_ar": "ما يجعل رد المساعد الصوتي مسموعاً بدل أن يكون نصاً فقط.",
        "example_ar": "تحويل رد النموذج النصي إلى صوت طبيعي يُشغَّل للمستخدم.",
        "related": ["speech_to_text"],
    },
    {
        "slug": "native_speech_to_speech", "term_en": "Native Speech-to-Speech", "term_ar": "الكلام إلى كلام الأصلي",
        "acronym": None, "aliases": ["speech-to-speech", "s2s"],
        "category": "Voice AI", "difficulty": "advanced", "tags": ["voice", "architecture"],
        "definition_en": "A voice architecture where a single model processes audio input and produces audio output directly, without separate STT/LLM/TTS stages - as opposed to a chained pipeline. Distinct from speech recognition, which only produces text.",
        "definition_ar": "بنية صوتية يعالج فيها نموذج واحد الصوت المدخل وينتج الصوت المخرَج مباشرة، دون مراحل منفصلة لتحويل الكلام إلى نص ثم للنموذج اللغوي ثم إلى كلام - على عكس الأنبوب المتسلسل. تختلف عن التعرّف على الكلام الذي ينتج نصاً فقط.",
        "explanation_simple_ar": "نموذج واحد يسمع الصوت ويرد بصوت مباشرة، دون المرور بخطوة تحويل الكلام إلى نص ثم العكس.",
        "why_it_matters_ar": "يقلل زمن الاستجابة ويحافظ على تفاصيل صوتية (نبرة، مشاعر) قد تضيع في الأنبوب المتسلسل.",
        "example_ar": "نموذج مثل Gemini Live أو OpenAI Realtime يعالج الصوت المدخل مباشرة دون تفريغه نصاً أولاً.",
        "related": ["speech_to_text", "text_to_speech"],
    },
    {
        "slug": "webrtc", "term_en": "WebRTC", "term_ar": "بروتوكول WebRTC",
        "acronym": None, "aliases": ["web real-time communication"],
        "category": "Voice AI", "difficulty": "advanced", "tags": ["voice", "networking"],
        "definition_en": "A browser-native protocol for real-time peer-to-peer audio, video and data, commonly used for low-latency voice-agent connections directly from a web page.",
        "definition_ar": "بروتوكول مدمج في المتصفح للاتصال اللحظي المباشر (نظير إلى نظير) بالصوت والفيديو والبيانات، يُستخدم غالباً لاتصالات وكلاء صوتية منخفضة زمن الاستجابة مباشرة من صفحة الويب.",
        "explanation_simple_ar": "تقنية تتيح للمتصفح إرسال واستقبال صوت وفيديو لحظياً دون برامج إضافية.",
        "why_it_matters_ar": "يوفر أقل زمن استجابة ممكن للمحادثات الصوتية من داخل المتصفح.",
        "example_ar": "مكالمة صوتية مع مساعد ذكي تعمل مباشرة من صفحة الويب دون تثبيت تطبيق.",
        "related": ["websocket"],
    },
    {
        "slug": "agent_handoff", "term_en": "Agent Handoff", "term_ar": "تسليم المهمة بين الوكلاء",
        # Bare "handoff" alone false-matched career-portfolio handoff and
        # CI/CD artifact handoff in real lessons (see association-quality
        # audit) — matching now requires the full "Agent Handoff" phrase, or
        # the more specific "human handoff" alias.
        "acronym": None, "aliases": ["human handoff"],
        "category": "Agents", "difficulty": "advanced", "tags": ["agents", "voice"],
        "definition_en": "Transferring an ongoing conversation or task from one agent to another (or to a human) without losing context, state, or continuity for the user.",
        "definition_ar": "نقل محادثة أو مهمة جارية من وكيل إلى آخر (أو إلى إنسان) دون فقدان السياق أو الحالة أو استمرارية التجربة بالنسبة للمستخدم.",
        "explanation_simple_ar": "تمرير المحادثة من وكيل لآخر (أو لموظف بشري) دون أن يشعر المستخدم بانقطاع.",
        "why_it_matters_ar": "ضروري في الأنظمة متعددة الوكلاء وأنظمة الدعم الصوتي التي قد تحتاج تدخلاً بشرياً.",
        "example_ar": "تحويل مكالمة من مساعد صوتي آلي إلى موظف بشري مع الحفاظ على سياق المحادثة كاملاً.",
        "related": ["multi_agent_collaboration"],
    },
    {
        "slug": "ann_search", "term_en": "Approximate Nearest Neighbor", "term_ar": "أقرب الجيران التقريبي",
        "acronym": "ANN", "aliases": ["ann", "approximate nearest neighbor search"],
        "category": "RAG", "difficulty": "advanced", "tags": ["retrieval", "vector-database"],
        "definition_en": "Algorithms and index structures (e.g. HNSW) that find vectors very close to a query quickly by accepting a small chance of missing the true nearest one, trading perfect accuracy for massive speed at scale.",
        "definition_ar": "خوارزميات وبنى فهرسة (مثل HNSW) تجد متجهات قريبة جداً من الاستعلام بسرعة، مقابل قبول احتمال ضئيل لتفويت الأقرب الحقيقي فعلاً - تضحّي بدقة مثالية مقابل سرعة هائلة على نطاق واسع.",
        "explanation_simple_ar": "بحث سريع جداً عن \"الأقرب تقريباً\" بدل \"الأقرب المضمون\"، لأن البحث الدقيق يصبح بطيئاً جداً مع ملايين المتجهات.",
        "why_it_matters_ar": "هو ما يجعل قواعد البيانات المتجهية عملية على نطاق واسع.",
        "example_ar": "قاعدة بيانات متجهية تستخدم فهرس HNSW للبحث بسرعة بين مليون متجه.",
        "related": ["vector_search", "vector_database"],
    },
]
